### ISSUE TITLE
WebUI: log login attempts, HTTP error codes, to be able to make it secure using fail2ban

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#1007]
I'm using fail2ban to protect myself from SSH bruteforce, and SSH DDOS attacks - this was my only service I used over WAN, and it could be easily changed with Flexget's new WebUI!

The WebUI should log to an other file, like `~/.flexget/webui.log`. Later I'll create a full regexp to the possible failures, in this format [filter.d/apache-auth.conf](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/apache-auth.conf#L13).

Thanks @stevezau!

**Comment by stevezau** [comment]
hmm, i thinking we store the web access logs in a different log file?? maybe ~/.flexget/flexget-access.log

Storing it within flexget.log might get messy?

**Comment by antivirtel** [comment]
Yes, it would be better, but the point is, that let the fail2ban find that regexp in a file, and then it will do its job.

**Comment by liiight** [comment]
Relevant to #1419

**Comment by antivirtel** [comment]
Is it still not working with Fail2Ban or it has been changed?
