### ISSUE TITLE
Add wishlist category support in anidb_list

### ISSUE THREAD

**Issue by Jonybat** [Flexget/Flexget#1031]
Hi

I've recently stumbled on this plugin, that would be very interesting for my setup, but it would need some improvements to fit my needs. Basically im talking about multiple lists from the same account, similar to what you can have with trakt. I am aware that this is a limitation from anidb itself, but we could use some of the default wishlist categories (To Get, To Watch, Buddy Recommendations, Undefined and Blacklist). I would be happy with just one option, like To Get.

I looked at the code and the request is being made directly to the url:
`url = 'http://anidb.net/perl-bin/animedb.pl?show=mywishlist&uid=%s' % config['user_id']`

So it would be just a matter of adding "&mode=3" to the url, for the "To Get" category. The default "All" category seems to be "&mode=0" in case that makes it easier.

Looks simple enough so i gave it a go, but i couldnt even get it to work hardcoded, so ill just leave it for those that know what they are doing.

Thanks

**Comment by liiight** [comment]
This plugin can be converted into a list interface. I'm preparing dev docs on that, if anyone wanna step up

**Comment by radek-sprta** [comment]
I'll take a look at it when I get home.

I am in the process of implementing the UDP API for the AniDB website, which would alllow a lot more stuff, and then I am planning to convert the plugin to the list interface. However, I'll have next to no time to work on it until June/July.

**Comment by Jonybat** [comment]
That sounds cool, because im also using some of the API features but with another script.

What im sugesting here should be simple to implement though, and will give people the ability to use the plugin to download from the "want to watch now" list and not from the "want to watch someday".

Baby steps :+1:

**Comment by liiight** [comment]
If you need help with list interface stuff feel free to ask on irc or gitter

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
