### ISSUE TITLE
 BUG: Unhandled error in plugin rss: u'url'

### ISSUE THREAD

**Issue by bread91** [Flexget/Flexget#1039]
Hi,
I get an error while using the rss plugin:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
>     return method(_args, *_kwargs)
>   File "/usr/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
>     return self.func(_args, *_kwargs)
>   File "/usr/lib/python2.7/site-packages/flexget/utils/cached_input.py", line 163, in wrapped_func
>     response = func(_args, *_kwargs)
>   File "/usr/lib/python2.7/site-packages/flexget/plugin.py", line 124, in wrapped_func
>     return func(_args, *_kwargs)
>   File "/usr/lib/python2.7/site-packages/flexget/plugins/input/rss.py", line 448, in on_task_input
>     e.setdefault('urls', [e['url']]).extend(
>   File "/usr/lib/python2.7/site-packages/flexget/utils/lazy_dict.py", line 69, in __getitem__
>     item = self.store[key]
> KeyError: u'url'

I am generating local xml files and use them as the rss source, since the original rss feed is a mess.
The items with one direct link look like this:

```
    <item>
        <title>London Has Fallen 2016 720p xxxxxxxxxx</title>
        <link>http://uplxxxxx.net/file/xxxxxxxxxx/London.Has.Fallen.2016.720.xxxxxxxxxx.mkv</link>
    </item>
```

and with several parts like this:

```
    <item>
        <title>The Revenant 2015 720p xxxxxxxxxxx</title>
        <link>http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part01.rar</link>
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part02.rar" />
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part03.rar" />
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part04.rar" />
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part05.rar" />
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part06.rar" />
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part07.rar" />
        <enclosure url="http://uplxxxxx.net/file/xxxxxxxxxx/The.Revenant.2015.720-xxxxxxxxxx.part08.rar" />
    </item>
```

And finally this is the rss configuration:

> ```
> rss:
>   url: file:///volume1/homes/admin/movies_720p_feed.xml
>   group_links: yes
> ```

It looks like the rss parser does not set e['url'] with this setting. Since 'link' is not set at all in the config and there are unequal 1 enclosures (zero or more than 1), rss should set e['url'] in line 433.

Any suggestions?

**Comment by paranoidi** [comment]
If you provide clean example file someone might take a look.
