### ISSUE TITLE
thetvdb_favorites.py not working

### ISSUE THREAD

**Issue by lucaorio** [Flexget/Flexget#1048]
After this discussion on the Flexget forum ( http://discuss.flexget.com/t/thetvdb-favorites-not-working/2208 ), I decided to open an issue here.

The new TVDB API Auth ( https://api-beta.thetvdb.com/swagger ) requires: `{"apikey":"APIKEY","username":"USERNAME","userkey":"USERKEY"}`

I took a look at the `thetvdb_favorites.py` plugin, and it seems like it calls the API in this way:
```
'username': {'type': 'string'},
'account_id': {'type': 'string'},
```

Still, it's not clear the difference between these values from TheTVDB (I tried every possible combination):
* Account Identifier
* Site User ID
* Username
* Password

and which ones are required by the plugin. The documentation (http://flexget.com/wiki/Plugins/thetvdb_favorites) it's not updated and doesn't help.

I don't know if it's related to an auth error or not, but this is the only error I get from Flexget:
`2016-04-18 10:56 INFO configure_series download Did not get any series to generate series configuration`

**Comment by stevezau** [comment]
I just updated the doco..

It should just be

    thetvdb_favorites:
      username: <username>
      account_id: <account identifier>

**Comment by stevezau** [comment]
Also, make sure you are on the latest version of flexget as there were a few api changes a few days back.

**Comment by stevezau** [comment]
please re-open if u have issues
