### ISSUE TITLE
Set config path from environment variable

### ISSUE THREAD

**Issue by Ram-Z** [Flexget/Flexget#1049]
`flexget` should read the path to the config file from an environment variable. `FLEXGET_CONFIG` for example.

The env variable should only be used if no command line config path has been given. I.e. set the path from the first one of these that is set:
1. `-c /path/to/config.yml`
2. `FLEXGET_CONFIG`
3. default locations, one of `~/.flexget`, `$XDG_CONFIG_HOME/flexget`

I guess this could work for Windows as well. Setting `%FLEXGET_CONFIG%`.

Any thoughts on the variable name?

**Comment by paranoidi** [comment]
Contributions are evaluated, we're not putting effort into this one.
