### ISSUE TITLE
my configration was not working(move to not working)... help me.

### ISSUE THREAD

**Issue by noainred** [Flexget/Flexget#1056]
Downloading is good. really good.

When downloading torrent finished, I want to move the file to specific directory.
But "move to" fuction is not working.

help me.
------------------------------------------------
web_server:
  bind: 0.0.0.0
  port: 9093
api: yes
webui: yes

tasks:
  PDF:
       rss: 'https://***.***/magazines/?rss=1'
       accept_all: yes
       download:
                 path: '/t/watch'
                 temp: '/t/ing'
                 fail_html: no
       move:
           to: '/t/Completed/Magazines/'

  ADT:
       rss: 'http://***.***/feeds/posts/default?alt=rss'
       accept_all: yes
       download:
                 path: '/t/watch'
                 temp: '/t/ing'
                 fail_html: no
       move:
           to: '/t/Completed/ADT/'

  Programming:
       rss: 'https://***.***/programming/?rss=1'
       accept_all: yes
       download:
                 path: '/t/watch'
                 temp: '/t/ing'
                 fail_html: no
       move:
           to: '/t/Completed/Programming/'

**Comment by cvium** [comment]
"move to" works fine, but you're using it wrong. You have to create a separate task that moves the files. You can't download _and_ move in the same task.
