### ISSUE TITLE
Flexget fails when Deluge is not on the same machine.

### ISSUE THREAD

**Issue by paulpoco** [Flexget/Flexget#1057]
Flexget fails when Deluge is not on the same machine.

Machine 1 gas Flexget
Machine 2 has Deluge 192.168.1.xxx

Flex get using these settings:

   deluge:
      host: 192.168.1.xxx
      port: 58846
      username: xxxxxx
      password: xxxxxx
      queuetotop: yes

**Comment by lepinkainen** [comment]
How does Flexget fail? Any error messages you could share with us?

**Comment by crawln45** [comment]
My guess is. Machine 1 does not have deluge-common installed. There for we cannot import some python files needed to communicate with Machine 2. Try installing deluge-common.

**Comment by crawln45** [comment]
Over 30 days old. Closing. Open again if more information is provided.
