### ISSUE TITLE
New Ubuntu 16.04 install

### ISSUE THREAD

**Issue by gazhay** [Flexget/Flexget#1071]
Fresh install, installed flexget, copied the config file from an existing working setup and getting "Failed to load config file: Did not pass schema validation".

I have confirmed it is working a) on the current server, b) passes YAML validation.

**Comment by stevezau** [comment]
post logs please.

**Comment by cvium** [comment]
If I had to guess, I'd say the working installation is an older version and the config needs to be updated.

**Comment by gazhay** [comment]
I've actually solved it.

I was migrating to a new server but hadn't migrated all disks yet.
Seems one of the plugins couldn't see a filesystem path, so threw an error.

It was a genuine error, though slightly confusing by the manifestation.
When the drive was connected the error went away.
