### ISSUE TITLE
Sqltype warning in tests

### ISSUE THREAD

**Issue by crawln45** [Flexget/Flexget#1084]
`tests/test_torrent.py::TestSeenInfoHash::test_same_run /home/crawln/git/Flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '2befa6d18df643d2e9097864f...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))`

`tests/test_content_size.py::TestTorrentSize::test_cache /home/crawln/git/Flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '735902f4042deced2d8aa6f33...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))`

`tests/test_content_size.py::TestTorrentSize::test_max /home/crawln/git/Flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'd26c9951071152202c7623610...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))`

`[gw2] PASSED tests/test_config_schema.py::TestSchemaValidator::test_resolves_local_refs /home/crawln/git/Flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'd98c195871a6428fc84de97e8...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))`

**Comment by leetwanker** [comment]
This looks related so I'm posting it here. My box has started mailing me this. 

`
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'f1e18d5abaa1e740b2938ba5d...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
`

**Comment by stevezau** [comment]
how can i reproduce this? When i ran tests i don't see those warnings?
