### ISSUE TITLE
Crash on start flexget 2.0.2

### ISSUE THREAD

**Issue by danageis** [Flexget/Flexget#1093]
After upgrade (via pip), launching flexget crashes with:
```
flexget
Traceback (most recent call last):
File "/usr/lib/flexget", line 7, in 
from flexget import main
File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 11, in 
from flexget import logger, plugin
File "/usr/lib/python2.7/site-packages/flexget/logger.py", line 3, in 
from past.builtins import basestring
File "/usr/lib/python2.7/site-packages/past/__init__.py", line 88, in 
from past.translation import install_hooks as autotranslate
File "/usr/lib/python2.7/site-packages/past/translation/__init__.py", line 41, in 
from lib2to3.pgen2.parse import ParseError
ImportError: No module named lib2to3.pgen2.parse
```
Seem to be fixed (temporarily) by commenting out the following lines in these 2 files:
```
/usr/lib/python2.7/site-packages/past/translation/__init__.py
     #from lib2to3.pgen2.parse import ParseError
     #from lib2to3.refactor import RefactoringTool
/usr/lib/python2.7/site-packages/libfuturize/fixes/__init__.py
     #from lib2to3 import refactor
```
This is on a NAS running generic linux w/ busybox and python 2.7.2

**Comment by stevezau** [comment]
hmm what happens if you run

```python -c "from lib2to3.pgen2.parse import ParseError"```

**Comment by danageis** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lib2to3.pgen2.parse
On Apr 26, 2016 1:48 AM, "Steve Adams" <notifications@github.com> wrote:

hmm what happens if you run

python -c "from lib2to3.pgen2.parse import ParseError"

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Flexget/Flexget/issues/1093#issuecomment-214671441>

**Comment by crawln45** [comment]
So I'm assuming since your new ticket it #1094 you managed to get flexget to startup. Remember how you managed that?

**Comment by danageis** [comment]
I suppose that is confusing... let me explain; I opened both of these tickets because I was asked to do so on the discussion forums.

This first ticket (#1093), was a problem I found that did not allow me to start flexget at all after upgrading to 2.02 with only py2.7.2 installed. Another user on the forum had the same issue, I posted my pseudo-fix, and I we were asked to create a git issue based on that thread.

I got flexget to startup exactly as I wrote in this issue, by commenting out the import lib2to3 calls in the traceback referenced files.

At this point, I was able to launch flexget without the lib2to3 errors. I can launch flexget -V (as long as a daemon is not running) and also launch flexget daemon start -d without errors. The daemon launched in this way is fully functional (launches scheduled tasks is usual from config.yml), except any manual commands passed to flexget result in the new error (#1094), such as flexget execute, flexget daemon status, flexget reload, etc.

I hope that makes sense, please let me know if you have more questions.

**Comment by stevezau** [comment]
The fact that when you tried to simple import that lib suggests it has nothing to do with flexget.

 A ticket for that lib was logged here: https://github.com/PythonCharmers/python-future/issues/209

closing this one.

**Comment by msj33** [comment]
Hi Steve.

Have the exact same error here when upgrading 1.2.469 -> 2.0.8

Is there a solution for this or how?

The other ticket is also closed - So looks like a dead end?

Hope you can help - Thanks in advance

/Morten

**Comment by danageis** [comment]
Did you try commenting out the lines? That's all I was able to do to fix it. Let's flexget run, but in my case still left with problems in issue #1094

**Comment by msj33** [comment]
Did a complete reinstall(also switched to entware-ng repo) and still same error.

I think this ticket should be reopened untill the error or dependency error has been fixed!

@danageis I got it running by uncommenting the 3 lines - But have no clue what affects it might have,

I am running Padavans custom firmware on Asus N56U router.

**Comment by stevezau** [comment]
@msj33 this has nothing to do with flexget, we use python future which imports that lib.

Ticket for that is here: https://github.com/PythonCharmers/python-future/issues/209 

add your comments there.

**Comment by msj33** [comment]
Sorry to hear - I would expected, if flexget has a dependency to python future, you at least will have a bug record here - The end result is still that Flexget is broken on new release - And in worst case scenario, they won't fix it anytime soon. Untill that, I can not recommend any user to upgrade to Flexget 2.x

Will add my comments to that ticket, thx

**Comment by stevezau** [comment]
@msj33 we do have a ticket there, I just pasted the url.  Python-future is core to making flexget work across python2/3.

This ONLY affects users who are running a "light" version of python (without lib2to3 compiled in). Commenting out those lines should get you by for now.

**Comment by programatix** [comment]
Does this mean that flexget is discontinuing support for python 2? This is because devices with python 2 only wouldn't be built with lib2to3, no? I suppose the before importing lib2to3 modules, a check should be done to see if it is running on python 2 or 3 and only import it if python 3 is being used.
