### ISSUE TITLE
Minor : webui not showing the correct tvdb series

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1096]
Some of my series have homonyms and the webui is fetching the series details from an incorrect series.

My series:
- Mom (tvdb_id=266967)
- Continuum (tvdb_id=258171)

The series shown in the webui:
- Mon (2015) (tvdb_id=299884)
- Continuum (Web Series) (tvdb_id=262262)

**Comment by stevezau** [comment]
Hmm can u show a screenshot, not sure i fully understand.

**Comment by liiight** [comment]
Series mismatch. We need an api endpoint to get multiple series results and select one via ui

**Comment by stevezau** [comment]
@liiight ??? i would of thought the webui would show all the series?

**Comment by Mirgolth** [comment]
@stevezau, yes all series will show on the webui but right now some series are incorrect due to homonyms.

I'm following the show Continuum (http://thetvdb.com/?id=258171&tab=series) but on the webui I see the show 	Continuum (Web Series) (http://thetvdb.com/?tab=series&id=262262). See screen shot

![continuum web series](https://cloud.githubusercontent.com/assets/15908911/14934612/b2b12754-0eb6-11e6-8e21-9e14a6bf94e5.png)

**Comment by Tommatheussen** [comment]
Yes indeed, as suspected, since the lookup API looks up using name right now, and not id, it might return the incorrect one. As @liiight mentioned, an mismatch API endpoint (and UI action) will allow users to set the correct one.
