### ISSUE TITLE
Problem with sabnzbd after upgrade to version 2.0.5

### ISSUE THREAD

**Issue by yodax** [Flexget/Flexget#1099]
Hi,

Last night I upgraded to version 2.0.5 from 1.2.521. I haven't made any config changes. Everything seems to work except adding downloads to sabnzbd. Reverting back to version 1.2.521 made everything work again.

```
2016-04-27 07:30 CRITICAL sabnzbd       usenet          Failed to use sabnzbd. Requested http://sabnzbd:8080/sabnzbd/api?nzbname=REL_NAME&apikey=11111&mode=addurl&name=URL_THAT_WORKS
2016-04-27 07:30 CRITICAL sabnzbd       usenet          Result was: 'Task' object has no attribute 'get'
2016-04-27 07:30 ERROR    entry         usenet          Failed REL_NAME (sabnzbd unreachable) 
```

Manually clicking the url does add the nzb to sabznbd. 

This runs in a FreeBSD 10.3 jail using Python 2.7.11 installed and upgraded using pip.

**Comment by crawln45** [comment]
@yodax Full traceback is usually required if any is given. Probably one of a very long list of py3 conversion issues we're going to have for a while. We'd appreciate it if users wouldn't revert right away to older versions. So we can actually find all the bugs from the new conversion. I understand. It's broken. But we can't fix all the issues your having if you revert back before we fix them.

**Comment by gazpachoking** [comment]
Just did a quick peek, but this appears to be the problem https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/sabnzbd.py#L87

That should be `task.requests.get`

**Comment by crawln45** [comment]
@gazpachoking yeah was about to fix that. Ohhh it was using something else before. makes sense now.

**Comment by gazpachoking** [comment]
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/sabnzbd.py#L88

This catch is also way too broad, and the reason @yodax didn't get a traceback and the error message was wrong.

**Comment by yodax** [comment]
Thanks for the quick fix! Switching between versions really isn't much of a problem. That's why you have zfs snapshots and jails. (Or even pip, which I used this time) Glad you could find the problem. Didn't post the config since bisecting showed that wasn't the problem. 

Friday night it will auto update again and I will retest.
