### ISSUE TITLE
[IMDB] Geolocation makes movie titles inconsistent depending on the source IP.

### ISSUE THREAD

**Issue by drwyrm** [Flexget/Flexget#1106]
IMDB geolocation causes lots of issues when you are outside of USA, as the names are localized using the source IP address.

This can be "fixed" by tricking IMDB into thinking that the request is from an USA IP address. IMDB geolocation honors X-Forwarded-For http headers, so, all that is needed is setting the header to a random IP address on a block assigned to the USA.

Fixing this would make imdb lookups consistent for all users, since all searchs would be done using the same language.

**Comment by liiight** [comment]
Imdb list have a `force_language` option. I started doing same thing for imdb lookup but dropped it a long time ago.

**Comment by drwyrm** [comment]
From a quick test here, Accept-Language headers makes no difference regarding search results, even when using "Accept-Language: en-US" I get localized titles for most movies.

With "X-Forwarded-For: <any ipv4 from USA>" I get consistent, always english names that match releases.
