### ISSUE TITLE
TVMaze estimator (and lookup) does not always return the expected date/id

### ISSUE THREAD

**Issue by cvium** [Flexget/Flexget#1111]
Log snippet: http://pastebin.com/raw/UB44hDWR

Sometimes, for some inexplicable reason, TVMaze lookup caches wrong data eg. an episode from a different show, which results in a wrong release estimation.

The log snippet shows that S04E02 of Inside Amy Schumer has id 721019 but that is incorrect as it is in fact S04E03.

I have been unable to reproduce it. It happens randomly. The config used is a basic `emit_series` with `discover`.

**Comment by liiight** [comment]
Log http://evenflow.nl/div/log

**Comment by crawln45** [comment]
@cvium the return from tvmaze is actually wrong. Which is why the amy schumer is that way. Someone should let them know.

**Comment by cvium** [comment]
@crawln45 Well, doesn't change the fact that on more than one occasion I've gotten one episode from Show A attached to Show B. Could be a TVMaze problem but I have no idea.

**Comment by liiight** [comment]
I doubt it @cvium. Like we discussed, I'll refactor the plugin and drop pytvmaze, let's see what happens then
