### ISSUE TITLE
thetvdb_lookup_season_offset error

### ISSUE THREAD

**Issue by Aidanb79** [Flexget/Flexget#1126]
Hi,

I have started getting this error 'Could not set content_filename for DCs Legends of Tomorrow S01E13 HDTV x264-LOL: (UndefinedError) 'thetvdb_lookup_season_offset' is undefined' it has started happening since i upgraded to the latest version of flexget.

hope someone can help.

Aidan

**Comment by liiight** [comment]
post full log and config please

**Comment by Aidanb79** [comment]
Hi, 

Please see the attached. if you need anything else please let me know.

[flexget.zip](https://github.com/Flexget/Flexget/files/244990/flexget.zip)

**Comment by liiight** [comment]
not sure what `thetvdb_lookup_season_offset` was but it doesn't exist anymore since tvdb lookup was redone. look here: http://flexget.com/wiki/Plugins/thetvdb_lookup

**Comment by Aidanb79** [comment]
Thanks for the help hope the change has fixed it.
