### ISSUE TITLE
[regexp_parse] useless required key

### ISSUE THREAD

**Issue by revsee65** [Flexget/Flexget#1131]
The plugin regexp_parse required the key `url` and `title` but in some case we just need one key.
For example i need to parse download's ids and use them with `exec: command id` so i don't need `url` key.
I think one key required is enought.

**Comment by cvium** [comment]
This is not really a regexp_parse requirement. Flexget entries must always contain a `title` and a `url`.

**Comment by revsee65** [comment]
I've change the plugin that i use for html plugin and it's working perfectly.
