### ISSUE TITLE
Failed by payload plugin because 91

### ISSUE THREAD

**Issue by kasperj** [Flexget/Flexget#1136]
2016-05-04 17:43 VERBOSE  task *** FAILED: `***` by pyload plugin because 91

**Comment by liiight** [comment]
congratulations, i think this is the worst bug description i ever saw in Flexget ;-)
please paste full config and log

**Comment by kasperj** [comment]
Well actually I didn't want to post it right away, just a reminder for myself :P
But now it is here ...

`input_serienjunkies_de_ul:
    rss: http://serienjunkies.org/xml/feeds/episoden.xml
    serienjunkies:
      language: german
      hoster: ul

  download_pyload:
    pyload:
      api: http://192.168.22.10:8000/api
      queue: yes
      package: "{{series_name|replace(\"'\", \"\")}} - {{series_id}} - {{quality}}"
      package_password: ***
      username: ***
      password: ***`

Everything else is basically task scheduling and other stuff, loading the rss, parsing, filtering, url-rewriting all working fine, but sending the download-links to payload throws this error, just updated to v2, worked fine before

**Comment by liiight** [comment]
you forgot to add full log, debug is best

**Comment by kasperj** [comment]
[verbose_log.txt](https://github.com/Flexget/Flexget/files/248880/verbose_log.txt)

**Comment by liiight** [comment]
reset retry_failed and run again please, we need the trace:
`flexget failed clear`

**Comment by kasperj** [comment]
2016-05-04 18:17 CRITICAL payload *** Unknown error: 'bool' object has no attribute 'replace'
[verbose_log.txt](https://github.com/Flexget/Flexget/files/248895/verbose_log.txt)

**Comment by liiight** [comment]
i think that's the same file. also, please use a paste service like http://hastebin.com/

**Comment by kasperj** [comment]
It is not, but you are right, only difference is the copied line above ...
http://pastebin.com/za4ff7KV

**Comment by kasperj** [comment]
Seems to be fixed with a reinstall with python3

**Comment by jbman11** [comment]
I have done a reinstall of flexget and I am still seeing the same issue

**Comment by Xaviee** [comment]
Same for me. I also did a fresh install of pyload.

**Comment by kasperj** [comment]
Using Python 3 or Python 2? My first try was with Python 2 and reinstall on a clean Python 3!

**Comment by gazpachoking** [comment]
I'm not certain if it's related to the problem. But the config schema for pyload plugin looks a bit wrong. According to the schema `pyload: yes` is a valid config, but it looks like that will crash. Also, in dict form of config, none of the fields are marked as required, which I think they probably should be.

**Comment by Xaviee** [comment]
@kasperj So you uninstalled python 2 and flexget and than installed python 3 with flexget?

**Comment by kasperj** [comment]
I was migrating to a new device so its a brand new debian vm with python 3 and flexget

**Comment by jbman11** [comment]
python 2 for me, i have not updated anything other than flexget.

I rolled back to version 1.2.521 and everything is working correctly again

**Comment by Xaviee** [comment]
@jbman11 How did u installed the old version of flexget?

**Comment by jbman11** [comment]
sudo pip install flexget==1.2.521

**Comment by jbman11** [comment]
How can we get this reopened, since the fix to install on a clean system with py3 isn't an option for all?

**Comment by kasperj** [comment]
I reopened the issue

**Comment by jbman11** [comment]
Anything needed to help get this one looked at?

**Comment by m3nu** [comment]
With Python3 I'm getting this error in Pyload:

`ValueError: 'b'Althaus Modernisieren - August/September 2016'' is not a valid expression`

When you look at [this line](https://github.com/Flexget/Flexget/blob/master/flexget/plugins/output/pyload.py#L195) you see that the title is encoded to bytes and then inserted into a string, which explains the weird value passed to Pyload.

I understand that this is a trick to remove weird characters and put quotes around them. The solution then is to add another `.decode()` to turn `bytes` back into a string and avoids passing those single quotes to Pyload.

I can do a proper PR and test it under py2 and py3, if there is still need.

**Comment by jbman11** [comment]
It would be great if this could be fixed. I had to roll back to 1.2.521 and stay there

**Comment by codenamedelta** [comment]
@m3nu Any chance you can explain what exact change needs to be made regarding this line? I am receiving the exact same error with Python 3.

On another note, with Python27 I also receive error 91

**Comment by m3nu** [comment]
Just make sure pyload gets a valid title. I simply added another `decode()` at the end.

```
post = {'name': "'%s'" % name.encode("ascii", "ignore").decode()
```

So this line encodes to ascii bytes (to remove crazy characters) and then back to a string, so pyload doesn't get the byte representationt with extra quotes.

**Comment by Roburetto** [comment]
Still facing this problem in Python 2.7. Tried the fix from previous post with no luck.

2016-09-06 13:23 DEBUG    utils.requests get_magazines_3 Fetching http://192.168.1.4:8000/api/login
2016-09-06 13:23 DEBUG    pyload        get_magazines_3 Parsing url "http://domain.com/webpage.html"
2016-09-06 13:23 DEBUG    utils.requests get_magazines_3 Fetching http://192.168.1.4:8000/api/parseURLs
2016-09-06 13:23 DEBUG    pyload        get_magazines_3 Add 1 urls to pyLoad
2016-09-06 13:23 DEBUG    utils.requests get_magazines_3 Fetching http://192.168.1.4:8000/api/addPackage
2016-09-06 13:23 DEBUG    entry         get_magazines_3 Marking entry 'One Magazine- September 2016' as failed
2016-09-06 13:23 ERROR    entry         get_magazines_3 Failed One Magazine - Septiembre 2016 (91)

**Comment by codenamedelta** [comment]
@m3nu Thanks, that fixed it for me. I'd say submit PR, but I don't know the implications for Python 2.7.

**Comment by cvium** [comment]
If someone could properly test my PR that'd be great.

**Comment by Roburetto** [comment]
Just tried your commit and guess what it now WORKS (python 2.7, Debian 8.5 Arhmf)

Thanks a lot.

**Comment by cvium** [comment]
@jbman11 @codenamedelta @m3nu  @kasperj @Xaviee You guys wanna test it?

**Comment by m3nu** [comment]
Yes. Will test. Thanks for the PR.
