### ISSUE TITLE
BUG: Unhandled error in plugin list_remove: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1139]
fmf@kodi:~$ flexget -V
2.0.11
You are on the latest release.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/list_remove.py", line 41, in on_task_output
    thelist -= task.accepted
  File "/usr/lib/python2.7/_abcoll.py", line 337, in __isub__
    self.discard(value)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/movie_list.py", line 144, in discard
    db_movie = self._find_entry(entry, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/movie_list.py", line 171, in _find_entry
    res = (self._db_list(session).movies.filter(func.lower(MovieListMovie.title) == name.lower())
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by liiight** [comment]
Upgrade and test again, you're not on latest

**Comment by effemmeffe** [comment]
fmf@kodi:~$ sudo -H pip install --upgrade flexget
[sudo] password for fmf:
Collecting flexget
  Using cached FlexGet-2.0.11-py2.py3-none-any.whl
Requirement already up-to-date: flask>=0.7 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: pynzb in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: pathlib>=1.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: apscheduler!=3.1.0,>=3.0.3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-compress>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: Safe>=0.4 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: rpyc in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: pyparsing>=2.0.3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: requests<3.0,>=2.8.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: path.py>=8.1.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-restful>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: SQLAlchemy!=0.9.0,<1.999,>=0.7.5 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-login>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: FeedParser>=5.2.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-cors>=2.1.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: PyRSS2Gen in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-restplus==0.8.6 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: jsonschema>=2.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: html5lib>=0.11 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: guessit<=2.0.4 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: future>=0.15.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: beautifulsoup4!=4.2.0,<4.5,>=4.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: cherrypy>=3.7.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: python-dateutil>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask>=0.7->flexget)
Requirement already up-to-date: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask>=0.7->flexget)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from pynzb->flexget)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from apscheduler!=3.1.0,>=3.0.3->flexget)
Requirement already up-to-date: futures in /usr/local/lib/python2.7/dist-packages (from apscheduler!=3.1.0,>=3.0.3->flexget)
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from apscheduler!=3.1.0,>=3.0.3->flexget)
Requirement already up-to-date: tzlocal in /usr/local/lib/python2.7/dist-packages (from apscheduler!=3.1.0,>=3.0.3->flexget)
Requirement already up-to-date: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->flexget)
Requirement already up-to-date: aniso8601>=0.82 in /usr/local/lib/python2.7/dist-packages (from flask-restful>=0.3.3->flexget)
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->flexget)
Requirement already up-to-date: functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema>=2.0->flexget)
Requirement already up-to-date: babelfish>=0.5.5 in /usr/local/lib/python2.7/dist-packages (from guessit<=2.0.4->flexget)
Requirement already up-to-date: rebulk>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from guessit<=2.0.4->flexget)
Installing collected packages: flexget
  Found existing installation: FlexGet 1.2.419
    Uninstalling FlexGet-1.2.419:
      Successfully uninstalled FlexGet-1.2.419
Successfully installed flexget-1.2.368
fmf@kodi:~$ flexget -V
2.0.11
You are on the latest release.
fmf@kodi:~$

**Comment by liiight** [comment]
Stop confusing me with facts 😄 
Please add debug log, I thoguht I had this down yesterday...

**Comment by cvium** [comment]
@liiight fix is simple. You're doing `None.lower()`. Just check that `name` is not `None`.

**Comment by liiight** [comment]
I thought that name is always returned by movie parser

**Comment by cvium** [comment]
Maybe it should. This is what I got:
```
2016-05-05 04:00 VERBOSE  imdb_lookup   clean_movie_queue Imdb lookup failed for memento.10th.anniversary.special.edition.2000.bluray.720p.x264.dts-wiki
2016-05-05 04:00 VERBOSE  tmdb_lookup   clean_movie_queue TMDB lookup failed for Memento.10th.Anniversary.Special.Edition.2000.BluRay.720p.x264.DTS-WiKi
2016-05-05 04:00 CRITICAL task          clean_movie_queue BUG: Unhandled error in plugin list_accept: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/list_accept.py", line 56, in on_task_filter
    if entry in thelist:
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/movie_list.py", line 150, in __contains__
    return self._find_entry(entry) is not None
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/movie_list.py", line 171, in _find_entry
    res = (self._db_list(session).movies.filter(func.lower(MovieListMovie.title) == name.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by liiight** [comment]
Ok, I guess I'll just check for none

**Comment by liiight** [comment]
Closed with https://github.com/Flexget/Flexget/commit/094e6311bef44545c84a232c1fd872e35da6794e
