### ISSUE TITLE
[plugin/html] Links are not kept when there is no link text inside

### ISSUE THREAD

**Issue by revsee65** [Flexget/Flexget#1144]
##### In the html plugin documentation it's write
> Note: This returns **ALL links from the page** so you need to configure some filters to match only to desired content. 

_[http://flexget.com/wiki/Plugins/html#Example](url)_

##### but in the code, links without link text are not kept
```
for link in soup.find_all('a'):
	# not a valid link
	if not link.has_attr('href'):
		continue
	# no content in the link
	if not link.contents:
		continue
```
_[https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/input/html.py#L168](url)_

##### I suggest to remove this part 
```
if not link.contents:
	continue
```

**Comment by liiight** [comment]
How is this an issue? And feel free to open a pr

**Comment by revsee65** [comment]
##### Link like this are not detected 
```
<a href="http://example.com/invisble_link" class="download_button"></a>
```

**Comment by revsee65** [comment]
The html plugin was build in order to ignore links that not contains elements used to create a title entry. 

For example with a link like that we can't find a title.
`<a href="http://example.com/invisible_link.torrent" class="download_button"></a>`

The process is logical but not flexible.
I suggest to let the plugin detect this type of link.
Here is my solution [https://gist.github.com/revsee65/dc4999f02daaffbe244f391238a8c7a4](url)
