### ISSUE TITLE
Qbittorrent Plugin crash

### ISSUE THREAD

**Issue by crawln45** [Flexget/Flexget#1166]
Seems qbittorrent plugin will crash in part because when adding a torrent multipart files is used. But no files are actually given to the web api. @dsemi please update your plugin to post data= not files= as files require that you send the downloaded files from the download output. And from looking at the code. on_task_download is not needed as qbittorrent will retrieve the files itself similar to deluge.

https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/qbittorrent.py#L79
that file is never given to qbittorrent. No need for it to download a temp file if it's never sent.
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/qbittorrent.py#L65
That is not needed for a json post to the webui and the entire line can be removed. Unless you plan on sending the actual temp file you downloaded in the on_task_download. At which point files can be used.
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/qbittorrent.py#L66
that should be
```
self.session.post(self.url + '/command/download', data=data)
```

**Comment by dsemi** [comment]
Can you post the stacktrace?
We do need to use multipart because qBittorrent doesn't decode the filenames properly otherwise. The tuples (None, v) == (file, data), so we are passing data and not files, this is just how you accomplish sending data and not files with a multipart request in requests (gross I know).

**Comment by crawln45** [comment]
I know why you think your using it. I'm here to tell you, It's not needed. Unless your going to send in the on_task_download temp files. data=data will work just fine. Edit and try it out.

**Comment by dsemi** [comment]
It is needed. `data=data` will send a single POST request with form encoded data and qBittorrent isn't expecting that. Multipart request data isn't encoded and that's what qBittorrent expects. I had the single POST request originally, but there were issues like [this](https://github.com/Flexget/Flexget/issues/1013) where any spaces in your save path would be replaced with plus signs because that's how a space is encoded in form data and qBittorrent wasn't decoding it.

**Comment by crawln45** [comment]
Problem is if savepath is None it causes an error. 2nd. savepath isn't being rendered when set under qbittorrent anyway.

```
tasks:
  test:
    series:
      - The Returned
    trakt_lookup: yes
    qbittorrent:
      host: localhost
      port: 8080
      label: 'TV-SERIES'
      path: "/home/user/git/{{trakt_series_name}} - test"
    rss: 'rss feed'
    
    
    creates /home/user/git/{{trakt_series_name}} - test
    not     /home/user/git/The Returned - test
```

now without path anywhere

```
2016-05-12 18:32 DEBUG    manager       test            Traceback:
Traceback (most recent call last):
  File "/home/crawln/git/Flexget/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/home/crawln/git/Flexget/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/crawln/git/Flexget/flexget/plugins/output/qbittorrent.py", line 111, in on_task_output
    self.add_torrent(data)
  File "/home/crawln/git/Flexget/flexget/plugins/output/qbittorrent.py", line 66, in add_torrent
    self.session.post(self.url + '/command/download', files=multipart_data)
  File "/home/crawln/git/Flexget/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/crawln/git/Flexget/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/home/crawln/git/Flexget/lib/python2.7/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/crawln/git/Flexget/lib/python2.7/site-packages/requests/models.py", line 298, in prepare
    self.prepare_body(data, files, json)
  File "/home/crawln/git/Flexget/lib/python2.7/site-packages/requests/models.py", line 449, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/home/crawln/git/Flexget/lib/python2.7/site-packages/requests/models.py", line 152, in _encode_files
    fdata = fp.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by dsemi** [comment]
The content renaming that expands {{series_name}} to 'The Returned' was never implemented here; if you'd like to add that, I'm sure it would be nearly identical to how it's done in the Deluge plugin.

I can fix the exception, that was a faulty assumption on my part that it would be included when it's not always.

**Comment by dsemi** [comment]
[Pull request](https://github.com/Flexget/Flexget/pull/1168) to fix the crash.
