### ISSUE TITLE
Windows VS2015: Python 3.x compile errors

### ISSUE THREAD

**Issue by qvazzler** [Flexget/Flexget#1170]
I have tried Python 3.1, 3.2, 3.3, 3.4 and 3.5 and none of them work.
Also tried IronPython and regular python launcher.
Tried cleaning the project and building again.

Understand that this "build" folder is probably special for Visual Studio.
Does anyone know why the below are happening? Are they legitimate errors?

## **Issue 1**
`
invalid syntax		D:\G\Flexget\build\lib\flexget\plugins\output\memusage.py (Line: 52)`
... **from** ...
`    print 'Resource Module memory usage: %s (kb)' % resource.getrusage(resource.RUSAGE_SELF).ru_maxrss`
... **in**
`Flexget\build\lib\flexget\plugins\output\memusage.py`

## **Issue 2** (Happens in 2 places)
`
", variable" not allowed in 3.x - use "as variable" instead. (Line 55 & Line 69)`
... **from** ...
`except re.error, e:`
... **in**
`Flexget\build\lib\flexget\plugins\modify\regex_extract.py`

**Comment by gazpachoking** [comment]
Those lines are from old code, and have since been updated. Only flexget 2.0+ is python 3 compatible.

**Comment by qvazzler** [comment]
@gazpachoking When will the old code be purged from the repo?
