### ISSUE TITLE
WebUI bug duplicate entries

### ISSUE THREAD

**Issue by Addicted5** [Flexget/Flexget#1171]
Hi,
I used trakt_list with option "strip_dates: yes"
But it stores series with dates ( year info.
if i run "flexget series list" , i can see series in format "series_name (year)".
then i ran "flexget exec" & then it created "series_name" & "series_name (year)" in web-UI series page.
"series_name" is not added to series list may be just cause it didn't accept entries (only cause no entries in rss).May be it'll be added to series list after my required torrents appear in rss.

So please solve duplicate entries in **Web-UI series page** & if "**strip_dates: yes**" used in trakt_list , add the series to series list with out dates/year.

`http://discuss.flexget.com/t/trakt-creating-entries-with-year/2337`

Post if you need any additional info or want me to run any additional command (for log etc)

**Comment by cvium** [comment]
> "strip_dates: yes" used in trakt_list , add the series to series list with out dates/year.

This already works.

This has something to do with web-ui and not the `trakt_list` plugin.

**Comment by liiight** [comment]
web-ui does not create any new series data in series db. it just calls on existing one and does tvdb lookups

**Comment by Addicted5** [comment]
It doesn't create new in series db.
But i'm seeing 2 entries in web-ui. "series_name (year)" & "series_name"
[http://discuss.flexget.com/uploads/default/original/2X/2/2e416f5d0be2537ea3888a4342ff65a7ad1aadc0.JPG](url)

**Comment by liiight** [comment]
those correlate to the ones you see in `series list`. All ui does is call `/api/series/`.
I'm not saying that there isn't an issue, i'm saying the UI can't be its cause. 

Please paste `series list` output, or better yet `/api/series/` API output.

**Comment by Addicted5** [comment]
`http://192.168.1.87:9090/api/series/?in_config=all&page=1&page_size=10&sort_by=show_name&descending=true`

`{
  "page": 1,
  "page_size": 10,
  "shows": [
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 46,
      "show_name": "True Detective (2014)"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [
        "tvshows"
      ],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 74,
      "show_name": "True Detective"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 47,
      "show_name": "The Vampire Diaries (2009)"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [
        "tvshows"
      ],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 75,
      "show_name": "The Vampire Diaries"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 48,
      "show_name": "The Shannara Chronicles (2016)"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [
        "tvshows"
      ],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 76,
      "show_name": "The Shannara Chronicles"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 49,
      "show_name": "The Originals (2013)"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [
        "tvshows"
      ],
      "latest_downloaded_episode": {
        "episode_age": "10h",
        "episode_id": 383,
        "episode_identifier": "S03E21",
        "last_downloaded_release": {
          "release_downloaded": true,
          "release_episode_id": 383,
          "release_first_seen": "Sun, 15 May 2016 05:00:28 GMT",
          "release_id": 424,
          "release_proper_count": 0,
          "release_quality": "hdtv h264",
          "release_title": "The Originals S03E21 HDTV x264-LOL"
        },
        "number_of_episodes_behind": 0
      },
      "show_id": 77,
      "show_name": "The Originals"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 50,
      "show_name": "The Magicians (2015)"
    },
    {
      "alternate_names": [],
      "begin_episode": {
        "episode_id": null,
        "episode_identifier": null
      },
      "in_tasks": [
        "tvshows"
      ],
      "latest_downloaded_episode": {
        "episode_age": null,
        "episode_id": null,
        "episode_identifier": null,
        "last_downloaded_release": null,
        "number_of_episodes_behind": null
      },
      "show_id": 78,
      "show_name": "The Magicians"
    }
  ],
  "total_number_of_pages": 7,
  "total_number_of_shows": 66
}`

**Comment by liiight** [comment]
well as far as i can see the numbered shows do not appear in any active task (under `tasks`) so they must be some junk that was left behind. i suggest you just delete those shows via CLI or API. It shouldn't happen again,
