### ISSUE TITLE
IndexError: list index out of range (piratebay search)

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#1180]
> flexget -V
> 2.0.21

```
2016-05-15 00:00 CRITICAL task          get-movies      BUG: Unhandled error in plugin discover: list index out of range
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 272, in on_task_input
    return self.execute_searches(config, entries, task)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 143, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "c:\python27\lib\site-packages\flexget\plugin.py", line 120, in wrapped_func
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\urlrewrite\piratebay.py", line 137, in search
    entry['title'] = link.contents[0]
IndexError: list index out of range
```

**Comment by cvium** [comment]
Config? Full log? Kinda need to see what it failed on. The crash log says nothing.

**Comment by lostsubstance** [comment]
The bug is just that `link.contents` does not have an index `0`.. which kills the task. I would assume this stacktrace was enough to locate and put a try/catch or length test and safely error the search, instead of letting it interrupt the entire task.

**Comment by lostsubstance** [comment]
The relevant/trimmed part of my config (though I don't think its actually helpful):
```
    discover:
      what:
        - movie_list: movies
      from:
        - piratebay:
            category: 207
            sort_by: date
```

**Comment by lostsubstance** [comment]
I should add, it doesn't seem to happen all the time. It happened once. so far. I was simply reporting the existence of a crasher. Was probably a transient error.

**Comment by cvium** [comment]
Well, I'm not just gonna throw a blanket try-except in the code without knowing the exact situation it's required. I need to know which movie caused it.

If I can't reproduce the error, I can't fix it.

**Comment by lostsubstance** [comment]
i wasn't suggesting a blanket try/catch. i was merely suggesting it be written defensively such that if the server (or a proxy) responded with malicious/bad/unknown data this plugin would handle logging an error and letting the task move on instead of crashing.

I don't know what it was looking for at the time. As i said above, i believe this to be rare and has only occurred the one time so far. this isn't blocking me. i just submitted this as a courtesy for general improvement. if it happens again, ill try to gather more info.

**Comment by cvium** [comment]
You don't have the logs preceding the crash log?
