### ISSUE TITLE
Transmission queue top feature

### ISSUE THREAD

**Issue by Addicted5** [Flexget/Flexget#1181]
Transmission add to queue top feature request.
There is already option to add to top of queue in deluge.
But not in transmission.
It'll be good to add the feature.So that certain priority downloads will be added to top.

**Comment by cvium** [comment]
I have no intention of testing my PR. If you want it merged, then feel free to test it for me.

https://github.com/Flexget/Flexget/pull/1183

**Comment by Addicted5** [comment]
No experience of doing so.(never done git work 1st time)
I just modified "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_transmission.py" as per [file changes](https://github.com/Flexget/Flexget/pull/1183/files).
Then reloaded config with "queue_position: 0".
It worked like intended
