### ISSUE TITLE
ftp_download plugin can only download directories

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#1184]
Maybe `download` plugin should handle that instead?

**Comment by crawln45** [comment]
What else would you want ftp_download to do? Try to find a specific file to download?

**Comment by liiight** [comment]
Sure. If the entry url is an ftp file and not a directory I don't see a reason that it shouldn't work.

**Comment by crawln45** [comment]
From what I see in the code it checks for file or folder. But that's as far
as I got. Lol
