### ISSUE TITLE
Linux CRON different filesystem encoding

### ISSUE THREAD

**Issue by plittlefield** [Flexget/Flexget#1185]
(from http://discuss.flexget.com/t/linux-cron-different-filesystem-encoding/2345)

Hi Folks,

I am getting this WARNING now on an hourly cron job...

    Your cron environment has different filesystem encoding (UTF-8) compared to your terminal environment (utf-8)

I cannot see what's wrong.

Here is the only **locale** installed...

    $ locale
    LANG=en_GB.UTF-8
    LANGUAGE=en_GB.UTF-8
    LC_ALL=en_GB.UTF-8

Here is my Linux **console environment**...

    $ env |egrep 'LC|LANG'
    LC_ALL=en_GB.UTF-8
    LANG=en_GB.UTF-8
    LANGUAGE=en_GB.UTF-8

At the top of my **crontab** is this...

    LC_ALL=en_GB.UTF-8
    LANG=en_GB.UTF-8
    @hourly /usr/local/bin/flexget --cron execute 

Anyone have any idea as to why it's complaining?

Thanks,

Paully

FlexGet 2.0.23
Ubuntu 14.04
Python 2.7.5

**Comment by plittlefield** [comment]
Wow, that was quick, thanks :-)

**Comment by liiight** [comment]
np
