### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1202]
#### Log:

https://nopaste.me/view/856bdbbe

I have this problem on
\u2026
\u2019
\u2018
\u2023
### Additional information:

C:\Python35\Scripts>flexget -V
2.0.27
You are on the latest release.
C:\Python35\Scripts>

**Comment by crawln45** [comment]
Provide debug logs/with --dump option so we can actually see what it's chocking on.

**Comment by crack00r** [comment]
https://nopaste.me/view/febd05a4
https://nopaste.me/view/0a79f194
https://nopaste.me/view/5040635c
https://nopaste.me/view/df90ecf5
https://nopaste.me/view/57bdf8da
https://nopaste.me/view/3ea01d5d


https://nopaste.me/view/5feb7a20

**Comment by crawln45** [comment]
Well one problem your having is your getting series in a movie task. That's just not going to work. As far as what's causing the issue. None of the movie titles or series titles are actually doing anything. Please paste your config.

**Comment by crack00r** [comment]
https://drive.google.com/file/d/0B81QzCCqll85VklMaWJESmtQV28/view

**Comment by crawln45** [comment]
Well a few issues arise. First there is no unicode in py 3.5 everything is a unicode string when it is a string and not bytes. So for your issue. I would first take a look at your external plugins. Since they are not written for py3.

**Comment by gazpachoking** [comment]
Hmm, looks like this is an error when trying to print certain characters that your terminal does not support. I believe we could change our output stream for logging and `console` function to use a stream that automatically replaces unsupported characters, haven't looked in to it yet though.
