### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by regystro** [Flexget/Flexget#1205]
Hi, I used to visit http://flexget.com/wiki/ChangeLog every new release to see changes.
Where is it now?
I know of http://flexget.com/wiki/UpgradeActions but I'd like to see minor changes too.

Thanks in advance.

**Comment by liiight** [comment]
We are currently working on a new changelog format, stay tuned.

**Comment by msj33** [comment]
*Bump*

**Comment by mundodisco8** [comment]
Yeah, looking forward to it, seeing that you are releasing almost everyday. Not that I am complaining! It's incredible the amount of effort you are putting on this, but is difficult to follow the changes, and right now we are updating to the latest version blindly, without knowing what the update will fix.
