### ISSUE TITLE
Backticks in logs

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#1207]
Is there a reason why flexget log files use backticks as quotes? It makes pasting the error messages interesting at times since the backtick is used as a formatting marker by markdown parsers.

**Comment by liiight** [comment]
Isn't that the point? What issue does this cause

**Comment by lepinkainen** [comment]
It bugs me and I want to know why. If the whole point is that the logs get automatically markdown-formatted, then why was it half-assed and the whole log line isn't markdown-enhanced?

**Comment by liiight** [comment]
So, you're saying that all issue is inconsistency? That I can get with.

**Comment by lepinkainen** [comment]
Using backticks in place of ' or " just because isn't a good reason to use them. If the purpose is to make log file snippets automagically be markdown formatted, then we need to go further with the formatting.

**Comment by liiight** [comment]
I think the root cause is that using " or ' can sometimes be a problem with the way that the string is being called. But having the logs be fully markdown ready sounds nice, but I doubt that every body will feel like that

**Comment by paranoidi** [comment]
I used backticks in logs for couple reasons
- rarely present in values anywhere else
- visually light
