### ISSUE TITLE
web ui Input payload validation failed

### ISSUE THREAD

**Issue by marine1988** [Flexget/Flexget#1216]
### Expected behaviour:

log in web ui

### Actual behaviour:

give 1 error "Input payload validation failed"

### Steps to reproduce:
- Step 1: ...

enter in web ui in version 2.0.37

#### Config:
```
web_server:
  bind: 0.0.0.0
  port: 3539
api: yes
webui: yes

```
  
#### Log:
```
Input payload validation failed
```

### Additional information:

- Flexget Version: 2.0.37
- Python Version:2.7.9
- Installation method: terminal
- OS and version: debian raspberry pi 2
- Link to crash log: none

Please verify that the following data is present before submitting your issue:

-Paste or link to a paste service ([pastebin](http://pastebin.com/) for example) of relevant config (preferably full config including templates if present. Remember to redact any personal information!
- Paste or link to a paste service of debug level logs of relevant task/s. Use `flexget -L debug execute --tasks <Task_name>`
- Flexget version (Use `flexget -V` to get it).
- Full Python version (`2.7.11` for example). Run `python -V` to get it.
- Installation method (pip, git install, etc.)
- OS and version
- Attach crash log if available

**Comment by liiight** [comment]
You're supposed to fill the relevant parts of the template, not leave them as is
