### ISSUE TITLE
"web" is ignored as a quality

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1218]
### Expected behaviour:

quality should be parsed as webrip

### Actual behaviour:

quality is parsed as '720p h264'

### Steps to reproduce:
- Step 1: ...

`flexget inject 'Powers.US.S02E01.720p.WEB.h264-DEFEATER' --task tv --dump`

#### Config:
```
series:
  tv:
    - Powers: {quality: <1080p webrip+}
```

  
#### Log:
```
2016-06-01 14:18 VERBOSE  series        tv             Ignored `Powers.US.S02E01.720p.WEB.h264-DEFEATER`. Does not meet quality requirement `<1080p webrip+`.

-- Undecided: --------------------------
title            : Powers.US.S02E01.720p.WEB.h264-DEFEATER
url              : http://localhost/inject/Gj8wRPBIkxmcu9gTtl3N2WYVzif5SL
original_url     : http://localhost/inject/Gj8wRPBIkxmcu9gTtl3N2WYVzif5SL
path             : ~/video/series/Powers/
proper           : False
proper_count     : 0
quality          : 720p h264
release_group    : None
series_episode   : 1
series_episodes  : 1
series_id        : S02E01
series_id_type   : ep
series_name      : Powers
series_parser    : <SeriesParser(data=Powers.US.S02E01.720p.WEB.h264-DEFEATER,name=Powers,id=None,season=2,episode=1,quality=720p h264,proper=0,status=OK)>
series_releases  : [91146]
series_season    : 2
task             : tv
```

### Additional information:

- Flexget Version: 2.0.38
- Python Version: 2.7.11
- Installation method: git
- OS and version: OS X

**Comment by n3mur1t0r** [comment]
As  you can see from here: http://flexget.com/wiki/Qualities
there is no "web" quality, only "webrip" or "webdl" - how is flexget supposed to know which of these two the release group meant if they only tag it as "web"?

In my opinion, it's the group's fault, not flexget's.

**Comment by grr** [comment]
"web" should map to the lowest possible choice, so it should map to "webrip". It's not like this was an uncommon mistake by a single group, "web" is used a lot by many groups. So it should be handled. Or there should at least be a way for users to create custom qualities without having to resort to an inaccurate use of the manipulate plugin.

**Comment by duramato** [comment]
FYI WEB is the Scene's equivalent  to the p2p groups web-dl naming

**Comment by grr** [comment]
But most of the groups that use WEB are not part of the scene and they use it for webrip quality. You can see here that most of the WEB torrents are webrips:
https://kat.cr/usearch/%22web%22%20-webdl%20-%22web%20dl%22%20-webrip%20category%3Atv/2/

On a related note, I did just stumble across one I hadn't seen before: WEBCAP. That's clearly webrip quality and flexget doesn't handle that one.

**Comment by duramato** [comment]
All the ones i see there except the one group with the x265 releases are scene
Scene releases: http://pre.c-burns.co.uk/pre.php?searchtext=WEB.h264

**Comment by liiight** [comment]
This should be recognized as `webrip`. Pushing a fix now.

**Comment by liiight** [comment]
I rushed the fix, need to fix a bunch more stuff to do this properly...

**Comment by grr** [comment]
any word on this?

**Comment by liiight** [comment]
A much needed touch up to entire qualities module is planned, this will be a part of that

**Comment by grr** [comment]
is there a ticket for that project so we can follow it? would like to know how long we have to manually download the shows that have this issue.

**Comment by cvium** [comment]
Next release will have `web`, `webdl` and `webrip` grouped together.

**Comment by grr** [comment]
please reconsider this.  webrip and web-dl are not similar quality-wise in the majority of cases. i also have many entries in my config to allow webrip, but exclude web-dl for series on showtime and hbo, because web-dl from those stations have been censored in the past.

**Comment by cvium** [comment]
Hmm. I guess we could have webrip/web > web-dl.

**Comment by grr** [comment]
i'd argue keep it how it was: 
https://forums.sonarr.tv/t/web-dl-webrip-quality-profiles-should-be-separated/4473
nothing has changed on this front.

**Comment by cvium** [comment]
I don't agree with his sentiment at all. web-dl includes iTunes releases which vary quite heavily in quality.

**Comment by grr** [comment]
before this drastic change is made, can we get more opinions first? i think for now we're only agreeing that webrip == web. and we're disagreeing which is better quality, web-dl or webrip.

**Comment by grr** [comment]
this summary seems to best summarize my position: https://www.reddit.com/r/trackers/comments/3d0na9/question_about_web_sourced_releases/ct0q2t0

**Comment by grr** [comment]
also, webcap shoud be added. from wikipedia:

> WEBCap	WEB-Cap
> Common, WEBRip/WEB-DL is preferred
> This is a rip created by capturing video from a DRM-enabled streaming service, such as Amazon Instant or Netflix. Quality can range from mediocre (comparable with low quality XVID encodes) to excellent (comparable with high quality BR encodes). Essentially, the quality of the image obtained depends on internet connection speed and the specifications of the recording machine.

**Comment by cvium** [comment]
Guessit parses `web` as `web-dl`. So I'm not entirely sure how to do this.

**Comment by cvium** [comment]
Reverted the changes until I can figure out if `web` is `web-dl` or `webrip`. Research leads me to believe it's `webrip`, but then we have to make a PR on guessit.

**Comment by duramato** [comment]
Per scene it is web-dl and tbh i don't see any others using it other than scene using, many of the others. 
And per the Scene Rules for web https://scenerules.org/t.html?id=wdx264v1.0-ecb63c67.nfo
```1) [ Untouched: WEB.H264 / WEB.x264 ]    ```
and
```3) [ Transcoded: WEBRip.x264 ] ```
