### ISSUE TITLE
[trakt_lookup] 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by cvium** [Flexget/Flexget#1219]
### Expected behaviour:
No crashes plzzz
### Actual behaviour:
Crashes
### Steps to reproduce:
- Step 1: Inject entry into task. Watch it burn.

#### Config:
Soon™
  
#### Log:
Soon™
### Additional information:

- Flexget Version: 2.0.37
- Python Version: Python 2.7.9
- Installation method: pip
- OS and version: `Linux osmc 4.4.6-3-osmc #1 SMP PREEMPT Fri Apr 1 20:55:03 UTC 2016 armv7l GNU/Linux`
- Link to crash log: included in paste

**Comment by effemmeffe** [comment]
Same here.
Config: https://github.com/effemmeffe/flexget/blob/master/config.yml
Crash log: http://pastebin.com/U06ZYA6b

**Comment by frumpymoons** [comment]
Config: http://pastebin.com/4GnPn2mB
Crash: http://pastebin.com/UhGfttyX

**Comment by Tommatheussen** [comment]
I'm not sure, but this might have been fixed by Trakt itself, according to their API changelog, the genres and translations now return an empty array. https://apiblog.trakt.tv/api-changelog-9f4041819718#.cnnxpe7ma

**Comment by liiight** [comment]
yeah, looks like. anyone that experienced this, can you please report if this still happens?

**Comment by effemmeffe** [comment]
Executing ringht now, will report as soon as it ends.

**Comment by effemmeffe** [comment]
Nope, still there.
I did a flexget update and daemon restart just in case.
debug log: http://pastebin.com/VcZjWT8U

**Comment by liiight** [comment]
hmm, try resetting the table first, maybe loaded stuff from cache:
`flexget database reset-plugin api_trakt`

**Comment by effemmeffe** [comment]
No luck: http://pastebin.com/Kbj7PFnh

**Comment by liiight** [comment]
k, thanks for trying
