### ISSUE TITLE
Crashes after upgrade, unable to reinstall

### ISSUE THREAD

**Issue by antiartist** [Flexget/Flexget#1220]
### Expected behaviour:  
Flexget check should check the config.yml file for errors.  Instead, it crashes.

### Actual behaviour:
Error that ends with:
> sqlalchemy.exc.InvalidRequestError: Table 't411_accounts' is already defined for this MetaData instance. Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

See paste for full error: http://pastie.org/private/ohbriyccjphgrl9f0yrrg

### Steps to reproduce:
- Step 1: run "flexget check", which crashes
- Step 2: upgrade pip 1.5.4 to 8.1.2
- Step 3: realize that upgrading pip has made matters worse because now "pip install --upgrade --force-reinstall flexget" now also crashes

#### Config:
n/a
  
#### Log:
Error attempting to execute flexget check: http://pastie.org/private/ohbriyccjphgrl9f0yrrg 
Error attempting to force reinstall flexget: http://pastie.org/private/fio0s6koepcorbbaj6b8ow

### Additional information:

- Flexget Version: 2.0.34 (unable to upgrade to 2.0.39 
- Python Version: 2.7.10
- Setuptools Version: 22.0.0
- Installation method: pip (version 8.1.2
- OS and version: Ubuntu 14.04 LTS

**Comment by antiartist** [comment]
Removing the distribute package seems to have resolved the issue. 

See 
http://discuss.flexget.com/t/crashes-after-upgrade-unable-to-reinstall/2379/7

**Comment by paranoidi** [comment]
Yay \o/
