### ISSUE TITLE
[feature request] Log management

### ISSUE THREAD

**Issue by Addicted5** [Flexget/Flexget#1221]
**1**.Default log folder is inside config directory.
Why not move it to "log" folder inside config directory.
e.g - /home/{username}/.config/flexget/log"
or "/home/{username}/.flexget/log"

I have defined custom log path in my "/etc/default/flexget" file.
So log is stored inside "log" folder.
But once in a while "flexget.log" is created in config directory.(may be when i run with custom log level)

Advantage:
Easier to recognize log files.
I even once deleted old log file along with a part of config (horrible.yml just below flexget.log)
Log level such as verbose or debug will created a lot of log.& old log files.So better to have it's own directory

**2.**I came across with logrotate that manages logs.(although still figuring out how to config it properly)
    It seems ideal to store old log in gzip achieve with compression.(debug creates a lot of log)
   May be instead of moving old log file to flexget.log.1,flexget.log.2 after 1000KB reached ,we can compress them with gzip

**Comment by effemmeffe** [comment]
This would be easy by using the system logrotate. It would allow to control how many log files will be crated, the location and even the zipping of the old logs.

**Comment by liiight** [comment]
cool, open a pr then

**Comment by effemmeffe** [comment]
pr?

**Comment by liiight** [comment]
[Pull Request](https://help.github.com/articles/using-pull-requests/)

**Comment by effemmeffe** [comment]
If I undestand it correctly opening a pull request would require from me to know how to add a feature, right?

**Comment by liiight** [comment]
i assumed you did, you suggested an implementation...

**Comment by effemmeffe** [comment]
I didn't want to be rude or something.
I just pointed out that logrotate does exactly what Addicted5 and I would like to see as a feature.
If I was somehow overstepping I apologize.
If adding requests or contribution to the discussion is not welcome I'll stop immediately.

**Comment by liiight** [comment]
i'm sorry if it seem i was being sarcastic, i was genuinely saying it's a good idea and thought that you suggested of doing it :-)
all additions are always welcome, this is just a misunderstanding.

**Comment by effemmeffe** [comment]
Ok. English is not my primary language, so I'm always concerned that I miss some tone in the discussion...
All clear now, thanks for being straightforward.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
