### ISSUE TITLE
WebUI Doesn't load after upgrade

### ISSUE THREAD

**Issue by Addicted5** [Flexget/Flexget#1232]
Hi,I upgraded to 2.0.42 from 2.0.41.
After upgrade UI page doesn't show anything.
It shows  that loading animation then a blank page.
While api page loads normally.
Config passes check correctly.Daemon running normally(just checked log file & it seems okay as it produced entries as supposed to due to scheduled exec)

**Comment by Tommatheussen** [comment]
Hmm, after first debugging, it seems that the 2.0.42 version installs JQuery v3 for some reason, which is not compatible with bootstrap.js. Downgrading to 2.0.41 does seem to work again, I will push a limit in the Jquery version to fix this
