### ISSUE TITLE
BUG: api_trakt crashes when trakt show does not have genre and/or translation

### ISSUE THREAD

**Issue by cuccuizzo** [Flexget/Flexget#1241]
### Expected behaviour:
Remove show from trakt list if show is collected and ended or cancelled

### Actual behaviour:
Crash

### Steps to reproduce:
- Step 1: add a show with no translation or genre to a trakt list
- Step 2: try to remove the show from the list

#### Config:
  clean-trakt:
    priority: 4

    trakt_list:
      account: <account>
      list: <list_name>
      type: shows

    trakt_lookup:
      account: <account>

    if:
      - trakt_collected and trakt_series_status == 'ended': accept
      - trakt_collected and trakt_series_status == 'canceled': accept

    list_remove:
      - trakt_list:
          account: <account>
          list: <list_name>
  
#### Log:
http://pastebin.com/KPet6f9f

#### Proposed solution:
Check in get_db_genres if genres variable is not null.
Check in get_db_trans if transf variable is not null.
See http://pastebin.com/qQGPVD5s

### Additional information:

- Flexget Version: 2.0.48
- Python Version: 2.7.3
- Installation method: pip/virtualenv
- OS and version: Ubuntu 12.04
- Link to crash log: http://pastebin.com/hezxvff6

**Comment by liiight** [comment]
Thanks for the detailed issue, we'll add the data to #1219
