### ISSUE TITLE
Unhandled error in lazy lookup plugin - Trakt

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1242]
### Expected behaviour:
No errors.

### Actual behaviour:
Critical error as shown in log - though the task then completes successfully. Running this task today generated 72 identical critical errors for different items (vs 300 items in the feed it's reading) each time it ran; the number of crashes per run varies.

### Steps to reproduce:
- Step 1: Unsure. I do not use the "trans" (translation? language?) field anywhere in my config. As you can see from the config, I used to check genre, but that was causing these same critical errors in Flexget v1.2.458. I commented those lines out, but the errors continued to be generated about genre, despite the fact it was no longer used anywhere in the config file. I then upgraded Flexget to see if it was resolved. Now it's mentioning a different field in the error.

#### Config:
http://pastebin.com/UHEucBxt
  
#### Log:
Part 1: http://pastebin.com/pFKP8X2U
Part 2: http://pastebin.com/jb4r3Lhj
Part 3: http://pastebin.com/hL6LNPkE

### Additional information:
- Flexget Version: 2.0.47
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Mac OS X 10.10.2
- Link to crash log: http://pastebin.com/s5PhrS3X

**Comment by liiight** [comment]
Thanks for the detailed issue, we'll add this to #1219
