### ISSUE TITLE
t411 : Animation category

### ISSUE THREAD

**Issue by Clem-** [Flexget/Flexget#1243]
### Expected behavior:

When searching for movies in "Animation" category with t411 plugins, it looks for a category beginning with "Animation" (as described in [wiki](http://flexget.com/wiki/Plugins/t411)).
### Actual behaviour:

The problem is that there is two categories beginning with Animation :
`Animation` (pid 455) and `Animation Série` (pid 637)
so the following error occurs :

> Multiple rows were found for one()

and the task fails.
#### Config:

```
  animMulti:
    discover:
      what:
        - movie_list: IMDbVO
      from:
        - t411:
            category: Animation

```
#### Log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 272, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 143, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 120, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_torrent411.py", line 99, in search
    search_result = proxy.search(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_t411.py", line 658, in search
    client_query = self.friendly_query_to_client_query(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_t411.py", line 478, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_t411.py", line 627, in friendly_query_to_client_query
    .filter(Category.name == friendly_query.category_name) \
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2727, in one
    "Multiple rows were found for one()")
MultipleResultsFound: Multiple rows were found for one()
```

**Comment by Icesenator** [comment]
Same issue here, I try with PID & ID but it also don't work.

**Comment by Clem-** [comment]
Yep, in order to make it work, I'm using the IF plugin:
```
    if:
      - t411_category != 455: reject
```
You'll also have to use the `t411_lookup: fill` to be able to filter according to t411_category.

Cheers.

**Comment by Icesenator** [comment]
J'avais déjà essayer avant de redemander mais j'ai toujours la même erreur
"Multiple rows were found for one ()"
I tried but I have the same issue.

Au niveau de la catégorie tu plugin t411, tu as mis quoi ?
What do you put in category for t411 plugin ?

Le mar. 5 juil. 2016 à 16:37, Clément E. <notifications@github.com> a
écrit :

**Comment by Clem-** [comment]
Oui il faut en fait mettre la catégorie "Film/Vidéo" dans ton plugin t411
(et non Animation).
You have to change the category parameter of t411 plugin from Animation to
"Film/Vidéo".

2016-07-05 16:51 GMT+02:00 Icesenator <notifications@github.com>:

**Comment by Icesenator** [comment]
Étrange maintenant que j'ai mis " Film/Vidéo" j'ai regardé un peu les inputs généré et il y a de tout. Des music, des magasins, des séries, des jeux...

**Comment by Clem-** [comment]
Oui. Et le filtre IF que j'ai proposé dans ma première réponse devrait rejeter toutes les entrées ne correspondant pas au PID du filtre.

**Comment by Icesenator** [comment]
Oki il faut que je m'arrange pour que le filtre PID passe avant le lookup
et ca m'ira :) Merci à toi !

Le mar. 5 juil. 2016 à 17:37, Clément E. <notifications@github.com> a
écrit :

> Oui. Et le filtre IF que j'ai proposé dans ma première réponse devrait
> rejeter toutes les entrées ne correspondant pas au PID du filtre.
>

**Comment by lildadou** [comment]
For mainteners:
It seems that the autocomplete tag name feature was a mistake. I will remove it for fixing the bug. Fixing scheduled for thix weekend.

Bonsoir et merci pour le ticket.
C'est la seconde fois que la possibilité de ne pas remplir complètement les tags cause des problème. Je vais retirer cette fonctionnalité. 

@Icesenator a écrit :
> Étrange maintenant que j'ai mis " Film/Vidéo" j'ai regardé un peu les inputs généré et il y a de tout. Des music, des magasins, des séries, des jeux... Et il fait un lookup Imdb avec tout ça ! Les terms ne sont également pas appliqué.

Ce n'est pas un bug. Tapes çà pour voir que la catégorie Film/Vidéo n'est associé à aucun type de terme : `flexget t411 list-terms --category "Film/Vidéo"`

**Comment by cvium** [comment]
Site is dead
