### ISSUE TITLE
Deluge plugin - client not defined error.

### ISSUE THREAD

**Issue by aazimh** [Flexget/Flexget#1252]
### Expected behaviour:

'flexget execute' works as expected.

### Actual behaviour:

Get the following error when running 'flexget execute'. 'flexget test' works perfectly, as does 'flexget check'.

`2016-06-26 19:53 CRITICAL task          test task       BUG: Unhandled error in plugin deluge: global name 'client' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_deluge.py", line 418, in on_task_output
    self.connect(task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_deluge.py", line 204, in connect
    client.set_disconnect_callback(self.on_disconnect)
NameError: global name 'client' is not defined
`

#### Config:

Config.yml:

http://pastebin.com/mv1CwiLk

### Additional information:

- Flexget Version: 2.1.1
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Raspbian

Any and all help appreciated!

**Comment by cvium** [comment]
Have you installed `deluge-common`?

**Comment by aazimh** [comment]
Yes, I have:

> Package: deluge-common
> Status: install ok installed
> Priority: optional
> Section: net
> Installed-Size: 4712
> Maintainer: Cristian Greco <cristian@debian.org>
> Architecture: all
> Source: deluge
> Version: 1.3.10-3
> Replaces: deluge-core (<< 1.2.0~rc1-1), deluge-torrent (<< 1.0.7.dfsg-1), deluge-torrent-common (<< 1.0.7.dfsg-1)
> Depends: python (>= 2.7), python (<< 2.8), python-twisted-web, python-openssl, python-pkg-resources, python-chardet, python-xdg, geoip-database
> Breaks: deluge-core (<< 1.2.0~rc1-1), deluge-torrent (<< 1.0.7.dfsg-1), deluge-torrent-common (<< 1.0.7.dfsg-1)
> Description: bittorrent client written in Python/PyGTK (common files)
>  Deluge is a full-featured, multi-platform, multi-interface BitTorrent client
>  using libtorrent-rasterbar in it's backend and featuring multiple
>  user-interfaces: GTK+, web and console.
>  .
>  It has been designed using the client-server model with a daemon process that
>  handles all the bittorrent activity. The Deluge daemon is able to run on
>  headless machines with the user-interfaces being able to connect remotely
>  from any platform.
>  .
>  This package contains data files commons to both the daemon and the
>  various user-interfaces.
> Homepage: http://www.deluge-torrent.org/
>

**Comment by aazimh** [comment]
When in doubt, reboot :) works now! Sorry for the unnecessary issue. Closing now.
