### ISSUE TITLE
Trakt_released field data type

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#1260]
### Expected behaviour:
Trakt_released should have the same type as tmdb_released, to be consistent across similar fields on different lookups. Changing lookups should not break stuff after updating the field names.

### Actual behaviour:
Trakt_released is a Date field, tmdb_released is a DateTime field, causing some stuff to function differently.

### Steps to reproduce:
- Step 1: Update first config to second config
- Step 2: Check logs from the IF statement

#### Config:
First config
```
  tmdb_lookup: yes
  if:
    - tmdb_released > now - timedelta(days=30): reject
```
Second config
```
  trakt_lookup: yes
  if:
    - trakt_released > now - timedelta(days=30): reject
```
  
#### Log:
First config, no logs related to if statement (other than normal reject)
Second config:
```
2016-06-28 15:12 ERROR    if            FillMovieQueue  Error occured while evaluating statement `trakt_released > now - timedelta(days=30)`. (can't compare datetime.datetime to datetime.date)
2016-06-28 15:12 ERROR    if            FillMovieQueue  Error occured while evaluating statement `trakt_released > now - timedelta(days=30)`. (can't compare datetime.datetime to datetime.date)
2016-06-28 15:12 ERROR    if            FillMovieQueue  Error occured while evaluating statement `trakt_released > now - timedelta(days=30)`. (can't compare datetime.datetime to datetime.date)
```

### Additional information:

- Flexget Version: 2.1.3
- Python Version: 2.7.6
- Installation method: Pip
- OS and version: Ubuntu 14.04 32bit

**Comment by crawln45** [comment]
Not a bug with trakt was done because there is no time on a release date. so there's no reason to add on extra data fields for no reason. Furthermore might want to look at how if handles this because datetime.date(2015, 11, 16) - datetime.timedelta(days=30) produces no error.
```
>>> datetime.date(2015,11,16) - datetime.timedelta(days=30)
datetime.date(2015, 10, 17)
>>> datetime.datetime(2015,11,16) - datetime.timedelta(days=30)
datetime.datetime(2015, 10, 17, 0, 0)
```

**Comment by liiight** [comment]
I disagree. DateTime is the de facto standard for thus data types in db, and is what's expected as an output when comparing. 
We already have to do some manipulation to use it in the api, now there's also this issue. The downside to use DateTime is non existing IMO.

**Comment by liiight** [comment]
Maybe there's a way to do it in both our ways by create a `date_synonym` that will allow getting DateTime from a Date field

**Comment by cvium** [comment]
@crawln45 Obviously the reason to add redundant data is to have consistency. Much more important than saving a few bytes.

I vote to change it.

**Comment by gazpachoking** [comment]
Is the issue just with an if statement? Could always do `trakt_released > now.date() - timedelta(days=30)`

**Comment by cvium** [comment]
To maintain some level of consistency it has been decided that movie release date fields should be Date. Will be changed in next major version.
