### ISSUE TITLE
rottentomatoes API

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1273]
> 2016-07-12 06:55 VERBOSE  api_rottentomatoes Movies_Watchlist_Stream_DE Searching from rt `mr poppers pinguine german dl`
> 2016-07-12 06:55 WARNING  api_rottentomatoes Movies_Watchlist_Stream_DE Request failed http://api.rottentomatoes.com/api/public/v1.0/movies.json?q=mr+poppers+pinguine+german+dl&apikey=rh8chjzp8vu6gnpwj88736uv: 403 Client Error: Forbidden for url: http://api.rottentomatoes.com/api/public/v1.0/movies.json?q=mr+poppers+pinguine+german+dl&apikey=rh8chjzp8vu6gnpwj88736uv
> 2016-07-12 06:55 INFO     rottentomatoes_lookup Movies_Watchlist_Stream_DE No results found from rotten tomatoes for <title=mr poppers pinguine german dl,year=none,rottentomatoes_id=none>
> 2016-07-12 06:55 VERBOSE  movie_list    Movies_Watchlist_Stream_DE trying to match movie based of name: Mr Poppers Pinguine German Dl and year: None
> 

{"error":"Account Inactive"}

**Comment by liiight** [comment]
There are a bunch of stuff that are required to be filled when submitting an issue. Please do not ignore them.
