### ISSUE TITLE
trakt ([Errno 2] No such file or directory

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1276]
trakt ([Errno 2] No such file or directory

Error:
http://nopaste.linux-dev.org/?1119460

Config:
https://github.com/crack00r/Flexget-Config

**Comment by crack00r** [comment]
nobody?

**Comment by liiight** [comment]
Looks like a momentary connectivity issue with Trakt. Does this reoccur?

**Comment by crack00r** [comment]
jup, cant get it working

**Comment by crack00r** [comment]
old and new i get

C:\Users\Manuel>flexget trakt auth crack00r ***
Warning: PIN authorization has been deprecated. Use Device Authorization instead.
Authorization failed: Token exchange with trakt failed: [Errno 2] No such file or directory

C:\Users\Manuel>



C:\Users\Manuel>flexget trakt auth crack00r
Authorization failed: Device authorization with Trakt.tv failed: [Errno 2] No such file or directory

C:\Users\Manuel>

**Comment by cvium** [comment]
It looks like it's an SSLError, but I don't think it has anything to do with Flexget but rather your environment.

**Comment by liiight** [comment]
Which version of python are you using?

**Comment by cvium** [comment]
No one else seems to have this issue and some quick Googling makes me thing this is an issue with OpenSSL, location of your certs and `requests` library. It's not something we can fix.
