### ISSUE TITLE
After upgrading FlexGet throws error when loading flexget.plugins.output.send_telegram

### ISSUE THREAD

**Issue by izeen** [Flexget/Flexget#1293]
Hello!

After upgrading flexget to the latest version: 2.1.20 from 2.0.X i can no longer execute flexget,

Throws an error about: Exception while loading plugin flexget.plugins.output.send_telegram

 Table 'telegram_chat_ids' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

im on python 2.7.12 and Ubuntu LTS 16.04, its installed through pip.

Debug log:
http://pastebin.com/5h8ce6Pv

**Comment by liiight** [comment]
Try to delete all .pyc files

**Comment by izeen** [comment]
Sorry but from where :) ?

**Comment by liiight** [comment]
`/usr/local/lib/python2.7/dist-packages/flexget/` recursively

**Comment by izeen** [comment]
same results, do i need to reinstall it after the deletion of the .pyc files?

**Comment by liiight** [comment]
Are you sure you deleted them all? Especially `send_telegram.py` since that file had been renamed and no longer exist.

**Comment by izeen** [comment]
you said all .pyc files? i deleted no files ending with .py

**Comment by izeen** [comment]
i ran, sudo find . -name "*.pyc" -type f -delete
