### ISSUE TITLE
BUG: Unhandled exception during task queue run loop. Python error

### ISSUE THREAD

**Issue by Merwenus** [Flexget/Flexget#1298]
### Expected behaviour:
Tasks 'Anime' run without error and it did, but updated flexget (for web service) and python in the last few weeks and error occured.

### Actual behaviour:
BUG: Unhandled exception during task queue run loop.

#### Config:
http://pastebin.com/Di6CHWQz
  
#### Log:
http://pastebin.com/QPhQm7Sr3
flexget -L debug execute --tasks Anime --no-cache
http://pastebin.com/zEYgDgTC

### Additional information:
Synology DS215J
- Flexget Version: v2.1.24
- Python Version: Python v2.7.11-15
- Installation method: Pip instal
- OS and version: Synology OS 6.1
- Link to crash log:
http://pastebin.com/QPhQm7Sr
http://pastebin.com/zEYgDgTC

**Comment by Merwenus** [comment]
It seems like this row causes it in Anime task:
parsing:
series: guessit

Without it it works fine (or at least no error message in the last 10 hours)

**Comment by cvium** [comment]
This is a bug in Guessit. Should be fixed in Guessit 2.1.1 (as of today, not released yet). https://github.com/guessit-io/guessit/issues/326

**Comment by cvium** [comment]
I've pushed a "fix" that will at least make it stop crashing. The issue should be fully resolved once guessit 2.1.1 is released (or install from git).

Closing this.
