### ISSUE TITLE
PTY allocation request failed on channel 0

### ISSUE THREAD

**Issue by mvaladas** [Flexget/Flexget#1322]
After flexget daemon has been running for some hours, when I try to SSH back to my synology machine, I get the following:

1. after SSH command:
 `ssh <host>`
2. i get the following output
 ` PTY allocation request failed on channel 0`
3. If I stop the daemon, I get normal behaviour as usual

It seems the flex get daemon is preventing PTY allocations after its been running for a while

**Comment by cvium** [comment]
When the issue arises, could you try executing `lsof /dev/pts/*` and pasting the output?

No one else seems to have this issue.

**Comment by mvaladas** [comment]
As luck would have it. I haven't seen the issue after the last restart of the daemon.
When it happens again I'll be sure to post the output.

**Comment by crawln45** [comment]
Flexget has 0% ability to affect pty sessions.

**Comment by mvaladas** [comment]
Okay. It seems I wrongly diagnosed flexget as the problem.
Sorry about that. Closing
