### ISSUE TITLE
Undefined variables in email plugin

### ISSUE THREAD

**Issue by sideeffffect** [Flexget/Flexget#1324]
### Expected behaviour:

I expect `now` and `tvdb` variables to be defined. They are not (all) defined.

### Actual behaviour:

e.g.
```
2016-08-12 00:31 ERROR    email         1_1080p_Preacher Error rendering email body: (UndefinedError) 'now' is undefined
```

also `tvdb_banner_url` is not defined and `tvdb_ep_image_url` is not defined, even though the are on thetvdb.com: [1](https://thetvdb.com/?tab=series&id=300472&lid=7), [2](https://thetvdb.com/?tab=episode&seriesid=300472&seasonid=660023&id=5672161&lid=7)

(on the other hand, some tvdb variables are available, like `tvdb_ep_name`, `tvdb_ep_air_date`, `tvdb_ep_rating`

### Steps to reproduce:

run flexget with the specific configuration

#### Config:

I'm referring to the configuration and email template at https://github.com/sideeffffect/flexgen

### Additional information:

- Flexget Version: 2.2.15
- Python Version: Python 2.7.6
- Installation method: pip
- OS and version: Ubuntu 14.04, `Linux odroid 3.8.13.28 #1 SMP PREEMPT Wed Dec 3 18:40:50 BRST 2014 armv7l armv7l armv7l GNU/Linux`

**Comment by crawln45** [comment]
You expect to much. "Now" is always available in jinja since it's actually datetime.now(). 2nd Sometimes not all fields are populated. are these fields that are constantly coming up as invalid. Or is it only sometimes. Logs would help in this affect. Also you can help by further using --dump while executing to see all populated fields that way we know what series is having issues because without that this will not be resolved.

**Comment by sideeffffect** [comment]
ok, so the `tvdb_banner_url` and `tvdb_ep_image_url` is just wrong, documentation. it was changed to `tvdb_banner` and `tvdb_ep_image`.
I have fixed the documentation: [wiki](http://flexget.com/_compare/Plugins/thetvdb_lookup/d0cd09df92507fee8249b17f16ca16f9b44380dd..ae616a5b9ac7e3651d5990ef8ac0201777c9b9cc), https://github.com/Flexget/Flexget/pull/1332

but `now` is still a problem! it's not reported from `--dump`. all I see in logs is this:

```
2016-08-12 23:18 ERROR    email         1_1080p_Preacher Error rendering email body: (UndefinedError) 'now' is undefined
```

could somebody please help me debug this?
