### ISSUE TITLE
missing rss feed for UpgradeActions wiki page

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1349]
The old trac wiki allowed pages to be watched using rss. This was very helpful so we could automatically be notified when the UpgradeActions page was changed. With the switch to the realms wiki, there is no longer an rss feed and users have to manually check the page.

**Comment by liiight** [comment]
https://github.com/scragg0x/realms-wiki/issues/11

**Comment by liiight** [comment]
Closing since this is not flexget related.

**Comment by grr** [comment]
Are you saying the flexget website has nothing to do with flexget?

**Comment by cvium** [comment]
The wiki is not related to this repo.
