### ISSUE TITLE
Config not available in webui since 2.3.0

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1350]
### Expected behaviour:

Config should show in the config tab of the webui

### Actual behaviour:
Tab opens but with no config, "save and apply button is grey"

### Steps to reproduce:
- Step 1: go in webui and click config ;)

#### Config:
 N/A
  
#### Log:
N/A

### Additional information:

- Flexget Version: 2.3.0
- Python Version:  Python 2.7.11
- Installation method: pip
- OS and version: Synology
- Link to crash log: None

**Comment by liiight** [comment]
What's your command to execute flexget?

**Comment by Tommatheussen** [comment]
Hmm, just upgraded myself and seeing this as well. I see that the config is still being loaded from the API, so the problem lies in the UI itself. Will investigate when I have the time, could be a package version issue.

**Comment by Tommatheussen** [comment]
Should be fixed in next release, reopen if not.
