### ISSUE TITLE
Imdb movie title updates not propagating to movie_list 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#1356]
### Expected behaviour:
When a movie is added to the imdb watchlist and then added to movie_list. If imdb website updates the title of the movie, the new information should update on your movie_list 
### Actual behaviour:
When a movie title is updated on imdb website, the updated title will not propagate to the movie_list. 
### Steps to reproduce:
- Step 1: add movies to imdb watchlist on website 

#### Config:
```
http://pastebin.com/VBbnRpUy

```
  
#### Log:
```
when it was originally added it was 
Untitled Matt Damon/Bourne Sequel │ 2016 │ │ tt4196776 │ │ │ 
and that's what is in my movie_list and it will not update. 
```

### Additional information:

- Flexget Version: 2.3.0
- Python Version:2.7.9
- Installation method: pip
- OS and version: raspbian
- Link to crash log: n/a

Please verify that the following data is present before submitting your issue:

-Paste or link to a paste service ([pastebin](http://pastebin.com/) for example) of relevant config (preferably full config including templates if present. Remember to redact any personal information!
- Paste or link to a paste service of debug level logs of relevant task/s. Use `flexget -L debug execute --tasks <Task_name>`
- Flexget version (Use `flexget -V` to get it).
- Full Python version (`2.7.11` for example). Run `python -V` to get it.
- Installation method (pip, git install, etc.)
- OS and version
- Attach crash log if available

**Comment by liiight** [comment]
I think the way too approach this would be to add a refresh command via CLI/API. This is very low priority though since this does not affect matching at all, so don't hold your breath...

**Comment by cvium** [comment]
@liiight You should edit this issue to better reflect your intention then. The answer to the original issue is just to use
```
seen:
  fields: [title]
```
in the "movie list filling" task.

**Comment by liiight** [comment]
The original issue is not even linked here

**Comment by chewy74** [comment]
Original issue 

http://discuss.flexget.com/t/imdb-watchlist/2628/10

**Comment by paranoidi** [comment]
AFIK this will also create duplicate entries in movie_list? If so I would not consider this low priority.

**Comment by liiight** [comment]
nah, movie list looks via identifier, and that doesn't change. it doesn't even affect matching (as long as target imdb_id and movie in movie_list imdb_id are the same).

**Comment by chewy74** [comment]
But if the original title attached to that imdb identifier gets updated after its added to the movie_list, it won't update the title and when searching that movie it will use the outdated title and never match /Download

So if you add a movie that's still in production and has a generic name before it's finalized and released, it will be added to your movie_list. When the movie is released and the movie name is finalized and changes, but the imdb Id remains the same, the movie name on your movie_list will not update to the new movie name... Searches for that movie will use the old and incorrect title name and won't match or download.  This is probably the 3rd time it's happened to me.

**Comment by cvium** [comment]
@chewy74 this issue is about API / Web UI. It will not affect the problem you're having.

**Comment by crawln45** [comment]
The problem isn't anything but the fact that a movie was added to the movie_list before it's release date. Even though it had an IMDB ID. IMDB name came back as something other than the movie's title at release time because it was in preproduction. A simpler fix would be to monitor movies released dates and check the metadata for updated information when it's released.

**Comment by liiight** [comment]
@chewy74 as long as both names will resolve to the same identifier via lookup, it doesn't matter.

**Comment by cvium** [comment]
@crawln45 movie_list should not do any such thing if you ask me.

**Comment by chewy74** [comment]
@crawln45 exactly! 
@liiight but search like the discover plugin searches for matches via titles from rss feeds and not the identifier (imdb Id?) correct?

**Comment by paranoidi** [comment]
When adding to movie list it needs to be smart enough to see that the ID already exists and simply update the title.

**Comment by cvium** [comment]
@paranoidi it is. Problem is when you have a `fill_movie_list` task. `seen` plugin rejects it because it matches a seen URL.

Dunno how it affects API.

**Comment by liiight** [comment]
Right, discover. Guess I'll remove the low priority label. 
I'm thinking of adding a `refresh` cli/api method. You think we need to add something in task as well?

**Comment by liiight** [comment]
@paranoidi that would require changing how lists work entirely...

**Comment by chewy74** [comment]
@paranoidi yes, that's exactly it

**Comment by liiight** [comment]
I was thinking about this, maybe we add a `metadata_refresh` event that will triggered refreshing all metadata from lookup providers. We can run it weekly or something, similar to db cleanup.

**Comment by liiight** [comment]
On second thought, @cvium's idea fits best. use:
```yaml
seen:
  fields: [title]
```
in your add task.
