### ISSUE TITLE
Plugin rutracker_auth does not work

### ISSUE THREAD

**Issue by movalex** [Flexget/Flexget#1360]
Due to [this](http://flexget.com/Plugins/rutracker) page, rutracker_auth plugin should work, but instead it is removed from v2.3.0

### Expected behaviour:
    flexget check >> Config passed check
### Actual behaviour:
    flexget check >> The key `rutracker_auth` is not valid here. Only known plugin names are valid keys
### Steps to reproduce:
if rutracker_auth is configured, error "The key `rutracker_auth` is not valid here. Only known plugin names are valid keys" is showed
#### Config:
```
rutracker_auth:
  username: 'username_here'
  password: 'password_here'
```
  
#### Log:
```
2016-08-21 15:54 VERBOSE  check                         Pre-checked 62 configuration lines
2016-08-21 15:54 CRITICAL manager                       [/templates/global] The key `rutracker_auth` is not valid here. Only known plugin names are valid keys.
2016-08-21 15:54 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
Could not start manager: Did not pass schema validation.
```

### Additional information:

- Flexget Version: 2.3.3
- Python Version: 2.7.12
- Installation method: pip install flexget
- OS and version: OSX 10.11.6

**Comment by OmgOhnoes** [comment]
A number of plugins have been removed in the 2.3.0 version. They can be seen in the [upgrade actions](http://flexget.com/UpgradeActions) page. Some of them simply no longer work, others i'm not sure the reason for their removal. Basically the wiki is out of date, if you want to continue using the rutracker_auth plugin you can get it from the last version of Flexget and put it in a "plugins" folder under your Flexget configuration.

**Comment by cvium** [comment]
rutracker was readded in 2.3.4
