### ISSUE TITLE
Using --help with passed config fails

### ISSUE THREAD

**Issue by Meliox** [Flexget/Flexget#1372]
### Expected behaviour:

$ flexget execute --help
usage: flexget execute [-h] [--tasks TASK [TASK ...]] [--learn] [--no-cache]
etc...

Should read the config that is passed as an argument (or better ignore it, as I don't think it has any uses)

--help argument should have shown help. Similar problems most likely happen with other arguments.
### Actual behaviour:

Reports: "Failed to find configuration file config.yml"
### Steps to reproduce:
- Step 1: Create a config with another naming than config.yml -->
  ~/.flexget$ ls
  autodl.yml
- Step 2: flexget **-c autodl.yml** execute --help
#### Config:

```
Any config will do
```
#### Log:

```
~/.flexget$ flexget -c autodl.yml execute --help
2016-08-26 18:18 CRITICAL manager                       Failed to find configuration file config.yml
2016-08-26 18:18 INFO     manager                       Tried to read from: ~/.flexget, /home/ammin/.flexget, /home/ammin/.config/flexget
Could not instantiate manager: No configuration file found.
```
### Additional information:
- Flexget Version: 2.3.3
- Python Version: Python 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.1 LTS
- Link to crash log: NA

**Comment by liiight** [comment]
This is because of this: https://github.com/Flexget/Flexget/blob/develop/flexget/manager.py#L139
The easiest fix will be to pass the config arg there too. Dunno if that's the best approach though, maybe we should rethink that hack? @gazpachoking @paranoidi

**Comment by liiight** [comment]
hmm this doesn't replicate for me;
```
C:\Flexget>python flexget_vanilla.py -c config2.yml execute --help
usage: flexget execute [-h] [--tasks TASK [TASK ...]] [--learn] [--no-cache]
                       [--stop-waiting NAME] [--disable-tracking]
                       [--cli-config VARIABLE=VALUE [VARIABLE=VALUE ...]]
                       [--try-regexp] [--discover-now]
                       [--tail-reset FILE|TASK] [--now] [-T NAME] [-v] [-s]
                       [--dl-path PATH]
                       [--dump [{eval,trace,accepted,rejected,undecided,title} [{eval,trace,accepted,rejected,undecided,title} ...]]]
                       [--dump-config]
...
```
Actually, i'd say i'm getting the opposite result as you, as **anything** i put after `-c` doesn't matter:
```
C:\Flexget>python flexget_vanilla.py -c confisazdfasfasdg2.yml execute --help
usage: flexget execute [-h] [--tasks TASK [TASK ...]] [--learn] [--no-cache]
                       [--stop-waiting NAME] [--disable-tracking]
                       [--cli-config VARIABLE=VALUE [VARIABLE=VALUE ...]]
...
```
The part that looks for config comes after that at https://github.com/Flexget/Flexget/blob/develop/flexget/manager.py#L153. So I'm not sure what's going on with your setup...

**Comment by Meliox** [comment]
Do you still have a config.yml present while testing?

**Comment by liiight** [comment]
ah, good point :-)
removed it and it successfully reproduces.
