### ISSUE TITLE
fix proper detection for series

### ISSUE THREAD

**Issue by y** [Flexget/Flexget#1377]
Just saw this commit merged (https://github.com/Flexget/Flexget/pull/1138/commits/4c996467fb3e8420184ddc3e06dd72b532873aa0) and it reminded me of the multiple tickets from the old trac system which complained that 'real' or 'final' in the series name would trigger proper detection. The same logic should be added to the series title parser, to only consider 'real' or 'final' after the episode or date identifier.

Here's some of the old tickets from yandex's cache: 
http://hghltd.yandex.net/yandbtm?fmode=inject&url=http%3A%2F%2Fflexget.com%2Fticket%2F2935&tld=com&lang=en&la=1467012352&tm=1472377905&text=%22flexget%22%20%22real%20time%20with%20bill%20maher%22&l10n=en&mime=html&sign=060cb1b6753861171a76c60f57db6fe5&keyno=0

http://cc.bingj.com/cache.aspx?q=%2bflexget+%22real+time+with+bill+maher%22&d=5002796641356705&mkt=en-US&setlang=en-US&w=AycqmVqBnxrjAljazGrAaImMsiE4I9Hq
http://cc.bingj.com/cache.aspx?q=%2bflexget+%22real+time+with+bill+maher%22&d=5002796641356705&mkt=en-US&setlang=en-US&w=AycqmVqBnxrjAljazGrAaImMsiE4I9Hq

**Comment by y** [comment]
Looks like I did mention this a few months ago: https://github.com/Flexget/Flexget/issues/1120#issuecomment-216093135

**Comment by liiight** [comment]
maybe do something like this for series: https://github.com/Flexget/Flexget/pull/1138/commits/4c996467fb3e8420184ddc3e06dd72b532873aa0
