### ISSUE TITLE
History details page is returning 502 error

### ISSUE THREAD

**Issue by Theldris** [Flexget/Flexget#1384]
### Actual behaviour: Getting a 502 bad Gateway error
Example: http://flexget.com/_commit/5ed54d4a2ff02f71bbc4c770c921a19a8eb27f15/home 

### Steps to reproduce:
- Step 1: Go the history page from flexget.com
- Step 2: Click on "View" on any line

**Comment by gazpachoking** [comment]
This is a bug in my partials update for reams https://github.com/scragg0x/realms-wiki/pull/170 which I have now fixed. I still need to deploy this fix to our server.

**Comment by gazpachoking** [comment]
Rolled out the fix to the server, this should be working properly now.
