### ISSUE TITLE
Plex-Home again broken

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#1386]
Plex-Home is again broken.. it worked a while, but now i tested it again with the following error:

> 401 Client Error: Unauthorized for url: http://localhost:32400/library/sections/?X-Plex-Token=QL4hXXXXXa9H4wxXXXRxnf&"

**Comment by stevezau** [comment]
This is flexget repo not Plex?

**Comment by stevezau** [comment]
Closing as it seems invalid, open it again if you don't agree

**Comment by snickers2k** [comment]
?!?
Flexget can't connect to plex anymore (again), when Plex-Home is activated. Why should Plex work on your implementation? :D Your Plugin is broken again.. nothing more, nothing less.

**Comment by stevezau** [comment]
The plugin page clearly shows it's not supported on plex home. If you want the support then please open a PR. I don't think that plugin is heavily used.

**Comment by pkoenig10** [comment]
I'm fairly certain this is security change in the behavior of Plex 1.1.3.  Previously, [Plex required authentication for all access to the server when using Plex Home](https://support.plex.tv/hc/en-us/articles/200890058-Require-authentication-for-local-network-access).

However with the recent 1.1.3 update, [this is now the default behavior for all Plex servers](https://forums.plex.tv/discussion/62832/plex-media-server/p7).  It appears that this can be mitigated by adding `127.0.0.1/255.255.255.255` to the list of IPs allowed without auth in the Plex server settings.  However, this has been unsuccessful in fixing the issue for me.

**Comment by liiight** [comment]
If you fixed it yourself please consider submitting a PR for it

**Comment by pkoenig10** [comment]
Just to clarify, fixing it simply involved updating my Flexget config.  Nothing needed to be changed in Flexget itself.  I just posted to provide info for others who may be having the same problem.

This issue should be closed.

**Comment by snickers2k** [comment]
hm.. thats strange. i always had "username" and "password" in my config .. and i already tried to allow 127.0.0.1 in Plex. But anyway, i switched my whole config to trakt and don't need plex anymore..^^

**Comment by tubedogg** [comment]
> When I try curl http://127.0.0.1:32400/library/sections the Plex log file indicates that the whitelist is being ignored for some reason.

I believe that means that the whitelist is being ignored for a request from the private IP address block 127.0.0.0/8, not that it's being ignored entirely. (Though the comment in the support article is...odd.)

Anyway, I just tested now with Plex v1.4.1 and Plex Home and putting user/pass in the config resolves the issue. I agree, this issue should be closed.
