### ISSUE TITLE
Qbittorrent plugin doesn't add torrent to client

### ISSUE THREAD

**Issue by EDanee** [Flexget/Flexget#1390]
### Expected behaviour:
Flexget to download the torrent and insert into qbittorrent

### Actual behaviour:
Flexget download the torrent to tmp and claims it added to qbittorrent but it never shows up in the client

### Steps to reproduce:
This is tricky as for some site the torrent gets added to the client without any problem. And in some case it doesn't, but the torrent file is created in the tmp folder.

#### Config:
```
templates:
  tv:
    qbittorrent:
      host: XXXXXX
      port: XXXX
      username: XXXX
      password: XXXX
      label: series
    series:
      settings:
        hdtv:
          quality: hdtv <720p
          set:
            path: path_to_directory/{{series_name}}
      hdtv:
        - Hit the floor
tasks:
  dlseries:
    headers:
      Cookie: "XXXXXXXX"
    rss: FEED URL
    verify_ssl_certificates: no
    template: tv

```
  
#### Log:
```
2016-09-06 17:39 DEBUG    series        dlseries           Series accepting. <TORRENTNAME> meets quality hdtv
2016-09-06 17:39 VERBOSE  task          dlseries           ACCEPTED: `<TORRENTNAME>` by series plugin because target quality
2016-09-06 17:39 DEBUG    urlrewriter   dlseries           Checking 1 entries
2016-09-06 17:39 INFO     download      dlseries           Downloading: <TORRENTNAME>
2016-09-06 17:39 DEBUG    download      dlseries           Downloading url '<TORRENTURL>'
2016-09-06 17:39 DEBUG    utils.requests dlseries           Fetching <TORRENTURL>
2016-09-06 17:39 DEBUG    download      dlseries           <TORRENTNAME> field file set to: /tmp/tmpX_QHcL/87a3ce82ae44e8d94daa57e28191bcb9
2016-09-06 17:39 DEBUG    download      dlseries           filename header latin1 decoded
2016-09-06 17:39 DEBUG    download      dlseries           Found filename from headers: <TORRENTNAME>
2016-09-06 17:39 DEBUG    download      dlseries           Mimetype guess for application/x-bittorrent is ['.torrent']
2016-09-06 17:39 DEBUG    download      dlseries           Filename <TORRENTNAME>.torrent extension matches to mime-type
2016-09-06 17:39 DEBUG    download      dlseries           Finishing download_entry() with filename <TORRENTNAME>.torrent
2016-09-06 17:39 DEBUG    download      dlseries           Successfully retrieved <TORRENTNAME> from <TORRENTURL>
2016-09-06 17:39 VERBOSE  details       dlseries           Summary - Accepted: 1 (Rejected: 0 Undecided: 39 Failed: 0)
2016-09-06 17:39 DEBUG    modif_torrent dlseries           <TORRENTNAME> seems to be a torrent
2016-09-06 17:39 DEBUG    torrent_files dlseries           <TORRENTNAME> files: [u'<TORRENTNAME>.mkv', u'Sample/<TORRENTNAME>.mkv', u'<TORRENTNAME>.nfo']
2016-09-06 17:39 DEBUG    torrent_size  dlseries           <TORRENTNAME> size: 319.150249481 MB
2016-09-06 17:39 DEBUG    qbittorrent   dlseries           Successfully connected to qBittorrent
2016-09-06 17:39 DEBUG    qbittorrent   dlseries           Added task to qBittorrent

```

### Additional information:

- Flexget Version: 2.3.18
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Debian 8.5 (OSMC)
- Link to crash log:

Please verify that the following data is present before submitting your issue:

-Paste or link to a paste service ([pastebin](http://pastebin.com/) for example) of relevant config (preferably full config including templates if present. Remember to redact any personal information!
- Paste or link to a paste service of debug level logs of relevant task/s. Use `flexget -L debug execute --tasks <Task_name>`
- Flexget version (Use `flexget -V` to get it).
- Full Python version (`2.7.11` for example). Run `python -V` to get it.
- Installation method (pip, git install, etc.)
- OS and version
- Attach crash log if available

**Comment by liiight** [comment]
Is the file that's being sent to qbitorrent local or http? Because the plugin doesn't support uploading local files apparently

**Comment by EDanee** [comment]
Hi,

Thanks for the reply!
The file is grabbed via http from an RSS feed. As far as I can tell flexget saves it in the tmp folder during download.
I hope that answers your question.

**Comment by liiight** [comment]
Well I use qbitorrent plugin with no issues...
The filename you redacted, does it have http:// schema or file://?

**Comment by gazpachoking** [comment]
Perhaps the torrent site requires some sort of log in, so when the url is passed to qbittorrent it fails to actually be added. Does qbittorrent have a log with anything?

**Comment by liiight** [comment]
I think that would still be added but with error state, but who knows...

**Comment by EDanee** [comment]
Hi guys,
The site does require login, but by using cookies that is bypassed.
qbittorrent has no longs - I will try to run it in non-daemon mode if that possible to get more information.
the file is https:// and it gets saved to a temp location
```
2016-09-06 17:54 INFO     download      dlseries           Downloading: Hit.the.Floor.S03E11.HDTV.x264-FLEET [Sorozat (ENG SD)]
2016-09-06 17:54 DEBUG    download      dlseries           Downloading url 'https://SITE/torrents.php?action=download&id=2023111'
2016-09-06 17:54 DEBUG    utils.requests dlseries           Fetching https://SITE/torrents.php?action=download&id=2023111
2016-09-06 17:54 DEBUG    download      dlseries           Hit.the.Floor.S03E11.HDTV.x264-FLEET [Sorozat (ENG SD)] field file set to: /tmp/tmpu84ajN/87a3ce82ae44e8d94daa57e28191bcb9
```

The strange this is that for other sites - where no cookie and https is used - the file gets added successfully.
So I suspect either this or maybe the filename has chars that causes problems?

**Comment by cvium** [comment]
You sort of answered your own question there.
@liiight wrote: `the plugin doesn't support uploading local files apparently`

You cannot pass the cookie via the url.

**Comment by dsemi** [comment]
@cvium I believe upload torrent from disk is actually to add a file to be seeded, not for downloading files. The current download from url should work fine; it sounds like a cookie param just needs to be added as a config option to the plugin. The API supports specifying a cookie: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#download-torrent-from-url

**Comment by dsemi** [comment]
@EDanee I've added the cookie param in my fork [here](https://github.com/dsemi/Flexget). Can you test it to make sure it's working for you?  You just have to update the config file to specify `cookie: XXX` in the `qbittorrent` section.
If everything is working, I'll submit a pull request.

**Comment by cvium** [comment]
> I believe upload torrent from disk is actually to add a file to be seeded, not for downloading files. 

Definitely not.

**Comment by dsemi** [comment]
> Definitely not.

Either way, the "download-torrent-from-url" has been working with local files on the system for everyone else that uses the plugin. I wrote it to download the torrent files to a temp folder and adds those to qBittorrent; changed it to that behavior after [this](https://github.com/Flexget/Flexget/pull/867#issuecomment-184493046) comment in the original PR. 

Now that I think about it though adding a cookie param wouldn't help since the torrent file is already downloaded, there shouldn't be any need to authenticate anymore. 

@EDanee What version of qBittorrent are you using?

**Comment by cvium** [comment]
@dsemi I don't think it's working quite how you intended. Only the torrent url is passed. The torrent file is definitely not passed.

**Comment by dsemi** [comment]
@cvium `entry['url']` should point to the file location after on_task_download. At least that's my understanding after reading the transmission plugin.

**Comment by dsemi** [comment]
Ah wait I see the issue, you're right, it's in a different location.

**Comment by gazpachoking** [comment]
@dsemi I think the nicest way would be to switch to using this endpoint https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#upload-torrent-from-disk to add the torrents based on the downloaded files, rather than passing urls to qbittorrent. This would eliminate the need for qbittorrent to know about cookies or anything. It should still fall back to the url way in the case of a magnet url.

**Comment by dsemi** [comment]
@gazpachoking Yeah there's a bug in the original implementation. It's not actually using the tmp torrent files that were downloaded.  I'll make a quick fix and send it out.

**Comment by gazpachoking** [comment]
> Yeah there's a bug in the original implementation. It's not actually using the tmp torrent files that were downloaded. I'll make a quick fix and send it out.

I bet the download bit was just put in there so the plugin worked properly with content_size and content_filter plugins. Using those downloaded files is indeed the nicer way to do it though, a PR would be great.

**Comment by liiight** [comment]
Also adding torrent files from a local resource, like a watchdir for example, is a feature I miss greatly

**Comment by gazpachoking** [comment]
> Also adding torrent files from a local resource, like a watchdir for example, is a feature I miss greatly

That should work already, no? If you do a filesystem input plugin it'll have file:// urls, which should work (as long as transmission is running on the same box as flexget.) Using the real files is still nicer though, @dsemi's upcoming update should take care of both situations I think.

**Comment by dsemi** [comment]
Hm. Unfortunately qBittorrent doesn't seem to support setting savepath, label, etc. when using a torrent file on disk. Or at least it's not documented.

@liiight Is that a thing in Flexget? You can set a watchdir in your torrent client.

**Comment by gazpachoking** [comment]
@dsemi Maybe try just putting the same fields like for this https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#download-torrent-from-url

Hopefully those work the same for this endpoint. Otherwise I think qbittorrent should improve their api...

**Comment by cvium** [comment]
https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/www/public/upload.html#L21-L26

Looks like it should support label and savepath

**Comment by EDanee** [comment]
@dsemi I'm using qbittorrent-nox (webUI only) version 3.3.6

**Comment by liiight** [comment]
@dsemi i like to use a flexget based watchdir since it allows me to easily keep series tracking even for manually added files. 

@gazpachoking unfortunately that does not work, adding files from a local resource requires an entirely different http request to qbitorrent than the one that's currently supported

**Comment by dsemi** [comment]
@gazpachoking Is there an easy way to test adding a random .torrent file? My setup is w/ magnets right now which doesn't really test the changes I'm making.

@liiight I see. I just wasn't aware of the filesystem plugin.

**Comment by gazpachoking** [comment]
@dsemi I'd just make a small test config like this:
```yaml
tasks:
  testtask:
    mock:
      - title: blah blah
        url: http://url.to/some/torrent
    accept_all: yes
    qbittorrent: whatever settings
    disable: [seen, seen_info_hash]  # so you can keep running this task over and over
```

**Comment by dsemi** [comment]
@gazpachoking Thanks for the tip. Created the [PR](https://github.com/Flexget/Flexget/pull/1397).

**Comment by EDanee** [comment]
I've managed to find a log file for qbt (very well hidden btw):
```
~/.local/share/data/qBittorrent/logs/qbittorrent.log
```
You were right, all it shows that it tries to add the torrent via the URL:
```
Downloading 'https://SITE/torrents.php?action=download&id=2023111', please wait...
```
No further entry of success or failure.

**Comment by EDanee** [comment]
Hi guys! I just wanted to say thank you! It works perfectly!
