### ISSUE TITLE
Sending execution to demonized flexget fails

### ISSUE THREAD

**Issue by m-hume** [Flexget/Flexget#1405]
### Expected behaviour:
Execution to be sent to the demon to execute 

### Actual behaviour:
There is a FlexGet process already running for this config, sending execution there.
Could not start manager: Int or String expected

### Steps to reproduce:
- Step 1: flexget start -d
- Step 2: flexget execute

#### Log:
```
flexget execute --debug
There is a FlexGet process already running for this config, sending execution there.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 290, in start
    client = IPCClient(ipc_info['port'], ipc_info['password'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 162, in __init__
    channel = rpyc.Channel(rpyc.SocketStream.connect('127.0.0.1', port))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 132, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 99, in _connect
    socktype, proto)[0]
error: Int or String expected
```

### Additional information:

- Flexget Version: 2.3.26
- Python Version: 2.7.3
- Installation method: pip
- OS and version: Ubuntu 12.04

issueing the command `flexget demon stop` produces the same error
i have to kill the pid to stop it
This was after updating from FlexGet-2.2.9

**Comment by m-hume** [comment]
Awesome quick fix!
Thanks

**Comment by arthurzqhu** [comment]
How did you fix this eventually? I ran into the same problem.

**Comment by m-hume** [comment]
https://github.com/Flexget/Flexget/commit/5ab10ad6ec7a24a97523724fa6ca1dfdbb67f7fe

Please excuse any typos as this was sent on the go.

On 11 Aug 2018, at 16:47, Arthur <notifications@github.com> wrote:

How did you fix this eventually? I ran into the same problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Flexget/Flexget/issues/1405#issuecomment-412283386>,
or mute
the thread
