### ISSUE TITLE
[API] Series banners fail to load since 2.3.17

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1410]
Series banners fail to load on the WebUI since version 2.3.17

HTML code for flexget-2.3.16:
`<img class="md-card-image" ng-src="http://thetvdb.com/banners/graphical/272644-g5.jpg" src="http://thetvdb.com/banners/graphical/272644-g5.jpg">
`

HTML code for flexget-2.3.17 up to  flexget-2.3.28:
`<img class="md-card-image" ng-src="/api/cached/?url=http://thetvdb.com/banners/graphical/272644-g5.jpg" src="/api/cached/?url=http://thetvdb.com/banners/graphical/272644-g5.jpg">
`

The error for this URL is:
```
{
    "code": 500, 
    "message": "Error: 13"
}
 
```

Update: It can be reproduce from the API test/doc page : http://flexget:5050/api/ 

### Additional information:

- Flexget Version: Started in flexget-2.3.17

**Comment by liiight** [comment]
Hmm that's an OS error, should be returned better though. Git logs or crash
logs?

**Comment by Mirgolth** [comment]
logs:
```
2016-09-17 09:28 ERROR    flexget.api                   Exception on /cached/ [GET]
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/volume1/@appstore/flexget/env/lib/python2.7/site-packages/flexget/api/cached.py", line 33, in get
    raise ApiError('Error: {}'.format(e.args[0]))
ApiError
```

**Comment by liiight** [comment]
Ok, the issue is that you have no permission to write to the default cache dir. I'll improve the error handling and add fallback logic for these errors. 
In the meanwhile, the cache dir name is `cached_resources` under your flexget execution path.

**Comment by Mirgolth** [comment]
I reset the flexget:users ownership to all files and restart but the dir is still not created automatically.

I tried to manually create a  `cached_resources` dir both under` /usr/local/flexget/` and `/usr/local/flexget/env/bin/` but error persists.

Any clue ?

**Comment by liiight** [comment]
Not really, I'll add more informative logs to this soon

**Comment by liiight** [comment]
After next release, please try again. API responses should be more helpful.

**Comment by Mirgolth** [comment]
```
{
    "code": 500, 
    "message": "Error: [Errno 13] Permission denied: '/cached_resources'"
}
```

Is it trying to write to the root folder ?

**Comment by liiight** [comment]
root folder being working dir

**Comment by gazpachoking** [comment]
@liiight I don't think it should use the working dir for cache. Probably under config dir is better?

**Comment by Mirgolth** [comment]
@gazpachoking I agree.

In my case the working dir was in fact `/` as the deamon is launched as a service by the system. I was going to propose to use log directory  which is the same as conf for many of us I guess.

**Comment by liiight** [comment]
yeah, my bad :-)
i'll fix this
