### ISSUE TITLE
imdb_list: Login to IMDB does no work any longer

### ISSUE THREAD

**Issue by tobiaslangner** [Flexget/Flexget#1421]
### Expected behaviour:

Using the imdb_list plugin, retrieve movies on the watch list and the like.
### Actual behaviour:

Login to IMDB does not work, plugin returns "Login to IMDB failed. Check your credentials." despite credentials being correct, i.e., I am able to login with the credentials printed in the log output. I tried both variants for the username, i.e., for email foo@bar.com I tried the whole address as well as just "foo", neither worked.
### Steps to reproduce:

Setup a config file with the below snippet and run `flexget --debug --test execute`
#### Config:

```
tasks:
  populate_list:
    imdb_lookup: true
    accept_all: true
    imdb_list:
      list: watchlist
      login: <login email>
      password: <password>
    list_add:
      - movie_list: my_movies
```
#### Log:

```
2016-09-25 10:37 DEBUG    utils.requests populate_list   Fetching https://www.imdb.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-handler&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=imdb_mobile_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
2016-09-25 10:37 DEBUG    imdb_list     populate_list   email=<login email>, password=<password>
2016-09-25 10:37 VERBOSE  utils.requests populate_list   Waiting 4.24 seconds until next request to imdb.com
2016-09-25 10:37 DEBUG    utils.requests populate_list   Fetching https://www.imdb.com/ap/signin/167-5712825-0663537?ie=UTF8&pf_rd_r=14YRHC25X2GR80X7EFC6&pf_rd_m=A2A1PIL045UJ9G&pf_rd_t=6301&pf_rd_i=imdb_mobile_us&pf_rd_p=2187562082&pf_rd_s=mobile-signin-slot
2016-09-25 10:37 VERBOSE  utils.requests populate_list   Waiting 4.79 seconds until next request to imdb.com
2016-09-25 10:37 DEBUG    utils.requests populate_list   Fetching http://www.imdb.com/profile
2016-09-25 10:37 CRITICAL plugin        populate_list   Login to IMDB failed. Check your credentials.
2016-09-25 10:37 WARNING  task          populate_list   Aborting task (plugin: imdb_list)
2016-09-25 10:37 DEBUG    task_queue                    task populate_list aborted: TaskAbort(reason=Login to IMDB failed. Check your credentials., silent=False)
```
### Additional information:
- Flexget Version: 2.3.31
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 14.04
- Link to crash log:

**Comment by mannionpatrick** [comment]
Watching this thread - I see the same errors, but wasn't sure it wasn't my config...

**Comment by faximan** [comment]
Same here!

**Comment by CkuT** [comment]
Same here

Python : 3.5.2
Flexget : 2.3.34
OS : Manjaro

**Comment by mannionpatrick** [comment]
Weird - problem seems to be gone now. Only action on my part was upgrading to 2.3.37.

**Comment by liiight** [comment]
Imdb list is basically a hack. Anyone using it should not expect 100% durability.

**Comment by liiight** [comment]
It seems no one in the team wants to touch this with a ten foot pole, so this probably won't get fixed. If anyone want to submit a PR, they're more than welcome. 
A minor workaround for those using imdb list just as input will be to tl use its rss form. It's not ideal, but it's something.

**Comment by richardasaurus** [comment]
this may be of use, but uses headless browser

```python
# On an Ubuntu system, first install the following
# sudo apt-get install tesseract-ocr phantomjs libjpeg8-dev
# pip install requests selenium pytesseract pillow
import csv
import time

import pytesseract
import requests
from io import BytesIO
from PIL import Image
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException

USER = 'mylogin@example.com'
PASS = 'mypassword123'
_BASE_URL = 'https://www.imdb.com'
INDEX_URL = _BASE_URL
WATCHLIST_URL = '{}/list/watchlist'.format(_BASE_URL)
RATINGSLIST_URL = '{}/list/ratings'.format(_BASE_URL)
LOGIN_URL = (
    '{}/ap/signin?openid.pape.max_auth_age=0'
    '&openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-handler'
    '&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2F'
    'identifier_select'
    '&openid.assoc_handle=imdb_us&openid.mode=checkid_setup'
    '&siteState=eyJyZWRpcmVjdFRvIjoiaHR0cHM6Ly93d3cuaW1kYi5jb20vIn0'
    '&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2F'
    'identifier_select'
    '&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&'
).format(_BASE_URL)
USER_AGENT = (
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:36.0) '
    'Gecko/20100101 Firefox/36.0 WebKit'
)
SLEEP_BETWEEN = 0.7

ELEMENTS = {
    'input_email': '#ap_email',
    'input_password': '#ap_password',
    'input_submit': '#signInSubmit',
    'captcha_image': '#auth-captcha-image',
    'input_captcha': '#auth-captcha-guess',
    'export_link_text': 'Export this list'
}


def _start_browser():
    dcap = dict(DesiredCapabilities.PHANTOMJS)
    dcap['phantomjs.page.settings.userAgent'] = USER_AGENT
    browser = webdriver.PhantomJS(desired_capabilities=dcap)
    browser.maximize_window()
    browser.implicitly_wait(SLEEP_BETWEEN)
    return browser


def _solve_and_input_captcha(browser):
    time.sleep(SLEEP_BETWEEN)
    image_url = (
        browser.find_element_by_css_selector(ELEMENTS['captcha_image'])
        .get_attribute('src'))
    image = requests.get(image_url)
    stream = BytesIO(image.content)
    img = Image.open(stream)
    result = pytesseract.image_to_string(img)
    for letter in result:
        (browser.find_element_by_css_selector(ELEMENTS['input_captcha'])
         .send_keys(letter))
        time.sleep(SLEEP_BETWEEN)


def _login_form_requesting_captcha(browser):
    try:
        browser.find_element_by_css_selector(ELEMENTS['captcha_image'])
        return True
    except NoSuchElementException:
        return False


def _fill_and_submit_login_form(browser, username, password):
    time.sleep(SLEEP_BETWEEN)
    (browser.find_element_by_css_selector(ELEMENTS['input_email'])
     .send_keys(username))
    time.sleep(SLEEP_BETWEEN)
    (browser.find_element_by_css_selector(ELEMENTS['input_password'])
     .send_keys(password))
    time.sleep(SLEEP_BETWEEN)
    browser.find_element_by_css_selector(ELEMENTS['input_submit']).click()
    time.sleep(SLEEP_BETWEEN)


def _retry_login_with_captcha(browser, password):
    _solve_and_input_captcha(browser)
    time.sleep(SLEEP_BETWEEN)
    (browser.find_element_by_css_selector(ELEMENTS['input_password'])
     .send_keys(password))
    time.sleep(SLEEP_BETWEEN)
    browser.find_element_by_css_selector(ELEMENTS['input_submit']).click()
    time.sleep(SLEEP_BETWEEN)

    failed = True
    try:
        browser.find_element_by_css_selector('#auth-captcha-guess')
    except NoSuchElementException:
        failed = False

    if failed:
        raise RuntimeError('login requiring captcha failed')


def _logged_in(browser):
    return (
        'Other Sign in options' not in
        browser.find_element_by_css_selector('body').text
    )


def login(browser, username, password):
    browser.get(INDEX_URL)
    browser.get(LOGIN_URL)

    _fill_and_submit_login_form(browser=browser, username=username,
                                password=password)

    if _login_form_requesting_captcha(browser):
        _retry_login_with_captcha(browser, password=password)
        time.sleep(SLEEP_BETWEEN)

    if not _logged_in(browser):
        raise RuntimeError('login failed')


def get_list(browser, list_url=None):
    browser.get(list_url)
    time.sleep(SLEEP_BETWEEN)

    session = requests.Session()
    session.cookies = requests.utils.cookiejar_from_dict(
        {c['name']: c['value'] for c in browser.get_cookies()}
    )

    list_download_url = (
        browser.find_element_by_link_text(ELEMENTS['export_link_text'])
        .get_attribute('href')
    )
    response = session.get(list_download_url)
    list_data = [f for f in csv.DictReader(str(response.content))]
    print(list_data)
    return list_data


if __name__ == '__main__':
    browser = _start_browser()
    login(browser=browser, username=USER, password=PASS)
    get_list(browser=browser, list_url=WATCHLIST_URL)
```

**Comment by cvium** [comment]
Seems more trouble than it's worth.

**Comment by philsturgeon** [comment]
Hey folks. I know this plugin is essentially a hack, and it is not designed to work forever, but if it doesn't work it should be removed from the site, the wiki, etc. 

One solution would be advertising the IMDB RSS feed solution, which I cannot get to work as there are no examples of list_add using an RSS feed as input. If that was documented it would be a viable workaround, and you could stop advertising this plugin.

Alternatively, the plugin could be tweaked to use the RSS feed internally as a fallback. 

You could even have option three which would be a fallback to trying to use the feed if login fails. An error showing "We tried logging in and it failed, please make your feed public to make this plugin continue to work" would get the job done.

**Comment by crack00r** [comment]
IT seams the bug is back?

root@***:~/.flexget# flexget -V
2.5.12
You are on the latest release.


2016-11-04 20:54 VERBOSE  utils.requests Remove_CollectedSeriesFromWatchlist Waiting 4.24 seconds until next request to imdb.com
2016-11-04 20:54 VERBOSE  utils.requests Remove_CollectedSeriesFromWatchlist Waiting 4.73 seconds until next request to imdb.com
2016-11-04 20:54 CRITICAL plugin        Remove_CollectedSeriesFromWatchlist Login to IMDB failed. Check your credentials.
2016-11-04 20:54 WARNING  task          Remove_CollectedSeriesFromWatchlist Aborting task (plugin: imdb_list)

**Comment by cvium** [comment]
It was never gone. Sometimes it works, sometimes it doesn't.

**Comment by snickers2k** [comment]
but nowdays it seems to be not working way more often, than it is working.. 
The tag-label is "Won't Fix". So i guess i have to completely switch to trakt? Maybe these problems should be clarified on the imdb_list-wiki for later users, running into the same problems

**Comment by firasdib** [comment]
I updated flexget by misstake which is why I have this issue now. My friend still runs an older version which works 100% of the time.... Why can't we just use that code instead?

**Comment by snickers2k** [comment]
that is really interesting. maybe you can ask your friend which version he uses? `flexget -V` in terminal.
but i guess it was the last change on the imdb_list.py 10 days ago. So maybe @tobinjt could take a look? i'll try the old version of the imdb_list.py and see what happens

**Comment by tobinjt** [comment]
I can't help you with this - my commit only changed a comment.  See https://github.com/tobinjt/Flexget/commit/6d9b973d73603bddd06f69e8523b2eb922735800#diff-d4b4dfe8a325db0d5c6c6e7ed96cd65b for the extent of my changes.

**Comment by snickers2k** [comment]
oh i see.. well, than this error is really strange..

**Comment by cvium** [comment]
**NOTE: imdb_list no longer working or working intermittenly has nothing to do with any commit**

I don't think you understand. This is out of our control. imdb has been forcing captchas on its users and there's really no nice way around that.

You can use the [old plugin](https://raw.githubusercontent.com/Flexget/Flexget/2305ff603efdf9fc5078b96a1d2477eeefdfbf0e/flexget/plugins/input/imdb_list.py) if you want, but there's no guarantee it will work and it most certainly won't work with any List specific plugins like list_add, list_remove, list_match etc.

**Comment by snickers2k** [comment]
okay.. that is really sad. i was just wondering why people saying it's still working with the old plugin. if the captchas are the problem, maybe a captcha-solver-service could be a solution? most people using flexget with shared-hosters have them already. i would be really happy about such solution. thanks

**Comment by cvium** [comment]
I guess I could've been clearer. The old plugin works by parsing a *public* imdb watchlist and avoids captchas that way, but it also means it won't be able to modify the watchlist in any way.

As for the current imdb_list, none of us have the time nor the motivation to find a proper fix if one exists, hence the labels "Won't Fix" and "Pending contribution".

**Comment by firasdib** [comment]
@cvium How would I go about using that plugin instead of the current one?

**Comment by cvium** [comment]
I've added the old imdb plugin as `imdb_watchlist`, http://flexget.com/Plugins/imdb_watchlist

It only works with public lists.

**Comment by snickers2k** [comment]
Okay, so the old-plugin works so far to crawl the imdb_watchlist.
So instead of using trakt for adding movies, i still use imdb and let flexget sync the imdb_watchlist with trakt. Okay, no way to delete entries in imdb (have now around 1300 movies in imdb), but it seems to work. as soon as the watchlist is full, i'll create a new imdb acc :D
Maybe this helps for anyone who want's to mainly use imdb for adding movies.

**Comment by lostsubstance** [comment]
It must be your account or password...
This config has been (and continues to be) working for me for the last year or so without error:
```
tasks:
  imdb:
    priority: 1
    no_entries_ok: yes
    disable: [seen]
    imdb_list:
      login: '{? imdb.login ?}'
      password: '{? imdb.password ?}'
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: movies
      - trakt_list:
          username: '{? trakt.username ?}'
          account: '{? trakt.username ?}'
          list: queued-movies
          type: movies
    list_remove:
      - imdb_list:
          login: '{? imdb.login ?}'
          password: '{? imdb.password ?}'
          list: watchlist
```

**Comment by liiight** [comment]
A potential fix for this was just pushed, will be released next version.

**Comment by cvium** [comment]
I was unable to trigger any captchas when working on #2062, but if someone manages to trigger it, we will probably attempt the following fix:

1. Auth cli tool similar to Trakt
2. Convert captcha to ASCII and print to console (should probably include a link to the image itself in case of non-monospaced fonts and tiny windows).

**Comment by cvium** [comment]
I will close this for now. If it happens again, just let us know.
