### ISSUE TITLE
Flexget Issues with Python3 on latest release

### ISSUE THREAD

**Issue by DefiantVisuals** [Flexget/Flexget#1429]
I'm trying to use Python3 with the latest release of flexget on my qnap nas since the python 2.7 version available doesnt have lib2to3. I installed everything but when it goes to create the initial setup of the databases t asks if i have pysqlite installed and if Im running Python 2.5 - 2.7. Is there any way to get flexget to work with Python3 ? Or is one of my dependencies pointing to a location where sqlite3 isnt?

Any help would be appreciated.

**Comment by paranoidi** [comment]
SQLite is supposed to be always available in python. Whoever compiled / packaged your python did not do it. There is no way for us around that.
