### ISSUE TITLE
SJ urlrewrite: Be less strict with special characters

### ISSUE THREAD

**Issue by segelkma** [Flexget/Flexget#1435]
It did not happen for the first time for me that the episode title in serienjunkies xml file does not match with the one on the show page, example (special character between WEB and DL does not match):
XML: Gotham.S03E03.Look.Into.My.Eyes.1080p.WEB.DL.DD5.1.H.264.NTb
Shows site: Gotham.S03E03.Look.Into.My.Eyes.1080p.WEB_DL.DD5.1.H.264.NTb

Search pattern: Gotham.S03E03.Look.Into.My.Eyes.1080p.WEB.DL.DD5.1.H.264.NTb

In other words, the url rewriter does not find the episode and rewriting fails. I suggest to be less strict with special characters. The dot between each word can of course be strict, but having a variaty of characters for those special words would be great and avoid further problems.

I know that this is an issue rather to be fixed by serienjunkies, but those mistakes will happen again in the future, being said to them or not.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
