### ISSUE TITLE
Daemon mode not parsing table-type

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#1457]
### Expected behaviour:
Daemon mode printing tables with the correct table type when using a cli command

### Actual behaviour:
Currently falls back to porcelain by default, and only 'single' type works.
Non daemon mode works fine.

### Steps to reproduce:
- Step 1: Start Daemon
- Step 2: Use any CLI command that outputs a table

#### Config:
/
  
#### Log:
```
 Name                                | Latest | Age      | Downloaded              | Identified By 
 American Horror Story 1 behind      | S06E05 | 7d 3h    | 1080p webdl h264 dd5.1  | ep            
 Atlanta                             | S01E08 | 2d 11h   | 1080p webdl h264 dd5.1  | ep            
 Better Things                       | S01E06 | 6d 7h    | 1080p webdl h264 dd5.1  | ep            
 Callboys                            | -      | -        | -                       | ep            
 Channel Zero                        | S01E02 | 1d 7h    | 1080p webdl h264 dd5.1  | ep        
```

### Additional information:
- Flexget Version: 2.4.1
- Python Version: 2.7.6
- Installation method: pip
- OS and version: Ubuntu 14.04

**Comment by liiight** [comment]
Need to pass TTY state via RPC
