### ISSUE TITLE
TomatoUSB Flexget intergration

### ISSUE THREAD

**Issue by cbonn85** [Flexget/Flexget#1461]
### Expected behaviour:
Should display version type
### Actual behaviour:
Traceback (most recent call last):
  File "flexget", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2994, in <module>
    @_call_aside
  File "/opt/local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2980, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3007, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/opt/local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 852, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'html5lib>=0.11' distribution was not found and is required by FlexGet

### Steps to reproduce:
- Step 1: cd /opt/local/bin
-Step 2: flexget -v

#### Config:
```
paste relevant config
use paste service if config is too long
```
  
#### Log:
```
paste log output
use paste service if log is too long
```

### Additional information:

- Flexget Version:???
- Python Version:2.5.6
- Installation method:
putty from windows
- OS and version:
Tomato Firmware 1.28.0000 -138 K26ARM USB AIO-64K
Linux kernel 2.6.36.4brcmarm and Broadcom Wireless Driver 7.14.43.40 (r527781)
- Link to crash log:

**Comment by crawln45** [comment]
Your biggest problem is that flexget no longer supports anything lower than python 2.7

**Comment by cbonn85** [comment]
Can't figure out how to update.

**Comment by cbonn85** [comment]
Tried
ipgk https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar -xzf Python-2.7.11.tgz  
cd /opt/Python-2.7.11

./configure  

output-->
checking build system type... Warning: creating insecure temp directory
armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... linux2
checking EXTRAPLATDIR...
checking for --without-gcc... no
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/opt/Python-2.7.11':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

**Comment by crawln45** [comment]
Check on tomatousb sites as it's not a flexget error.
