### ISSUE TITLE
[discover][morethantv] Error searching with morethantv: 1,005.98 MB does not look like a file size

### ISSUE THREAD

**Issue by qvazzler** [Flexget/Flexget#1470]
### Expected behaviour:
(No error)

### Actual behaviour:
2016-10-27 19:20 ERROR    discover      get_series      Error searching with morethantv: 1,005.98 MB does not look like a file size

### Steps to reproduce:
- Step 1: Find something with decimals and dots? :smile: 

- Flexget Version: 2.3.xx? Somewhat new
- Python Version: 2.7.9
- Installation method: pip
- OS and version: raspbian, jessie
- Link to crash log: none

**Comment by cvium** [comment]
Was fixed in 2.3.35. DENIED.
