### ISSUE TITLE
imdb_list plugin seems to ignore "force_language" option

### ISSUE THREAD

**Issue by pilluli** [Flexget/Flexget#1486]
I am trying to add movies from a imdb list. However, it seems as if option "force_language" does not work. For instance, using movie http://www.imdb.com/title/tt3691740. The original / english title is "The BFG" and the Spanish one "Mi amigo el gigante". Using "force_language: es-es" I was hoping to get the spanish title however still results in the movie added in english language:

> 2016-11-04 10:54 VERBOSE  task          movies_watchlist_spanish ACCEPTED: `The BFG (2016)` by accept_all plugin

**Comment by liiight** [comment]
that plugin is no longer supported, see #1421
