### ISSUE TITLE
WebUI : Status page shows tasks that doesn't exist anymore on my conf

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1488]
Hi, 

The new "status" WebUI page is showing a task that doesn't exist on my conf anymore for probably 3 months. 
The task cannot be executed on the "Execute", so yes I'm sure it's not hidden on my conf ;)

### Additional information:

- Flexget Version: Flexget 2.5.13
- Python Version: 2.7
- Installation method: pip
- OS and version: Linux 3.2.40 on Synology

**Comment by liiight** [comment]
First off, I'm pretty happy to get feedback on this already. 
I can add a time range filter param to the tasks api call. @Tommatheussen sounds good?

**Comment by paranoidi** [comment]
Status plugin should purge removed tasks. There's todo about that in there ...

**Comment by liiight** [comment]
dunno, I see some value in historically saving that, no?

**Comment by liiight** [comment]
DB cleanup will clean the unneeded data. Can be run from UI (under the setting menu), CLI and also triggers once a week.

**Comment by Mirgolth** [comment]
Thx !
