### ISSUE TITLE
Feature request : no_plugins_ok plugin

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1500]
Hi,

Could you implement a plugin similar to no_entries_ok for input/filter/output plugins ?

        if phase == 'filter':
            log.warning('Task does not have any filter plugins to accept entries. '
                        'You need at least one to accept the entries you  want.')
        else:
            log.warning('Task doesn\'t have any %s plugins, you should add (at least) one!' % phase)

I have a task that only consist of a clean_transmission.

http://discuss.flexget.com/t/no-plugins-ok-plugin/2883/2

**Comment by gazpachoking** [comment]
I think clean_transmission is the only plugin this would be useful with. I really wish we could fix that plugin instead of hacking around the design choice of that plugin.

**Comment by cvium** [comment]
I agree with @gazpachoking. A better solution is refactoring clean_transmission to comply with the task flow.
