### ISSUE TITLE
Feature Request: Filesystem Plugin - New Entry Fields (parent directory, path)

### ISSUE THREAD

**Issue by jasonlyle88** [Flexget/Flexget#1504]
This is from a feature request on the forum that liiight recommended I place here in a git issue.  The feature request can be found at [http://discuss.flexget.com/t/filesystem-plugin-new-entry-parent-directory/2874](url).  Please note, the below description is slightly modified to add a second new entry field which I didn't recognize as useful until after playing with the filesystem plugin for a bit.  The second entry field, not mentioned in the orginal post on the form (but is described below) is to give us the path to the file (new entry field), not just the location of the file (existing entry field).

I would find it useful if a new entry field were to be added to the filesystem plugin. Namely, if one of the entry fields provided the name of the parent directory of the input item.

For example, lets say we are looking for TARGET (doesn't matter if it is a file, directory or symlink that is retrieved) in a filesystem:
```
/
|----Folder1
|--------Folder2
|------------Folder3
|----------------TARGET
```
Right now, the entry fields are:
- url
  - "file:///Folder1/Folder2/Folder3/TARGET"
- location
  - "/Folder1/Folder2/Folder3/TARGET"
- title
  - "TARGET"
- accessed/modified/created
  - dependent on TARGET

I propose the following new entry fields:
- parent_directory
  - "Folder3"
- path
  - "/Folder1/Folder2/Folder3/"

Thanks for you consideration!

**Comment by cvium** [comment]
Don't really think that makes sense as a separate entry. As an entry field though? Sure.

**Comment by jasonlyle88** [comment]
Ah, my apologies, that is what I meant.  Thanks cvium, I'll make sure i get the terminology right next time!

**Comment by cvium** [comment]
`path` has special meaning. It should probably be `parent_path`.

**Comment by gazpachoking** [comment]
Didn't read through this fully, but does this add anything we don't get with our existing jinja filters? http://flexget.com/Jinja#jinja2-filters

location: /Folder1/Folder2/Folder3/TARGET
location|dirname: /Folder1/Folder2/Folder3
location|dirname|basename: Folder3

I'm just thinking this is not such a common need that we need to add these fields explicitly.

**Comment by jasonlyle88** [comment]
Ah, the jinja filters do work for this @gazpachoking, thanks!.  However, you were a little off with the filter's names.  The correct answer (for future sake) is as follows:

```location```                            : /Folder1/Folder2/Folder3/TARGET
```location|pathdir```                : /Folder1/Folder2/Folder3
```location|pathdir|pathbase```: Folder3

I believe this is a completely acceptable answer.  Thanks guys!

**Comment by liiight** [comment]
that's a good point @gazpachoking, probably need to be added to wiki
