### ISSUE TITLE
Flexget waking up every thread every 0.5 seconds in Deamon mode

### ISSUE THREAD

**Issue by jrett2** [Flexget/Flexget#1515]
### Expected behaviour:
In Deamon mode, flexget should sleep between scheduled tasks. wake ups kick the CPUs out of power saving modes, and cause my computer to use a lot more power than it needs to.

### Actual behaviour:
flexget wakes up 15.4 times a second in my setup. 1.2 ms/s of Usage. This is about 25% of the total wakeups on my system.

### Steps to reproduce:
- Step 1: ...
run flexget in deamon mode
use strace or powertop to see it wake up often

 
I'm pretty sure it comes from here
https://github.com/Flexget/Flexget/blob/83bc8dc86fd4760c4f059353975a24e04e681888/flexget/task_queue.py#L105

            while self._thread.is_alive():
                time.sleep(0.5)

I think the real fix would be to let the tread join, or wait, and just handle the KeyboardInterrupt without a busy loop. But I think the easier solution, and the one I'd like to see in the short term, is to just add a check for daemon mode here and join instead of waiting for a cnrl-c. Since in daemon mode it is impossible for a thread to get a cnrl-c, these wake ups are just wasted energy.

Something like this should work:
-if sys.version_info >= (3, 4):
+if sys.version_info >= (3, 4) or is_daemon:
    self._thread.join()

### Additional information:

- Flexget Version:
2.6.2
- Python Version:
Python 2.7.12
- Installation method:
- OS and version:
jrett@ender:~$ uname -a
Linux ender 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04.1 LTS

PowerTOP 2.8      Overview   Idle stats   Frequency stats   Device stats   Tunables                                     

Summary: 208.0 wakeups/second,  0.0 GPU ops/seconds, 0.0 VFS ops/sec and 12.5% CPU use

                Usage       Events/s    Category       Description
              0.8 ms/s      50.3        Process        /home/jrett/flexget/bin/python /home/jrett/flexget/bin/flexget daemon start
            114.7 ms/s       1.7        Process        powertop
              0.9 ms/s      43.3        Process        Plex Plug-in [com.plexapp.system] /usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versi
            130.4 µs/s      35.5        kWork          dbs_timer
              4.8 ms/s      10.4        Process        /usr/bin/python /usr/bin/deluged -d
            218.1 µs/s      12.1        Process        [rcu_sched]
            209.2 µs/s       6.9        Process        /usr/lib/plexmediaserver/Plex Media Server

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
