### ISSUE TITLE
Docker support broken

### ISSUE THREAD

**Issue by stevezau** [Flexget/Flexget#1542]
Docker support is broken, this issue is a reminder for steve to fix it.

**Comment by paranoidi** [comment]
@stevezau is it working? ;D

**Comment by http403** [comment]
I would like to contribute a Dockerfile and wrote one already but I need some help. I wasn't able to build the WebUI.

**Comment by metaMMA** [comment]
@http403 I think the webui is working in this one, but I haven't had time to check. It might be a good starting point.
https://github.com/wiserain/docker-flexget/blob/master/Dockerfile

**Comment by http403** [comment]
@metaMMA Thank you. I checked that one. Yes, it got webUI because it install FlexGet from PyPI. I'm installing from source, so I can do versioning and tagging easier (thus better for PR). This difference makes me hard to use it as a reference.

**Comment by gazpachoking** [comment]
I've seen multiple dockerfile updates since this, assuming it isn't relevant anymore.
