### ISSUE TITLE
Send notification only when something is added

### ISSUE THREAD

**Issue by martinberg** [Flexget/Flexget#1543]
``` notify_task ``` and ```notify_entries``` currently sends a notification even when nothing is added, ie ```Task returned 0 accepted entries```. 

Suggesting to add an option to only send a notification when actually somethings is added.

**Comment by ivanich** [comment]
Noticed this issue as well.

**Comment by liiight** [comment]
closed with https://github.com/Flexget/Flexget/commit/e717df255c2b4ddea57e01b243218df5da7b81d6
