### ISSUE TITLE
Feature request: Allow iNTERNAL releases after normal and vice versa

### ISSUE THREAD

**Issue by kolyagora** [Flexget/Flexget#1550]
I propose adding ability to download iNTERNAL releases after normal ones and vice versa.

According to the scene rules iNTERNAL and normal releases don't dupe each other. But Flexget doesn't distinguish them and treats them as dupes.

There are at least two cases when getting one after another might be wanted.

**First case:** iNTERNAL release comes first, then comes a normal one.

Example:
First release: The.Grand.Tour.S01E04.iNTERNAL.720p.WEBRiP.x264-PLUTONiUM
Second release: The.Grand.Tour.S01E04.720p.WEBRip.X264-DEFLATE

Appearing of an iNTERNAL release before a normal one usually means that it has some technical flaws which are known to a releaser but not tolerated by rules. Following normal release shouldn't have these flaws and is preferred to have but it doesn't contain a PROPER tag in its name and won't be accepted.

**Second case:** normal release comes first, then comes an iNTERNAL one.

Sometimes iNTERNAL tag is used to avoid dupeing of normal release pre'd before. There are few possible reasons:
- an original release has some flaws but cannot be propered because they aren't violating the rules;
- an original release is fine, but an iNTERNAL has better source or is encoded with better settings and, for example, has higher bitrate.

In this case Flexget also won't accept an iNTERNAL release after a normal one.

I believe iNTERNAL releases deserve a special treatment by Flexget to handle the described scenarios. I see it as a plugin which will let us choose one or more possible options:
- allow iNTERNAL after normal;
- allow normal after iNTERNAL;
- disallow iNTERNAL (at the moment might be done using `regexp` plugin);

It should work for both movies and series.

Any thoughts are welcome.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
