### ISSUE TITLE
[Web-UI] Search in series doesn't work

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1559]
### Expected behaviour:
The search returns the searched word every time.

### Actual behaviour:
If I search for a word and I get two results then I delete one of the two series found the GUI goes to the list of series and then the search for that word doesn't work anymore.

### Steps to reproduce:
- Have two series with the searched word in the name.
- Go to the Series page
- Type the word in the search field and press enter
- Once the two series are found delete one of the two, the GUI will return to the Series home page.
- The word is still in the search field, but pressing enter doesn't give the left series as a result.

### Additional information:

- Flexget Version: 2.8.4
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.1 LTS

**Comment by Tommatheussen** [comment]
Added in 4d5aa9d
