### ISSUE TITLE
RarBG error: Too many requests per second

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1560]
Got this in my log:
ERROR rarbg download-series-discover Error code 5: Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later!

#### Config:
https://github.com/effemmeffe/flexget/blob/master/config.yml1
  
### Additional information:

- Flexget Version: 2.8.4
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.1 LTS

**Comment by paranoidi** [comment]
I get this one too, even when doing first request! I think the plugin needs special retrying with increasing interval for few times ...

**Comment by liiight** [comment]
@paranoidi we have TimedLimiter exactly for that:
 https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/notifiers/join.py#L17

**Comment by gazpachoking** [comment]
What domain is giving this error? Could it be when we get to download phase, and the rarbg limiter is only set on a local requests session, and not the task one?

**Comment by paranoidi** [comment]
You didn't read, I have seen this from FIRST request .. :)

**Comment by crawln45** [comment]
Does he ever read :P

**Comment by mfonville** [comment]
I also received this error, on the first search operation
```
Error code 5: Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later!
```
Maybe there are already too fast requests during the set-up phase?
