### ISSUE TITLE
Piratebay error in discover

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1561]
Got this in my log:
`ERROR    discover      download-movies-1080p-discover Error searching with piratebay: Tried to set title to <span class="__cf_email__" data-cfemail="69595e475950475a59472b05080a02472b060602475b59595f472b051c3b0810475e5b591947115b5f5d29211d">[email\xa0protected]</span>
`
#### Config:
https://github.com/effemmeffe/flexget/blob/master/config.yml1
  
### Additional information:

- Flexget Version: 2.8.4
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.1 LTS

**Comment by cvium** [comment]
This looks related to CloudFlare. Have you tried using https://flexget.com/Plugins/cfscraper?

**Comment by effemmeffe** [comment]
I don't even know what CloudFlare is.

**Comment by cvium** [comment]
CloudFlare is mostly used for DDoS protection, but it also tends to affect non-malicious automated bots.

**Comment by effemmeffe** [comment]
Ok, will try it.

**Comment by cvium** [comment]
Bah, looks like it won't have any effect because of how we wrote the plugin. I'll see if I can reproduce it.

**Comment by cvium** [comment]
Can't reproduce it. I'll push a change that should make cfscraper work with the plugin. You can test it tomorrow.

**Comment by cvium** [comment]
Is this still an issue?

**Comment by effemmeffe** [comment]
Never occurred again, thanks.
