### ISSUE TITLE
movie-list CLI: can't delete a movie if the title ends with something in parenthesis

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#1562]
### Expected behaviour:
Be able to copy the movie title from the output of `flexget movie-list list [LIST_NAME]` and remove it from the list with the command `flexget movie-list del [list name] <movie title>`.

### Actual behaviour:
If the movie title ends with something in parenthesis, e.g. `The Human Centipede III (Final Sequence)` (please don't ask how this movie ended up on my list), the movie-list plugin is not able to find it in the list. It seems that it treats the part in parenthesis as the year of the movie.

### Steps to reproduce:
- Add a movie with parentheses in the title to a list, e.g. `flexget movie-list add [LIST_NAME] "The Human Centipede III (Final Sequence)" -i imdb_id=tt1883367`
- Output the movie list: `flexget movie-list list [LIST_NAME]`
- Copy the movie title: `The Human Centipede III (Final Sequence)`
- Remove it from the list: `flexget movie-list del [LIST_NAME] "The Human Centipede III (Final Sequence)"`
- Get an error: "Could not find movie with title The Human Centipede III (Final Sequence) in list [LIST_NAME]"

#### Config:
Irrelevant.
  
#### Log:
No entries in the log that seem relevant.

### Additional information:

- Flexget Version: 2.8.4
- Python Version: 2.7.9
- Installation method: pip
- OS and version: OSMC: Open Source Media Center

### Workaround

Add the year manually:
`flexget movie-list del [LIST_NAME] "The Human Centipede III (Final Sequence) (2015)"`
`Removing movie The Human Centipede III (Final Sequence) (2015) from list [LIST_NAME]`

It would also be nice if there was a way of removing a movie by one of the IDs, e.g. `flexget movie-list del [LIST_NAME] -i imdb_id=tt1883367`.

**Comment by liiight** [comment]
I added the ability to delete by movie ID with https://github.com/Flexget/Flexget/commit/8bce8453e1abdf7dd7400a87cf11297759ac5068
It's not a full fix, but will do until I change the title matching logic (it has some effects on movie list in general, need to test it thoroughly)

**Comment by liiight** [comment]
I think this can be closed actually.
