### ISSUE TITLE
Forget series not working

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1564]
I'm trying to have flexget to forget the show High maintenance.
I removed the show from my trakt.tv list.
Then I ran flexget forget "High maintenance", it reports that multiple series match to `high maintenance`:

```
fmf@kodi:~$ flexget series show "high maintenance"
There is a FlexGet process already running for this config, sending execution there.
 WARNING: Multiple series match to `high maintenance`.
 Be more specific to see the results of other matches:
 
 High Maintenance (2016)
 
┌High Maintenance─────────┬────────────────────────────────────────────────┬─────────────────┬────────┐
│ Episode ID │ Latest age │ Release titles                                 │ Release Quality │ Proper │
├────────────┼────────────┼────────────────────────────────────────────────┼─────────────────┼────────┤
│ S01E04     │ 4h         │ High Maintenance - S01E04 - [720p hdtv h264] * │ 720p hdtv h264  │        │
│ S01E05     │ 4h         │ High Maintenance - S01E05 - [720p hdtv h265] * │ 720p hdtv h265  │        │
│ S01E06     │ 4h         │ High Maintenance - S01E06 - [720p hdtv h264] * │ 720p hdtv h264  │        │
└────────────┴────────────┴────────────────────────────────────────────────┴─────────────────┴────────┘
 * Downloaded
 
 Series uses `ep` mode to identify episode numbering (identified_by).
 See option `identified_by` for more information.
```

But it seems it worked:

```
fmf@kodi:~$ flexget series forget "High Maintenance (2016)"
There is a FlexGet process already running for this config, sending execution there.
Removed series `High maintenance (2016)` from database.
```

But actually it's not:

```
fmf@kodi:~$ flexget series show "high maintenance"
There is a FlexGet process already running for this config, sending execution there.
 
┌High Maintenance─────────┬────────────────────────────────────────────────┬─────────────────┬────────┐
│ Episode ID │ Latest age │ Release titles                                 │ Release Quality │ Proper │
├────────────┼────────────┼────────────────────────────────────────────────┼─────────────────┼────────┤
│ S01E04     │ 4h         │ High Maintenance - S01E04 - [720p hdtv h264] * │ 720p hdtv h264  │        │
│ S01E05     │ 4h         │ High Maintenance - S01E05 - [720p hdtv h265] * │ 720p hdtv h265  │        │
│ S01E06     │ 4h         │ High Maintenance - S01E06 - [720p hdtv h264] * │ 720p hdtv h264  │        │
└────────────┴────────────┴────────────────────────────────────────────────┴─────────────────┴────────┘
 * Downloaded
 
 Series uses `ep` mode to identify episode numbering (identified_by).
 See option `identified_by` for more information.
 
fmf@kodi:~$
```

So I did some digging: I noticed that if I run `flexget -L debug forget $SHOWNAME` it run forget command on the show and on all the episodes somewhere (maybe in the seen database? don't know, don't really care, somewhere it's enough fo rme at this point)
But if I run `flexget -L debug forget "high maintenance"` it doesn't run forget on that somewhere, so if then I run `flexget -L debug forget "high maintenance"` I still see the episodes list.
So I tried to run `flexget -L debug forget "high maintenance (2016)"` afterward and it run forget also on those episodes, even if the show is become unknown due to the first forget command.
It happens on shows with the ($YEAR) in the name, another one is "shut eye (2016)".

Dug a little more and another problem popped up on the web-ui: I had a show on the trakt list named Chewing gum.
I removed it from trakt.tv, stopped the daemon, run the series forget command and it seems it's forgotten:
```
fmf@kodi:~$ flexget series show "chewing gum"
There is a FlexGet process already running for this config, sending execution there.
ERROR: Unknown series chewing gum
fmf@kodi:~$

```
Then I started the daemon, but in the web ui I still see it: http://i.imgur.com/nhGkTVB.png

#### Config:
https://github.com/effemmeffe/flexget/blob/master/config.yml

  
### Additional information:

- Flexget Version: 2.8.4
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.1 LTS

**Comment by liiight** [comment]
ui issue aside (clear browser cache and try again) i'm still not convinced that there's an issue here.
paste output of `flexget series show "high maintenance"` again please.

**Comment by effemmeffe** [comment]
```
fmf@kodi:~$ flexget series show "high maintenance"
There is a FlexGet process already running for this config, sending execution there.

┌High Maintenance (2016)──┬────────────────┬─────────────────┬────────┐
│ Episode ID │ Latest age │ Release titles │ Release Quality │ Proper │
└────────────┴────────────┴────────────────┴─────────────────┴────────┘
 * Downloaded

 Series uses `ep` mode to identify episode numbering (identified_by).
 See option `identified_by` for more information.

fmf@kodi:~$
```

**Comment by liiight** [comment]
looks like it did delete and forget everything but you still have a task that configures that show.

**Comment by effemmeffe** [comment]
How do I get rid of it?

**Comment by liiight** [comment]
remove it from the task? you're probably getting it from a trakt list. that's why you see it in the ui too btw. 
anyway, not a bug

**Comment by gazpachoking** [comment]
Do a shift-reload in the webui to make sure you have most recent data. I found that series removes or forgets didn't populate in the webui until I did the full reload.
