### ISSUE TITLE
CRITICAL error in task with plugin email

### ISSUE THREAD

**Issue by atekoa** [Flexget/Flexget#1568]
### Expected behaviour:
Send an email

### Actual behaviour:
Critical error
BUG: Unhandled error in plugin email: 'in <string>' requires string as left operand, not int

### Steps to reproduce:
Use this config.yml

#### Config:
```
templates:
  global:
    email:
      from: xxx@domain.com
      to: xxx@gmail.com
      smtp_host: domain.com
      smtp_port: 587
      smtp_username: xxx@domain.com
      smtp_password: _thepasss123_
      smtp_tls: true
  # Series
  series-dir:
    thetvdb_lookup: yes
    series:
      agroup:
        - House
        - Westworld
tasks:
  sort-series:
    priority: 10
    filesystem:
      path: /downloaded/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    seen: local
    template:
      - series-dir
    series:
      settings:
        agroup:
          parse_only: yes
    require_field: series_name
    accept_all: yes
    move:
      to: /series/{{tvdb_series_name|default(series_name)}}/s{{tvdb_series_season|default(series_season)}}/
```
  
#### Log:
```
2016-12-16 20:45 CRITICAL task          sort-series     BUG: Unhandled error in plugin email: 'in <string>' requires string as left operand, not int
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/email.py", line 167, in on_task_output
    plugin.get_plugin_by_name('notify').instance.send_notification(task, notify_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify.py", line 152, in send_notification
    notifier.notify(**notification_data)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/email.py", line 151, in notify
    mailServer.login(str(smtp_username), str(smtp_password))
  File "/usr/lib/python2.7/smtplib.py", line 607, in login
    (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
  File "/usr/lib/python2.7/smtplib.py", line 571, in encode_cram_md5
    response = user + " " + hmac.HMAC(password, challenge).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
  File "/usr/local/lib/python2.7/dist-packages/future/types/newstr.py", line 390, in translate
    if ord(c) in table:
TypeError: 'in <string>' requires string as left operand, not int
```

### Additional information:

- Flexget Version: 2.8.4
- Python Version: 2.7.9
- Installation method: pip
- OS and version: xbian raspberry b+
- Link to crash log:

**Comment by liiight** [comment]
@gazpachoking i kept that `str` in the refactor:
https://github.com/Flexget/Flexget/blob/e52cd99f2207154a120d342618bf64d2c5f0c736/flexget/plugins/notifiers/email.py#L151-L151
Not sure if that's even needed, probably can get rid of that.

**Comment by atekoa** [comment]
Could it be related to ascii encoding or something like?

**Comment by liiight** [comment]
yep, it's in the neighborhood. you down for a little experiment? I wanna change a line in `/flexget/plugins/notifiers/email.py`. Change line 151 to:
`mailServer.login(smtp_username, smtp_password)`
this seems to work for me in py2 and py3

**Comment by atekoa** [comment]
I'm pretty sure that the problem is because the smpt_username contains '@' that is needed in my case

**Comment by liiight** [comment]
I doubt it. `@` is in ASCII, no reason for it to fail. Did you try my change?

**Comment by atekoa** [comment]
CRITICAL task          sort-series     BUG: Unhandled error in plugin email: character mapping must return integer, None or unicode

**Comment by liiight** [comment]
Hmm, is your password digits only? Try adding "" in the config if so

**Comment by liiight** [comment]
Same credentials worked on a different server? 
Hit me up on https://gitter.im/Flexget/Flexget if you can, I'd like to test with your credentials if possible

**Comment by gazpachoking** [comment]
> @gazpachoking i kept that str in the refactor:
> https://github.com/Flexget/Flexget/blob/e52cd99f2207154a120d342618bf64d2c5f0c736/flexget/plugins/notifiers/email.py#L151-L151
> Not sure if that's even needed, probably can get rid of that.

This is almost certainly something to do with it. I suspect either we should take that out, or perhaps it should be a native_str. smtplib doesn't document very well what it's expecting for these on the different python versions.

**Comment by gazpachoking** [comment]
Did a bit more poking in smtplib, looks like indeed we should be sending these params as a native str on both platforms.

**Comment by liiight** [comment]
closed with https://github.com/Flexget/Flexget/commit/01eabe345b1ca91019889834438ec2f0e49d93e8
messed up the bug number on the commit...
