### ISSUE TITLE
`failed list` failure

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1580]
$ flexget -V
    2.8.8
    $ flexget failed list
    ERROR: Table could not be rendered correctly using it given data
    $ flexget failed list | less
    Could not start manager: 'ascii' codec can't encode character u'\xe1' in position 500: ordinal not in range(128

**Comment by liiight** [comment]
Could you verify that this worked please?

**Comment by grr** [comment]
only the first failure is fixed. the other error (when piping output) is still failing. you probably need to test with an entry that has non-ascii in the title.

**Comment by liiight** [comment]
Will do, at least this one is fixed.
