### ISSUE TITLE
porcelain mode should not be adding extra whitespace

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1584]
an issue from https://github.com/Flexget/Flexget/issues/1361#issuecomment-256147795 was never addressed:

> under porcelain mode there's lots of whitespace padding being added to the end of the fields to match the length of the longest field value of the entire output, so too much whitespace is added  which causes it to wrap and appear as if an extra line is added. in my case, i have a url (from `flexget history | less`) which causes it's line (`URL | ...`) to be 171 characters, but that results in every single line of output to be padded to 171 characters.

**Comment by liiight** [comment]
Hmm, should we just disable all padding in porcelain mode?

**Comment by liiight** [comment]
oh i misunderstood you i think. what do you expect it to do, truncate values? porcelain doesn't wrap the fields

**Comment by gazpachoking** [comment]
@liiight I'm guessing this is referring to extra whitespace after the last character in a line, but before the newline?

**Comment by liiight** [comment]
Yeah, that's what I meant. That is the expected behavior, porcelain mode does not touch the output data in any way.

**Comment by grr** [comment]
That extra space isn't in the data itself, and it shouldn't be added under porcelain mode. It makes it harder to read the information.

@liiight, do you really believe this is what users should see?  http://i.imgur.com/nk2i64t.png
*redactions in white

**Comment by liiight** [comment]
The wrapping comes from the usage of less and not from the table data itself probably. 
I'm not arguing that this isn't pretty but I'm asking what alternative can there be? If a value in a column is long, what would you expect the table to do other than wrap it or drop the entire column?

**Comment by grr** [comment]
`less` does not add spaces, but I think flexget had different logic if the terminal was interactive. 

But the wrapping you're talking about isn't even done properly. The long lines are wrapped naturally by the user's terminal and does not use the internal wrapping function implemented by flexget. You can see that in the long url in my screenshot. The added trailing spaces serve no purpose other than annoyance, since they don't help align anything.

Porcelain is described in the docs as parseable output.  I think in this mode there should be no wrapping and no formatting. Even the field names should not have padding.

**Comment by gazpachoking** [comment]
```
' Task    | test_Aranyélet•                                              \n Title   | Ara•nyélet.S01E01.720p.x264-FlexGet                          \n URL     | mock://localhost/mock/1019166630                             \n Time    | Sun Dec 25 11:30:50 2016                                     \n Details | Accepted by series (reason: choosing best available quality) '
```
@liiight The issue in question is the spaces directly before the newlines as can be seen more easily in the output above. I'm not sure if it should abandon alignment altogether in porcelain mode, but the whitespace before the newlines could certainly be removed with no side effects other than to prevent the extra wrapping (that I can think of.)

**Comment by mfonville** [comment]
@grr 
I think the docs then don't describe the *porcelain* vs *plumbing* in the way it was coined for git.
For git the porcelain mode is NOT meant to be parsed by scripts, but should be presented in a human-readable manner. *no wrapping and no formatting* would NOT be in line with that.

What you are looking for if wanting unformatted data, would be some *plumbing* commands instead.

**Comment by liiight** [comment]
Ok, I got this now, sorry for being thick.
Some table we created are ( like `history` and `seen`) different in the sense that they have a vertical axis instead of the default horizontal one that the majority of tables have, The reason for this is that the expected output of each of the column would always be long (title, URLs etc.).
The apparent problem with this approach is that we mess up some of the default behavior of the table. Since cell alignment is pretty much what this feature does, disabling it per a specific scenario could be tricky. I'll look into it

**Comment by liiight** [comment]
Opened relevant PR at lib repo

**Comment by gazpachoking** [comment]
@liiight If it's not appropriate to get it in upstream we could just do the stripping after all the other formatting here https://github.com/Flexget/Flexget/blob/develop/flexget/terminal.py#L95

**Comment by liiight** [comment]
Not really @gazpachoking. `self.table.table` will return one formatted string, which will be near impossible and very hacky to try and manipulate imo. 
You need to do thus at the table creation. I'm obviously open to suggestions though, I don't see how it could be done alternatively.

**Comment by grr** [comment]
it's very simple to do with a single regular expression, but yes. it's hacky, but it is simple.

**Comment by liiight** [comment]
I'll push the regex fix until that pr will be accepted.
