### ISSUE TITLE
Error downloading from FTP: Retrying download after error signed integer is greater than maximum

### ISSUE THREAD

**Issue by ghost** [Flexget/Flexget#1593]
### Expected behaviour:
download multiple files from ftp
### Actual behaviour:
randomly the download stops and retry multiple times with this debug message:

Retrying download after error signed integer is greater than maximum

### Steps to reproduce:
- Step 1: launch flexget -L trace execute

#### Config:
```
download_files:
    manual: no
    ftp_list:
      host: *********
      username: ***********
      password: ***********
      recursion: false
      retrieve: dirs
      use_ssl: no
      dirs:
        - '/files/COMPLETED'
    disable:
      - seen_info_hash
      - seen
      - backlog
    accept_all: yes
    ftp_download:
      ftp_tmp_path: /mnt/*****/
      delete_origin: true
      use-ssl: yes
```
  
#### Log:
```
2016-12-30 00:15 INFO     ftp           download_files Starting download .....
2016-12-30 00:15 DEBUG    ftp           download_files Retrying download after error signed integer is greater than maximum
2016-12-30 00:15 DEBUG    ftp           download_files Connecting to *****
2016-12-30 00:15 DEBUG    ftp           download_files Changing directory to: //files/COMPLETED/****
2016-12-30 00:15 DEBUG    ftp           download_files Retrying download after error signed integer is greater than maximum
2016-12-30 00:15 DEBUG    ftp           download_files Connecting to *****
```

### Additional information:

- Flexget Version: 2.8.14
- Python Version: Python 2.7.12
- Installation method: pip
- OS and version: Ubuntu 14.04 LTS
- Link to crash log: No crash log created

**Comment by crawln45** [comment]
Problem stems from https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/ftp_download.py#L163-L167

Setting file size to 1 when the file is bigger than 1. So once the local file exceeds one it errors out. @liiight @cvium not exactly sure what could be done on this. Seems like the ftp server isn't sending a filesize when requested.

**Comment by liiight** [comment]
we probably need to redo this plugin with an ftp lib

**Comment by paranoidi** [comment]
Raise exception (PluginError) saying server does not give size, setting value to 1 is not the right way to handle error ..
