### ISSUE TITLE
Plugin loading from external directories

### ISSUE THREAD

**Issue by kevin-stuart** [Flexget/Flexget#1595]
I'm not sure if there is a way to do this or if this is a feature request or an oversight:

Assume that I have a plugin that works if placed with regular plugins: `flexget/plugins/filter/my_filter.py`. I now want to this plugin from a custom directory location, for example, assume that it is now located at `~/foobar/flexget/plugins/filter/my_filter.py`.

I tried using `PYTHONPATH` or `FLEXGET_PLUGIN_PATH`, but neither worked; either all other regular plugins in the flexget plugin directory are no longer found or my plugin cannot be found. Is my use case supported? Or am doing something wrong?

There could be more documentation for this, I found `FLEXGET_PLUGIN_PATH` by looking at the source of `flexget/plugin.py`.

**Comment by cvium** [comment]
The third party plugin directory is usually `~/.flexget/plugins`. It should be a folder called `plugins` in the same directory as your config.

**Comment by kevin-stuart** [comment]
Thanks for the feedback. Is it possible to change this?

**Comment by cvium** [comment]
Not that I know of.

**Comment by kevin-stuart** [comment]
I just tried your suggested method. I copied the `flexget/plugins/filter/accept_all.py` to `./plugins/filter/accept_all.py` (with `.` I mean the directory where my config file is and I call `flexget execute`). Then I renamed it to accept_all2.py and inside I changed the string to 'accept_all2' and the class name in the register call and above as well.

While it seems that this use case is supported as just creating the file changed the behavior without any further configuration; I did not even use the plugin in the configuration. However, the problem now is that I get some error regarding the dependencies:

```
2016-12-30 14:00 CRITICAL plugin                        Plugin `flexget.plugins.filter.accept_all2` failed to import dependencies
Traceback (most recent call last):
  File "/opt/python27/lib/site-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
ImportError: No module named accept_all2
2016-12-30 14:00 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-12-30 14:00 VERBOSE  details       task1      Produced 2 entries.
2016-12-30 14:00 WARNING  task          task1      Task does not have any filter plugins to accept entries. You need at least one to accept the entries you  want.
2016-12-30 14:00 VERBOSE  details       task1      Summary - Accepted: 0 (Rejected: 0 Undecided: 2 Failed: 0)
2016-12-30 14:00 WARNING  task          task1      Task doesn't have any output plugins, you should add (at least) one!
```

It does not say what the problem is. Do I need to do anything else for this to work?

**Comment by cvium** [comment]
Sounds like you changed too much/little. Just change https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/filter/accept_all.py#L31 to `plugin.register(FilterAcceptAll, 'accept_all2', api_ver=2)`

**Comment by kevin-stuart** [comment]
The error remains the same. I just tried to create a minimal working test. I should be able to use an arbitrary in register as long as I still use the same name in the declaration above. If I place the file inside the `site-packages/flexget/plugins/filter` everything works, if I move the file to `./plugins/filter` it breaks for me. Is there anything else I need to do for it to work?

**Comment by kevin-stuart** [comment]
I think I found the problem: In the "plugins" directory, the structure must not mirror the structure of the flexget packages; i.e. you cannot use a "filter" subdirectory as it was used, instead the `*.py` file for the plugin has to placed directly in `plugins`.

Nevertheless, this is all not easily accessible or well-documented, or is it? And this is more or less a workaround for what I initially asked, although I guess using the current working directory as it can be done is not a bad solution for using a custom path.

**Comment by paranoidi** [comment]
Hmm, yeah. It was never intended to have directory structure in there. Indeed, not very well documented (if at all).

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
