### ISSUE TITLE
Upgrade flask-restplus to 0.9.2

### ISSUE THREAD

**Issue by arcresu** [Flexget/Flexget#1615]
Currently `flask-restplus` is pinned at 0.8.6. Would it be possible to update this to the newest `0.9.2`? Below is the relevant changelog delta.

The first breakage I see is that in noirbizarre/flask-restplus@c716cc4bdd26676c6d11c0199e878c5bd674030d (part of noirbizarre/flask-restplus#95) the `Api.response` method was moved to `Namespace.response`, and Flexget is [patching this at its original location](https://github.com/Flexget/Flexget/blob/bb6d3df69475d64c3df18db82a31945686400a3d/flexget/api/app.py#L191-L205).

### 0.9.0 (2016-02-22)
  - **Make `Namespace` behave like `flask.Blueprint` for `flask.Flask`**
  - Deprecated ``parser`` and ``body`` parameters for ``expect`` in `Namespace.doc` decorator
  - Deprecated `Model.extend` in favor of `Model.clone`
  - Added the `Namespace.param` decorator
  - Honour method restrictions in Swagger documentation (noirbizarre/flask-restplus#93)
  - Improved documentation

### 0.9.1 (2016-04-22)
  - Added some Swagger-UI Oauth configurations:
      - `SWAGGER_UI_OAUTH_CLIENT_ID`
      - `SWAGGER_UI_OAUTH_REALM`
      - `SWAGGER_UI_OAUTH_APP_NAME`
  - Expose ``type: object`` in Swagger schemas (noirbizarre/flask-restplus#157)
  - Fix an issue with error handlers (noirbizarre/flask-restplus#141)
  - Fix an issue with Postman export when using OAuth (noirbizarre/flask-restplus#151)
  - Miscellenaous code and documentation fixes
  - Remove last `flask-restful` references (unless needed) and add missing attributions

### 0.9.2 (2016-04-22)
  - Same version but a PyPI bug force reupload.

**Comment by liiight** [comment]
We have an outstanding pr in that repo that is yet to be merged. It's almost two years old now so it should probably any moment now... 
Restplus project is unfortunately dead, it's dev abandoned it. 
But why is this an issue to you? Api works fine with the current version.

**Comment by arcresu** [comment]
I didn't notice a PR, which one did you mean? It seems like the project still has some activity though - the dev updated the contributing guidelines as recently as October.

My interest is that I'm resuming in earnest my efforts to package Flexget for Debian, starting with its dependencies. Flask-restplus is one of the dependencies which is not already in Debian and if I'm going to package it it seemed sensible to package the most recent version. However since the motivation is just to get Flexget working (for now) I can presumably get away with packaging the exact version Flexget needs.

The only actual dependency blocker I'm seeing is #1398 since Debian already has a newer version of guessit and we can't downgrade to satisfy the existing Flexget requirement there.

**Comment by liiight** [comment]
I invite you to look into restplus gitter to see how much it's dead, which sucks. 
Anyway, this is not an issue.
