### ISSUE TITLE
"New version available" indicator on Web-UI issue

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1617]
Hi, 

The "New version available" indicator on the Web-UI doesnt work. Available version is not correct.

```
Version info
Flexget: 2.8.23  "New version available (2.8.20)
API: 1.1.2
```

**Comment by liiight** [comment]
Why do you think it doesn't work?

**Comment by Tommatheussen** [comment]
It seems the deploy process is not tagging the GitHub releases anymore, so the check for latest version is stuck on `2.8.20`.
This doesn't take away the fact that it shouldn't show previous version as new available ones.

**Comment by cvium** [comment]
This should be fixed now.

**Comment by Tommatheussen** [comment]
Actually, not completly, sure the API side returns correct info now, but the procedure of showing it in de UI still is wrong (nomally lower versions don't appear, but still...)

**Comment by cvium** [comment]
Good point.
