### ISSUE TITLE
Can’t send email notification with full statistics including rejected and undecided entries (not only accepted/failed ones)

### ISSUE THREAD

**Issue by dchubkov** [Flexget/Flexget#1657]
### Expected behaviour:
notification with accepted|rejected|undecided|failed entries is sent

### Actual behaviour:
notification with only accepted and failed entries is sent

### Steps to reproduce:
- Step 1: add to tasks "digest" plugin with "accepted|rejected|undecided|failed" options
- Step 2: add "emailreport" task with "notify" and "from_digest" plugins and "restore_state: yes" option
- Step 3: execute tasks from step 1

#### Config example:
```
schedules:
  - tasks: 'task1'
    interval:
      hours: 2
  - tasks: 'task2'
    interval:
      hours: 4
  - tasks: 'emailreport'
    schedule:
      hour: 21
...
templates:
  ...
  video:
    digest:
        list: email_list
        state:
          - accepted
          - rejected
          - undecided
          - failed
...
tasks:
  task1:
    template:
      - video
...
  task2:
    template:
      - video
...
  emailreport:
    no_entries_ok: yes
    from_digest:
      list: email_list
      restore_state: yes
    seen: local

    notify:
      task:
        title: "[FLEXGET] Daily report"
        template: custom_html.template
        via:
          - email:
              from: '{? email.email_from ?}'
              to:
                - '{? email.email_to1 ?}'
                - '{? email.email_to2 ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? email.smtp_username ?}'
              smtp_password: '{? email.smtp_password ?}'
              smtp_tls: yes
              html: yes
```
  
#### Log:
```
2017-01-26 21:00 VERBOSE  details       emailreport     Produced 586 entries.
2017-01-26 21:00 VERBOSE  manipulate    emailreport     Modified 0 entries.
2017-01-26 21:00 VERBOSE  details       emailreport     Summary - Accepted: 0 (Rejected: 1070 Undecided: 586 Failed: 0)
2017-01-26 21:00 WARNING  task          emailreport     Task doesn't have any output plugins, you should add (at least) one!
2017-01-26 21:00 VERBOSE  notify_entry  emailreport     No accepted or failed entries, not sending a notification.
```

### Additional information:

- Flexget Version: 2.9.8
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04

P.S.
As @liiight proposed maybe "always_send" should be added to the "notify" plugin

Related issue and FR in forum:
https://discuss.flexget.com/t/cant-send-email-notification-with-full-statistics-including-rejected-and-undecided-entries-not-only-accepted-failed-ones/3129
https://discuss.flexget.com/t/add-always-send-option-to-notify-plugin/3130?source_topic_id=3129

**Comment by gazpachoking** [comment]
The concern I have is making sure the template lines up with when the plugin sends. If we add an always_send option to task notifications, but the configured template doesn't report on rejected or failed entries, it will start sending out mostly blank emails. I'm not sure the best solution.

**Comment by liiight** [comment]
I think this is solvable via some jinja if condition, shouldn't be a problem imo

**Comment by dchubkov** [comment]
Yes, in my custom_html.template I have something like this:

```
{% if task.accepted %}
...
{% endif %}
{% if task.rejected %}
...
{% endif %}
...
etc.
```

**Comment by cvium** [comment]
That's not going to stop it from sending you a blank email.

**Comment by gazpachoking** [comment]
We could go back to the way email plugin did it, and make the template have the logic (and produce a totally blank result to signify nothing should be sent.) I wasn't wild about that, but I guess it sorta makes sense, as the template has to match whatever logic you have for sending notifications anyway.

**Comment by liiight** [comment]
Nah, that's not so nice

**Comment by dchubkov** [comment]
For me the empty email is not a problem at all. The problem is that I can't send report with anything except accepted and failed reports. The problem is that new notification approach is less configurable and flexible than previous one, imho. If someone like me would like to receive extended report then just put a note in Wiki about possible empty email sending.
Or additionally to the "always_send" option add kind of "except_empty" option with default "true" value :)

**Comment by cvium** [comment]
That's awful tbh. It needs to be done right.

**Comment by dchubkov** [comment]
Sorry guys, maybe I'm not completely understand the problem.
In current implementation notify plugin sends emails about only accepted and failed entries. If none of them exists - it does not send email.

I'm not asking to break this logic, I'm just kindly asking to add 2 more states. 
If none of them (including rejected and undecided) entries exists - do not send email (or any other type of notification)

**Comment by cvium** [comment]
I think adding a config option like
```
notify:
  when:
    - accepted
    - failed
    - rejected
```
would be better. It at least makes it clearer.

**Comment by gazpachoking** [comment]
> I think adding a config option like
> 
> notify:
>   when:
>     - accepted
>     - failed
>     - rejected
> would be better. It at least makes it clearer and the template is free to pull any entries.

Would that be passed in to the template as well somehow? Or the templates should show all of those and you'll see all of them when the right event fires?

**Comment by gazpachoking** [comment]
> Or the templates should show all of those and you'll see all of them when the right event fires?

Hmm, on second thought, that's not so good. We don't want to see rejected entries in every email if it isn't selected. I guess we need some way to pass that selection in to the template.

**Comment by liiight** [comment]
I think we're over thinking this. Sending a notification per task run is a non common scenario. I'd say we add a statistics templates and mention in the wiki that this can result in empty notifications.

**Comment by gazpachoking** [comment]
> I think we're over thinking this. Sending a notification per task run is a non common scenario. I'd say we add a statistics templates and mention in the wiki that this can result in empty notifications.

You mean it would change the trigger events based on selecting one specific template? Or you mean along with adding an option on when to trigger, but certain triggers are only compatible with certain templates..

**Comment by gazpachoking** [comment]
Maybe we switch the task template to iterate over the all_entries list, and also pass in some sort of filter function, or list of desired states?

**Comment by cvium** [comment]
@gazpachoking My idea was just to make it send notifications if there were any entries with the desired state and then pass all entries to the template.

**Comment by gazpachoking** [comment]
@cvium What do you mean by "all entries"?

**Comment by cvium** [comment]
I just mean "make all entries available in the template", which I think they already are?

**Comment by gazpachoking** [comment]
Indeed they are available, the task just gets passed into the context. I guess I just think it would be surprising that there is an option to send notifications on different triggers, e.g. rejected entries, but that the included templates would send notifications about accepted and failed entries only in that case still. I don't really want to add complicated logic in though, maybe you guys are right. If we add it, I think we should discourage use of this new option in the docs, and clearly list the caveats to do with template matching your desired (uncommon) needs.

**Comment by liiight** [comment]
so we're cool with just adding a flag and a warning in the wiki?

**Comment by dchubkov** [comment]
Hello dear developers. Any news when this fix will be released? :)

**Comment by liiight** [comment]
@gazpachoking i wanna merge #1662. objections?
