### ISSUE TITLE
How to run tests (or please fix tests)

### ISSUE THREAD

**Issue by ymartin59** [Flexget/Flexget#1668]
### Expected behaviour:
I would like tests to run to confirm packaging of flexget is fully functional. My target is Synology using synocommunity wheel packaging chain.

### Actual behaviour:
When running tests on tag 2.9.14
```
$ nosetests
Ran 701 tests in 15.176s
FAILED (errors=644, failures=2)
```

### Steps to reproduce:
- pip install paver nose pytest
- git clone -b '2.9.14' --single-branch --depth 1 https://github.com/Flexget/Flexget.git
- cd Flexget
- pip install .
- nosetests

Alternatively the following `Dockerfile` can be used:
```
FROM python:2
RUN pip install paver nose pytest
RUN git clone -b '2.9.14' --single-branch --depth 1 https://github.com/Flexget/Flexget.git /Flexget
WORKDIR /Flexget
RUN pip install .
ENTRYPOINT nosetests
```

- Flexget Version: 2.9.14
- Python Version: 2.7.13
- Installation method: pip install
- OS and version: Debian 8.7

**Comment by cvium** [comment]
We don't use nosetests anymore. Run tests with `py.test`.

**Comment by ymartin59** [comment]
A so fast answer... For anyone else interested in details, here are tests requirements to install `pip install  mock vcrpy pytest pytest-capturelog` before expected `py.test` to pass.

**Comment by cvium** [comment]
Dev requirements can be installed with `pip install -r dev-requirements.txt`

**Comment by ymartin59** [comment]
Thanks. Here are results I got with my docker container:
```
======================================= pytest-warning summary ========================================
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
WI1 /usr/local/lib/python2.7/site-packages/pytest_capturelog.py:171 'pytest_runtest_makereport' hook uses deprecated __multicall__ argument
WC1 None pytest_funcarg__caplog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 None pytest_funcarg__capturelog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
========= 1082 passed, 26 skipped, 3 xfailed, 1 xpassed, 4 pytest-warnings in 292.75 seconds ==========
```
