### ISSUE TITLE
Resolve OSX "Deluge.App" and flexget compatability

### ISSUE THREAD

**Issue by tennantje** [Flexget/Flexget#1671]
### Expected behaviour:
When the installed version of Deluge is "Deluge.App" on MacOS (the standard version of installation on MacOS)- i.e. not via Macports or from source.

Running "flexget execute" should not result in the error:

"Plugin deluge cannot be used because dependency deluge is missing."

### Actual behaviour:
The Error occurs: "Plugin deluge cannot be used because dependency deluge is missing."

### Resolution
I'm not a python developer, well certainly not a competent one, but the following code resolves this bug when added to line 45 of "./flexget/clients/deluge.py". It's duplicated code from the Windows code above it, with an updated path to reflect OSX. It's for the reason of duplication, and my lack of python prowess that I've created this issue (rather than a pull request) as I suspect you'll refactor, and DRY it up.

```python
def add_deluge_osx_install_dir_to_sys_path():
    if not (sys.platform.startswith('darwin')):
        return
    deluge_dir = '/Applications/Deluge.app/Contents/Resources/lib/python2.7'
    log.debug('Looking for deluge install in %s' % deluge_dir)
    if not os.path.isdir(deluge_dir):
        return
    deluge_egg = glob.glob(os.path.join(deluge_dir, 'deluge-*-py2.?.egg'))
    if not deluge_egg:
        return
    minor_version = int(re.search(r'py2\.(\d).egg', deluge_egg[0]).group(1))
    if minor_version != sys.version_info[1]:
        log.verbose('Cannot use deluge from install directory because its python version doesn\'t match.')
        return
    log.debug('Found deluge install in %s adding to sys.path' % deluge_dir)
    sys.path.append(deluge_dir)
    for item in os.listdir(deluge_dir):
        if item.endswith(('.egg', '.zip')):
            sys.path.append(os.path.join(deluge_dir, item))


add_deluge_osx_install_dir_to_sys_path()
```

### Warning
This may introduce an issue for users who install via Macports or Source - but I'd imagine that this is the edge case. Perhaps instead of just simply querying the Operating system to apply this fix (like my code does above) you could query the existence (or non-existence) of an environment variable - and publish the required environment variable in your wiki?

**Comment by paranoidi** [comment]
Patching sys.path is a bit dangerous path ...

**Comment by tubedogg** [comment]
This is just anecdotal of course, but I have been running the code above for a month or six weeks now and have had no issues.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)

**Comment by tubedogg** [comment]
Added to [feathub](http://feathub.com/Flexget/Flexget/+12).

**Comment by tubedogg** [comment]
I released this as a separate third-party plugin. See the [wiki](https://flexget.com/Plugins/app_deluge_find).
