### ISSUE TITLE
error using Sickrage?

### ISSUE THREAD

**Issue by mgaulton** [Flexget/Flexget#1672]
### Expected behaviour:
Sickrage task should complete normally to build show list.
### Actual behaviour:
task crashes with unknown error
### Steps to reproduce:
run configured task, crash happens

#### Config:

Using latest Sickrage, master git branch, with Custom qualities (preferred and allowed list)

 Sickrage:
    priority: 10
    configure_series:
      from:
       sickbeard:
         base_url: http://localhost
         port: 8182
         api_key: <API>
         include_ended: true
         only_monitored: true
         include_data: true
    thetvdb_lookup: yes
    # content_size:
    #    max: 650
    all_series:
      quality: sdtv+ <=720p
      tracking: backfill
      propers: 12 hours
  
#### Log:
```
2017-02-07 11:22 CRITICAL task          Sickrage        BUG: Unhandled error in plugin configure_series: u'quality_details'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flexget/plugins/operate/configure_series.py", line 71, in on_task_start
    result = method(task, input_config)
  File "/usr/lib64/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flexget/plugins/input/sickbeard.py", line 108, in on_task_input
    fg_qualities = self.quality_requirement_builder(show_json['data']['quality_details']['initial'])
KeyError: u'quality_details'
```

### Additional information:

- Flexget Version: 2.9.15
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Opensuse Leap 42.2
- Link to crash log:

**Comment by liiight** [comment]
Please attach debug logs

**Comment by mgaulton** [comment]
That snip is all i really see in the debug log file. Is there a way to turn on higher logging?

**Comment by liiight** [comment]
`flexget --debug execute --tasks Sickrage`

**Comment by mgaulton** [comment]
thanks, coming up

**Comment by mgaulton** [comment]
[crash_report.2017.02.08.103707586363.txt](https://github.com/Flexget/Flexget/files/761098/crash_report.2017.02.08.103707586363.txt)

**Comment by liiight** [comment]
I pushed a check for this should be out next release.
Note that this is an issue with sicbeard/sickrage API, you should talk to them as well.

**Comment by mgaulton** [comment]
Ahh thanks for looking at it. I'll share it there as well.
