### ISSUE TITLE
Add helpful message when `flexget series list` is empty

### ISSUE THREAD

**Issue by haarts** [Flexget/Flexget#1720]
When no series are tracked/configured the command `flexget series list` returns an empty list.
That is not to say flexget doesn't know about *any* series, they might simply be unconfigured. The series can be viewed with the `flexget series list all` (or `flexget series list unconfigured`) command.

Currently the output of `flexget series list` is:
```shell
$ flexget series list

lqqqqqqwqqqqqqqqwqqqqqwqqqqqqqqqqqqwqqqqqqqqqqqqqqqk
x Name x Latest x Age x Downloaded x Identified By x
mqqqqqqvqqqqqqqqvqqqqqvqqqqqqqqqqqqvqqqqqqqqqqqqqqqj
Use `flexget series show NAME` to get detailed information
```

Like the helpful note on how to get more detailed information, a similar note could be added on the three available filters ('configured', 'unconfigured', 'all'). This message could be made conditional on the list being empty.

Additionally the output could lead with which filter the list is shown to begin with. Something like: 
```shell
$ flexget series list {,unconfigured,configured,all}
{Unconfigured,Configured,All} series are:
lqqqqqqwqqqqqqqqwqqqqqwqqqqqqqqqqqqwqqqqqqqqqqqqqqqk
x Name x Latest x Age x Downloaded x Identified By x
mqqqqqqvqqqqqqqqvqqqqqvqqqqqqqqqqqqvqqqqqqqqqqqqqqqj
Use `flexget series show NAME` to get detailed information
Use `flexget series FILTER` to use different filter
```

### Additional information:

- Flexget Version: 2.10.10
- Python Version: 3.5.2
- Installation method: pip3
- OS and version: Ubuntu 16.04

**Comment by haarts** [comment]
Would you mind assigning this one to me? Seems like something I can do and ease me into the project. Same for https://github.com/Flexget/Flexget/issues/1724 actually. I'll work on it beginning of next week.

**Comment by liiight** [comment]
Just post a pr then
