### ISSUE TITLE
Daemon is stopping after a connexion timeout with rss

### ISSUE THREAD

**Issue by Choukajohn** [Flexget/Flexget#1728]
Hi everyone,
I have an instance of flexget running in daemon mode and reading a rss flux every 10 min. But if for some reason the rss flux isn't available once and the connection timeout is reached the daemon is stopped immediately.
Last version of flexget.
Daemon started via crontab @reboot or manually.
Thanks for your help.

**Comment by cvium** [comment]
We have created an issue template for a reason.
