### ISSUE TITLE
Include plugin does not reload data from file on data change

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1733]
### Expected behaviour:
When a change is made to an external file added to a task with the ``include`` plugin, the change will be reflected in Flexget running in daemon mode, in a task that involves ``next_series_episodes`` (at least after ``daemon reload-config``, if not before).

### Actual behaviour:
I'm having a very similar problem to #957, and it seems to be related to discover/next_series_episodes, except I am using an ``include`` as opposed to a ``template`` directly in the config file. A change to the actual task in the main config file is required for the external include file to be reloaded. This does not seem to affect other uses of ``include``, such as a task filtering an externally included series list against an RSS feed - in that case, changes are always reflected immediately.

### Steps to reproduce:
- Step 1: Start Flexget in daemon mode.
- Step 2: Run the ``search_for_show`` task with debug logging and note what show name it lists as being searched for.
- Step 3: Change the show name in tmp/newshow and run ``flexget daemon reload-config`` (do not make any changes to the main config file).
- Step 4. Run the ``search_for_show`` task again and note that the show name being searched has not changed.

#### Config:
```
  search_for_show:
    manual: yes
    include: [tmp/newshow]
    discover:
      what:
        - next_series_episodes: yes
      from:
        - [search plugin]
      interval: 1 minute
```
Separate file ``tmp/newshow``:
```
    series:
      - Not Going Out:
          quality: 720p hdtv|webdl|webrip h264
          exact: yes
          begin: S08E01
 ```

#### Log:
The log just shows the series name being searched for. There are no error messages and no crashes.

### Additional information:

- Flexget Version: 2.10.9
- Python Version: 2.7.10
- Installation method: pip
- OS and version: macOS 10.11.6
- Link to crash log: n/a

**Comment by tubedogg** [comment]
I was playing around with this again this afternoon. I ran my task with ``--dump-config`` and it shows the new show being included in the merged config...but running the task again immediately results in the old show being used as the discover target.

**Comment by Jonybat** [comment]
I just ran into this issue. If you need any test or logs just let me know.

**Comment by tubedogg** [comment]
I'm assuming this is related to [this line](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/filter/series.py#L2025) in ``series``? So if the included file changes, what causes it to trigger that the config was modified?

**Comment by liiight** [comment]
This is purely an include plugin issue, has nothing to do with series

**Comment by tubedogg** [comment]
I assumed so. I was pointing to the fact that `series` checks if the config was modified before connecting series to tasks (which includes clearing old connections). The config is not being flagged as modified, hence my problems with `series`/`discover`.
