### ISSUE TITLE
Database upgrade returned (None) from plugin api_rottentomatoes

### ISSUE THREAD

**Issue by Meliox** [Flexget/Flexget#1734]
### Expected behaviour:
Database upgrade
### Actual behaviour:
Database upgrade failed.
### Steps to reproduce:
- Step 1: Upgrade from version 2.6.3 to 2.10.2 using pip install --upgrade setuptools & pip install --upgrade flexget.
- Step 2: Execute flexget -c config.yml check
- Step 3: Returns error: "A lower schema version was returned (None) from plugin api_rottentomatoes upgrade function than passed in (-1)"

#### Config:
```
Not relevant.
```
  
#### Log:
```
http://pastebin.com/nzDimsBx
```

### Additional information:

- Flexget Version: 2.10.2
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.2 LTS
- Link to crash log: Se above

**Comment by gazpachoking** [comment]
Hmm. This is a tough one. It seems like the logs are saying that this function returned `None`, but I can't see how that's possible at the moment. https://github.com/Flexget/Flexget/blob/83bc8dc86fd4760c4f059353975a24e04e681888/flexget/plugins/internal/api_rottentomatoes.py#L38-L54

**Comment by Meliox** [comment]
Isn't "None" returned from the db query? Which could mean that nothing is found in the db...

**Comment by Meliox** [comment]
Hmm. I must have been doing something wrong, I guess. As everything works now. I will close this issue and mark it as is invalid.
(It might work to reset the plugin using the sql query "insert into plugin_schema (plugin, version) values ('api_rottentomatoes', 0);)

**Comment by bash64** [comment]
i have the same error. however, there is no explanation of what made flexget start working...
