### ISSUE TITLE
Improvement: Allow specifying deluge config directory

### ISSUE THREAD

**Issue by BackSlasher** [Flexget/Flexget#1741]
### Expected behaviour:
In `flexget/plugins/clients/deluge.py`, username/password lookup is done using `get_localhost_auth`.
Have a field called `config_directory` to specify alternate config dir.

### Actual behaviour:
We have to use the default directory or explicitly specify all of the config (user/password/port)

### Additional information:
I'm thinking of doing this some day, just wanted to float that up in case this is interesting to anyone.

Looks like the right way is by importing `deluge.configmanager` and using `deluge.configmanager.set_config_dir`

https://github.com/s0undt3ch/Deluge/blob/5841521133f8bc1b761d6330c41312f8e83cb79d/deluge/configmanager.py#L127

- Flexget Version: 2.10.17
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.10
- Link to crash log:

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)

**Comment by BackSlasher** [comment]
Done in http://feathub.com/Flexget/Flexget/+7
