### ISSUE TITLE
imdb lookup invalid parameter

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1744]
Hi, i need german titles for my rss search, so i modify flexget just a bit, to get imdb german titles,
but then i get "invalid parameters"

https://nopaste.me/view/0d5895e4

i just change in
/usr/local/lib/python2.7/dist-packages/flexget/utils/imdb.py
from en-US,en to de-DE,de

then flexget is adding it with german title into database
BUTTTT
i get invalid parameter 
here is part of debug
https://nopaste.me/view/73d4229d

why is it search the RSS with english title, but not with german?

**Comment by liiight** [comment]
It doesn't find the movie because it can't get an estimation from bluray.com
Add `release_estimations: ignore` to your discover task
