### ISSUE TITLE
Join notifier requires api key

### ISSUE THREAD

**Issue by ShadwMan** [Flexget/Flexget#1746]
You can use API_KEY but cannot use DEVICE parameter to direct messages to specific devices. 

### Expected behaviour:
device parameter parameter used to direct notifications to specified devices....

### Actual behaviour:
Generates message on Join device:
API Key Not Used
All Join API pushes now REQUIRE the API Key parameter. Please go to https://joaoapps.com/join/web and regenerate your API URL with the apikey parameter

### Steps to reproduce:
- Step 1: Configure join notifier with devices
- Step 2: Trigger notify

#### Config:
```
          - join:
            device:
              devicekey1
              devicekey2```
  
#### Log:
```
Error while sending notification to `join`: User Not Authenticated
```

### Additional information:

- Flexget Version: 2.9.11
- Python Version: 2.7.12
- Installation method: pip
- OS and version: FreeBSD 11.0

**Comment by Bruny07** [comment]
[Here](https://plus.google.com/+Jo%C3%A3oDias/posts/GYwEvtSb238) is a post by the dev saying that from now on you need both the api key and device id

**Comment by ShadwMan** [comment]
That's the impression I was getting from the error message and the API messaging that was presented.

**Comment by liiight** [comment]
Wiki updated: https://flexget.com/Plugins/Notifiers/join
