### ISSUE TITLE
Deluge hide_sparse_files should avoid torrent collision

### ISSUE THREAD

**Issue by BackSlasher** [Flexget/Flexget#1754]
### Issue:
Usecase: Having multiple torrents with `move_content` set to `/` to get the main file "out" of the parent directory in the same folder (think show episodes in a specific season).

Because of the way [moving sparse files works](https://github.com/Flexget/Flexget/blob/2.10.20/flexget/plugins/clients/deluge.py#L650), they will be moved to a directory called `.sparse_files` in the torrent's parent directory, meaning that multiple torrents can collide.
A possible solution is to change the directory to be named `sparse_files_TORRENTID`, since I assume torrent IDs are unique in Deluge

Could be related to #804 (not sure what the problem is there)
Original behavior change in #489

#### Config:
```
    set:
      # Slash is to game the deluge plugin into taking the file out of its directory
      content_filename: >
        /{{ series_name }} - {{ series_id }}
        {% if trakt_ep_name|default(False) %} - {{ trakt_ep_name }} {% endif %} - {{
        quality|upper }}
        {% if proper_count %} - proper{% if proper_count > 1 %}{{ proper_count }}{%
        endif %}{% endif %}

```
### Additional information:

- Flexget Version: 2.10.20
- Python Version: 2.7
- Installation method: pip
- OS and version: Ubuntu 16.10

**Comment by BackSlasher** [comment]
Might grab that, just wanted to share first

**Comment by gazpachoking** [comment]
Hmm, if I remember correctly, moving files from a torrent out of their parent folder isn't a thing anymore with deluge. If that's the case, this issue should be moot. Please re-open if not.
