### ISSUE TITLE
t411.li changed to t411.ai

### ISSUE THREAD

**Issue by karma007** [Flexget/Flexget#1756]
### Expected behaviour:

thanks for the change (api, etc.)

### Steps to reproduce:
- Step 1: ...

#### Config:
```
paste relevant config
use paste service if config is too long
```
  
#### Log:
```
paste log output
use paste service if log is too long
```

### Additional information:

- Flexget Version:
- Python Version:
- Installation method:
- OS and version:
- Link to crash log:

**Comment by liiight** [comment]
Ignoring the template will just get your issue ignored.

**Comment by karma007** [comment]
sorry but it's too complicated, i'm not a developer. thanks
