### ISSUE TITLE
Pass quality parameters to BTN search

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1758]
The BTN API supports sending [quality parameters](http://apidocs.broadcasthe.net/apigen/class-btnapi.html#_getTorrents) in a search request. Using the quality string, if present in the entry, would narrow the results returned and present a greater likelihood of finding what the user wants when there are a lot of results.

There is at least one caveat - WEB-DL and WEBRip are condensed into a single "WEB" identifier.

**Comment by liiight** [comment]
I feel like you could probably do this one yourself already 😉

**Comment by tubedogg** [comment]
I've started to do this a couple times but I need to figure out how to get the quality field from ``discovery`` to ``btn`` (since ``next_series_*`` doesn't actually loop through the entries).

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
