### ISSUE TITLE
T411 new domain

### ISSUE THREAD

**Issue by scoony** [Flexget/Flexget#1764]
### Expected behaviour:
supposed to work

### Actual behaviour:
can't work properly due to new domain and maybe an API change

### Steps to reproduce:
Simply execute using t411 to reproduce

#### Config:
Ubuntu 16.04.2
  
#### Log:

2017-04-01 08:03
ERROR
discover
dl-series-fr
Error searching with t411: Expecting value: line 1 column 1 (char 0)

### Additional information:

- Flexget Version: 2.10.24
- Python Version: 2.7
- Installation method: pip install flexget
- OS and version: Ubuntu 16.04.2

<!---
Please verify that the following data is present before submitting your issue:

I've changed the T411API_DOMAIN_URL = "api.t411.ai" automatically using cron/bash

Here is my code:

> #### Vérification du domaine de T411
> if [[ -f "/usr/local/bin/flexget" ]] ; then
>   t411_api=`curl -m 5 -s http://t411.xyz/index.php | grep "SITE" | grep -Eo '(http|https)://api[^/"]+' | sed 's|https://||g'`
>   if [[ "$t411_api" == "" ]]; then
>     echo -e "\e[41mBAD!!\e[0m Le site pour le domaine de T411 ne répond pas"
>   else
>     cd /usr/local/lib/python2.7/dist-packages/flexget
>     flexget_file=`grep -rl 'T411API_DOMAIN_URL' | grep -v '.pyc'`
>     flexget_api=`awk -F "=" '/T411API_DOMAIN_URL/ {print $2}' $flexget_file |sed -n 1p | sed 's/"//g' | sed 's/ //g'`
>       if [[ "$t411_api" != "$flexget_api" ]]; then
>         echo -e "\e[41mBAD!!\e[0m Un changement de domaine de T411 a été détecté ("$flexget_api"/"$t411_api")"
>         full_flexget_path=`echo "/usr/local/lib/python2.7/dist-packages/flexget/"$flexget_file`
>         sed -i 's/'$flexget_api'/'$t411_api'/g' $full_flexget_path
>       else
>         echo -e "\e[42mTEST OK!!\e[0m Le domaine de T411 est valide ("$t411_api")"
>       fi
>   fi
> fi

This issue still occur sometimes (not eveytime)

**Comment by cvium** [comment]
#1763
