### ISSUE TITLE
Cannot use variables with integer-only values

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1765]
### Expected behaviour:
Variables should be able to handle integer-only values.

### Actual behaviour:
Configuration parsing error (when using ``'{? deluge.port ?}'``): ``Got `50586`, expected: integer``
Configuration parsing error (when using ``{? deluge.port ?}``):
```
while parsing a flow mapping in "<unicode string>", line 16, column 13: port: {? deluge.port ?} ^ expected ',' or '}', but got '?' in "<unicode string>", line 16, column 28: port: {? deluge.port ?} ^
```

### Steps to reproduce:
- Step 1: Try to use below config.

#### Config:
```
    from_deluge:
      host: '{? deluge.host ?}'
      port: '{? deluge.port ?}'

```
  
#### Log:
See above.

### Additional information:

- Flexget Version: 2.10.24
- Python Version: 2.7.9
- Installation method: pip
- OS and version: macOS El Capitan 10.11.6
- Link to crash log: n/a

**Comment by cvium** [comment]
Nope, #892

**Comment by liiight** [comment]
I never tested this but try this '{% variable.integer | int %} `
I'm not sure what happens when you try to mix `variables` with regular jinja2 filters.

**Comment by tubedogg** [comment]
Appreciate the thought but I got the same errors.

**Comment by gazpachoking** [comment]
Looks like we could get this working using http://jinja.pocoo.org/docs/2.10/nativetypes/

**Comment by nbarrientos** [comment]
Thanks for implementing this ;)
