### ISSUE TITLE
Unable to forget season release from series database

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1769]
Sorry @liiight, I didn't even think to test this the other day.

### Expected behaviour:
```
flexget series forget ShowName S01
```
forgets S01 from ShowName.

### Actual behaviour:
``Unknown identifier S01 for series ShowName``

### Steps to reproduce:
- Step 1: Add season pack to series database.
- Step 2: Try to forget it.

#### Config:
n/a
  
#### Log:
n/a (see above)

### Additional information:

- Flexget Version: 2.10.26
- Python Version: 2.7.13
- Installation method: pip
- OS and version: macOS El Capitan 10.11.6
- Link to crash log: n/a

**Comment by liiight** [comment]
bah, i knew cli will come back to fuck me :-)

**Comment by tubedogg** [comment]
Closed in #1797.
