### ISSUE TITLE
mechanize error when its already installed

### ISSUE THREAD

**Issue by nam31ess** [Flexget/Flexget#1779]
### Expected behaviour:
No error thrown when mechanize module is installed

### Actual behaviour:
Error message is thrown saying to install mechanize even though it's already installed

### Log
flexget --test execute
2017-04-07 19:18 INFO     manager                       Test mode, creating a copy from database ...
2017-04-07 19:18 INFO     manager                       Test database created
2017-04-07 19:18 VERBOSE  task_queue                    There are 3 tasks to execute. Shutdown will commence when they have completed.
2017-04-07 19:18 CRITICAL formlogin     IPT_Login       mechanize required (python module), please install it.
2017-04-07 19:18 WARNING  task          IPT_Login       Aborting task (plugin: form)

pip install mechanize
Requirement already satisfied: mechanize in /Library/Python/2.7/site-packages

  

### Additional information:

- Flexget Version: 2.10.29
- Python Version: 2.7.10 and 3 installed
- Installation method: installed flex get with pip3
- OS and version: 10.10.5 Yosemite

**Comment by liiight** [comment]
`pip3 install mechanize`

**Comment by cvium** [comment]
`mechanize` only supports py2

**Comment by liiight** [comment]
Really? Didn't know that. So I guess the answer is that you have to install flexget for python 2

**Comment by nam31ess** [comment]
I originally installed flexget with python 2.7, but i wasn't able to upgrade to the latest version using pip. So to counter I install python3 to enable the use of pip3 for the upgrade, worked perfectly and I'm now running the latest version. However now I'm being told i don't have mechanize, even with pip install mechanize, it tells me i have it but flexget won't recognise it.

**Comment by cvium** [comment]
That's not how it works. They need to be installed in the same python
environment.

**Comment by nam31ess** [comment]
Any reason why python 2.7 would not allow an upgrade and smash my terminal with errors?

I think i will need to do a complete reinstall with python 2.7

**Comment by liiight** [comment]
Anyway, not a flexget issue
