### ISSUE TITLE
Request: Waffles.ch Plugins

### ISSUE THREAD

**Issue by Lorenz1508** [Flexget/Flexget#1798]
A plugin that performs searches on Waffles.ch and returns entries for each result.

like the Whatcd Plugin

https://flexget.com/Plugins/whatcd

so Maybe it is possible to adapt the old what.cd plugin to Waffles.ch

**Comment by cvium** [comment]
WCD had a public API. I'm pretty sure Waffles does not as it doesn't use Gazelle iirc.

I don't think anyone on the team is even on Waffles, so it's unlikely to ever happen unless someone creates a PR.

**Comment by liiight** [comment]
Moved to [feathub](http://feathub.com/Flexget/Flexget/+1)
