### ISSUE TITLE
Update required guessit version to 2.1.2

### ISSUE THREAD

**Issue by tkurbad** [Flexget/Flexget#1804]
### Expected behaviour:

While building Flexget, a current version of guessit, i.e. >=2.1.0, should be used along with python-dateutil-2.5.3.

### Actual behaviour:

Flexget force-uses guessit<=2.0.4, since guessit-2.0.5 introduced a dependency on python-dateutil-2.5.2, which was lifted again in guessit 2.1.0.
According to guessit docs, 2.1.0 is fully backwards compatible to 2.0.4.

### Additional information:

- Flexget Version: 2.10.35
- Python Version: 2.7.12
- Installation method: Gentoo ebuild
- OS and version: Gentoo unstable/current
- Link to crash log:

### Resolution

If I change the requirements.txt file with the following patch:
```
--- FlexGet-2.10.35.orig/requirements.txt	2017-01-26 08:12:09.000000000 +0100
+++ FlexGet-2.10.35/requirements.txt	2017-04-23 00:54:29.465410859 +0200
@@ -11,12 +11,11 @@
 jinja2
 # There is a bug in requests 2.4.0 where it leaks urllib3 exceptions
 requests>=2.8.0, <3.0
-#Guessit requires python-dateutil<=2.5.2
 python-dateutil>=2.5.3
 jsonschema>=2.0
 path.py>=8.1.1
 pathlib>=1.0
-guessit<=2.0.4
+guessit>=2.1.2
 apscheduler>=3.2.0
 terminaltables>=3.1.0
 colorclass>=2.2.0
```

Flexget builds and runs fine.

Best,
Torsten

PS: If such dependency issues aren't fixed, Linux distributions will drop support for Flexget.
Related Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=614758

**Comment by liiight** [comment]
Thanks for this

**Comment by cvium** [comment]
Y'know, there was a reason we hadn't upgraded yet. It's not backwards compatible with Flexget.

**Comment by liiight** [comment]
so that's why all the test fail 😆 
reverting...

**Comment by tkurbad** [comment]
So, what needs to be done to get that running?

**Comment by liiight** [comment]
[This](https://github.com/Flexget/Flexget/pull/1398)

**Comment by tkurbad** [comment]
Well, I don't quite follow the conversation in those other issues. Is there something, the guessit folks have to fix/change first?
For me, 3 tests are failing. I'll try and fix them and send a PR iff I manage to do so.

**Comment by cvium** [comment]
If you can fix the tests, then it should be fine to merge...
