### ISSUE TITLE
Add support for napiprojekt in subliminal plugin

### ISSUE THREAD

**Issue by dolohow** [Flexget/Flexget#1807]
`subliminal` has a support for `napiprojekt` already.

I think its just a matter of extending `PROVIDERS` list here:
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/subtitles_subliminal.py#L19

but I could be wrong.

**Comment by cvium** [comment]
You are somewhat wrong. It grabs the list of providers from subliminal here https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/subtitles_subliminal.py#L16-L17. It only defaults to that list if it fails.

**Comment by dolohow** [comment]
Yeah, you are right.  I have no clue how I missed that
