### ISSUE TITLE
Make log rotation settings configurable, or increase log limit

### ISSUE THREAD

**Issue by miracle2k** [Flexget/Flexget#1808]
It seems the byte per log file and the max number, 9, is currently hardcoded:

https://github.com/Flexget/Flexget/blob/13e28570de2692634e28645c60ce9be20ae34293/flexget/logger.py#L201

In verbose logging mode, some of the plugins generate *a lot* of output. These 9 log files are being filled within 2 minutes on my machine. And it's not like 9MB really is a huge amount.

**Comment by cvium** [comment]
We use http://feathub.com/Flexget/Flexget for feature requests now.
