### ISSUE TITLE
SFTP hitting the timeout, no config for timeout

### ISSUE THREAD

**Issue by bymem** [Flexget/Flexget#1809]
moving large files over SFTP will hit the timeout at 15 minutes, but if our sftp server is slower you'll hit the time out with no possibilities to change to the time out. 

A possible timeout config could soleved the problem

- Flexget Version: 2.20.40
- Python Version: 3.4
- Installation method: pip
- OS and version: ububutu

**Comment by liiight** [comment]
Please do not ignore the issue template, it's there for a reason
