### ISSUE TITLE
For python3, there's no need to require pathlib at all

### ISSUE THREAD

**Issue by je-vv** [Flexget/Flexget#1822]
### Expected behaviour:
flexget should just work for python3 without pathtlib installed, given it's arealdy part of python3, and also because it's on maitainance mode only.  If needing extra libs, pathlib2 should be a better match...

https://pathlib.readthedocs.io/en/1.0.1

++++
This module has been included in the Python 3.4 standard library after PEP 428 acceptance. You only need to install it for Python 3.3 or older.
++++

### Actual behaviour:

However, flexget always complains with:

+++
pkg_resources.DistributionNotFound: The 'pathlib>=1.0' distribution was not found and is required by FlexGet
+++

If ptyhon3 pathlib is not present...

### Additional information:

- FlexGet version:  2.10.14
- Python version:  3.6.1
- Installation method:  python.setup
- Using daemon (yes/no):  no
- OS and version:  Arch GNU/Linux

**Comment by cvium** [comment]
We do not support 3.6, but we do support 3.3, which does require pathlib.

**Comment by je-vv** [comment]
Oh...  BTW, someone made me aware, the install page mistakenly indicates 3.4 and 3.5 (which should remove pathlib requirement) are also supported:

https://flexget.com/Install
Supported Python versions: 2.7, 3.3, 3.4 and 3.5. Python 3.6 may have issues.

I'm staying on 3.6, removing pathlib myself.  Though, at some point this should be addressed any ways...

**Comment by gazpachoking** [comment]
We should change our requirements file to only require it where appropriate: http://pip-python3.readthedocs.io/en/latest/reference/pip_install.html#requirement-specifiers

`pathlib>=1.0; python_version<'3.4'`
