### ISSUE TITLE
Add support for Trakt.tv calendar

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#1823]
A new plugin or extension of `trakt_list` to support the episodes listed in https://trakt.tv/calendars/my/shows

relevant API:
http://docs.trakt.apiary.io/#reference/calendars/my-shows/get-shows

Shows in the list are automatically added if watched, collected or on a watchlist, and NOT marked as hidden (https://trakt.tv/settings/hidden)

Should do something like `next_trakt_episodes` combined with an `age`

See discussion on Gitter

**Comment by cvium** [comment]
Re-open on feathub: http://feathub.com/Flexget/Flexget
