### ISSUE TITLE
`series remove` fails to parse episode id

### ISSUE THREAD

**Issue by y** [Flexget/Flexget#1855]
### Expected behaviour:
As documented, it should perform similarly to `flexget series forget`, except it only clears the episode from the series table and not other tables, like seen.

### Actual behaviour:
Fails to parse the episode id properly. `flexget series forget` works fine, though.

### Steps to reproduce:
See log.

#### Log:

    $ flexget series remove 'better call saul' S03E08
    2017-05-31 17:17 INFO     parser_internal                 Title `Better Call Saul S` looks like series `Better Call Saul` but cannot find any series numbering.
    Invalid identifier for series `Better Call Saul`: `S`
    Unknown identifier `0` for series `Better call saul`
    Unknown identifier `3` for series `Better call saul`
    2017-05-31 17:17 INFO     parser_internal                 Title `Better Call Saul E` looks like series `Better Call Saul` but cannot find any series numbering.
    Invalid identifier for series `Better Call Saul`: `E`
    Unknown identifier `0` for series `Better call saul`
    Unknown identifier `8` for series `Better call saul`

### Additional information:

- FlexGet version: 2.10.56
- Python version: Python 2.7.13
- Installation method: git
- Using daemon (yes/no): no

**Comment by tubedogg** [comment]
Confirmed. I'll address this in a few minutes.
