### ISSUE TITLE
feedparser.py get exception.

### ISSUE THREAD

**Issue by SongShawn** [Flexget/Flexget#1869]
### Expected behaviour:

flexget check command ok.

### Actual behaviour:
command "flexget check" crashed.
try command "flexget --help", crashed too.

### Steps to reproduce:
- Step 1: run cmd "flexget --version". ---ok
- Step 2: run cmd "flexget check". ---failed.
- Step 3: run cmd "flexget --help". ---failed. same print with 'Step 2'.

#### Config:
```
tasks:
  HDHome.Auto:
    rss: 'http://hdhome.org/torrentrss.php?myrss=1&linktype=dl&uid=63012'
    accept_all: yes
    download: /root/.flexget/rss/hdhome/
```

  
#### Log:
```

SyntaxError: invalid syntax
2017-06-06 13:11 CRITICAL plugin                        Exception while loading plugin flexget.plugins.sites.nyaa
Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/flexget/plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "/opt/lib/python3.6/site-packages/flexget/plugins/sites/nyaa.py", line 7, in <module>
    import feedparser
  File "/opt/lib/python3.6/site-packages/feedparser.py", line 316
    raise KeyError, "object doesn't have key 'category'"
```

### Additional information:

- FlexGet version: 2.10.60
- Python version: 3.6.1
- Installation method: pip3 install flexget
- Using daemon (yes/no): no
- OS and version: DSM6.1
- Link to crash log:

**Comment by cvium** [comment]
We do not support Python 3.6 (yet).

**Comment by SongShawn** [comment]
I get help from this pase "https://flexget.com/InstallWizard/SynologyNAS".
please give me a Python version list.
Thanks.

**Comment by cvium** [comment]
https://flexget.com/InstallWizard

**Comment by SongShawn** [comment]
ok~

**Comment by cvium** [comment]
We should keep this issue open though. We want to support Python 3.6+ eventually. If `feedparser` isn't compatible we need to find another parser library.

**Comment by gazpachoking** [comment]
Hmm, can anyone trace how execution jumps from here
```
  File "/opt/lib/python3.6/site-packages/flexget/plugins/sites/nyaa.py", line 7, in <module>
    import feedparser
```
all the way to [here](https://github.com/kurtmckee/feedparser/blob/master/feedparser/feedparser.py#L316)
```
  File "/opt/lib/python3.6/site-packages/feedparser.py", line 316
    raise KeyError, "object doesn't have key 'category'"
```
I don't understand why importing feedparser is already initializing a feedparser dict. It seems like there should be more lines inbetween those in the traceback.

@SongShawn You didn't shorten that log output did you?

**Comment by adamrothman** [comment]
@SongShawn I actually wrote that page on the FlexGet wiki, but unfortunately it's now out of date. The best way to run FlexGet on your Synology NAS these days is using Docker. I'll try to find some time to update the wiki page.

**Comment by mixedd69** [comment]
What about the python 3.6 compability??
Some progress??
'Čause i get the same error on synology DSM 6.1

**Comment by cvium** [comment]
No one is working on Python 3.6 compatibility. It is unlikely to happen at this stage.

**Comment by mixedd69** [comment]
Then thears no posibilities to install it normally on synology devices! Because installing as flexget instructions on site says, trough opkg, opkg install latest python version

**Comment by adamrothman** [comment]
I have updated [the wiki](https://flexget.com/InstallWizard/SynologyNAS) to include a guide on installation via Docker. Hope it's helpful!

**Comment by liiight** [comment]
python 3.6 support was added in 2.11.0. Please upgrade and test

**Comment by adamrothman** [comment]
2.11.1 is working just fine for me under Python 3.6. Thanks to everyone who worked on this!
