### ISSUE TITLE
Crash downloading subtitles [periscope and transmission] 

### ISSUE THREAD

**Issue by irodmar** [Flexget/Flexget#1874]
### Expected behaviour:
- Download from RSS
- Download subtitles
- Sort files

### Actual behaviour:

When the task for subtitles starts it get so many time between elements and at the end it raises an error, so doesn't download any subtitle.

### Steps to reproduce:
- Step 1: run flex get execute.
- Step 2: download elements from rss --> OK
- Step 3: download subtitles --> crash

#### Config:

```
templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: 'user'
      password: 'pass'
      ratio: -1
      path: /media/HDDRaspberry/Incompletas
      addpaused: no
tasks:
  rss:
    priority: 1
    rss: http://showrss.info/user/
    all_series: yes
  subtitles:
    priority: 4
    disable: builtins 
    filesystem:
      path:
        - /media/HDDRaspberry/Incompletas
      regexp:  '.*\.(mp4|mkv|avi)$'
      recursive: yes
    accept_all: yes    
    regexp:  
      reject:
        - '.*[sS]ample.*'
    periscope:
      languages:
        - en
      alternatives:
        - es
      overwrite: yes
  sort:
    priority: 5
    disable: builtins
    filesystem:
      path: /media/HDDRaspberry/Incompletas/
      mask: '*.srt'
      recursive: yes
    accept_all: yes
    seen: local
    thetvdb_lookup: yes
    all_series:
      parse_only: yes
    move:
      to:  /media/HDDRaspberry/Descargas/Series/{{ tvdb_series_name }}/Season {{ tvdb_season|pad(2) }}/
      rename: '{{ tvdb_series_name }} - {{ series_id }} - {{ tvdb_ep_name}}{{ location | pathext }}'
      clean_source: 100
      along:
        extensions:
          - mkv
          - mp4
          - avi
```
  
#### Log:
```
2017-06-13 23:17 VERBOSE  filesystem    subtitles       Starting to scan folders.
2017-06-13 23:17 VERBOSE  filesystem    subtitles       Scanning folder /media/HDDRaspberry/Incompletas. Recursion is set to True.
2017-06-13 23:17 INFO     download      subtitles       Downloading: Gotham.S03E18.720p.HDTV.x264-KILLERS
2017-06-13 23:19 INFO     download      subtitles       Downloading: orange.is.the.new.black.s05e01.proper.720p.webrip.x264-morose
2017-06-13 23:21 CRITICAL task          subtitles       BUG: Unhandled error in plugin transmission: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/transmission.py", line 303, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/transmission.py", line 411, in add_to_transmission
    filedump = base64.b64encode(f.read()).decode('utf-8')
MemoryError
```

### Additional information:

- FlexGet version: 2.10.53
- Python version: Python 2.7.9
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: osmc VERSION_ID="2017.04-2"
- Link to crash log:

**Comment by cvium** [comment]
You're using transmission in a global template, which means it tries to add the mkv files to transmission. We should probably make sure that the files being added to transmission are torrent files.

But what you're experiencing is not so much a bug as it is misusing the global template.

**Comment by irodmar** [comment]
I have another config file in other raspberry working perfectly, but It doesn't works in this new one, I think for 2.x upgrade, so I rewrited the file with Tested & Working 2.x Configs (https://flexget.com/Cookbook/Users) where several files have transmission or deluge in global template. 

For this reason I didn't think it was a config problem. Do you know how It could be easily solve? Thanks!

**Comment by cvium** [comment]
> Do you know how It could be easily solve?

Don't put transmission in the global template.

**Comment by irodmar** [comment]
> Don't put transmission in the global template.

Ok, thanks

**Comment by liiight** [comment]
This is not something I ever see us addressing directly (other than getting rid of global templates...)
