### ISSUE TITLE
Add 'accessed' to the database to bypass system metadata handling

### ISSUE THREAD

**Issue by hhiru** [Flexget/Flexget#1875]
### Disclaimer: I'm posting here because _feathub.com/Flexget/Flexget_ is down.

I noticed (at least on windows) that when a file is created it generates an `accessed` field too that has the same value of the `created` field. With this logic, no matter if you specified a `accessed` or a `created` field in your automatic deletion task, the file will be deleted even if you never played it! Since this is a cross-platform program, the database should store an `accessed` field that is blank when the file is first downloaded and overwritten with the latest accessed time when necessary. I'm not sure if this is possible, especially when you stream files over the network not accessing them directly on the host build but I guess it was worth asking here for a feature like this.

In my personal case I can't schedule an auto-deletion task using the `accessed` field because: A) I'm playing files via smb on a guest build (not directly on the host build) and B) the `created` and `accessed` fields are the same until you cause an update. The host build is using a Debian distro, the guest build (streaming content via smb) is using Windows 10.

Kodi has a plugin that does the job but I think it works because you are using the Kodi platform to play the file AND to manage the database so it's natural that it's easier to manage `created` and `accessed` metadata like that. Hopefully this can be emulated with python in some way..

**Comment by liiight** [comment]
This has nothing to do with the database. `filesystem` just retrieves these values from the os. What you can and cannot do with them is up to you. 
What people generally do is base progress via trakt scrobbling.

**Comment by cvium** [comment]
In the case of Windows, "file accessed" is the same as "file modified". This is a limitation with the OS and we will not be trying to "fix" this.
