### ISSUE TITLE
Downloads leave empty temp directories

### ISSUE THREAD

**Issue by rollor** [Flexget/Flexget#1878]
### Expected behaviour:
Clean up empty temp directories after download completes.

### Actual behaviour:
Every download leaves a new empty temp directory in `~/.flexget/temp/`, which are never removed.
The oldest directories are from December 19, 2016. And there are multiple per day, for a total of 1602 directories.

#### Log:
Nothing relevant in the log, except for the time of the downloads, which corresponds to the timestamps on the temp directories.

### Additional information:

- FlexGet version: 2.10.61
- Python version: Python 2.7.13
- Installation method: git
- Using daemon (yes/no): no
- OS and version: OS X El Capitan

**Comment by liiight** [comment]
This shouldn't happen unless your task crashes. You got crashes in your logs?

**Comment by liiight** [comment]
This should never happen as temp files are cleaned even if your task crashes

**Comment by rollor** [comment]
The directories exist and flexget is the only process creating them. I don't know python, but a quick google search shows that it's a frequent problem that the directory created with tempfile.mkdtemp isn't properly cleaned. If many others have issues with it in other software, it's not unreasonable to expect the same here. Unless I'm mistaken, there's not even a test to verify this should never happen in test_download.py.

**Comment by rollor** [comment]
A little more info. I'm using the standard recipe of setting a default global download dir and then overriding the path with set depending on task, series, etc. The only non-standard bit is this, but it's been working for many years:

        exec: { on_output: { phase: notifier_shell_script } }

**Comment by rollor** [comment]
I disabled the exec and no change- temp directories are still not removed. I checked the git log for commits just before this started happening and found this likely commit: https://github.com/Flexget/Flexget/commit/eccb2b387f6f863df7b9563b042ac094cc476942 .  It's dated 2 days before the problem started and the commit is titled:
> Have download plugin clean up 'file' field when it moves temp file.

**Comment by Aokromes** [comment]
I confirm this issue, i have 100s of empty tmp* directories.

**Comment by liiight** [comment]
@gazpachoking you seeing this? This is weird...

**Comment by paranoidi** [comment]
860 empty directories here :)

**Comment by gazpachoking** [comment]
Looks like @rollor traced it down properly. If the file gets moved successfully, the 'file' entry field is removed from the entry. Then all the temp directories get cleaned up for any entries that have the 'file' entry field. Should be fixable with a bit of tweaking.

**Comment by gazpachoking** [comment]
I feel like reverting the 2 lines from eccb2b3 is likely the way to go. I think I added them in response to this thread https://discuss.flexget.com/t/cant-seem-to-consolidate-emails/3008/12 where the 'file' entry field was getting stored to entry_list, when maybe it shouldn't be. On looking again though, the cleanup call in the 'finally' block should take care of that anyway, so maybe that change didn't do anything but cause these folders to be left behind.

**Comment by liiight** [comment]
let's try that then
