### ISSUE TITLE
Timeframe doesn't work

### ISSUE THREAD

**Issue by dolohow** [Flexget/Flexget#1908]
Hi I am using timeframe and it looks like it doesn't work for me.  I set it up so that will wait for 1080p 8 hours and if 1080p won't show up, it will fallback to 720p.
 
### Expected behaviour:
720p is downloaded, because 1080p was no available at the time.

### Actual behaviour:
Nothing is downloaded.

### Steps to reproduce:
Just run with `flexget daemon start -d`

#### Config:
```
.
.
.
tasks:
  get_entry:
    manual: yes
    template: tv
.
.
.
templates:
  tv:
    regexp:
      reject:
        - german
        - multi
        - french
    series:
      settings:
        tv:
          timeframe: 8 hours
          target: 1080p hdtv
          quality: 720p-1080p hdtv
```
  
#### Log:
```
2017-08-03 04:00 INFO     series        get_entry       `Series`: timeframe waiting for 07h:59min. Currently best is `Series S01E01 720p HDTV`.
2017-08-03 04:00 WARNING  backlog       get_entry       No input snapshot available for `Series S01E01 720p HDTV`, using current state
2017-08-03 04:03 INFO     series        get_entry       `Series`: timeframe waiting for 07h:57min. Currently best is `Series.S01E01.720p.HDTV`.
2017-08-03 04:03 WARNING  backlog       get_entry       No input snapshot available for `Series.S01E01.720p.HDTV`, using current state
.
.
.
2017-08-03 18:46 ERROR    irc                           Failed to parse message. Skipping:
```

### Additional information:

- FlexGet version: 2.10.74
- Python version: 2.7.13
- Installation method: pip in virtualenv
- Using daemon (yes/no): yes

**Comment by kecksk0enig** [comment]
hi thats not how the timeframe plugin is supposed to work.
the timeframe  you specify is the time to WAIT for the desired quality if lower quality is seen.
So ehen first the 720p is seen the timeframe starts tu run ( like shown in the logs) if within the next 8 hours (timeframe) no 1080p equivalent is found the already seen 720p is downloaded.

If you want to first download the "worse" quality and if avaible upgrade if the desired quality is scraped you should look to the "upgrade" plugin (https://flexget.com/Plugins/series/upgrade)


also have a look at the plugins 
https://flexget.com/Plugins/series/qualities
and
https://flexget.com/Plugins/series/quality

for further clarification

**Comment by gazpachoking** [comment]
> I set it up so that will wait for 1080p 8 hours and if 1080p won't show up, it will fallback to 720p.

The log messages you posted look like it's waiting the desired 8 hours before downloading the 720p version. Do you feel something different is happening?

**Comment by dolohow** [comment]
After 8 hours still not downloading.

**Comment by cvium** [comment]
We need more information than that... like logs.
