### ISSUE TITLE
Task Queue has died unexpectedly

### ISSUE THREAD

**Issue by pbathuk** [Flexget/Flexget#1947]
### Expected behaviour:
When rebooting my Rpi with flexget and the daemon run via crontab, the schedule appears to be intermittent, it never runs right away, which is fine.. but sometimes it could not run at all, or it does not appear to be run. 
The issue I find is that on a fresh reboot (the log is attached below -- part of the log that is) I can then run flexget execute, which should process the tasks.. which is does but I get the line 
2017-08-16 21:36 ERROR    manager                       Task queue has died unexpectedly. Restarting it. Please open an issue on Github and include any previous error logs.
Which happens on every reboot. I therefore changed the crontab to be : 
@reboot /usr/local/bin/flexget --logfile debug_test.log --loglevel debug daemon start -d

I then rebooted and this is where the log was from.

### Steps to reproduce:
have flexget setup on crontab
reboot
after reboot run flexget execute
see error :)

#### Config:
https://pastebin.com/YPq7rhLJ
  
#### Log:

https://pastebin.com/6TfKjdD0

### Additional information:

- FlexGet version: 2.10.79 (it has done this for a while and I normally keep updated)
- Python version: 3.4.2
- Installation method: sudo pip3 install flexget (sudo pip3 install -U flexget for update)
- Using daemon (yes/no): yes
- OS and version: Linux : 4.9.35-v7+
- Link to crash log: https://pastebin.com/6TfKjdD0

**Comment by liiight** [comment]
When you reboot, you reboot gracefully or just kill everything?

**Comment by dolohow** [comment]
I have the same issue.

**Comment by Kharag** [comment]
I can confirm this.
Bug is reproducible here with the following steps:

1. Stop Flexget daemon
2. Start the daemon again (flexget daemon start -d)
3. flexget execute

You immediately find the entry in the logfile (Task queue has died...)

I tried running with loglevel debug, but there is no stacktrace or any other hint of any crash.

Interesting fact: I can't kill flexget normally after the task queue crash. (i.e. with pkill flexget or simple kill PID)
I have to explicitly use kill -9.
If I don't use flexget execute after starting the daemon I can kill it gracefully..

**Comment by shotfirer** [comment]
Any news on that matter? The issue still persist in 3.1.6 (2.5 years later): in daemon mode any manual execution (execute or inject) causes the same error, and flexget can't be stopped by "daemon stop" command afterwards, only with SIGKILL.

**Comment by gazpachoking** [comment]
I can not reproduce this issue. Are you all on raspberry pis?

**Comment by shotfirer** [comment]
Yeah, kind of. I have an ARMv7-based Orange Pi, with Ubuntu-based Armbian Linux.

**Comment by dolohow** [comment]
I am running on Intel atom

**Comment by paranoidi** [comment]
Please report your hardware (architecture, ram, etc). Seems like some small set of users are affected by this but not 99% or so.

**Comment by shotfirer** [comment]
Orange Pi +2E (Allwinner H3 / ARM Cortex-A7, 2Gb RAM)
Armbian Linux 4.19.62-sunxi (Ubuntu 18.04)
Python 3.6.9
Flexget 3.1.8, pip installation, daemon mode
