### ISSUE TITLE
To-Be-Deprecated plugins

### ISSUE THREAD

**Issue by cvium** [Flexget/Flexget#1962]
This issue is just to track the list of deprecated plugins until we actually have time to clean it up:

- [freshon](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/freshon.py)
- [sceneaccess](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/sceneaccess.py)
- [t411](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/t411.py)
- [torrent411](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/torrent411.py)
- [extratorrent](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/extratorrent.py)
- [torrentshack](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/torrentshack.py)

PR: #1801

**Comment by liiight** [comment]
All those are dead, right?

**Comment by cvium** [comment]
Yes.

**Comment by liiight** [comment]
so why wait, lets nuke'em

**Comment by chewy74** [comment]
Torrentshack is also dead

**Comment by cvium** [comment]
Added

**Comment by andocromn** [comment]
extratorrent lives again http://extratorrent.rip/

**Comment by cvium** [comment]
@andocromn The plugin would probably have to be rewritten though. Is the site legit?

**Comment by chewy74** [comment]
@cvium it looks like a clone site and a fake. I would definitely not trust it.

Most of etrg uploaders have gotten together and created a new site here. 

https://www.ettv.tv

**Comment by andocromn** [comment]
@cvium I've gotten some good content off of it, but I can't speak to its "legit" status...  If it would require any more than changing the TLD probably not worth rewriting

**Comment by cvium** [comment]
Feel free to test the plugin with the TLD change @andocromn ;)

**Comment by andocromn** [comment]
@cvium tested the TLD change to .rip and the /rss.xml is 404 so yeah extratorrent can be nuked
