### ISSUE TITLE
newpct plugin search function not fetching results

### ISSUE THREAD

**Issue by OSTNeoX** [Flexget/Flexget#2000]
Hi.

search function in newpct.py plugin is not fetching results. 

With this file: https://raw.githubusercontent.com/malkavi/Flexget/develop/flexget/plugins/sites/newpct.py the search works, but does no retrieve torrent.

this is my config.yml (modified from https://github.com/Flexget/Flexget/issues/1964),
https://pastebin.com/cD2zHUye

And this is the trace log (with newpct.py that retrieves searchs, but is not getting torrents)
https://pastebin.com/uvuk0ned

Any idea? Thanks!

**Comment by malkavi** [comment]
I have to say that I haven't try series in search... I made it testing movies. The issue is that the url is not for the chapter, is for the whole serie.

**Comment by OSTNeoX** [comment]
@malkavi Yes. But, if you see, all results are the same, for example

Gotham T4 English: http://newpct1.com/series-vo/gotham/2156
Gotham T3 Spanish: http://newpct1.com/series-hd/gotham/1874
Gotham T3 English: http://newpct1.com/series-vo/gotham/2156

I'm not expert in python (only basic knowledge...) but i think is possible that if series is the plugin, get distinct links and read inside. I dont know if it is possible inside flexget.

However, using rss feed it works great, but would be interesting for example to download entire serie from begin.

**Comment by malkavi** [comment]
@OSTNeoX It's possible but you need to parse the entire page and all the sub-pages, is a lot of work and different from movies.
First, we need to difference from movies, and later parse each link from all pages. And this for all the search results.

**Comment by cvium** [comment]
Maybe the plugin should be changed to only support movies then?

**Comment by euod92** [comment]
Thank you liiight. Cvium: as described in #2011, now, is not working for movies.
