### ISSUE TITLE
Can I translate flexget/wiki to other language like zh-cn?

### ISSUE THREAD

**Issue by Rhilip** [Flexget/Flexget#2009]
I feel sorry to disturb you and others.

After trying Flexget, I feel it's powerful. And want to introduce other about it's project. However most wiki isn't easy for beginner in my country to understand and use. 
So Can I translate flexget/wiki to other language like chinese by myself, Though it may take too many time? If it is YES, Then what license should I obey?

Yesterday, I forked https://github.com/Flexget/wiki to https://github.com/Rhilip/Fleget-wiki-zh-cn, and want to translate and make it as A Gitbook. 

Since the project Flexget/wiki didn't open Issues, I hope nothing wrong to open An issue here.

**Comment by cvium** [comment]
You are free to fork all you want. I don't know if the wiki software supports different languages though, so you'll probably have to host it yourself (ask @gazpachoking).

As for license, we use MIT, but I don't think the wiki content itself is licensed.

**Comment by Rhilip** [comment]
Thanks for your Reply.
