### ISSUE TITLE
Flexget Status Causes Traceback on FreeBSD?

### ISSUE THREAD

**Issue by sisfs** [Flexget/Flexget#2022]
### Expected behaviour:
When running `flexget status` I expect to receive a summary of the most recently run instance of each of my tasks. When running `flexget status --task task-name` I expect to see a detailed listing of a number of the most recent calls for that specific task.
<br>
### Actual behaviour:
Instead of producing the expected tabulated summary I receive this [traceback](https://pastebin.com/ULkYZWn8) when running `flexget status`. Oddly, when running `flexget status --task My-TV-Shows` I get the expected [detailed output.](https://pastebin.com/8YpZtnLq)
<br>
### Steps to reproduce:
Run `flexget status` from the cli.

#### Config:
My config.yml is available on [Gitlab](https://gitlab.com/sisfs/dotfiles/blob/master/config.yml)
  
#### Log:
No relevant log entries are produced even with debug level logging. 
<br>
### Additional information:
- FlexGet version: 2.11.2
- Python version: 2.7.14
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: FreeBSD 11.0-RELEASE-p10
- Link to crash log: none is created

**Comment by liiight** [comment]
This is weird since the filter is task that succeeded and produced more than 0 results, so how come it fail on last_execution time is beyond me. Maybe corrupted data? I'll try to put a band aid on this as I cannot get this to reproduce.

**Comment by liiight** [comment]
what a weird state, a task that registered but without an execution...not sure how that can happen other than corrupted data, but ill apply a band aid anyway

**Comment by sisfs** [comment]
Awesome! Thanks @liiight, that totally fixed my issue!
