### ISSUE TITLE
Fix transmission related plugins and handling of complete torrents

### ISSUE THREAD

**Issue by afranke** [Flexget/Flexget#2026]
### Expected behaviour:

Be able to identify completed torrents, remove them from the queue and move download files, all from flexget and without any workaround.

### Actual behaviour:

One can get complete torrents removed from the queue with `clean_transmission` but that doesn’t allow to move the files at the same time. One can use `move` to move the files, but there is no way to identify the ones that are complete **and** removed from the queue by `clean_transmission`.

It seems one could use `from_transmission` to feed `move` with the completed ones, but there is no way to ensure this is done before or at the same time as `clean_transmission` runs.

Apparently plugins  for other torrent clients have a way to do it directly.

It doesn’t make sense to paste config or log since I’m describing something that cannot be achieved.

### Additional information:

- FlexGet version: 2.10.111.dev
- Python version: 3.6.3
- Installation method: git
- Using daemon (yes/no): no
- OS and version: Fedora 26

**Comment by cvium** [comment]
Feature requests belong in [Feathub](https://feathub.com/flexget/flexget).

> It seems one could use from_transmission to feed move with the completed ones, but there is no way to ensure this is done before or at the same time as clean_transmission runs.

https://flexget.com/Plugins/priority

**Comment by zosky** [comment]
FG is the backbone of our operation in many senses but not the only component. _no workarounds_ would be nice but really this is a patchwork of tools & i don't agree any 1 app should be the only solution. 

long before i started using flexget a few years ago, i solved for this with a bash script and _script-torrent-done-enabled_ in transmission 

in theory you could point _script-torrent-done-enabled_ back to FG with a bash 1 liner like
`flexget execute --tasks=complete-sorter $TR_TORRENT_NAME`
