### ISSUE TITLE
imdb_watchlist plugin broken

### ISSUE THREAD

**Issue by jeroen-s** [Flexget/Flexget#2035]
Presumably due to IMDB making changes on their end.

Flexget version: 2.11.8

Stacktrace:
```
2017-12-08 19:34 CRITICAL task          populate_movies_list BUG: Unhandled error in plugin imdb_watchlist: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flexget/plugins/input/imdb_watchlist.py", line 106, in on_task_input
    total_item_count = int(soup.find('div', class_='desc').get('data-size'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Arghh** [comment]
Hi. 

I have the same problem on 2.11.9 (had it on an older version aswell). Problems started yesterday. My config was working fine before,  I did not making any changes. However I dont get any errors just:

`2017-12-09 16:06 VERBOSE  imdb_watchlist find-movies     No movies were found in imdb list: watchlist
2017-12-09 16:06 WARNING  input_cache   find-movies     Input imdb_watchlist did not return a list, cannot cache.
2017-12-09 16:06 VERBOSE  details       find-movies     Task didn't produce any entries.`

also the same with ` flexget execute --now --tasks "find-movies" --no-cache`

Altho I have movies on the list. I also removed all movies and added 1. Still nothing.

Probly something to do with user created lists on imdb side?

**Comment by GMBridge** [comment]
looking at the plugin, and the returned HTML from imdb, it appears imdb changed how the page is structured, so the existing soup.find() in the plugin needs to be updated to reflect the new page layout.

**Comment by jvlomax** [comment]
I tried having a look at the code for this yesterday. It looks like the watchlist entries are no longer in the HTML returned when doing the get request, but is injected by some javascript on the webpage. I have a [gist](https://gist.github.com/jvlomax/e93158f4fdc973f116037e8ae461f615) of what the js looks like. I have no idea what would be the best way to make the imdb_watchlist plugin make use of this though.

**Comment by ranirahn** [comment]
So compact view is missing on IMDB site. So only way to get it working again is to get all data from a normal view.

**Comment by thawn** [comment]
IMDB changed two things:

1. on the watchlist page, the list is now dynamically generated using a react javascript widget. This widget uses a JSON api.
2. on other list pages, the compact view is gone

Accordingly, I wrote a parser for the javascript list of imdb title ids and the JSON api, and updated the html parsing code to be able to handle the detailed list view.

**Comment by itsbebbo** [comment]
Thanks for the update thawn - this seems to be working well at the moment. I assume your parser manages to pull back all pages of the watchlist from IMDB as the javascript on their website is incremental in that it retrieves 40ish entries at a time?

**Comment by vkasotis** [comment]
Thanks Thawn for the update. I have updated flexget to version, 2.11.17, still, no luck. Is there something I can do manually?

Thanks in advance!
V.

**Comment by itsbebbo** [comment]
It isn’t in version .17, you will need to pull down the updated IMDb plugin python file and drop it into your flexget install...

**Comment by vkasotis** [comment]
Thanks itsbebbo! You see a very new to linux/osmc and flexget..... Is there a command I could execute or where I can find new IMDb plugin python file so as to copy it? More importantly, where should I copy it? 
I mean, I have  folder for flexget like "/home/osmc/.flexget" where I have the config.yml. 

Probably these question should seem silly to you, but as I said I'm rather new a this.

Thanks for your time.
V.

**Comment by vkasotis** [comment]
Got it guys! Found a way....

Happy new year to all!

**Comment by thawn** [comment]
For the impatient: you can already use the updated plugin by downloading the file [imdb_watchlist.py](https://raw.githubusercontent.com/thawn/Flexget/develop/flexget/plugins/input/imdb_watchlist.py) and dropping it into a folder called plugins below your config.yml file (e.g. on linux it will go into ~/.flexget/plugins/ ).

**Comment by thawn** [comment]
@itsbebbo: yes, the parser pulls all entries even for very long watchlists (tested with a watchlist containing ~600 entries). All the imdb ids are stored on the page from the start. The parser uses that list of imdb ids to grab all entries at once using the new unofficial imdb API that the widget also uses to pull the entries ~ 50 at a time.

**Comment by itsbebbo** [comment]
That’s fantastic and very quickly implemented - thanks again @thawn...

**Comment by chewy74** [comment]
I just updated and imdb_watchlist is still returning with no results

`pi@raspberrypi:~ $ flexget execute --tasks IMDB
There is a FlexGet process already running for this config, sending execution there.
2018-01-01 11:26 VERBOSE  utils.requests IMDB            Waiting 4.44 seconds until next request to imdb.com
2018-01-01 11:26 VERBOSE  details       IMDB            Task didn't produce any entries.
2018-01-01 11:26 VERBOSE  details       IMDB            Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)`

**Comment by thawn** [comment]
@chewy74 I think the fix will be in v2.11.19. Until then, put the fixed file into your plugins directory as I [described above](https://github.com/Flexget/Flexget/issues/2035#issuecomment-354599860).

**Comment by chewy74** [comment]
@thawn thanks for the reply. I'm getting an error message that it can't be registered
`
pi@raspberrypi:~ $ flexget daemon start -d
2018-01-01 12:25 CRITICAL plugin                        Error while registering plugin imdb_watchlist. A plugin with the same name is already registered`

**Comment by ranirahn** [comment]
This error does not matter. I have it also but I get my list downloaded. After it will be integrated into new version it will be gone but just ignore that error for now.

**Comment by chewy74** [comment]
OK, but I still don't get my list... What's the cli command to clear the watchlist cache? I will try that

**Comment by thawn** [comment]
@chewy74  did you restart the flexget process? I noticed the message `flexget already running for this config` in your earlier comment. I think you need to restart all flexget processes for the updated plugin to take effect.

**Comment by ranirahn** [comment]
Ah thats why i did not had that problem because i dont run daemon. I run it with cron.

**Comment by chewy74** [comment]
I did stop and restart the daemon @thawn

**Comment by liiight** [comment]
The pr was merged, just update Flexget and restart daemon

**Comment by chewy74** [comment]
@liiight OK, I'm not sure what's going on because my watchlist is not being retrieved. I've tried adding new movies to my watchlist, but it's not retrieving and approving new, or existing entries to my movie list.

Log looks like it's pulling up the queue, but it's not doing anything with the queue. 

Debug log 
https://pastebin.com/ateXfqd4

**Comment by liiight** [comment]
Then it's unrelated to this issue, plead discuss in forums or chat

**Comment by cvium** [comment]
@chewy74 `imdb_list` != `imdb_watchlist`.
