### ISSUE TITLE
flexget history - Could not start manager due to unicode.

### ISSUE THREAD

**Issue by chrisbrasington** [Flexget/Flexget#2037]
### Expected behaviour:
To be able to pipe "flexget history -s" into the TAIL command or into file. Such as..

flexget history -s | tail -n 10
or
flexget history -s > /tmp/flex-history.txt

### Actual behaviour:
flexget history -s | tail -n 10 
Could not start manager: 'ascii' codec can't encode character u'\xed' in position 3601: ordinal not in range(128)

### Steps to reproduce:
**A unicode character must be present in a history log to cause breakage**. Example: í (u'\xed'), http://www.codetable.net/hex/ed.

### Additional information:

- FlexGet version: 2.10.48-1
- Python version: 3.6.3
- Installation method: AUR
- Using daemon (yes/no): no
- OS and version: Manjaro, 17.1pre3

**Comment by rollor** [comment]
Same thing happens for `flexget series list all`.  This is a frequent regression- it repeatedly breaks on various subcommands ,then gets fixed, then breaks again. I got sick of waiting for a proper fix, and just alias flexget to "LC_ALL='en_US.utf8' flexget" which works around the bug.

**Comment by chrisbrasington** [comment]
@rollor thanks for the workaround.

**Comment by paranoidi** [comment]
This is a bit annoying issue with python, depending on where stdout is going default encoding changes ...
