### ISSUE TITLE
trakt to sonarr options [question/request]

### ISSUE THREAD

**Issue by JourneyOver** [Flexget/Flexget#2039]
So I stumbled upon the sonarr_list plugin while googling for ways to import lists from trakt to sonarr, and it looks nice and all and I plan on using it but I was wondering if there was any options to set "Root Path", "Profile", "Series Type" and "Season Folder"? As the only options I currently see that are available are options to set how the show is monitored.

If these are not options currently then I kindly request them to be added if at all possible..

**Comment by liiight** [comment]
Please request new features via [feathub](https://feathub.com/Flexget/Flexget)

**Comment by JourneyOver** [comment]
@liiight so going by your comment I guess these are not options then??

**Comment by liiight** [comment]
Correct

**Comment by JourneyOver** [comment]
Well damn, guess I'll add a request to feathub in hopes that it gets picked up quickly as I now have to wait for these options before I can use flexget any.

**Comment by JourneyOver** [comment]
It shouldn't be to hard to implement I think.

have set up the request on feathub now as well so you can take a better look at what options I'm requesting. https://feathub.com/Flexget/Flexget/+49

**Comment by JourneyOver** [comment]
@liiight hows possibly getting the request implemented going? and I forgot to ask as well, does the trakt/sonarr plugins (mainly trakt to sonarr) support private lists or does it only support public lists?

**Comment by liiight** [comment]
Well, it's been around 24 hours so I'd say I accomplished a good 0% already, give or take...
And trakt list works with private lists just fine if you authenticate, check out the wiki

**Comment by JourneyOver** [comment]
@liiight lol well didn't know if you had looked things up at some point and was doing stuff behind the scenes and just hadn't pushed anything to github yet xD and good to hear, as I have my sonarr lists set to private.

So then I have two questions while I wait for things to get implemented into flexget,

1. If I was to go into flexget/plugins folder and change the default `show['qualityProfileId '] = 1` to let's say `show['qualityProfileId '] = 2` in the sonarr_list.py script would it change the qualityprofile trakt to sonarr uses, or would it still default to 1?

2. Does trakt to sonarr currently take whatever the rootpath is set at in sonarr. so for example if I was to have a paths like 

-  D:\Media\TV
-  D:\Media\Anime
-  F:\Media\Anime

in sonarr currently and my default path when adding shows was currently set to "D:\Media\TV" would trakt to sonarr use that as the rootfolder? or does the plugin go and create it's own rootfolder path?

**Comment by cvium** [comment]
This issue has been closed, Please continue this on our [forums](https://discuss.flexget.com) or [Gitter/IRC](https://flexget.com/Chat).

Locked.
