### ISSUE TITLE
piratebay plugin needs update

### ISSUE THREAD

**Issue by homestreaming** [Flexget/Flexget#2042]
### Expected behaviour:
Discover searching with piratebay should return results.

### Actual behaviour:
An error occurs instead:
Error searching with piratebay: Tried to set title to <span class="__cf_email__" data-cfemail="3e0e09100e07100c0610660c100c0e0e0d107a6a565b5f4a5b4c10090c0e4e10460c080a107a6a6d7e764a">[email protected]</span>

### Steps to reproduce:
- Step 1: Run a task that uses discover against piratebay. See sample config.
- Step 2: Restart daemon to see if it recovers and processes discover correctly with piratebay. It doesn't.

#### Config:
https://pastebin.com/GACbKKPz
  
#### Log:
https://pastebin.com/SHmYX8AQ

### Additional information:

- FlexGet version: 2.11.12.dev
- Python version: Python 3.6.3
- Installation method: git install
- Using daemon (yes/no): yes
- OS and version: Archlinux
- Link to crash log: none generated

**Comment by liiight** [comment]
`2017-12-17 14:56 ERROR    discover      download-torrent-movies-1080p-discover Error searching with piratebay: Tried to set title to <span class="__cf_email__" data-cfemail="28181f061811061a1006701a061a18181b066c7c404d495c4d5a061f1a185806501a1e1c066c7c7b68605c">[email protected]</span>`

**Comment by gazpachoking** [comment]
Hmm. Is this still a thing? The pastebin links are expired.

**Comment by paranoidi** [comment]
Closing, stale
