### ISSUE TITLE
[irc] Change log level of missing variable

### ISSUE THREAD

**Issue by dolohow** [Flexget/Flexget#2045]
Can this be changed to `warning` level?  It is pretty annoying.

https://github.com/Flexget/Flexget/blob/7e0de3f5c5ac257f0fe63cc55b669cfd46386542/flexget/plugins/daemon/irc.py#L465

**Comment by cvium** [comment]
This is not a bug. Either discuss this in Gitter/IRC, on our forums or add a feature request on Feathub.
