### ISSUE TITLE
Newpct doesn't download. HTML Web Changes

### ISSUE THREAD

**Issue by ciltocruz** [Flexget/Flexget#2063]
### Expected behaviour:
Newpct fails again. This is related to error #2054 already corrected some time ago.

#### Log:
REJECTED: `XXXXXX` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Unexpected html content received from `http://www.newpct1.com/torrents/103656.torrent` - maybe a login page?)

### Additional information:

- FlexGet version: 2.11.23
- Python version: Python 2.7.14
- Installation type: pip
- Using daemon (yes/no): no
- OS and version: Qnap 4.3.3

**Comment by ciltocruz** [comment]
Can anyone check the Newpct plugin?

**Comment by Peregrinox** [comment]
It's working for me (retrieving from rss ,the search never worked), 

I tried latest  2.12.1 and with 2.11.24. This is a relevant extract of my config:

`
 anchors:
    ...
    _settings_newpct: &settings_newpct
      settings:
        ep_regexp:
          - Cap.(\d+)(\d\d)
        quality: 1080p 720p
        identified_by: ep
        path: /media/TOSHIBA EXT/flexget/series/
...
  spaseries:
    template:
      - torrent_server
    priority: 5
    configure_series:
      from:
        entry_list: trakt-series
      <<: *settings_newpct
    rss:
      url: http://feeds2.feedburner.com/newpctorrent/

`

**Comment by ciltocruz** [comment]
It Works.

I have changed the RSS to the file that you have put.

The RSS that fails is this: http://newpct1.com/feed/

Thanks!

**Comment by liiight** [comment]
So can this be closed?

**Comment by ciltocruz** [comment]
Yes!

**Comment by Aokromes** [comment]
issue superseded by https://github.com/Flexget/Flexget/issues/2083
