### ISSUE TITLE
Newpct has died and tvsinpagar.com has replaced it.

### ISSUE THREAD

**Issue by ciltocruz** [Flexget/Flexget#2083]
Newpct fails again. This is related to error #2054  already corrected some time ago.

I have manually edited the newpct.py file by changing newpct.com to tvsinpagar.com and finding the torrentId by the javascript method (openTorrent) and it seems that way it works.

FlexGet version: 2.11.23
Python version: Python 2.7.14
Installation type: pip
Using daemon (yes/no): no
OS and version: Qnap 4.3.3

**Comment by Peregrinox** [comment]
Confirmed. Those "newpct" sites are currently using some kind of DNS redirection to their new locations:
newpct -> tvsinpagar
newpct1 -> descargas2020.com

@ciltocruz: Can you share your modified newpct.py file?

**Comment by ciltocruz** [comment]
Yeah right!

It is an edited version to work and, at least, until now it seems to work.


[newpct.txt](https://github.com/Flexget/Flexget/files/1764475/newpct.txt)

**Comment by nonestisoneu** [comment]
As far as I found, there are at least 4 domains:
- torrentlocura.com
- torrentrapid.com
- tvsinpagar.com
- descargas2020.com

I've rewrited newpct.py to make it work with all of them:
[torrentlocura.txt](https://github.com/Flexget/Flexget/files/1765064/torrentlocura.txt)

Just rename to torrentlocura.py and move to .flexget/plugins or whatever at [your config](https://flexget.com/Configuration).

Found a fifth domain: tumejortorrent.com but must to be added.

Enjoy.

**Comment by Aokromes** [comment]
Sometimes 2s is not enough:
rewriting descargas2020 failed: Unable to locate torrent ID from url http://descargas2020.com/Espere unos segundos...

**Comment by Aokromes** [comment]
@nonestisoneu maybe if you change the 2s thing you can create one PR for this :) it fixed most of the issues i had.

**Comment by Rafa-and** [comment]
Hi,

Great! It works again using @nonestisoneu solution.
Thank you very much

**Comment by brainstormi** [comment]
Not working for me. Using flexget version 2.13.1 and one of the new RSS feeds, like  http://descargas2020.com/feed or the old one http://feeds2.feedburner.com/newpctorrent with the same result.
Logs reports errors like: FAILED: `XXXX` by download plugin  by download plugin because valueError unknown url type: None
In log also appearing like torrentlocura plugin is choosing the URL from the feed that represent the image of the movie instead the download page:
   VERBOSE  torrentlocura Pelis_Desesperada Descargas2020 URL: http://www.descargas2020.com/pictures/f/thumbs/105000_-1519981826-mal-genio--bluray-microhd.jpg
2018-03-04 10:25 INFO     urlrewriter   Pelis_Desesperada Entry 'Mal Genio' URL rewritten to None (with torrentlocura)

**Comment by brainstormi** [comment]
@Aokromes that feed solved my issues. Thanks!.

**Comment by ciltocruz** [comment]
With the solution of @Aokromes (RSS) and @nonestisoneu (feed), it works for me.

But they are still "homemade solutions"...

**Comment by Lukeid** [comment]
@brainstormi You can try specifying the link field:
```
    rss: 
      url: http://descargas2020.com/feed
      link: link
```

About the @nonestisoneu solution, it's working for me.

But I did these modifications:
- Added tumejortorrent to timer and regexp
- Replaced torrentlocura duplicate timer by torrentrapid one

**Comment by monoetharyus** [comment]
Thanks @nonestisoneu and @Aokromes for the solution

**Comment by euod92** [comment]
With all the modifications from @nonestisoneu and @Aokromes (RSS) i still getting an error: 

```
2018-03-05 20:49 INFO     download      spanish task    Downloading: The Walking
 Dead - Temporada 8 [HDTV 720p][Cap.809][AC3 5.1 Español Castellano]
2018-03-05 20:49 ERROR    entry         spanish task    Failed The Walking Dead
- Temporada 8 [HDTV 720p][Cap.809][AC3 5.1 Español Castellano] (Unexpected html
content received from `http://descargas2020.com/descargar-seriehd/the-walking-de
ad/capitulo-89/hdtv-720p-ac3-5-1/` - maybe a login page?)

```

PD:i add `  ```
  rss: 
      url: http://descargas2020.com/feed
      link: link`
```
as @Lukeid says but it not help.

**Comment by Lukeid** [comment]
@euod92 for me is working that way.

Anyway, your error is not related with RSS feed.

This is what I did:
I copied the .py to the sites folder, then compiled the .py (and got a .pyc) and the restarted flexget, after that everything worked.

**Comment by euod92** [comment]
@Lukeid Yes, sorry i edit the comment in the same time you answering ;-).
I copy the file to the wrong folder so flexget still using newpct.py instead of the new file.

Thank you again.

**Comment by aykot** [comment]
Hi everyone, sorry to interrupt, but I´ve applied the changes from @Lukeid and @nonestisoneu but I keep getting the same error 

> failure reason: Unexpected html content received from http://www.descargas2020.com/pictures/c/767_series.jpg - maybe a login page?

Does anybody knows how t fix this?

Thank you in advance.

**Comment by nonestisoneu** [comment]
@aykot Sorry, but by now is just working with feedburner links as @Aokromes said
http://feeds.feedburner.com/descargas2020

I've bee working with a new file/plugin name to avoid problems with newpct plugin.
https://flexget.readthedocs.io/en/latest/develop/tdd.html#create-plugin

Not developer, sorry, I just took newpct plugin and tuned it to get barely working.

**Comment by aykot** [comment]
@nonestisoneu thanks for the effort. Don't know why  but I was testing some modifications and the problem is suddenly gone, it seems it was a server side error, because I was testing the unmodified plugin.

Regards

**Comment by Aokromes** [comment]
https://github.com/Flexget/Flexget/commit/bffbd64a43f66292dcb9bb7cdd9d44549359404d
