### ISSUE TITLE
KickassTorrents plugin revive

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#2086]
### Expected behaviour:
To be able to use https://thekickasstorrents.com/ as torrent website, which had been revived by some former staff and moderators

### Actual behaviour:
The plugin has been removed in commit https://github.com/Flexget/Flexget/commit/0a2a5c4f0400ac4e23d26613fb2db0aea94c71fe

### Fix
It could be a good idea to re-add the plugin and allow users to specify one of the (official) mirrors if the original domain does not work for them (as they state on their main page).
This could be implemented in the same way I had added the url-support for thepiratebay:
http://kat.cr
http://katcr.to
http://kickass.to
http://kickasstorrents.to
http://kickasstorrents.cr
http://kickass.cr
http://kat.am

**Comment by cvium** [comment]
I very much have my doubts about the legitimacy of that site.

**Comment by mfonville** [comment]
I don't know about the legitimacy myself; but when googling this was the first article to pop-up, it is a reliable source, so it seems to be legit: https://torrentfreak.com/kickasstorrents-brought-back-to-life-by-original-staffers-161216/

**Comment by cvium** [comment]
TF is about as reliable as Fox. The sidebar in this subreddit says something else https://www.reddit.com/r/kickasstorrents/

**Comment by mfonville** [comment]
aha, so then the homepage i did find is bogus, but https://katcr.co/ would be legit?
