### ISSUE TITLE
Jinja replacement in path does not work for qBittorrent plugin

### ISSUE THREAD

**Issue by chipriz** [Flexget/Flexget#2097]
Variable in example doesn't work. Instead, it creates the folder literally called {{series_name}}
Quotation marks and apostrophes do not make a difference.
Forward or backward slashes do not make a different.
Windows machine. Python 2.7. Flexget 2.13.2

qbittorrent:
  path: P:/Pending/{{series_name}}/
  host: localhost
  port: 8888
Have also tried numerous other configurations with path. For example

series:
  settings:
    set:
      path: P:/Pending/{{series_name}}/

Just simply does not want to use the variable whatsoever.
Works fine in uTorrent plugin, but as I've switched to qBittorrent it is causing a headache unfortunately. Everything else working fine so appears to just not be supported / meant to be used in this manner.

Please kindly add the {{series_name}} ability to work with qBittorrent

**Comment by cvium** [comment]
I'm not a fan of `os.path.expanduser` as these clients can technically be on another host, which means user expansion won't work if the usernames are different...

The requested change has been added in 0bd856995b6e9fcbf5b7bce47d770368b47e4606
