### ISSUE TITLE
simple_persistence: Flexget crashed while pulling Nyaa.si RSS Feeds

### ISSUE THREAD

**Issue by DonGrobione** [Flexget/Flexget#2101]
Hi Guys,

I just now upgraded Flexget to the latest version and was running bevor 1.2 something (I think, cant remember but was something wit version 1.x). I did not change my config in any way, but now whenever flexget tries to work on the task "Nyaa" and "Sukebei Nyaa" by pulling the RSS Feeds it crashes and generates two crash reports.

Here are some examples:
[crash_report.2018.03.16.015732484258.log](https://github.com/Flexget/Flexget/files/1817602/crash_report.2018.03.16.015732484258.log)
[crash_report.2018.03.16.015732503060.log](https://github.com/Flexget/Flexget/files/1817603/crash_report.2018.03.16.015732503060.log)

Right now I commented both tasks out, to keep Flexget from crashing, but I do not know why it crashed after the version upgrade, as it was fine bevor.

Here is my config: 
[config.yml.txt](https://github.com/Flexget/Flexget/files/1817627/config.yml.txt)

- FlexGet version: 2.13.5
- Python version: 2.7.12
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Ubuntu 16.04.4 LTS

**Comment by liiight** [comment]
please do `pip freeze | grep sqlalchemy`

**Comment by DonGrobione** [comment]
When I do `pip freeze | grep sqlalchemy`

I get `You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by liiight** [comment]
Hmm, just paste `pip freeze` then

**Comment by DonGrobione** [comment]
This is the result of `pip freeze`:

`acme==0.4.1
aniso8601==1.2.1
appdirs==1.4.3
APScheduler==3.5.0
babelfish==0.5.5
beautifulsoup4==4.6.0
certifi==2017.4.17
chardet==3.0.3
cheroot==5.5.0
CherryPy==10.2.2
click==6.7
colorama==0.3.7
colorclass==2.2.0
ConfigArgParse==0.10.0
configobj==5.0.6
contextlib2==0.5.4
cryptography==1.2.3
decorator==4.0.10
demjson==2.2.4
Django==1.8.7
dnspython==1.12.0
enum34==1.1.6
eventlet==0.19.0
feedparser==5.2.1
Flask==0.12.2
Flask-Compress==1.4.0
Flask-Cors==3.0.2
Flask-Login==0.4.0
Flask-RESTful==0.3.6
flask-restplus==0.10.1
FlexGet==2.13.5
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
geopy==1.11.0
googlemaps==2.4.4
gpsoauth==0.3.0
gpxpy==1.1.1
greenlet==0.4.10
guessit==2.1.4
haversine==0.4.5
html5lib==0.999999999
idna==2.5
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.9.6
jsonschema==2.6.0
letsencrypt==0.4.1
MarkupSafe==1.0
mock==2.0.0
ndg-httpsclient==0.4.0
networkx==1.11
numpy==1.11.0
ordereddict==1.1
packaging==16.8
parsedatetime==1.4
path.py==10.3.1
pathlib==1.0.1
pbr==1.10.0
Pillow==3.1.2
plumbum==1.6.3
polyline==1.3.1
portend==1.8
progressbar==2.3
protobuf==3.0.0b4
protobuf-to-dict==0.1.0
psutil==3.4.2
pyasn1==0.1.9
pycrypto==2.6.1
pycryptodomex==3.4.2
pycurl==7.43.0
PyICU==1.9.2
pynzb==0.1.0
pyOpenSSL==0.15.1
pyparsing==2.2.0
pyRFC3339==1.0
PyRSS2Gen==1.1
python-dateutil==2.6.1
python-engineio==0.9.2
python-socketio==1.4.2
python2-pythondialog==3.3.0
pytvmaze==1.4.7
pytz==2017.2
PyYAML==3.12
raven==5.23.0
rebulk==0.9.0
requests==2.16.5
rpyc==3.3.0
s2sphere==0.2.4
Safe==0.4
six==1.10.0
socketIO-client==0.7.0
SQLAlchemy==1.1.10
sqlparse==0.1.18
tempora==1.8
terminaltables==3.1.0
timeout-decorator==0.3.2
tmdb3==0.7.2
transmissionrpc==0.11
tzlocal==1.4
universal-analytics-python==0.2.4
urllib3==1.21.1
webencodings==0.5.1
websocket-client==0.37.0
Werkzeug==0.12.2
xxhash==0.6.1
zope.component==4.2.2
zope.event==4.2.0
zope.hookable==4.0.4
zope.interface==4.1.3
zxcvbn-python==4.4.15
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`
