### ISSUE TITLE
Descargas2020 failing to download

### ISSUE THREAD

**Issue by moilete** [Flexget/Flexget#2107]
Hello

I'm trying to reconfigure flexget to download from [http://feeds2.feedburner.com/descargas2020/](http://feeds2.feedburner.com/descargas2020/)  but i can't

Running on a QNAP TS-212 with Entware-ng
I just upgrade Flexget via PIP to last version 2.13.6

I'm tried with python2.7 and python3.6 and 3.6 i got an error when parsing

With pyhton2.7:

` /opt/bin/python2.7 /opt/bin/flexget -c .flexget/config.yml_NEW execute`

  I get this error in console and by email:

> The following entries have failed for task mis_series:
> - The Walking Dead - Temporada 8 [HDTV][Cap.812][Español Castellano] (http://feedproxy.google.com/~r/Descargas2020/~3/iHZUOlqRCOI/) Reason: Unexpected html content received from `http://feedproxy.google.com/~r/Descargas2020/~3/iHZUOlqRCOI/` - maybe a login page?
> 
> - Arrow - Temporada 6 [HDTV][Cap.615][Español Castellano] (http://feedproxy.google.com/~r/Descargas2020/~3/Vma6JVWNMbw/) Reason: Unexpected html content received from `http://feedproxy.google.com/~r/Descargas2020/~3/Vma6JVWNMbw/` - maybe a login page?
> 
> - Hawaii Five 0 - Temporada 8 [HDTV][Cap.816][Español Castellano] (http://feedproxy.google.com/~r/Descargas2020/~3/rI7Ey5SFXKc/) Reason: Unexpected html content received from `http://feedproxy.google.com/~r/Descargas2020/~3/rI7Ey5SFXKc/` - maybe a login page?

I upgraded flexget because this ticket #2093 but I can't get it working

Config file (only problematic task):

> rss:
>   url: http://feeds2.feedburner.com/descargas2020/
>   link: link
> series:
>   settings:
>     normales:
>       ep_regexp:
>         - Cap.(\d+)(\d\d)
>       quality: hdtv <720p
>   normales:
>       - Scandal:
>           set:
>             patch: "/share/external/sdr1/Series/Scandal/"
>   regexp:
>   reject:
>     - V.O.:
>         from: title

Is a bug or only an error in config files?
How can I get it working??

Can anyone help me?

thanks in advance!!

**Comment by movalex** [comment]
looks like the links from your feed will not provide .torrent files

**Comment by moilete** [comment]
Thank very much to both!

I was using the old url for the feed. I didn't know is was a bug with new "descargas2020 urlrewrite" plugin or an missmatch in config files

No problem if rss is slow in updating links... I only want to accumulate the donwloads in NAS server "ready for use"

  Thank you and, please, close ticket

Moises

**Comment by Aokromes** [comment]
you can close ticket youself :)
