### ISSUE TITLE
Unable to find login fields with YGGTorrent.is and plugin Form

### ISSUE THREAD

**Issue by bilyboy785** [Flexget/Flexget#2125]
#### Situation
I've got an error until Yggtorrent has changed : 
```
Unable to find login fields
```

#### Config:
```
yggtorrent:
    form:
       url: https://yggtorrent.is/user/login
       userfield: id
       passfield: pass
       username: 'myuser'
       password: 'mypassword'
```
  
#### Log:
```
2018-04-20 16:45 CRITICAL formlogin     packmagazines   I have saved the login page content to /root/.flexget/received/packmagazines.formlogin.html for you to view
2018-04-20 16:45 CRITICAL formlogin     packmagazines   Unable to find login fields
2018-04-20 16:45 WARNING  task          packmagazines   Aborting task (plugin: form)

```

### Additional information:

- FlexGet version: 2.13.14
- Python version: Python 2.7.13
- Installation method: pip install
- Using daemon (yes/no): yes
- OS and version: Debian 9.4

**Comment by cvium** [comment]
Opening `https://yggtorrent.is/user/login` in a browser returns nothing, so this is not a Flexget issue. They probably changed something on the site.

**Comment by bilyboy785** [comment]
I know, the form is now in a Popup.. can we do something to fix this ?

**Comment by cvium** [comment]
The login form is present on the front page, so try that... `https://yggtorrent.is/`. If you wish to discuss it further, there's the forums and IRC/Gitter.
