### ISSUE TITLE
Flexget 2.13.14 unhandled errors with transmission 2.93

### ISSUE THREAD

**Issue by specie77** [Flexget/Flexget#2126]
### Expected behaviour: 
establish a connection with Transmission 2.93

### Actual behaviour:
Everytime I execute flexget to connect to transmission, an unhandled error occurs.  Transmission host was just upgraded to 2.93, and now flexget won't connect. Included settings.json from transmission for reference.
[settings.json.txt](https://github.com/Flexget/Flexget/files/1949598/settings.json.txt)

### Steps to reproduce:
- Step 1: 
flexget execute --tasks clean_up

#### Config:
[config.yml.txt](https://github.com/Flexget/Flexget/files/1949578/config.yml.txt)

#### Log:
[flexget.log](https://github.com/Flexget/Flexget/files/1949595/flexget.log)

### Additional information:
- FlexGet version: 2.13.14
- Python version: 3.5.3
- Installation method: pip
- Using daemon (yes/no): error occurs with and without daemon
- OS and version: Windows Server 2012 R2 Standard
- Link to crash log: 
[crash_report.2018.04.25.225359801753.log](https://github.com/Flexget/Flexget/files/1949580/crash_report.2018.04.25.225359801753.log)

**Comment by lamski** [comment]
Have you tried updating transmissionrpc?
```
pip install --upgrade transmissionrpc
```

**Comment by specie77** [comment]
From what I can tell, 2.93 is the latest version, no?

**Comment by lamski** [comment]
I think Transmission 2.94 is out.

**Comment by specie77** [comment]
Done, upgraded.  Now, for some strange reason, it's returning an incorrect username/password error.  However when I connect via the web client, it works perfectly.  Something is strange here.

**Comment by lamski** [comment]
Wait, looking at your flexget config file, I think you need to set the transmission port to the rpc-port which, in your case is port 80. The transmission web port usually defaults to port 9091, but in your settings.json, it's set to port 80.

**Comment by specie77** [comment]
You’re right, it was port 9091, I annonimized the config. I was confused, it is the rpc port. But it tells me my username and password are incorrect, they are not.

**Comment by lamski** [comment]
Is your transmission running on the same machine as flexget?
Is transmission the desktop version or the server version?

Perhaps you could troubleshoot it using [transmission remote GUI](https://github.com/transmission-remote-gui/transgui)?

I have flexget and transmission running on an ubuntu server and transmission remains at 2.92 so I'm not experiencing the issue.

**Comment by specie77** [comment]
Transmission is actually running on a cloud hosted seedbox as an app. Unfortunately I don’t have access to the platform. It used to work well, then I don’t know what happened.

**Comment by lamski** [comment]
Found a similar issue in the trans-GUI issues list: https://github.com/transmission-remote-gui/transgui/issues/1127

**Comment by specie77** [comment]
Wait, in the transmission settings, or my flexget config?

**Comment by lamski** [comment]
The transmission host in your flexget config.

From the transmission documentation, found these two new properties introduced in v 2.93:

> - rpc-host-whitelist: String (Comma-delimited list of domain names. Wildcards allowed using '*'. Example: "*.foo.org,example.com", Default: "", Always allowed: "localhost", "localhost.", all the IP addresses. Added in v2.93)
> - rpc-host-whitelist-enabled: Boolean (default = true. Added in v2.93)

If you still could not connect, try setting rpc-host-whitelist-enabled to false.
