### ISSUE TITLE
How to reject all season packs?

### ISSUE THREAD

**Issue by jiangjiangflies** [Flexget/Flexget#2130]
I've read the documentation and only found how to download season packs. However, I want to avoid downloading any season packs of any shows because of my limited disk space. How to do this?

**Comment by liiight** [comment]
Season pack are rejected by default. In the future, please ask questions in the forums, issues is for, well, issues...

**Comment by jiangjiangflies** [comment]
Thank you. I will open new threads in the forum next time.

But actually I got season packs anyway. Here is my configuration:
tasks:                                                     
  Test:                                            
    rss: xxx                                 
    accept_all: yes                                        
    transmission:                                          
      host: localhost                                      
      port: 9091                                           
      username: xxx                                   
      password: xxx                                     
    content_size:                                          
      min: 0                                               
      max: 5120 

I want to accept all shows in the rss feed but limit the size to 5GB per torrent.  At the same time, I want to reject all season packs because my private tracker requires a long seeding time for season packs.  The configuration above can't exclude them.

**Comment by liiight** [comment]
You mentioned you read the wiki so I assumed you did, but you're not using series plugin at all, and are using `accept_all` which does just that.

Anyway, please move to the forums.

**Comment by jiangjiangflies** [comment]
Thanks! I went to the forum and finally fixed it myself by adding regexp plugin. https://discuss.flexget.com/t/how-to-reject-any-season-packs-of-any-shows/4159 
This pattern can reject all season packs like` Dog.With.a.Blog.S03.1080p.AMZN.WEB-DL.DDP5.1.x264-TrollHD`
