### ISSUE TITLE
Unhandled error in lazy lookup plugin +thetvdb

### ISSUE THREAD

**Issue by Oshayr** [Flexget/Flexget#2133]
- Flexget Version: 2.13.15 and 2.13.14
- Python version: 2.7.14
- Installation method: pip
- Using daemon (yes/no) yes:
- OS and version: Win10

**Expected behaviour:**
Not to throw Critical Error 

**Actual behaviour:**
Critical Error, task stops running

**Steps to reproduce:**
```yaml 
ttv-list:
    metainfo_series: yes
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    list_clear:
      what:
        - entry_list: tvlist
    accept_all: yes
    if:
      - tvmaze_series_status == 'Ended': reject
      - tvdb_status == 'Ended': reject
      - "'WWE' in title": reject
    set:
      title: "{{tvdb_series_name|default(tvmaze_series_name)|default(series_name)}}"
    next_trakt_episodes:
      < trackt login data>
      context: watched
      strip_dates: yes
    list_add:
      - entry_list: tvlist
```
  
**Log:**
```
2018-05-07 23:40 ERROR    lazy_lookup   ttv-list  Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\utils\lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\thetvdb_lookup.py", line 159, in lazy_episode_lookup
    entry.update_using_map(self.episode_map, episode)
  File "c:\python27\lib\site-packages\flexget\entry.py", line 276, in update_using_map
    v = value(source_item)
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\thetvdb_lookup.py", line 99, in <lambda>
    'tvdb_ep_id': lambda ep: 'S%02dE%02d' % (ep.season_number, ep.episode_number)
TypeError: %d format: a number is required, not NoneType`
```

**Comment by liiight** [comment]
Can you provide full debug logs please?

**Comment by Chaosmagnetx** [comment]
Attached is  the relevent part of the debug output from running:
flexget -L debug execute --tasks ttv-list
[flexget-debug-ttv-list-log.txt](https://github.com/Flexget/Flexget/files/1983441/flexget-debug-ttv-list-log.txt)

**Comment by liiight** [comment]
this error has absolutely nothing in common with the reported issue... It just shows you had a DB IO issue.

**Comment by chewy74** [comment]
I'm having this issue also... This stops my task before it can finish, and the torrent doesn't get sent to transmission for download. 

This only seems to happen when the task runs in daemon mode. Manual execution will see the task complete and torrent download.
