### ISSUE TITLE
uTorrent error: path is not added to utorrent webui allowed download directories

### ISSUE THREAD

**Issue by antonioribeiro** [Flexget/Flexget#2138]
### Expected behaviour:

Using uTorrent and Web UI, add downloads to their proper directories. 

### Actual behaviour:

I get the error 

```
path `Z:\videos\tv\The Good Fight\Season 2` (or one of its parents) 
is not added to utorrent webui allowed download directories. 
You must add it there before you can use it from flexget. 
Adding to default download directory instead.
```

### Steps to reproduce:

- Download something using flexget and uTorrent Web UI, with Download directories properly configured.

#### Config:
```
#download: /Volumes/MediaCenter/Drive X/MediaCenter/!tv
tasks:
  tv-task:
    rss: https://tracker.net/feeds.php?
    series:
      settings:
        seriesgroup:
          set:
            path: Z:\videos\tv\{{series_name}}\Season {{series_season}}
            #path macOS: /Volumes/macbook-2tb/mediacenter/tv/{{series_name}}/Season {{series_season}}
      seriesgroup:    
        - The Good Fight
    #transmission:
    #  host: 172.17.0.115
    #  port: 9091
    #  username: admin
    #  password: password
    utorrent:
      url: http://172.17.0.150:8087/gui/
      username: admin
      password: password
      path: Z:\videos\tv\  # Either c:\stuff, or c:\stuff\here must be added to your allowed download folders
schedules:
  - tasks: 'tv-task'
    interval:
      minutes: 1
```
  
#### Log:

This is how uTorrent is configured:

![image](https://user-images.githubusercontent.com/3182864/40029685-41434786-57bc-11e8-939c-d5d014e31be4.png)

It doesn't matter if I just put Z:\videos or the full path of the video, nothing works

This is the full log of the error: 

```
2018-05-14 21:14 INFO     scheduler                     Starting scheduler
2018-05-14 21:14 INFO     download      tv-task         Downloading: The Good Fight - S02E11 [ 2018 ] [ MKV | H.264 | WEB-DL | 720p | Scene | FastTorrent ] [ Uploader: Anonymous ]  [ The.Good.Fight.S02E11.INTERNAL.720p.WEB.H264-DEFLATE ]
2018-05-14 21:14 ERROR    utorrent      tv-task         path `Z:\videos\tv\The Good Fight\Season 2` (or one of its parents)is not added to utorrent webui allowed download directories. You must add it there before you can use it from flexget. Adding to default download directory instead.
2018-05-14 21:14 INFO     utorrent      tv-task         Added `https://tracker.net/torrents.php?action=download&authkey=XXXXXf&torrent_pass=XXXX&id=XXXX` to utorrent
2018-05-14 21:14 INFO     utorrent      tv-task         in folder 0
```

### Additional information:

- FlexGet version: 2.13.17
- Setuptools: 39.1.0
- Python version: 2.7.10
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: macOS 10.13.3
- Link to debug log: https://pastebin.com/qZQvsbLG
- uTorrent version: 3.5.3 (build 44428)

**Comment by BrutuZ** [comment]
Setting an individual torrent's download path shouldn't be on the plugin since it's not supported by their WebAPI. [Source](http://help.utorrent.com/customer/en/portal/articles/1573954-limitations---webapi)

**Comment by antonioribeiro** [comment]
> Setting an individual torrent's download path shouldn't be on the plugin since it's not supported by their WebAPI. Source

Individual torrent's download path are supported by uTorrent since 2.0, via labels, which are supported by WebAPI.

And this is something that was working fine in Flexget, had one glitch, but once properly configure it worked, [as you can see here](https://discuss.flexget.com/t/configuring-utorrent-webui-allowed-download-directories-for-flexget/3895/3), for some time, then it stopped working. After the fix was pushed, it was broken for good.

**Comment by BrutuZ** [comment]
My bad then. Tried to set this up a couple times without success, found that limitations page and assumed the call had been discontinued.
Worked around it with monitored folder and a task to move the files from completed folder, a "good enough" solution for my use case.
