### ISSUE TITLE
Enhancement: More robust "if" plugin

### ISSUE THREAD

**Issue by tmknight** [Flexget/Flexget#2139]
Unfortunately, the feathub link is not valid nor is the request forum accepting new posts.  So I hope you will consider the following:

Extend 'if' plugin to all execution of all other plugins.  Right now, it is limited to a few filter plugins and set.  It would be very useful if other plugins such as manipulation plugins would be permitted.

There are a lot of RSS feeds that are very sparse and only supply the required elements, thus requiring more complex queries to dial-in to the desired version of a torrent.  They being resistant to change, Flexget, you are my only hope!

Cheers

**Comment by cvium** [comment]
It is already supported...
