### ISSUE TITLE
Wiki on web flexget.com is missing titles

### ISSUE THREAD

**Issue by kepi** [Flexget/Flexget#2148]
I find it really hard to work with recipes from Flexget.com Cookbook as title of the page is "FlexGet" on every page.

I didn't find better place to report this issue, so sorry it is in app repo.

As every page has nice title it would be amazing to put it to title attribute in html head section too so I can open multiple pages and don't get lost after minute.

**Comment by gazpachoking** [comment]
I agree, this would be nice. Our wiki library doesn't have support for that at the moment, but I think something can be worked out. I created an issue over there about it, if anyone wants to give it a crack. scragg0x/realms-wiki#220

**Comment by gazpachoking** [comment]
Our wiki app is pretty much dead now. We'll solve this when we eventually transition to another one. (Maybe wiki.js? Maybe I'll look in to it once they finish the transclusion feature.)
