### ISSUE TITLE
horriblesubs plugin no longer functional

### ISSUE THREAD

**Issue by Hark0nnen** [Flexget/Flexget#2166]
HorribleSubs  remade their website on 01.07.2018, and plugin no longer works. "Task didn't produce any entries"

 FlexGet version:  2.14.2

**Comment by paranoidi** [comment]
Looks like there are quite big changes

**Comment by Liboicl** [comment]
I've got a fix wrote for this. I'll be uploading it shortly after a little more testing.

**Comment by ksurl** [comment]
just wondering, is there a benefit to using the hs plugin rather than just using the rss feed?

**Comment by Hark0nnen** [comment]
hs feed contains magnets only, which can be undesirable. convert_magnets produced invalid torrents for me, and i didnt find any way to save them in a non rtorrent specific way (is there any?). i ended up switching my setup to directly feed magnets to a client, but this is not an optimal solution for me.

**Comment by Liboicl** [comment]
I also often start a series that's already begun and the plugin can load a series directly and grab older entries.

**Comment by ksurl** [comment]
ahh. I use the rss feed from nyaa which uses .torrents and flexget can backfill series episodes via config.

**Comment by ksurl** [comment]
as far as I can tell. the ones on nyaa go all the way back. not the rss on their homepage
