### ISSUE TITLE
trakt auth not working

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2181]
#### Log:
```
snikay@vmi13332283:/$ sudo flexget trakt auth snikay
Please visit https://trakt.tv/activate and authorize Flexget. Your user code is F952FDFC. Your code expires in 10.0 minutes.
Waiting.....................Successfully authorized Flexget app on Trakt.tv. Enjoy!
snikay@vmi13332283:/$ sudo flexget execute --now --tasks Specials2
2018-07-28 01:10 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2018-07-28 01:10 INFO     interval      Specials2       No previous run recorded, running now
2018-07-28 01:10 CRITICAL plugin        Specials2       Account {? trakt.acc ?} has not been authorized. See `flexget trakt auth -h` on how to.
2018-07-28 01:10 WARNING  task          Specials2       Aborting task (plugin: list_add)
  
```

### Additional information:

- FlexGet version: 2.14.9

{? trakt.acc ?} is definitely "snikay"

**Comment by cvium** [comment]
> {? trakt.acc ?} is definitely "snikay"

It would definitely not log `{? trakt.acc ?}` if it was.

**Comment by snickers2k** [comment]
i  didnt changed that?! thats the exact output :/

**Comment by cvium** [comment]
And I'm saying your config must be wrong ie. variables plugin has not been initialized properly.

**Comment by snickers2k** [comment]
oh sorry.. i installed the quick-fix for the trakt-plugin while it was broken. and now i guess it weren't overwritten by pip after last update? i'll update it manually and let you know

**Comment by snickers2k** [comment]
but still strange.. should be updated.. and i'm on 14.9

**Comment by cvium** [comment]
Your config, not installation. You've left out half the issue template.

**Comment by liiight** [comment]
Not a bug.

**Comment by snickers2k** [comment]
found the issue.. i "outsourced" most of that  task to another file and the variables-plugin does not work with the include-plugin  or inside included files.
