### ISSUE TITLE
rtorrent SCGI transport looks like GPLed code with its license stripped

### ISSUE THREAD

**Issue by JohnDoee** [Flexget/Flexget#2196]
The [SCGI XML-RPC transport used in Flexget](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/rtorrent.py#L99-L224) looks exactly like the GPLed one that's floating around. An example of this can be seen [here](https://github.com/TinyHTPC/xbmc-dev-repo/blob/a3184d3f9451b23865bcf1abce380099f9367876/script.service.audo/resources/SickBeard/lib/rtorrent/lib/xmlrpc/scgi.py) or [here](https://gist.github.com/query/899683/7e5d0c123cd5a6117b3e3d0a9d41a583260516fd)

This also matches my experience looking for a better licensed SCGI Transport back in start of 2015 (before this code was added to Flexget) which resulted in me writing my own transport as none existed.

I suggest replacing the plagiarized SCGI Transport with [my own version](https://github.com/JohnDoee/autotorrent/blob/develop/autotorrent/scgitransport.py) as it should have no license issues and be functionally equivalent.

**Comment by stevezau** [comment]
Is yours a drop in replacement?

I'm not that familiar with the licencing. I thought we could re-use it but need to keep the license at the top of the file intact?

**Comment by stevezau** [comment]
I'm not familiar with how the licenses work or what's allowed. We should re-add the licence back. But reading the license I didn't realise Flexget would also need to be GPL.

So onto yours.. Is it a drop in replacement?

**Comment by paranoidi** [comment]
@stevezau please read up about licenses

Code under GPL can not be included in FlexGet repository. A separately distributed plugin under GPL would be an option though. However for this we should switch to @JohnDoee implementation ASAP.

**Comment by JohnDoee** [comment]
If you copy the code from scgitransport.py and use a function like this:
```
from six.moves.urllib.parse import quote, urlsplit
from six.moves.xmlrpc_client import ServerProxy

def create_proxy(url):
    parsed = urlsplit(url)
    proto = url.split(':')[0].lower()
    if proto == 'scgi':
        if parsed.netloc:
            url = 'http://%s' % parsed.netloc
            return ServerProxy(url, transport=SCGITransport())
        else:
            path = parsed.path
            return ServerProxy('http://1', transport=SCGITransport(socket_path=path))
    else:
        logger.debug('Creating Normal XMLRPC Proxy with url %r' % url)
    return ServerProxy(url)
```

then it's almost a drop-in replacement. When the proxy is created then functionally it should be equivalent at least.

The GPL problem also exist with Deluge implementation but there's already a pull request for that in the works.

GPL is literally the reason I've written both a Deluge client and an SCGI transport.
