### ISSUE TITLE
Daemon does not handle SIGTERM

### ISSUE THREAD

**Issue by X-dark** [Flexget/Flexget#2243]
It would be great if flexget daemon would properly handle SIGTERM. It would allow to gracefully shutdown (ie equivalent to `flexget daemon stop`) when receiving such signal.
It would be useful for proper docker behavior.

**Comment by ksurl** [comment]
how about using systemd to control it? create flexget.service file and enable it so it autostarts on boot. specify execstop command as `flexget daemon stop`

**Comment by X-dark** [comment]
Yes, it is working fine on a standard host. But in a container, there is no systemd. There is just one main process and when you stop the container it receives a SIGTERM.

**Comment by gazpachoking** [comment]
Hmm, it's supposed to handle that already. Not working then I guess? https://github.com/Flexget/Flexget/blob/develop/flexget/manager.py#L453

**Comment by X-dark** [comment]
Yes I have seen that afterward. From what I was able to test, sending a SIGTERM has no effect to the daemon.

**Comment by lamski** [comment]
Perhaps it's the way Flexget was setup in the Docker container which is the reason it is not receiving signals - https://hynek.me/articles/docker-signals/

**Comment by cvium** [comment]
Sending a SIGTERM works for me, but I too have problems propagating the signal inside Docker even with s6-overlay.

**Comment by paranoidi** [comment]
Assuming SIGTERM is same as shutting down foreground running daemon with CTRL-C, it almost always fails for me ...

**Comment by diogosena** [comment]
This still a issue..
