### ISSUE TITLE
from_deluge keys option is incomplete

### ISSUE THREAD

**Issue by jasonlyle88** [Flexget/Flexget#2257]
### Expected behaviour:
For the `keys` option of `from_deluge` to accept any (simple) value that deluge provides in its RPC API.

### Actual behaviour:
As of right now, the `keys` option of `from_deluge` supports a subset of keys available from the RPC API. Examples of missing keys that are available from the RPC API but not from `from_deluge` are:
1. `eta`
2. `hash`
3. `is_finished`
4. `label`
5. `move_completed`
6. `move_completed_path`
7. `move_on_completed_path`
8. `name`
9. `num_peers`
10. `num_seeds`
11. `private`
12. `progress`
13. `ratio`
14. `save_path`
15. `seeding_time`
16. `seeds_peers_ratio`
17. `state`
18. `time_added`
19. `total_size`
### Steps to reproduce:
Configure from_deluge, and attempt to set the keys option to any of the values listed above.

NOTE: I have not tested every single one of those to see if they throw an error. I tested a few and found they were not able to be used in the `keys` option. I then looked at the documentation for a list of the  available `keys` values and compared it with the results of an RPC call to see what was missing. The above list is what is present in the RPC call but missing from the `from_deluge ` `keys` option documentation.

#### Config:
```
    seen: local
    seen_info_hash: local
    from_deluge:
      host: '{? deluge.host ?}'
      port: 58846
      username: '{? deluge.username ?}'
      password: '{? deluge.password ?}'
      keys:
        - stop_ratio
        - seeding_time
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
There is a FlexGet process already running for this config, sending execution there.
2018-11-20 15:37 VERBOSE  check                         Checking config file `/root/.flexget/config.yml`
2018-11-20 15:37 VERBOSE  check                         Pre-checked 315 configuration lines
2018-11-20 15:37 CRITICAL check                         [/templates/input-deluge_torrents/from_deluge/keys/1] Must be one of the following: active_time, is_seed, num_pieces, total_payload_download, stop_at_ratio, total_seeds, peers, next_announce, total_payload_upload, paused, file_progress, max_download_speed, max_upload_slots, prioritize_first_last, piece_length, download_payload_rate, message, upload_payload_rate, max_connections, compact, move_on_completed, trackers, total_done, is_auto_managed, total_peers, total_wanted, queue, num_files, max_upload_speed, distributed_copies, tracker, stop_ratio, seed_rank, tracker_status, total_uploaded, tracker_host, remove_at_ratio
```
</details>

### Additional information:

- FlexGet version: 2.7.13
- Python version: 2.7.12
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 14.04

**Comment by cvium** [comment]
This is not really a bug, but a feature request.

**Comment by jasonlyle88** [comment]
@cvium Okay... do you need me to create a feature request for this then?

Sorry, I just figured this was more of an issue seeing as most likely almost all the code is already there, the intent for the use is already there, it is just missing keys that should be there.

**Comment by gazpachoking** [comment]
I think most, if not all of these fields are available by default, with a `deluge_` prefix to the key. It is a bit confusing how some of them are default, and some have to be specified in the `keys` part of the config, and how those ones don't get the `deluge_` prefix. Not sure if we should try to clean that up or not.

https://flexget.com/Plugins/from_deluge#entry-fields

https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/deluge.py#L85-L100

**Comment by jasonlyle88** [comment]
@gazpachoking , yeah, some of those are definitely available as entry fields... not sure why I overlooked those when I was doing my comparison! I'll do some testing and update this issues. Looking at the code you referenced, it looks like the documentation doesn't quite line up in regards to settigns_map => entry fields and extra_settings_map => keys fields (Just basing this off comparison of number of entries in the code vs number of entries in the documentation).

Also, comparing my list to keys reference between settings_map and extra_settings_map leaves the following data elements out from the deluge RPC API:

1. `is_finished`
2. `move_completed`
3. `move_completed_path`
4. `seeds_peers_ratio`
5. `time_added`

**Comment by gazpachoking** [comment]
Yeah, looks like some of those are missing. We are doing move_on_completed, and move_on_completed_path, which looks like they have been deprecated in favor of the versions without the 'on'.

**Comment by paranoidi** [comment]
@gazpachoking cleanup with consistent deluge_ prefix along with consistent plugin option naming (with underscores). Maybe something for next upgrade actions version?

**Comment by gazpachoking** [comment]
Okay, with that merge from_deluge will provide all fields from deluge by default.
