### ISSUE TITLE
torrent_cache plugin isn't adding valid urls

### ISSUE THREAD

**Issue by ghost** [Flexget/Flexget#2307]
guys, the "magnets: no" option which uses itorrents, zoink and torrage isnt working (maybe a login page?, Unexpected html content received from) it seems to be cause they have changed their URL

ive narrowed down the issue with torrage in that where flexget is looking for "http://torrage.com/torrent/f22dac9a98944c1a6528daaf1d0ee3d20c0977ac.torrent" it should actually be looking for "http://torrage.info/torrent.php?h=f22dac9a98944c1a6528daaf1d0ee3d20c0977ac" and even after that it needs to download it which is "https://t.torrage.info/download?h=f22dac9a98944c1a6528daaf1d0ee3d20c0977ac" looking at the code (https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/services/torrent_cache.py#L13) the extension .torrent gets added, but making it not do that in this case is out of my depth

thetorrent changes are as follows. going to this returns a download page and not the actual torrent file (https://thetorrent.org/f22dac9a98944c1a6528daaf1d0ee3d20c0977ac.torrent) and the download link has a extra bit at the end which changes (http://thetorrent.org/F22DAC9A98944C1A6528DAAF1D0EE3D20C0977AC.torrent?_=5c489047a2afc) (http://thetorrent.org/4E4F9A62C273341CF008598CCF3E9312A7789E05.torrent?_=5c48922c8e7c7) and the torrent file wont download without it

as for zoink, it redirects to eztv and i couldnt find any torrent caching system with them.

**Comment by monokoo** [comment]
same issue

**Comment by gazpachoking** [comment]
Hmm, seems like these sites are trying to make sure you actually visit now. Tried to fix torrage, but if you just visit the download link it'll give you a 404. I'm assuming you have to set the referrer header to show you came from their landing page or something, but it's no longer as easy to just plug a url in via our torrent_cache plugin. I'm assuming that parameter at the end of the thetorrent.org url is meant for the same reason

**Comment by gazpachoking** [comment]
I've disabled torrent_cache from being a built-in for now, since it's broken. b73ac1b2cdf394c141cf58949147d1559ccbb6b6
