### ISSUE TITLE
how do I set series to accept all feeds from an rss source? when adding flex to a gui of transmission?

### ISSUE THREAD

**Issue by Deep61** [Flexget/Flexget#2336]
### Steps to reproduce:
- Step 1: ...

#### Config:
```
paste FULL config and remove any personal info
if config is too long, attach the file to the ticket
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version:
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

**Comment by Deep61** [comment]
Here is an example of a dummy guide using variables instead of actual values:

tasks:
  task1:
    rss: feed_URL
    series:
      - series_name
    transmission:
      host: server.feralhosting.com
      port: 80
      username: username
      password: password

**Comment by gazpachoking** [comment]
@Deep61 The forum is the right place for this sort of question, not quite sure what you are asking though. Follow up [there](https://discuss.flexget.com/t/how-do-i-set-series-to-accept-all-feeds-from-an-rss-source-when-adding-flex-to-a-gui-of-transmission/4551?u=gazpachoking)
