### ISSUE TITLE
GuessIt output not handled correctly for episode_details

### ISSUE THREAD

**Issue by JohnDoee** [Flexget/Flexget#2340]
It seems like `episode_details` can also be a list. [I verified this issue is still present in latest version of Flexget](https://github.com/Flexget/Flexget/blob/develop/flexget/components/parsing/parsers/parser_guessit.py#L309)

Example GuessIt entry:
```
For: Some.Show.S01E01.Special.Pilot-crap
GuessIt found: {
    "title": "Some Show",
    "season": 1,
    "episode": 1,
    "episode_title": "Special Pilot-crap",
    "episode_details": [
        "Special",
        "Pilot"
    ],
    "type": "episode"
}
```

Flexget exception
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flexget/plugins/filter/series.py", line 1615, in on_task_metainfo
    parsed = parser.parse_series(entry['title'])
  File "/usr/local/lib/python3.5/site-packages/flexget/plugins/parsers/plugin_parsing.py", line 74, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flexget/plugins/parsers/parser_guessit.py", line 245, in parse_series
    special = guess_result.get('episode_details', '').lower() == 'special'
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by gazpachoking** [comment]
So, I think this was fixed in #2252, however it may not be the right answer. In this instance, if guessit found episode details other than 'special' first, we wouldn't detect the episode as a special properly. I'm wondering if we shouldn't switch our guessit options from 'single_value' over to 'enforce_list', and just bite the bullet and handle lists properly for every property.

**Comment by gazpachoking** [comment]
Actually, looks like when we force 'single_value' like we are now, we can still get the list of values from the 'values_list' dict. We can then just switch the 'special' detection (and any other bit where we want to look at all the guessit matches) over to looking at that.

**Comment by gazpachoking** [comment]
So, that commit doesn't really fix the reported issue, (since that issue should already be fixed,) but it fixes the special detection when `final`, `pilot`, or `unaired` was in the name before the word `special`.
