### ISSUE TITLE
FlexGet uses old version of urllib3 that has known weaknesses

### ISSUE THREAD

**Issue by alexdevsec** [Flexget/Flexget#2341]
### Expected behaviour:

Pyup's security tool should report no dependencies on libraries with known vulnerabilities. 2.20.1 still uses urllib3 1.21.1.

### Actual behaviour:
...
(formatting changed to fit this form)

package: urllib3
installed: 1.21.1
affected: < 1.23
ID 36541
description: 

urllib3 before 1.23 does not remove the Authorization HTTP header when      following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.

### Steps to reproduce:

Running:
pip install flexget
pip install safety
pip freeze | safety --stdin 

Should report no errors.

#### Config:

Picked up during install.
  
### Additional information:

- FlexGet version: 2.20.1
- Python version: 3.7 (but same exists for 2.7)
- Installation method: pip
- Using daemon (yes/no): NA
- OS and version: Ubuntu 16.04
- Link to crash log: N/A

**Comment by gazpachoking** [comment]
Fixed in 27e329581ba26232ec3df88e57df8a814e4e41b8, thanks!
