### ISSUE TITLE
Flexget can't handle broken IPv6 situations

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#2343]
### Expected behaviour:
When using a website that has AAAA records available for crawling e.g. a piratebay mirror like `unblocktheship.org` I expect flexget to fetch the results from that website, and if IPv6 doesn't work, that it uses IPv4 instead.
Just like wget does when IPv6 fails:
```
wget https://unblocktheship.org/
Resolving unblocktheship.org (unblocktheship.org)... 2606:4700:30::681f:121e, 2606:4700:30::681f:131e, 104.31.18.30, ...
Connecting to unblocktheship.org (unblocktheship.org)|2606:4700:30::681f:121e|:443... failed: Network is unreachable.
Connecting to unblocktheship.org (unblocktheship.org)|2606:4700:30::681f:131e|:443... failed: Network is unreachable.
Connecting to unblocktheship.org (unblocktheship.org)|104.31.18.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

### Actual behaviour:
Instead, flexget gets stuck on the IPv6 try and never resorts to IPv4.
```
Error searching with piratebay: RequestException: HTTPSConnectionPool(host='unblocktheship.org', port=443): Max retries exceeded with url: XXXXXXXXXXXXXXXXXXXXXXX (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f64846092d0>, 'Connection to unblocktheship.org timed out. (connect timeout=30)'))
```
later entries to be searched:
```
Error searching with piratebay: RequestException: Requests to this site (unblocktheship.org) have timed out recently. Waiting before trying again.
```

#### Config:
```
discover:
      what:
        - next_series_episodes: yes
      from:
        - piratebay:
            url: https://unblocktheship.org
```
  

### Additional information:

- FlexGet version: 2.20.3
- Python version: Python 2.7.15+
- Installation method: pip
- OS and version: Ubuntu 18.10

Temporary workaround was to enable in `/etc/gai.conf` the line `precedence ::ffff:0:0/96  100` but the real solution would be for flexget to automatically fall back to IPv4 if it fails with IPv6

**Comment by paranoidi** [comment]
We are using Requests Python library. Unless there's something we are doing wrong with it, we are likely at the "mercy" of working as well as it does.

It is generally thought to be an excellent library, so I'm not really sure if there is anything we can do.

**Comment by mfonville** [comment]
I did check the documentation of requests concerning IPv6 and it should (unless they have a bug...) iterate over all DNS entries, both IPv4 and IPv6 before failing and raising an exception.
But for an unknown reason when running it in flexget, it already fails after iterating only on the IPv6 entry/entries.

I can reproduce this bug consistently (my new ISP has a broken IPv6 setup...) so clearly requests/flexget is not able to correctly handle the situation and fallback to IPv4 like wget does.
