### ISSUE TITLE
Trakt_watched cache ignored if "No watched data returned from trakt"

### ISSUE THREAD

**Issue by shotfirer** [Flexget/Flexget#2356]
### Expected behaviour:
If Flexget can't connect to Trakt or can't get a data for some reason, use cached data from previous successful session. Do not download any watched episode based on cached data.

### Actual behaviour:
Cache not used, watched episode downloaded.
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-03-27 15:14 WARNING  flexget.components.trakt.api_trakt RARBG           No watched data returned from trakt.
```
</details>

### Additional information:

- FlexGet version: 2.20.16
- Python version: 3.6.7
- Installation method: pip, global
- Using daemon (yes/no): yes
- OS and version: ARMBIAN 5.75 (Ubuntu 18.04)

**Comment by cvium** [comment]
Watched data is only cached for 15 mins.

**Comment by shotfirer** [comment]
Could it be preserved until the next successful retrieval (as a backup)? At least optional.
