### ISSUE TITLE
readme: git virtualenv doc: maybe recommend python 3 and venv?

### ISSUE THREAD

**Issue by Niluge-KiWi** [Flexget/Flexget#2376]
In the README (and in https://flexget.readthedocs.io/en/latest/develop/index.html) the instructions to run flexget from git recommend to use `virtualenv`, but in python3 there is a native `venv`: maybe these docs could be updated to recommend use python3 and `venv` ?

**Comment by gazpachoking** [comment]
Sounds like a good plan. Want to send us a pull request?
