### ISSUE TITLE
Critical error during check when using variable

### ISSUE THREAD

**Issue by BHMath** [Flexget/Flexget#2379]
### Expected behaviour:
Checking my config file when a $var is inside should not throw a critical error and validate it. Information taken from [https://flexget.com/Plugins/--cli-config](https://flexget.com/Plugins/--cli-config)

### Actual behaviour:
When I check my config it throws a critical error

### Steps to reproduce:
- Step 1: create the most simple task with var using the sign dollar like just below
- Step 2: run `flexget check`
- Step 3: error happens

#### Config:
```
tasks:
  htmltask:
    html: 
      url: '$url'
    exec: 
      - echo {{url}}    
```

#### Log:
```
$ flexget check
There is a FlexGet process already running for this config, sending execution there.
2019-04-30 12:37 VERBOSE  check                         Checking config file `/config/config.yml`
2019-04-30 12:37 VERBOSE  check                         Pre-checked 6 configuration lines
2019-04-30 12:37 CRITICAL check                         [/tasks/htmltask/html/url] u'$url' is not a u'url'

```

### Additional information:

- FlexGet version: 2.20.18
- Python version:Python 2.7.14
- Installation method: Docker with cpoppema/docker-flexget image
- Using daemon (yes/no): I think so
- OS and version: Alpine Linux 3.7 inside a docker container hosted on headless Ubuntu 16.04.2 LTS

**Comment by paranoidi** [comment]
We may have outgrown the --cli-config with better validation ... very tricky to resolve. Maybe a toplevel configuration section like 

```
cli_config_defaults:
  url: http://localhost
```

or require them even with `check` ..

**Comment by gazpachoking** [comment]
Another possibility is migrating to jinja, similar to variables plugin. That would allow something like:
```
html:
  url: {-- url|default('http://defaultsite.com') --}
```
I sorta like the idea of moving to jinja, although I'm not wild about that as a solution for the config validation problem.

Maybe cli-config  could disable any tasks that don't have their values specified on the command line?

**Comment by paranoidi** [comment]
That jinja2 is better solution than what I proposed, disabling sounds best if we can support that via apis and everything ... possibly not?
