### ISSUE TITLE
Allow directory creation in move and copy plugin

### ISSUE THREAD

**Issue by BHMath** [Flexget/Flexget#2380]
This is more a suggestion than a bug. I'm not sure if i should post it here or somewhere else, please tell me if I'm wrong.

If you set a path "to" in the move plugin that doesn't exist nothing happens. Maybe with an option the path could be created before moving the file only if it doesn't exists

I imagine something like this :
```
move:
  to: /non/existing/path
  dir_create: true
```

**Comment by gazpachoking** [comment]
I peeked in to this. It looks like move/copy plugin will already create directories if they don't exist. Schema validation however won't work if you specify a non-existing directory. This is to help with typos when you are configuring.
The exception to this is if you use jinja in your destination path, such that it's a dynamic location. Then only the static part of the path must exist. For example if you have `to: /somwhere/{{somedynamicfolder}}` only `/somewhere` must exist, the dynamic directory will be created when the file is moved/copied.
I'm inclined to leave this behavior as-is, as it would only ever be a one time folder creation you have to do manually when setting up your config.

**Comment by BHMath** [comment]
Wow ! Thanks for this answer got to try it ;)
