### ISSUE TITLE
Unable to donate

### ISSUE THREAD

**Issue by qriff** [Flexget/Flexget#2404]
https://flexget.com -> https://gratipay.com/flexget = 404

> May 11, 2018 - Gratipay is shutting down at the end of the year 2017.

https://gratipay.news/the-end-cbfba8f50981

**Comment by gazpachoking** [comment]
Appreciate the thought! I've removed the defunct gratipay link. I'll update the section if we find a new means of donating. In the mean time the only way to donate is to help out on forums/chat/bug reports/pull requests. 😃
