### ISSUE TITLE
Notifications via Slack plugin using attachments are not working as expected with Python 3.7.3

### ISSUE THREAD

**Issue by gitraar** [Flexget/Flexget#2406]
### Expected behaviour:

Slack notifications for movie downloads using attachments should appear, as they did with Python 2, like in the picture linked below:

https://imgur.com/Orx1YSE

### Actual behaviour:

Notifications appear like the one in the picture linked below:

https://imgur.com/61vBtSX

### Steps to reproduce:

Download any movies while having Slack notifications with attachments.

#### Config:

Relevant part of the configuration:

```
    notify:
      entries:
        via:
          - slack:
              web_hook_url: '{? slack.webhook ?}'
              message: "{{ imdb_name }}"
              icon_emoji: movie_camera
              attachments:
                - title: "{{ imdb_name }} ({{ imdb_year }})"
                  image_url: "{{ tmdb_posters | first }}" # better quality
                  title_link: "{{ imdb_url }}"
                  fallback: "{{ imdb_name }} ({{ imdb_year }})"
                  text: "{{ imdb_plot_outline }}"
                  color: "#e67e22"
                  footer: "{{ task }}"
                  footer_icon: "https://avatars2.githubusercontent.com/u/17483320?s=400&v=4"
                  fields:
                    - title: Runtime
                      value: "{{ tmdb_runtime }} mins"
                      short: true
                    - title: Score
                      value: "{{ imdb_score }}"
                      short: true
                    - title: Genres
                      value: "{{ imdb_genres | join(', ') | title }}"
                      short: true
                    - title: Rating
                      value: "{{ imdb_mpaa_rating }}"
                      short: true
                    - title: Cast
                      value: >
                        {% for key, value in imdb_actors.iteritems() %}{{value}}{% if not loop.last %}, {% endif %}
                        {% endfor %}
                      short: false
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-06-02 06:34 VERBOSE  task          upgrade_movies  ACCEPTED: `Captain Marvel 2019 1080p BluRay DTS x264-Du ` by upgrade plugin because upgraded quality
2019-06-02 06:34 VERBOSE  api_trakt     upgrade_movies  Received 198 records from trakt.tv for user XXXX from endpoint watched/movies
2019-06-02 06:34 INFO     download      upgrade_movies  Downloading: Captain Marvel 2019 1080p BluRay DTS x264-Du
2019-06-02 06:34 VERBOSE  details       upgrade_movies  Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2019-06-02 06:34 INFO     rtorrent      upgrade_movies  Captain Marvel 2019 1080p BluRay DTS x264-Du  added to rtorrent
2019-06-02 06:34 ERROR    notify        upgrade_movies  Error rendering slack plugin config field attachments/0/fields/2/value: (TypeError) 'NoneType' object is not iterable
2019-06-02 06:34 VERBOSE  notify        upgrade_movies  Successfully sent a notification to `slack`

```
</details>

### Additional information:

- FlexGet version: 2.21.1
- Python version: 3.7.3
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 19.04

**Comment by gazpachoking** [comment]
I'm thinking this might be because imdb_genres is not populated for this movie. Perhaps if you set a default as an empty list, like so: `{{ imdb_genres | default([]) | join(', ') | title }}`

**Comment by gazpachoking** [comment]
That said, it does seem like it should continue trying to render the rest of the fields, even if there is an error with one, so there is probably some room for improvement on how this is working.

**Comment by gitraar** [comment]
It's been happening with all movies since I moved from Python 2 to Python 3. Notifications without attachments work as usual. On different movies I've seen a different error:

````
2019-05-29 01:12 ERROR    notify        download_movies Error rendering slack plugin config field attachments/0/fields/4/value: (UndefinedError) 'dict object' has no attribute 'iteritems'
````

I'll try you suggestion and check if it helps.

Thank you.

**Comment by gitraar** [comment]
I think I found the issue.

If I change imdb_actors.iteritems() to imdb_actors.items() it works again. Apparently Python 3 deprecated iteritems() or something. I'm clearly not an expert on python.

I guess the wiki on the slack plugin wasn't updated to reflect the changes from Python 2 to Python 3.

**Comment by gazpachoking** [comment]
Ahh, yes indeed, iteritems is no more in python 3. I updated the wiki page with that change now. I still think it's worth investigating a bit more, because it seems like a failure in one field should still let the other fields populate, which it didn't seem like was happening in your example.

**Comment by crawln45** [comment]
Anyway to actually tell us what failed instead of the long line of pathing to the error? Like we used to have. hey could not render {{imdb_actors}}

**Comment by gazpachoking** [comment]
Made a few changes that should improve this.
- The error message will now have the template text that failed, and put the json pointer in a debug message.
- The rest of the fields will continue to render even after one fails. This should result in improved notifications, even when bits of it fail.
