### ISSUE TITLE
Wiki page for Tarznab

### ISSUE THREAD

**Issue by l13t** [Flexget/Flexget#2430]
would be great to have wiki page with description how to configure torznab feeds in flexget.
it's merged since may, but still no info how to configure it: https://github.com/Flexget/Flexget/pull/2375

@andrasmaroy @gazpachoking @cvium

**Comment by andrasmaroy** [comment]
Slipped my mind to create the wiki page, I'll get around to it this week. Thanks for reminding!

**Comment by andrasmaroy** [comment]
Done, see https://flexget.com/Searches/torznab

**Comment by gazpachoking** [comment]
Thanks!
