### ISSUE TITLE
python3  ('>' not supported between instances of 'int' and 'str')

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2439]
python 3.6
flexget: latest

worked just fine with python2 , but not with 3 ..
`
2019-09-09 20:23 ERROR    if            Merge_Trakt_Lists Error occurred while evaluating statement `trakt_votes > '50'`. ('>' not supported between instances of 'int' and 'str')`

hapening for every task where there is "<" or ">" at least.

**Comment by snickers2k** [comment]
strange.. doesn't happen anymore

**Comment by snickers2k** [comment]
in fact the whole "if-plugin" is broken. "trakt_collected: accept" does not work neither.

**Comment by gazpachoking** [comment]
You need to remove the quotes around 50 to make it a number. i.e. `trakt_votes > 50` It wouldn't crash on python 2, but it also won't do what you expect.

**Comment by snickers2k** [comment]
oh, sorry. thank you
