### ISSUE TITLE
flexget --help requires a config file to exist

### ISSUE THREAD

**Issue by Zopieux** [Flexget/Flexget#2443]
Might be related with #1537.

### Expected behaviour:

```
$ flexget --help
usage: flexget [-V] [--test] [-c CONFIG] [--logfile LOGFILE]
               [--loglevel LEVEL] [--bugreport] [--profile [OUTFILE]] [--cron]
… (rest of the argparse help text) …
```

### Actual behaviour:

```
$ flexget --help
2019-09-23 20:50 CRITICAL manager                       Failed to find configuration file config.yml
2019-09-23 20:50 INFO     manager                       Tried to read from: /tmp, /home/zopieux/.flexget, /home/zopieux/.config/flexget
Could not instantiate manager: No configuration file found.
```

I understand that I need to create a config file, but a program `--help` *should not* be stateful or rely on the presence of a file to work. That's what most people run to start using a program.

### Additional information:

- FlexGet version: FlexGet-2.21.19-py2.py3-none-any.whl
- Python version: 3.7
- Installation method: venv, pip

**Comment by paranoidi** [comment]
@Zopieux you are absolutely right. Unfortunately our architecture is build in a way which does not make this easy.

(Manager is created by passing in a configuration file, and is responsible for loading plugins which then register arguments via events).

**Comment by rue-ieaston** [comment]
Could we create some sort of null configuration object to satisfy the dependency?

**Comment by paranoidi** [comment]
Indeed, that might be the easiest way around this
