### ISSUE TITLE
Upgrade qBittorrent WebAPI version

### ISSUE THREAD

**Issue by AvailCat** [Flexget/Flexget#2450]
### Expected behaviour:
It should able to control qBittorrent over WebAPI

### Actual behaviour:
Did nothing, qBittorrent's old API support was complete dropped in 4.2.0.

### Steps to reproduce:
- 1. Use qBittorrent 4.2.0 with qBittorrent plugin
- 2. Log report success but actual did nothing because old API was removed

See https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation for new API since 4.1.0

  
#### Log:
<details>
 <summary>(click to expand)</summary>
2019-10-04 17:14 DEBUG    qbittorrent   ourbits         Successfully connected to qBittorrent

2019-10-04 17:14 DEBUG    qbittorrent   ourbits         Added torrent file /tmp/tmpt9fy5421/4e805944e20f5389085ade323aba5146 to qBittorrent
</details>

### Additional information:

- FlexGet version: 2.21.21
- Python version: 3.7.3
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Debian 10

**Comment by gazpachoking** [comment]
This was fixed in #2525
