### ISSUE TITLE
API "PUT"  method for variables endpoint fails to update variables.yml

### ISSUE THREAD

**Issue by metaMMA** [Flexget/Flexget#2464]
### Steps to reproduce:
- Step 1: Create `variables.yml` file with only the following single line:

`a:b`

- Step 2: From terminal, execute: `curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Token TOKEN_REDACTED' -d '{"a":"c"}' 'http://localhost:5050/api/variables/'`

- Step 3: Observe output as:
`a:b`

#### Config:

```
variables: /path/to/flexget/variables.yml
web_server: yes
templates:
  dl:
    deluge: yes
....
...
...
```

#### Variables:
```
a: b
```
#### Log:
<details>
No information was added to the log after the API call.
</details>

### Additional information:

- FlexGet version: 2.21.25  
- Python version: 3.7.3
- Installation method: pip3
- Using daemon (yes/no): yes
- OS and version: Kubuntu 19.04
- Link to crash log: null

**Comment by metaMMA** [comment]
@gazpachoking was able to shed some light on this issue via the slack channel. 

It seems that the `variables.yml` acts as a 'seed' for the variables section in the flexget database, when the line `variables: /path/to/variables.yml` is included in `config.yml`.  The `PUT` method for the flexget API with the `variables` endpoint only works when the that line in `config.yml` is amended to `variables: yes` instead of the location of the `variables.yml` file.

However, using the command:

```curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Token TOKEN_REDACTED' -d @variables.json 'http://localhost:5050/api/variables/'```

results in the the variables being wiped out and replaced by the JSON payload (the `@variables.json` in the above command).

I have a very long list of variables (hundreds). So I would need to use the `GET` method on the variables first, save the output as a `variables.json` file, make the change(s), save it, then use the `PUT` method to reinstall the new variables in the database via the updated `variables.json` file.

Is it possible to use the API to simply change a single value within the variables? Or is that function not available?

**Comment by liiight** [comment]
The API only operates on the DB and not on the file. This was a design decision as to eliminate having two sources of truth.

**Comment by gazpachoking** [comment]
@liiight The new issue he was talking about is that sending a PUT replaces the entire variable store. So to update a single variable you have to do a get, modify the returned data structure, then submit the whole thing back. Maybe we should add a PATCH endpoint or something where you can send in just the variables you want updated.

**Comment by liiight** [comment]
Ah ok. I'm not sure how to do that since variables is just a json blob basically. We have no base structure for it so I'm not sure how we could add single "entity", since that entity's definition can change for each user.

**Comment by gazpachoking** [comment]
I mean, if we wanted a PATCH, it could just load the current variables, call an update on it and save it again.

**Comment by liiight** [comment]
I'm not sure how that would work. How would you join the existing data to the new payload?

**Comment by liiight** [comment]
Oh, you something like do a dict `.update()` using the new payload? Guess that could work

**Comment by gazpachoking** [comment]
Yep, a dict.update is exactly what I was thinking.

**Comment by gazpachoking** [comment]
Hmm, not sure the optimal way PATCH should work for heavily nested variables files. Would it be a recursive dict.update, or just on the first level?

**Comment by liiight** [comment]
I think first level is good enough.
Although, I maybe something like [glom](https://github.com/mahmoud/glom) would be nice here. I use it heavily at work and it's amazing for operating on nested data (among other things).

**Comment by gazpachoking** [comment]
If we want the update to work with nested data that's easy enough to do. We could also change the api interface to allow using json pointers to get/change specific nested data.

e.g. PUT /variables/some/nested/path/0

**Comment by gazpachoking** [comment]
Maybe only doing a first level update with PATCH, and adding the nested access via path is the nicest way.

**Comment by liiight** [comment]
dunno, I don't really like the path approach. I see variables as a single object, I don't really like to start manipulating it so dynamically. Also, json pointer like that via path is kinda weird to me, never saw something like out in the wild

**Comment by gazpachoking** [comment]
> I see variables as a single object

I see them as separate... variables. 😉 

I still like the path idea, but I also like keeping it simple unless we have some demand for it, so I'm good with your solution.

**Comment by liiight** [comment]
What I meant is since variables are not bound to any structure, I think the user should have the responsibility of managing it.
