### ISSUE TITLE
AniList plugin only loads the first page

### ISSUE THREAD

**Issue by Kazakuri** [Flexget/Flexget#2471]
### Expected behaviour:

Using the AniList plugin on my account (`username: Kazakuri`) should create 840 entries with completed status

### Actual behaviour:

It creates 50 entries.

### Steps to reproduce:

1. Use the AniList input plugin with an account that has more than 50 entries of a given status.
2. Observe results.

#### Config:
```yaml
    tasks:
  example:
    anilist:
      username: kazakuri
      status:
        - completed
      release_status:
        - finished
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-10-26 23:09 VERBOSE  input_cache   example          Restored entries from cache
2019-10-26 23:09 VERBOSE  details       example          Produced 50 entries.
2019-10-26 23:09 WARNING  task          example          Task does not have any filter plugins to accept entries. You need at least one to accept the entries you  want.
2019-10-26 23:09 VERBOSE  details       example          Summary - Accepted: 0 (Rejected: 0 Undecided: 50 Failed: 0)
2019-10-26 23:09 WARNING  task          example          Task doesn't have any output plugins, you should add (at least) one!
```
</details>

### Additional information:

- FlexGet version: 2.21.32
- Python version: 3.7.5
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Alpine Linux 3.10

The [query being built](https://github.com/Flexget/Flexget/blob/ea11cdccce95c6513d8be9978bdd9d0baeb88b7b/flexget/plugins/input/anilist.py#L96) wraps the `MediaList` type with the `Page` type, but by design the `Page` type limits the response to 50 entries.

#### Querying Each Page

You can query the number of pages in the same query and use that to iterate over all the available pages in a loop.

#### Using MediaListCollection and Querying Each Chunk

Instead of using `Page` With `MediaList`, you can query with `MediaListCollection` instead to retrieve up to 500 entries per chunk.

**Comment by BrutuZ** [comment]
The plugin fetched all 1047 entries. However, the task ran out of memory (8GB system) and crashed trying to save that many entries with ~16 fields at once to the cache.

---

Out of mere curiosity tho, what's your use case for feeding these types of entries (Finished + Completed)?

**Comment by Kazakuri** [comment]
Ah, I simplified the config when I created the issue, but I was pulling my list into Sonarr with Flexget to get a more automated collection management. 

Most of those entries are already downloaded, so it's more of a completeness thing.
