### ISSUE TITLE
qBittorrent can‘t set label and maxupspeed

### ISSUE THREAD

**Issue by tyhunter** [Flexget/Flexget#2506]
### Expected behaviour:
Auto add label and set max upload speed

### Actual behaviour:
I was according to those code in this page(https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/qbittorrent.py) , add the label and maxupspeed , but it didn't work 

### Steps to reproduce:
- Step 1: ...

#### Config:
```yaml
Paste FULL config and remove any personal info if config is too long, attach the file to the ticket.
If issue is with a single task, you can get get resulting configuration by running:
  flexget execute --task <NAME> --dump-config
Make sure to redact any personal information (passwords, api keys, etc) !
```
      qbittorrent:
      path: /root/download/
      port: 8080
      maxupspeed: 10
      label: BTSCHOOL
      username: admin
      password: "adminadmin"

#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version:2.21.35
- Python version:Python 3.5.3
- Installation method:python venv
- Using daemon (yes/no):no
- OS and version:debian 9 
- Link to crash log:

**Comment by pospqsjac** [comment]
What is your qBittorrent version?  Version below v3.2.0 do not support setting labels or max up/down speed.

**Comment by tyhunter** [comment]
the qb version is 4.1.9.1

pospqsjac <notifications@github.com> 于 2019年12月11日周三 23:48写道：
