### ISSUE TITLE
qBittorrent 4.2.0 can't work

### ISSUE THREAD

**Issue by lllluqu** [Flexget/Flexget#2522]
Hi
  I've upgrade to qBittorrent 4.2.0 and flexget can't add new tasks to qBittorrent.
  
FlexGet version: 3.0.11
Python version: 3.7.5

**Comment by liiight** [comment]
Please add more information, like config, error and etc

**Comment by gazpachoking** [comment]
Looks like there may have been some API changes with the latest version of qBittorrent. Not much more info, but some more discussion on forum
https://discuss.flexget.com/t/flexget-not-working-with-qbittorrent-v4-2/4921
https://discuss.flexget.com/t/qbittorrent-plugin-does-not-work/4929

**Comment by lllluqu** [comment]
Yes Flexget report no error and added torrents to qBittorrent normally,
but there's no torrents be added at qBittorrent Clients

**Comment by liiight** [comment]
I'll take this, I'm using qbitorrent myself
