### ISSUE TITLE
qBittorrent plugin stopped working after update

### ISSUE THREAD

**Issue by etakpte** [Flexget/Flexget#2554]
### Expected behaviour:
qBittorent plugin to work with verify_cert: False

### Actual behaviour:
qBittorrent plugin doesnt work anymore. Probably check_api_version introduced in #2525 also needs to consider verify_cert value

### Steps to reproduce:
- Step 1: update to latest flexget
- Step 2: put verify_cert False in config

#### Config:
```yaml
     qbittorrent:                                                                                           
      port: 9091
      use_ssl: True                                                                                            
      verify_cert: False
```
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-01-02 19:17:48 CRITICAL plugin        task1           Error when trying to send request to qBittorrent: HTTPSConnectionPool(host='localhost', port=9091): Max retries ex
ceeded with url: /api/v2/app/webapiVersion (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed'
)])")))
```
</details>

### Additional information:

- FlexGet version: 3.0.30
- Python version: 3.7
- Installation method: pip
- Using daemon (yes/no): yes
- qBittorrent v4.1.5

**Comment by BCITMike** [comment]
Plugin works when https disabled in QB's configuration, but that isn't a long term workaround.

This error happens even with a valid cert (valid being: matches hostname, valid dates, chrome verifies cert with lock. It's a Let's Encrypt cert). Probably means I need to go through the hassle of setting up a reverse nginx proxy instead of QB's built in certificates.

Oof. Thought I found the last piece in my automation until running into this bug. Was disappointed to run into this and realize I need to switch to another solution, setup reverse proxy or else disable https.  

FlexGet version: 3.1.42
Python version: 3.6
Installation method: pip
Using daemon (yes/no): cron
qBittorrent v4.2.0alpha2

**Comment by BCITMike** [comment]
Ok, even though there still appears to be a bug in that it verifies the certificate regardless of verify_cert: False, the problem looks to be on the user side in the certificates.

I am using Let's Encrypt certificate that gets saved as /home/user/.config/qBittorrent/WebUICertificate.crt

I tried updating ca-certificates, adding my certificate to the ssl anchors dir, and no luck. I did find that if I ran curl against my qbittorrent address, I'd get:

```
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

So I went to https://letsencrypt.org/certificates/ and appended the current Intermediate and Root certificates to my WebUICertificate.crt file, restarted qbittorrent, and then curl no longer whined and dumped a bunch of html.  So then I executed flexget, and it successfully added the torrent to qbittorrent.

So this will probably happen when qbittorrent is using built in https, whether self-signed or LE, but not likely to happen with a reverse proxy that has support for supplying a chains file (whereas QB doesn't).

**Comment by gazpachoking** [comment]
I think I fixed the initial reported bug where verify_cert setting was getting ignored. Don't have qbittorrent though, would be nice if someone verified.

**Comment by etakpte** [comment]
working fine for me.
thanks
