### ISSUE TITLE
Problem with dependencies in Qnap

### ISSUE THREAD

**Issue by ciltocruz** [Flexget/Flexget#2572]
Hello.

I have tried to update Flexget to the latest version in my Qnap and since version 3.0.28 I cannot update.

I think there are new dependencies that Qnap does not have in its packages but I am not sure what this is.

My dependency manager in Qnap is Entware, which does not include development packages: https://github.com/Entware/Entware/wiki

My log: http://dpaste.com/3CWN3HG

- FlexGet version: 3.0.28
- Python version: pip 19.3.1 from python 3.7
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Qnap QTS 4.4.1

Thanks!

**Comment by gazpachoking** [comment]
Yeah, we added some new dependencies that are causing problems on some systems. We are going to remove them again. Tracking this in #2571 
Thanks for the report!
