### ISSUE TITLE
Flexget fails on daemon startup if CWD doesn't exist

### ISSUE THREAD

**Issue by joat42** [Flexget/Flexget#2600]
Ran into a funny problem that had me scratching my head for a couple of minutes before I deduced the problem. It seems flexget doesn't have any exception-handling for when os.getcwd() fails.

It's trivial, but a sanity-check of cwd on startup may be a good thing.

Steps to reproduce:
- Create a dummy-folder
- Set CWD to dummy-folder
- Delete dummy-folder
- Run flexget daemon start

Host-info:
- Centos Community 6.10.0 Final
- Python 3.6.9
- Flexget 3.1.21

[flexget.log](https://github.com/Flexget/Flexget/files/4171701/flexget.log)

**Comment by liiight** [comment]
Not sure there's anything to do about this, as the import that crashes is part of cherrypy.
