### ISSUE TITLE
markupsafe 1.0 throws an error

### ISSUE THREAD

**Issue by greenaar** [Flexget/Flexget#2622]
### Expected behaviour:

`pip install flexget` should install flexget.

### Actual behaviour:
14:59:49    Downloading MarkupSafe-1.0.tar.gz (14 kB)
14:59:49  [91m    ERROR: Command errored out with exit status 1:
14:59:49       command: /opt/flexget/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ewpbt6pd/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ewpbt6pd/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ewpbt6pd/markupsafe/pip-egg-info
14:59:49           cwd: /tmp/pip-install-ewpbt6pd/markupsafe/
14:59:49      Complete output (5 lines):
14:59:49      Traceback (most recent call last):
14:59:49        File "<string>", line 1, in <module>
14:59:49        File "/tmp/pip-install-ewpbt6pd/markupsafe/setup.py", line 6, in <module>
14:59:49          from setuptools import setup, Extension, Feature
14:59:49      ImportError: cannot import name 'Feature'
14:59:49      ----------------------------------------

(followed by install failure)
### Steps to reproduce:
`pip install flexget`

### Additional information:

A quick search shows this relevant issue : https://github.com/pallets/markupsafe/issues/57, as such it may be as simple as incrementing the version in use.

**Comment by paranoidi** [comment]
confirmed

**Comment by liiight** [comment]
Does upgrading setuptools help?

**Comment by gazpachoking** [comment]
That markupsafe ticket says we need latest markupsafe.

**Comment by mgilardi** [comment]
Updating MarkupSafe to 1.1.1 didn't work for me, but downgrading Setuptools did.

`pip3 install setuptools==45.2.0`

This version worked for me.

**Comment by paranoidi** [comment]
I tested with clean py3.7 venv and it failed. If users experience crash on install without upgrading setuptools something is horribly wrong.
