### ISSUE TITLE
Issue: Could not import pystray: Bad display name ""

### ISSUE THREAD

**Issue by 00lex** [Flexget/Flexget#2633]
Since 3.1.38 until latest version 3.1.41 I get the following error. 

> 2020-03-21 01:54:43.751 | WARNING  | flexget.tray_icon:<module>:19 - Could not import pystray: Bad display name ""

I've downgraded to last version 3.1.37 without this error

**Comment by wiserain** [comment]
seems not critical, but would be nice if we have an option to disable for headless use like running in docker.

**Comment by liiight** [comment]
This was introduced as part of a new tray icon feature. Level should be a debug message in latest version and its completely harmless. 

I'll improve the message to be a bit more informative but adding logic to disable the tray icon completely would raise complexity while not solving any issues.

**Comment by liiight** [comment]
Added ability to disable tray icon by adding `--disable-tray-icon` to `daemon start`

**Comment by paranoidi** [comment]
@liiight is that argument required in order not to crash? That would suuuck :)

**Comment by liiight** [comment]
AFAIK, it doesn't crash currently, just throws that log message. I'll encapsulate all the import though under this option in order not to even show that

**Comment by Xake** [comment]
Oh, it,s a crasher if you have gtk3 installed.
```
[flexget@liten ~]$ ./bin/flexget --version
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
3.1.42
You are on the latest release.
```

Without gtk3 installed:
```
[flexget@liten ~]$ ./bin/flexget daemon start
2020-03-22 09:31:40.583 | DEBUG    | flexget.tray_icon:<module>:20 - Could not import pystray: Bad display name ""
2020-03-22 09:31:47 INFO     scheduler                     Starting scheduler
```

With gtk installed:
```
[flexget@liten ~]$ ./bin/flexget daemon start
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
2020-03-22 09:36:48 INFO     scheduler                     Starting scheduler

(flexget:451802): Gtk-CRITICAL **: 09:36:48.053: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(flexget:451802): Gtk-CRITICAL **: 09:36:48.053: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(flexget:451802): Gtk-CRITICAL **: 09:36:48.054: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
```

**Comment by liiight** [comment]
Yikes. Will handle asap, thanks.

**Comment by liiight** [comment]
@Xake can you paste debug logs of that crash please?

**Comment by liiight** [comment]
using `--disable-tray-icon` should now completely disable it. 
Please let me know if it works

**Comment by paranoidi** [comment]
We should not crash or have shitty UX without arbitrary arguments.

**Comment by jbalyork** [comment]
I've been meaning to write my own downloader script for a while. This might just push me over the edge. This level of bloat is unacceptable.

**Comment by liiight** [comment]
@jbalyork are you under the impression that someone owes you anything? Are you aware that this is an open source project? Your comments and tone is what is unacceptable and you are more than welcome to get lost if you have a problem with anything

**Comment by jurgenweber** [comment]
we appreciate your efforts @liiight

**Comment by jbalyork** [comment]
MY tone? Christ. I hope your day is as pleasant as you are.
