### ISSUE TITLE
Dependencies on non pure Python modules

### ISSUE THREAD

**Issue by nbarrientos** [Flexget/Flexget#2651]
Hi,

Sorry for [x-posting](https://discuss.flexget.com/t/dependencies-on-non-pure-python-modules/5086). This is kind of a development issue so it might fit here better than in the forum. Feel free to just close this and reply on Discourse.

When upgrading Flexget I stumbled upon the fact that now it depends on Pillow, as per:

https://github.com/Flexget/Flexget/pull/2621

My Flexget runs on an embedded aarch64 device so every time you add a dep on a module that links against C libraries (Pillow depends on zlib and libjpeg) I have to cross compile the necessary native extensions, distribute them etc. Either that or manually installing a skimmed `requirements.txt` and finally installing Flexget passing `--no-dependencies` to `pip install`.

Does adding a tray icon justify this hassle for users? No saying that’s wrong of course, just trying to bring to your attention this use case and the potential annoyance for users.

Could perhaps these things be made optional at install/build time by relaxing the hard dependency?

Thanks.

**Comment by liiight** [comment]
I totally agree that the tray icon does not justify this hassle. I'll make the neccesary changes.

**Comment by nbarrientos** [comment]
Many thanks!
