### ISSUE TITLE
Flexget install using python 3.x fails while trying to install "Pillow"

### ISSUE THREAD

**Issue by alirz1** [Flexget/Flexget#2654]
when i try to install flexget on a synology Nas, using Python 3.x installed via entware.
It fails while trying to install pillow. Looks like that dependency on Pillow is still there?

Im using this article for the isntallation of flexget:
https://flexget.com/InstallWizard/SynologyNAS/PythonPackage

Some additional info if you would on my issue. Last post on this page at the moment
https://github.com/python-pillow/Pillow/issues/4530

**Comment by liiight** [comment]
We have an unrelated issue which prohibits us from releasing a new version. The dependency changes will be a part of the next version.

**Comment by liiight** [comment]
Release is out now, fixed in v3.1.51

**Comment by alirz1** [comment]
Thanks. Looks to be fixed.
