### ISSUE TITLE
Choose magnet over .torrent 

### ISSUE THREAD

**Issue by mrtntome** [Flexget/Flexget#2708]
When searching using Argenteam plugin, .torrent links are broken but magnets are not.
I can't make flexget choose magnet over .torrent.

**Comment by Kahana82** [comment]
It is possible to convert .magnet links to .torrent files by using [convert_magnet](https://flexget.com/Plugins/convert_magnet) in your task (or template):
convert_magnet: yes
download: /path/to/your/monitored/folder/
