### ISSUE TITLE
webUI cost too much time on version query

### ISSUE THREAD

**Issue by xmt328** [Flexget/Flexget#2725]
### Expected behaviour:

query lastest version on background

### Actual behaviour:

visit http://*/api/server/version in api/core/server.py

it will query https://pypi.org/pypi/FlexGet/json for  lastest version info

it cost 20+ seconds on loading page

p.s. maybe it's fast for most country, but it's hard to connect to pypi in China

### Steps to reproduce:
- Step 1: open webUI on any browser, it will loading 20s+

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 8080
  web_ui: yes
```

### Additional information:

- FlexGet version: 3.1.70
- Python version: 3.7.3
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: debian 10.2

**Comment by liiight** [comment]
Good point. @kristenmills maybe we can make the option to compare to latest version clickable?

**Comment by kristenmills** [comment]
We currently use the version endpoint to check whether you are already logged in which is why the first request to version blocks page load. Probably should make just make a dedicated endpoint that's cheaper for that purpose.

**Comment by kristenmills** [comment]
This should be fixed in the next version of flexget.
