### ISSUE TITLE
Flexget website cert expired

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#2735]
### Expected behaviour:

load site normally

### Steps to reproduce:
- Step 1: open https://flexget.com in a modern browser
- Step 2: get invalid cert error due to expired Let's Encrypt cert

### Additional information:

is the autorenewal broken?

**Comment by gazpachoking** [comment]
Whoops, yep. Migrated forum to new server and old server autorenewal is broken. Should be renewed now.
