### ISSUE TITLE
I want to use WebSocket to connect to my aria2 service.

### ISSUE THREAD

**Issue by upupoo108** [Flexget/Flexget#2743]
For some reason, I can only use WebSocket to connect to my aria2 service.But flexget aria2 plugin seems to be no this option.

What should I do to solve this problem?

**Comment by ksurl** [comment]
Are they running on the same host? Or same network?

**Comment by upupoo108** [comment]
> 它们是否在同一主机上运行？还是同一个网络？

Different host.

**Comment by upupoo108** [comment]
how can I use "ws://" to connet aria2 service?

**Comment by ksurl** [comment]
Using the ip and port aria is running on doesn't work?

**Comment by upupoo108** [comment]
> Using the ip and port aria is running on doesn't work?

yes,because my aria2 running in colab,I can't use http to connect,I use ngrok.
I can go through aria2NG to connect,use "ws://"

**Comment by upupoo108** [comment]
I wish Flexget Aria2 plugin had more ways to connect aria2 service,like ws://

**Comment by ksurl** [comment]
How about ssh tunnel? Autossh can do this. Then it looks to flexget like it is on localhost

**Comment by upupoo108** [comment]
> How about ssh tunnel with port forward? Autossh can do this. Then it looks to flexget like it is on localhost

I don't know how to do it, can you have a try?
https://github.com/biplobsd/OneClickRun
https://github.com/hmglife/aria2-colab

**Comment by upupoo108** [comment]
I modified the plug-in code and tried to connect, but the following error occurred.
CRITICAL aria2         Anime           Socket connection issue with aria2 daemon at ws://0743be323be1.ngrok.io:80/jsonrpc: unsupported XML-RPC protocol.
So sad,I may need to do more work to understand how it works.

**Comment by evoblicec** [comment]
> I modified the plug-in code and tried to connect, but the following error occurred.
> CRITICAL aria2 Anime Socket connection issue with aria2 daemon at ws://0743be323be1.ngrok.io:80/jsonrpc: unsupported XML-RPC protocol.
> So sad,I may need to do more work to understand how it works.

It seems you are trying XML RPC over JSON RPC url. Maybe try `ws://0743be323be1.ngrok.io:80/rpc` instead
[https://aria2.github.io/manual/en/html/aria2c.html#sample-xml-rpc-client-code](https://aria2.github.io/manual/en/html/aria2c.html#sample-xml-rpc-client-code)

**Comment by upupoo108** [comment]
> > 我修改了插件代码并尝试连接，但是发生以下错误。
> > aria2守护程序在ws：//0743be323be1.ngrok.io：80 / jsonrpc上发生严重的aria2动漫套接字连接问题：不支持的XML-RPC协议。
> > 太可惜了，我可能需要做更多的工作才能了解它的工作原理。
> 
> 看来您正在尝试通过JSON RPC URL进行XML RPC。也许尝试`ws://0743be323be1.ngrok.io:80/rpc`改用
> https://aria2.github.io/manual/en/html/aria2c.html#sample-xml-rpc-client-code

2020-10-07 03:57:07 CRITICAL aria2         Anime           Socket connection issue with aria2 daemon at ws://81ab0f77d344.ngrok.io:6800/rpc: unsupported XML-RPC protocol
2020-10-07 03:57:07 WARNING  task          Anime           Aborting task (plugin: aria2)
In addition to changing links, what adjustments do I need to make to the plugin aria2?
I can connect through aria2Ng,but I don't not how it work.
