### ISSUE TITLE
Conflict dependency with python-telegram-bot

### ISSUE THREAD

**Issue by wiserain** [Flexget/Flexget#2749]
For the latest release of python-telegram-bot [v13.0](https://github.com/python-telegram-bot/python-telegram-bot/releases/tag/v13.0), they explicitly set the minimum requirement for pytz [here](https://github.com/python-telegram-bot/python-telegram-bot/pull/2121) to be able to use a new attribute. See related issue [here](https://github.com/python-telegram-bot/python-telegram-bot/pull/2121)

My docker build stays with python-telegram-bot v12.8 for now, but would be great to handle this by Flexget, e.g. fixing python-telegram-bot version or bump the minimum version of pytz compatible with the latest telegram-bot.

Thanks!

### Additional information:

- FlexGet version: 3.1.72
- Python version: 3.8
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

**Comment by malomehi** [comment]
Is it planed to update the pytz dependency to version 2020.x?

**Comment by marcelrv** [comment]
I did an upgrade with `pip install -U pytz` so far did not see any negative effects except the warning.
Before flexget did not want to start, after the upgrade at least it was starting again

**Comment by malomehi** [comment]
Also if you upgrade `python-telegram-bot` and then you upgrade `FlexGet` you get:
`ERROR: python-telegram-bot 13.0 requires APScheduler==3.6.3, but you'll have apscheduler 3.5.0 which is incompatible.`

**Comment by liiight** [comment]
I'm looking into bumping version of pytz now. This is an issue since this is a non-required dep, since telegram is a non-core plugin.

@gazpachoking maybe we can add a flexget[extra] installation that will handle all/some plugin deps with the ability to lock them?

**Comment by gazpachoking** [comment]
@liiight Yeah, I've been trying to figure out some good way to handle this but I'm not exactly sure what would be best. If we could at least get a workflow which alerted us when our pinned deps conflicted with extra deps that would be nice. I was trying to figure something out with scripting pip-compile with multiple `in` files, but that doesn't work out so well due to it not preserving markers, which means I have to manually edit the generated requirements to remove the windows specific stuff every time.

**Comment by gazpachoking** [comment]
@liiight Ooh, this looks promising, I've been waiting for movement from poetry to allow building with locked deps, I think it could help us simplify the whole workflow if it gets merged. https://github.com/python-poetry/poetry/pull/3341

**Comment by liiight** [comment]
@gazpachoking looks good 🤞

**Comment by malomehi** [comment]
Is there a plan to bump `python-telegram-bot` to any version >=13.0 at any time soon?

**Comment by BrutuZ** [comment]
> Is there a plan to bump `python-telegram-bot` to any version >=13.0 at any time soon?

Any chance you're asking about the third-party docker image (https://github.com/wiserain/docker-flexget/) since `python-telegram-bot` is not installed by Flexget?

**Comment by private-tracker** [comment]
I have the same issue.

**Comment by private-tracker** [comment]
See https://github.com/python-telegram-bot/python-telegram-bot/issues/2758.
