### ISSUE TITLE
Incompatible pytz version

### ISSUE THREAD

**Issue by houchang1991** [Flexget/Flexget#2752]
flexget 3.1.74 requires pytz 2017.x version, but it can't work when loading plugins: 
```
AttributeError: module 'pytz' has no attribute 'BaseTzInfo'
```
only after i uninstall pytz 2017.x version, and install the latest version pytz 2020.x, flexget finally starts up, but show a incompatible 
 warning.

**Comment by BrutuZ** [comment]
Dupe of #2749 ?

**Comment by houchang1991** [comment]
yes, seem to be the same
