### ISSUE TITLE
configure_series blacklist option

### ISSUE THREAD

**Issue by strikersh** [Flexget/Flexget#2753]
configure_series should have an option for disabling certain series.
the use case is for user of anilist/kitsu/mal/TheTVDB who want to set specific settings for a series.

if the entry is both in series and configure_series then flexget fail

**Comment by BrutuZ** [comment]
Where's the issue template with relevant config segment and log output?
The interaction between `series` and `configure_series` does work for that purpose. I use it myself on maybe 4 tasks and the specific series settings work as intended, all Flexget does is give a soft-warning when it finds a show on both plugins

**Comment by strikersh** [comment]
just check my config and I had other issues, but I think it should be a possibilities if someone don't want to download a serie from it's list

**Comment by BrutuZ** [comment]
There are ways to accomplish it already, I can think of a couple from the top of my head, there's likely more.

- "Unreasonable" requirement to aforementioned `series` plugin
```yaml
series:
  - That Unacceptable Show:
      quality: 368p bluray h265 dts
```

- Add the title to a `if` plugin reject entry
```yaml
if:
  - "'That Unacceptable Show' in title": reject
```

**Comment by gazpachoking** [comment]
You could also use the [from_task](https://flexget.com/Plugins/from_task) plugin to modify your list before feeding it into configure_series.
```yaml
tasks:
  my modified series list:
    my_anime_list: theconfig
    accept_all: yes
    regexp:
      reject:
        - that unacceptable show
  real task:
    configure_series:
      from:
        from_task: my modified series list

**Comment by paranoidi** [comment]
or explicitly configure that one show with "parse_only" option
