### ISSUE TITLE
crash w/ transmission plug - NameError: name 'partial' is not defined

### ISSUE THREAD

**Issue by jhelmer1976** [Flexget/Flexget#2779]
Seeing a crash with the latest transmission plugin, the fix seems trivial in my case.

Crash:
 tail crash_report.2020.11.07.180031705399.log

NameError: name 'partial' is not defined
Traceback (most recent call last):
  File "/home/grimace/flexget/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "/home/grimace/flexget/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/home/grimace/flexget/flexget/plugins/clients/transmission.py", line 616, in on_task_output
    start_torrent = partial(self.client.start_torrent, [torrent_info.id])
NameError: name 'partial' is not defined

change:

grimace@rodent:~/flexget$ git diff "/home/grimace/flexget/flexget/plugins/clients/transmission.py"
diff --git a/flexget/plugins/clients/transmission.py b/flexget/plugins/clients/transmission.py
index c200265e6..e9fe64eab 100644
--- a/flexget/plugins/clients/transmission.py
+++ b/flexget/plugins/clients/transmission.py
@@ -6,6 +6,7 @@ from fnmatch import fnmatch
 from netrc import NetrcParseError, netrc
 from time import sleep
 from urllib.parse import urlparse
+from functools import partial, wraps

 from loguru import logger

**Comment by ksurl** [comment]
Should be fixed in next release. Recommend roll back until you can update. There's a couple other issues already open for this

**Comment by ksurl** [comment]
3.1.86 with fix is out!

**Comment by jhelmer1976** [comment]
Seems to work now, thx.
