### ISSUE TITLE
discuss.flexget.com down for several days now

### ISSUE THREAD

**Issue by lamski** [Flexget/Flexget#2813]
The discussion forum has been unreachable for the past couple of days.
Just wanted the devs to know.

**Comment by ksurl** [comment]
They're aware in the slack and discord chat. The host is having issues. For now the link on the home page is now pointing https://github.com/Flexget/Flexget/discussions.

**Comment by ksurl** [comment]
it seems it's not coming back. so github discussions will be the place going forward for asking for help that may or may not be a bug
