### ISSUE TITLE
Color range(HDR) as a quality component?

### ISSUE THREAD

**Issue by denngie** [Flexget/Flexget#2835]
Hi, now that HDR is becoming more and more common, is it time to create a new component called something like color range? With the following options ordered in best to worse:

- Dolby Vision
- HDR10+
- HDR10
- 10bit (move existing 10bit from codecs where it does not belong)
- 8bit (assumed default)

Some relevant links: [Wikipedia](https://en.wikipedia.org/wiki/High-dynamic-range_video) and [scenerules for x265](https://scenerules.org/t.html?id=2020_X265.nfo) and [scenerules for web rips](https://scenerules.org/t.html?id=2020_WDX.nfo)

**Comment by frankyw** [comment]
Nice change @soloam 👍
