### ISSUE TITLE
Episode regex needs to match against sanitized entry

### ISSUE THREAD

**Issue by teemuatlut** [Flexget/Flexget#2865]
### Expected behaviour:

Entry `[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv` accepted by Series plugin
as per instructed by configured ep_regexp `S(\d) - (\d\d)`.

### Actual behaviour:

Episode number is not recognized and therefore Flexget tries and succeeds with season_pack.
**This is caused by a splitting step** before the remaining data string is passed to the `parse_episode` method. It removes the hyphen character from the string but what would've been expected to still be there for matching against the user defined episode regex.

My solution for now is to define the regex without a hyphen and that seems to match against correct entries.
Whether this is a documentation issue or a code issue is up to you. I hope this may help someone as it wasn't clear for me.

---

### Steps to reproduce:
1. Set ep_regexp for a show as follows: `S(\d) - (\d\d)`
1. Execute against an rss feed that contains a show which is marked by <series name> S2 - 123 ...

#### Config:
```yaml

--- config from task: rssAnime
deluge:
  magnetization_timeout: 30
  password:
  username:
rss: https://nyaa.si/?page=rss&q=720p+%28SubsPlease%7CErai-raws%29&c=1_2&f=0
series:
  720p+:
    - Dr. Stone:
        ep_regexp: S(\d) - (\d\d)
        identified_by: ep
        target: 720p+
set:
  add_paused: 0
  path: /mnt/Downloads/DLTV/{{ series_name }}
  ratio: 5
template:
  - myAnime
  - myDeluge

---

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-02-25 21:03:17 DEBUG    parser_internal rssAnime        Parsing series: `[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv` kwargs: {
	'name': 'Dr. Stone',
	'identified_by': 'ep',
	'alternate_names': [],
	'name_regexps': [],
	'strict_name': False,
	'allow_groups': [],
	'date_yearfirst': None,
	'date_dayfirst': None,
	'special_ids': [],
	'prefer_specials': None,
	'assume_special': None,
	'ep_regexps': ['S(\\d) - (\\d\\d)'],
	'date_regexps': [],
	'sequence_regexps': [],
	'id_regexps': []
}
2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        name: dr stone data: [SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv
2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        NAME SUCCESS: ^(?:(?:\[[^\[\]]*\])|(?:HD.720p?:)|(?:HD.1080p?:)|(?:HD.2160p?:))?(?:[^\w&]|_)*(Dr(?:[^\w&]|_)*Stone)(?:\b|_)(?:[^\w&]|_)* matched to [SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv
2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        data stripped:  s2 - 07 (720p) [00f5bce4].mkv [subsplease] 
2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        parsing quality ->
2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        quality detected, using remaining data ` s2 - 07 () [00f5bce4].mkv [subsplease] `

2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        data for date/ep/id parsing 's2 07 00f5bce4 mkv subsplease'
2021-02-25 21:03:17 TRACE    seriesparser  rssAnime        season pack regexp (?:season\s?|s)(\d{1,})(?:\s|$)(?!(?:(?:.*?\s)?(?:episode|e|ep|part|pt)\s?(?:\d{1,3}|X{0,3}(?:IX|XI{0,4}|VI{0,4}|IV|V|I{1,4}))|(?:\d{1,3})\s?of\s?(?:\d{1,3}))) match ('2',)
2021-02-25 21:03:17 DEBUG    parser_internal rssAnime        Parsing result: <SeriesParser(data=[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv,name=Dr. Stone,id=(2, 0),season=2,season_pack=True,episode=None,quality=720p,proper=0,status=OK)> (in 1.322040999999885 ms)

2021-02-25 21:03:17 DEBUG    series        rssAnime        `[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv` detected as `<SeriesParseResult(data=[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv,name=Dr. Stone,id=(2, 0),season=2,season_pack=True,episode=0,quality=720p,proper=0,special=False,status=OK)>`, field: `title`
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_parser = <flexget.components.parsing.parsers.parser_common.SeriesParseResult object at 0x7f4982d5e7d0>
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_name = 'Dr. Stone'
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: quality = <Quality(resolution=720p,source=unknown,codec=unknown,audio=unknown)>
2021-02-25 21:03:17 TRACE    metainfo_quality rssAnime        Found quality 720p for [SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: quality = <Quality(resolution=720p,source=unknown,codec=unknown,audio=unknown)>
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: proper = False
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: proper_count = 0
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: release_group = None
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: season_pack = True
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_season = 2
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_episodes = 1
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_id = 'S02'
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_id_type = 'ep'
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_identified_by = 'ep'
2021-02-25 21:03:17 TRACE    entry         rssAnime        ENTRY SET: series_exact = False


After changing the regex to match post split syntax


2021-02-25 21:08:08 DEBUG    parser_internal rssAnime        Parsing series: `[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv` kwargs: {
	'name': 'Dr. Stone',
	'identified_by': 'ep',
	'alternate_names': [],
	'name_regexps': [],
	'strict_name': False,
	'allow_groups': [],
	'date_yearfirst': None,
	'date_dayfirst': None,
	'special_ids': [],
	'prefer_specials': None,
	'assume_special': None,
	'ep_regexps': ['S(\\d) (\\d\\d)'],
	'date_regexps': [],
	'sequence_regexps': [],
	'id_regexps': []
}
2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        name: dr stone data: [SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv
2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        NAME SUCCESS: ^(?:(?:\[[^\[\]]*\])|(?:HD.720p?:)|(?:HD.1080p?:)|(?:HD.2160p?:))?(?:[^\w&]|_)*(Dr(?:[^\w&]|_)*Stone)(?:\b|_)(?:[^\w&]|_)* matched to [SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv
2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        data stripped:  s2 - 07 (720p) [00f5bce4].mkv [subsplease] 
2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        parsing quality ->
2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        quality detected, using remaining data ` s2 - 07 () [00f5bce4].mkv [subsplease] `

2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        data for date/ep/id parsing 's2 07 00f5bce4 mkv subsplease'
2021-02-25 21:08:08 TRACE    seriesparser  rssAnime        found episode number with regexp S(\d) (\d\d) (('2', '07'))
2021-02-25 21:08:08 DEBUG    parser_internal rssAnime        Parsing result: <SeriesParser(data=[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv,name=Dr. Stone,id=(2, 7),season=2,season_pack=None,episode=7,quality=720p,proper=0,status=OK)> (in 1.2556020000000778 ms)

2021-02-25 21:08:08 DEBUG    series        rssAnime        `[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv` detected as `<SeriesParseResult(data=[SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv,name=Dr. Stone,id=(2, 7),season=2,season_pack=None,episode=7,quality=720p,proper=0,special=False,status=OK)>`, field: `title`
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_parser = <flexget.components.parsing.parsers.parser_common.SeriesParseResult object at 0x7faa49b30d50>
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_name = 'Dr. Stone'
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: quality = <Quality(resolution=720p,source=unknown,codec=unknown,audio=unknown)>
2021-02-25 21:08:08 TRACE    metainfo_quality rssAnime        Found quality 720p for [SubsPlease] Dr. Stone S2 - 07 (720p) [00F5BCE4].mkv
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: quality = <Quality(resolution=720p,source=unknown,codec=unknown,audio=unknown)>
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: proper = False
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: proper_count = 0
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: release_group = None
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: season_pack = None
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_season = 2
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_episode = 7
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_episodes = 1
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_id = 'S02E07'
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_id_type = 'ep'
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_identified_by = 'ep'
2021-02-25 21:08:08 TRACE    entry         rssAnime        ENTRY SET: series_exact = False


```
</details>

### Additional information:

- FlexGet version: 3.1.103
- Python version: 3.7.9
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Ubuntu 18.04.5 LTS
- Link to crash log:

**Comment by luizoti** [comment]
I use this template to clean and manipulate the title, this is for episodes only and should capture the vast majority of titles from most fansubs.

For seasonal packages, there is another template, similar.

```
  ANIMES-TITLE-NORMALIZE:
    manipulate:
      - filename:
          from: title
      - title:
          replace:
            regexp: '(?i)(?<![\w\d])(PT-BR|PTBR|ENG|SPA)(?![\w\d])'
            format: ' '
      - title:
          replace:
            regexp: '(?i)(?:h|x)(.|)(?:264|265)'
            format: ' '
      - title:
          replace:   
            regexp: '(?<![\w\d])(\!|\:|\?|\.)(?![\w\d])'
            format: ' '
      - title:
          replace:
            regexp: '(\d*) ~ (\d*)'
            format: ' '
      - title:
          replace:
            regexp: '(?i)((?:nd|rd|th)\s(?:Season))'
            format: ' episode'
      - title:
          replace:
            regexp: '(?i)(season)\s*'
            format: 'S0'
      - title:
          replace:
            regexp: '(?i)Book '
            format: 'S0'
      - title:
          replace:
            regexp: '(?i)\s(end)'
            format: ' '
      - title:
          replace:
            # regexp: '\(\d{4}\)'
            regexp: '(?<![\w\d])((?:1|2|3|4|5|6|7|8)(?:[0-9])\d\d)(?![\w\d])'
            format: ' '
      - title:
          replace:
            regexp: '(?i)(v\d*)\s'
            format: ' '
      - title:
          replace:
            regexp: '(?i)\[Multiple Subtitle\]|Audio|Subs|Multi'
            format: ' '
      - title:
          replace:
            regexp: '(?i)(BD)'
            format: ''
      - title:
          replace:
            regexp: '(?i)(E-AC-3|EAC3|AC3)'
            format: ''
      - title:
          replace:
            regexp: '(?i)(8(?:\s|)bit(?:s|))'
            format: ''
      - title:
          replace:
            regexp: '(\]\[)'
            format: '] ['
      - title:
          replace:
            regexp: '(\[\])'
            format: ' '
      - title:
          replace:
            regexp: '(\]\s*)'
            format: ']  '
      - title:
          replace:
            regexp: '(\s*\])'
            format: ']'
      - title:
          replace:
            regexp: '(\[\s*|\[)'
            format: ' ['
      - title:
          replace:
            regexp: '(?i)((?:6|12|19)(?:\d*)x)'
            format: ''
      - title:
          replace:
            regexp: '((?<![\w\d])\-(?![\w\d])|\(|\))'
            format: '  '
      - title:
          replace:
            regexp: '(?<![\w\d])(1080|\[1080\]|1080p|\[1080p\]|FULL HD|FULLHD)(?![\w\d])'
            format: '- [1080p]'
      - title:
          replace:
            regexp: '(?<![\w\d])(720|\[720\]|720p|\[720p\]|HD|hdrip)(?![\w\d])'
            format: '- [720p]'
      - title:
          replace:
            regexp: '(?<![\w\d])(480|\[480\]|480p|\[480p\]|DVDrip|DVD)(?![\w\d])'
            format: '- [480p]'
      - title:
          replace:
            regexp: '\[\-'
            format: '-'
      - title:
          replace:
            regexp: 'bit\]'
            format: 'bit'
      - title:
          replace:
            regexp: '(?<![\w\d])I(?![\w\d])'
            format: '1'
      - title:
          replace:
            regexp: '(?<![\w\d])II(?![\w\d])'
            format: '2'
      - title:
          replace:
            regexp: '(?<![\w\d])III(?![\w\d])'
            format: '3'
      - title:
          replace:
            regexp: '(?<![\w\d])IV(?![\w\d])'
            format: '4'
      - title:
          replace:
            regexp: '(?<![\w\d])V(?![\w\d])'
            format: '5'
      - title:
          replace:
            regexp: '(?<![\w\d])VI(?![\w\d])'
            format: '6'
      - title:
          replace:
            regexp: '(?<![\w\d])VII(?![\w\d])'
            format: '7'
      - title:
          replace:
            regexp: '(?<![\w\d])VIII(?![\w\d])'
            format: '8'
      - title:
          replace:
            regexp: '(?<![\w\d])IX(?![\w\d])'
            format: '9'
      - title:
          replace:
            regexp: 'S((?:1|2|3|4|5|6|7|8)(?:[0-9])\d\d)'
            format: 'S01'
      - title:
          replace:
            regexp: '[ ]{2,}'
            format: ' '

  ANIMES-TITLE-EP:
    manipulate:
      - title:    
          replace:
            # High Score Girl 2 07 - [1080p]
            regexp: '(.+?)\s{1,5}(\d{1,4})\s{1,5}(\d{1,5})\s{1,5}\-\s{1,5}\[(.+?)\]'
            format: '\1 - S0\2E\3 - \4'
      - title:    
          replace:
            # Bungou Stray Dogs 3 episode 10 - [720p]
            regexp: '(.+?)\s{1,10}(\d{1,3})\s{1,10}episode\s{1,10}(\d{1,3})\s{1,10}\-\s{1,10}\[(.+?)\]'
            format: '\1 - S0\2E\3 - \4'            
      - title:    
          replace:
            # Shingeki no Kyojin S03 09 - [1080p]
            regexp: '(.+?)\s{1,10}(S\d*)\s{1,10}(\d*)\s{1,10}\-\s{1,10}(\[.+?\])'
            format: '\1 - \2E\3 - \4'
      - title:    
          replace:
            # Enen no Shouboutai 04 - [1080p] [4DB588FC]
            # SSSS. Gridman 04 - [1080p] 10bit
            # SSSS. Gridman 04 - [1080p]
            regexp: '(.+?) (\d*) - (?:\[((?:1080|720|480)p)\].*)'
            format: '\1 - S01E\2 - \3'

```

**Comment by BrutuZ** [comment]
@teemuatlut Can probably be avoided by setting the appropriate tracking method. You're using `identified_by: ep` instead of `identified_by: sequence`

**Comment by teemuatlut** [comment]
@BrutuZ True for shows that are actually marked sequentially but here it was marked as ShowName S2 - 07.mkv and the S3 will again start from 1.

@luizoti Thanks but I wasn't looking to search and replace away my issue here and my current setup seems to work quite alright for now.

**Comment by BrutuZ** [comment]
> @BrutuZ True for shows that are actually marked sequentially but here it was marked as ShowName S2 - 07.mkv and the S3 will again start from 1.

The S2 is part of the name in this case, which is quite common with anime. You do want `identified_by: sequence` and if it wasn't matching you'd change the series' name to _Dr. Stone S2_

**Comment by paranoidi** [comment]
@BrutuZ Putting S2 as part of the series name is a bad solution. None of the integrated services put it in there. When using move or other features to organize it would mean that every season is listed as own series.

I still think that the right solution is to implement "anime" style for ep_identifier.

It should parse in following manner:

"Some Series - 04" as S01E04
"Some Series S2 - 04" as S02E04

**Comment by BrutuZ** [comment]
@paranoidi But what we call seasons ARE considered separate shows by anime databases and its scene. The ` S(eason )?\d` suffix isn't even standard, some databases might have it, other times those are just arbitrarily thrown in by the release group which each follow their own rules when it comes to naming and source thereof.

For instance, _Dr. Stone S2_ is already an alternate name for _Dr. STONE: Stone Wars_
> https://anilist.co/anime/113936/Dr-STONE-STONE-WARS/
https://myanimelist.net/anime/40852/Dr_Stone__Stone_Wars
https://anidb.net/anime/15305

As someone with mostly anime in the flexget tasks, I'd welcome a dedicated parser mode, however, there's not enough standardization in the scene to make it viable IMHO. Sure, that proposed mode would handle this one edge case and maybe a couple others this season, but most would still have to be manually adjusted.

**Comment by luizoti** [comment]
> Putting S2 as part of the series name is a bad solution. None of the integrated services put it in there. When using move or other features to organize it would mean that every season is listed as own series.
> 
> I still think that the right solution is to implement "anime" style for ep_identifier.
> 
> It should parse in following manner:
> 
> "Some Series - 04" as S01E04
> "Some Series S2 - 04" as S02E04

My solution with regex covers these cases and others I remember that there were other seasonal identities that are covered as well.

Prior to this solution, flexget usually does not detect epsody and season.

On the basis, supporting the cleaning with the `ANIMES-TITLE-NORMALIZE` template, flexget converts the title to a more comprehensive and standardized information, and not end, following an ordering that the flexget itself can determine the correct data.

I have been using this solution for over 1 years, for animes, it was the best that can be achieved taking into account the disorder that fansubs do.

"Some Series - 04" as S01E04
"Some Series S2 - 04" as S02E04

The cases like Dr. Stone, are the situations where I did not find a solution, not least because the flexget ignores the full title, theoretically the search should be done on sites like anidb or try to identify based on the date.

**Comment by BrutuZ** [comment]
To further illustrate my point above, the first item in this list is a "third season", all the others are "second seasons" and each is named its own way
![Log Horizon: Entaku Houkai
BEASTARS 2
Yakusoku no Neverland 2
Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2
Tensei Shitara Slime Datta Ken 2nd Season
Dr. STONE: STONE WARS
](https://i.imgur.com/PlO7ISz.png)

**Comment by luizoti** [comment]
You are right, but as I tried to show, this is not a silver bullet, it does not solve everything mainly by the fact that each fansub does what it wants with the titles.

I use Erai-Raws, Seicher and other Brasilian Fansubs (the most problematic) the result is: 

```
[Erai-raws] Yakusoku no Neverland 2nd Season - 08 [1080p][Multiple Subtitle].mkv

Yakusoku no Neverland - S02E09 - 1080p
```
This was the most general and efficient solution I have found so far.

The plugin handles as substitutions in sequence starting from the top if at the beginning for example, to put the title and asked to substitute for the value referring to the season, this reduces the problem a little:

 Log Horizon: Entaku Houkai                -----> Season 3
 Shingeki no Kyojin: The Final Season -----> Season 4
 Dr. Stone: Stone Wars                          -----> Season 2

```
  ANIMES-TITLE-NORMALIZE:
    manipulate:
      - filename:
          from: title
      - title:
          replace:
            regexp: 'Entaku Houkai'
            format: ' Season 3'
      - title:
          replace:
            regexp: 'The Final Season'
            format: ' Season 4'
      - title:
          replace:
            regexp: 'Stone Wars'
            format: ' Season 2'
      - title:
          replace:
            regexp: '(?i)(?<![\w\d])(PT-BR|PTBR|ENG|SPA)(?![\w\d])'
            format: ' '
```
A little more complex to manage, but I believe it generates something close to this:: 
`Shingeki no Kyojin - S04E01 -  1080p`

In the end the problem is cases of animes with 'Part 2' how to determine the number of the episode in the correct sequence of the season? I do not know.

**Comment by BrutuZ** [comment]
@luizoti My previous message was meant as a follow-up to my own, not as a counter-point to what you said, sorry if there was confusion.

Now in regards to your solution in the last message, at that point setting the season directly at the series' entry is probably easier to maintain. I have a `include` file for such exceptions, for example:
```yaml
series:
  settings:
    anime:
      set:
        series_season: "{{path_season|d(tvdb_season)|d(series_season)|d(1)}}"
  anime:
    - Tensei shitara Slime Datta Ken 2nd Season:
        set:
          tvdb_id: 352408
          path_season: 2
    - "5-Toubun no Hanayome ":
        name_regexp:
          - (Go|5)[ -]?toubun no Hanayome( (S(eason )?2|∬))?
          - (The )?Quintessential Quintuplets( (S(eason )?2|∬))?
        alternate_name:
          - Go-Toubun no Hanayome
        set:
          path_season: 2
    - Yakusoku no Neverland 2:
        name_regexp: (Yakusoku no|The Promised) Neverland( (S|Season )?2(nd Season)?)?
          tvdb_id: 348002
          path_season: 2
```

**Comment by luizoti** [comment]
> @luizoti My previous message was meant as a follow-up to my own, not as a counter-point to what you said, sorry if there was confusion.
> 
> Now in regards to your solution in the last message, at that point setting the season directly at the series' entry is probably easier to maintain. I have a `include` file for such exceptions, for example:
> 
> ```yaml
> series:
>   settings:
>     anime:
>       set:
>         series_season: "{{path_season|d(tvdb_season)|d(series_season)|d(1)}}"
>   anime:
>     - Tensei shitara Slime Datta Ken 2nd Season:
>         set:
>           tvdb_id: 352408
>           path_season: 2
>     - "5-Toubun no Hanayome ":
>         name_regexp:
>           - (Go|5)[ -]?toubun no Hanayome( (S(eason )?2|∬))?
>           - (The )?Quintessential Quintuplets( (S(eason )?2|∬))?
>         alternate_name:
>           - Go-Toubun no Hanayome
>         set:
>           path_season: 2
>     - Yakusoku no Neverland 2:
>         name_regexp: (Yakusoku no|The Promised) Neverland( (S|Season )?2(nd Season)?)?
>           tvdb_id: 348002
>           path_season: 2
> ```

I may be mistaken, but your config example is more aimed at informing the anime title in the configuration, in my case I use lists, currently trakt and myanimelist (to get the titles in Japanese and English) The idea is to modify the file as little as possible. 

This is part of my cfg: https://pastebin.com/KJBfWfrK

I would very much like a solution (or the closest) to be integrated directly into the code, it would be something very nice kkk

**Comment by BrutuZ** [comment]
@luizoti I use lists too, AniList in my case. The entries in that snippet are just the ones that need fixing for the season, the fields set in `series` here get merged to the ones from `configure_series`

**Comment by luizoti** [comment]
> @luizoti I use lists too, AniList in my case. The entries in that snippet are just the ones that need fixing for the season, the fields set in `series` here get merged to the ones from `configure_series`

Haa, I got it, I didn't remember that you could use everything together, well, do you think it's possible to implement something that will reduce this problem?

**Comment by paranoidi** [comment]
I see, I didn't think places list S2 as a separate series. And there's not much we could do with silly situations like "The Final Season" easily. I guess the series plugin `identified_by: anime` could track season identifiers like:

`{series name} {unique season identifier} {episode number}`

Where `{unique season identifier}` could be "S2" or "The Final Season" etc. Basically whatever is between the `{series name}` and `{episode number}.

Not sure what kind of identifier that would make, because S02E04 type would not be possible. Maybe something like "S[The Final Season]E02" ....

**Comment by luizoti** [comment]
I don't remember for sure if all the fansubs release the last season as The Final Season, in the case of `Shingeki no Kyojin`, I think it's taken from `Crunchyroll` and there the fourth season is named `The Final Season`.

Assuming that `The Final Season` is already common, flexget could search tvdb (or others) for the last one, currently on display or not, and define this season as an identifier.

For all other cases, perhaps, normalizing the title and then using expressions to identify it may be applicable.

If it is the last it is probably the last in any situation.

**Comment by paranoidi** [comment]
Series parsing is not connected to any lookups and I don't think we want to make it so for this edge case.

**Comment by luizoti** [comment]
> Series parsing is not connected to any lookups and I don't think we want to make it so for this edge case.

`The Final Season` e similares são mais incomuns, mas todas as outras situações relacionadas a animes são bem comuns.

**Comment by BrutuZ** [comment]
If I had to list common suffixes for sequel series that'd be something like

- \#
- S#
- #(nd|rd|th) Season
- Season #
- Roman Numerals (II|III|IV|V|VI||VII|IIX|IX)

Other than that, they can always come up with a suffix than can't be easily guessed and will require manual numbering anyway, like `The Final Season`, `Banana-hen` (Banana arc\chapter), `Ni no Shou` (The Second Act), or even my personal favorite oddball for this season: `∬`

**Comment by luizoti** [comment]
I agree, they are the most common ones.

`Roman Numerals` for me are the most boring to detect correctly, but I don't know how to create such good expressions either.

**Comment by BrutuZ** [comment]
> 
> 
> I agree, they are the most common ones.
> 
> `Roman Numerals` for me are the most boring to detect correctly, but I don't know how to create such good expressions either.

`{{series_name|re_replace('\bII\b$','S02')|re_replace('\bIII\b$','S03')|re_replace('\bIV\b$','S04')|re_replace('\bV\b$','S05')|re_replace('\bVI\b$','S06')|re_replace('\bVII\b$','S07')|re_replace('\bVIII\b$','S08')|re_replace('\bIX\b$','S09')}}`

**Comment by luizoti** [comment]
thx, i will try this.

**Comment by soloam** [comment]
I also have this template, and I aply it to all the tasks that I need:

```
  clean_trash:
    manipulate:
      - title:
          replace:
            regexp: '^\[.*\]\s?'
            format: ''
```

**Comment by soloam** [comment]
Is this issue still relevant? Did the config solved the problem?

**Comment by luizoti** [comment]
> Is this issue still relevant? Did the config solved the problem?

@soloam  do you talk about this configuration?

At least in regex101 he takes the whole title, was that the goal?

**Comment by soloam** [comment]
I was talking about the solution provided by @BrutuZ or mine above! In the one provided by @BrutuZ the content is replaced with jinja, on mine I use the regex with replace to search by the first block and remove it!
