### ISSUE TITLE
Is that possible to add "list_sync" feature?

### ISSUE THREAD

**Issue by ProteinPig** [Flexget/Flexget#2962]
We got add remove clear features in managed list. Recent days I try to sync local list and trakt list, and got that work with add and remove methed. But not perfect worked, so I  was wondering that it's  possible to add "list_sync" feature?

**Comment by soloam** [comment]
I kinda do that also, to avoid going to trakt all the time (not the most stable service in the world), the main issue that normally I face is the cache, you do something in trakt that takes some time to reflect in the flexget list! I kinda like the idea, but this would be bound to the same cache restrictions.

**Comment by ProteinPig** [comment]
No need for real-time synchronization, but just keep the configuration file as simple as much.
to get the sync worked with add and remove, I write 4 tasks(or maybe there is simple method I don't know).

**Comment by soloam** [comment]
4 tasks? I did it with 2... 1 cross matching to know what to add to the local list, another with crossmatch to know what to remove from the local list

**Comment by ProteinPig** [comment]
Because I need filter movies from Flexget then add to trakt, not just add movies from trakt then add to local.

**Comment by soloam** [comment]
Oh ok I see, you sync 2 lists! Let me see if we can think on anything that would be useful

**Comment by gazpachoking** [comment]
Hmm, two way sync is a bit hard. If one of the lists has an extra item, how does it know whether it should remove it, or add it to the other?

**Comment by soloam** [comment]
not 2 way... 1 way... remote to local... or local to remote... At lest this is what I was thinking!

```
list_sync:
  from: trakt_list....
  to: my_cool_movies
```

If it exists in trakt but does not exists in local, add... if it does not exist in trakt but exists in local, remove

**Comment by ProteinPig** [comment]
> Hmm, two way sync is a bit hard. If one of the lists has an extra item, how does it know whether it should remove it, or add it to the other?

You are right, so I sync them twice. Use priority to figure that. 

`  sync.add_3rd_new_movies_to_local:
    priority: 21
    <<: *3rd_wanted_movies
    list_match:
      from:
        - movie_list: wanted-movies
      action: reject
      remove_on_match: no
    accept_all: yes
    list_add:
      - movie_list: wanted-movies
    seen: local

  sync.remove_3rd_del_movies_from_local:
    priority: 21
    movie_list: wanted-movies
    list_match:
      from:
        - <<: *3rd_wanted_movies
      action: reject
      remove_on_match: no
    accept_all: yes
    list_remove:
      - movie_list: wanted-movies
    disable: [seen]

  sync.add_new_movies_to_3rd:
    priority: 999
    movie_list: wanted-movies
    list_match:
      from:
        - <<: *3rd_wanted_movies
      action: reject
      remove_on_match: no
    accept_all: yes
    list_add:
      - <<: *3rd_wanted_movies
    seen: local

  sync.remove_del_movies_from_3rd:
    priority: 999
    <<: *3rd_wanted_movies
    list_match:
      from:
        - movie_list: wanted-movies
      action: reject
      remove_on_match: no
    accept_all: yes
    list_remove:
      - <<: *3rd_wanted_movies
    disable: [seen]
`
