### ISSUE TITLE
[Lostfilm Plugin] Handle Cloudflare protection 

### ISSUE THREAD

**Issue by zankevich** [Flexget/Flexget#2983]
Looks like lostfilm added Cloudflare protection. Can we do something with that?
@Karlson2k

```
2021-05-15 01:55:19  CRITICAL    plugin    lostfilm    Received 525 status instead of 200 (OK)
```

**Comment by GreyKat** [comment]
`2021-05-15 14:22:42 CRITICAL task          LostFilm        BUG: Unhandled error in plugin lostfilm: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

2021-05-15 14:22:42 CRITICAL manager       LostFilm        An unexpected crash has occurred. Writing crash report to /opt/flexget/crash_report.2021.05.15.142242863610.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.123`

**Comment by BrutuZ** [comment]
If `cfscraper` doesn't get the job done you can try dumping CloudFlare's tokens for this site in the `cookies` plugin

**Comment by johnmate** [comment]
Are there any possible fixes?

**Comment by BrutuZ** [comment]
@johnmate 
> you can try dumping CloudFlare's tokens for this site in the `cookies` plugin

**Comment by johnmate** [comment]
added token `cf_clearance` to the `cookies `but it does not give a positive result

> 2021-05-21 20:01:41 DEBUG    scheduler                     executing tasks: ['lostfilm']
2021-05-21 20:01:41 DEBUG    scheduler                     task finished executing: lostfilm
2021-05-21 20:01:41 DEBUG    manager       lostfilm        Not running db cleanup, last run 2021-05-21 12:59:22
2021-05-21 20:01:41 DEBUG    task          lostfilm        executing lostfilm
2021-05-21 20:01:41 DEBUG    template      lostfilm        Merging template tvshows into task lostfilm
2021-05-21 20:01:41 DEBUG    template      lostfilm        Merging template notification into task lostfilm
2021-05-21 20:01:41 DEBUG    include       lostfilm        Merging /var/lib/transmission/.config/flexget/private/series_lostfilm.yml into task lostfilm
2021-05-21 20:01:41 DEBUG    cookies       lostfilm        Loading mozilla cookies
2021-05-21 20:01:41 DEBUG    cookies       lostfilm        mozilla cookies loaded
2021-05-21 20:01:41 VERBOSE  lostfilm      lostfilm        Generated pre-filter list with 6 entries
2021-05-21 20:01:41 DEBUG    utils.requests lostfilm        GETing URL https://www.lostfilm.tv/v_search.php with args () and kwargs {'params': {'c': 226, 's': 7, 'e': 10}, 'allow_redirects': True, 'timeout': 30}
2021-05-21 20:01:41 CRITICAL task          lostfilm        BUG: Unhandled error in plugin lostfilm: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

**Comment by BrutuZ** [comment]
I usually just change all the domain's cookies expiry to the same date and add them to the cookie file.
Probably a good idea to remove `cfscrape: yes` since the cookies will be doing its job instead

**Comment by johnmate** [comment]
returns the following errors if disable `cfscrape`

> May 21 20:42:09 cent.name flexget[460456]: 2021-05-21 20:42:09 CRITICAL task          lostfilm        BUG: Unhandled error in plugin lostfilm: unsupported format string passed to HTTPError.__format__
May 21 20:42:09 cent.name flexget[460456]: Traceback (most recent call last):
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/components/sites/sites/lostfilm.py", line 207, in on_task_input
May 21 20:42:09 cent.name flexget[460456]:     response = task.requests.get(redirect_url, params=params)
May 21 20:42:09 cent.name flexget[460456]:                |    |        |   |                    -> {'c': 226, 's': 7, 'e': 10}
May 21 20:42:09 cent.name flexget[460456]:                |    |        |   -> 'https://www.lostfilm.tv/v_search.php'
May 21 20:42:09 cent.name flexget[460456]:                |    |        -> <function Session.get at 0x7f6bdb2a3a60>
May 21 20:42:09 cent.name flexget[460456]:                |    -> <flexget.utils.requests.Session object at 0x7f6bd40fda20>
May 21 20:42:09 cent.name flexget[460456]:                -> <flexget.task.Task object at 0x7f6bd4d549e8>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
May 21 20:42:09 cent.name flexget[460456]:     return self.request('GET', url, **kwargs)
May 21 20:42:09 cent.name flexget[460456]:            |    |              |      -> {'params': {'c': 226, 's': 7, 'e': 10}, 'allow_redirects': True}
May 21 20:42:09 cent.name flexget[460456]:            |    |              -> 'https://www.lostfilm.tv/v_search.php'
May 21 20:42:09 cent.name flexget[460456]:            |    -> <function Session.request at 0x7f6bd9506510>
May 21 20:42:09 cent.name flexget[460456]:            -> <flexget.utils.requests.Session object at 0x7f6bd40fda20>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/utils/requests.py", line 271, in request
May 21 20:42:09 cent.name flexget[460456]:     result.raise_for_status()
May 21 20:42:09 cent.name flexget[460456]:     |      -> <function Response.raise_for_status at 0x7f6bdb5eae18>
May 21 20:42:09 cent.name flexget[460456]:     -> <Response [503]>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
May 21 20:42:09 cent.name flexget[460456]:     raise HTTPError(http_error_msg, response=self)
May 21 20:42:09 cent.name flexget[460456]:           |         |                        -> <Response [503]>
May 21 20:42:09 cent.name flexget[460456]:           |         -> '503 Server Error: Service Temporarily Unavailable for url: https://www.lostfilm.tv/v_search.php?c=226&s=7&e=10'
May 21 20:42:09 cent.name flexget[460456]:           -> <class 'requests.exceptions.HTTPError'>
May 21 20:42:09 cent.name flexget[460456]: requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://www.lostfilm.tv/v_search.php?c=226&s=7&e=10
May 21 20:42:09 cent.name flexget[460456]: During handling of the above exception, another exception occurred:
May 21 20:42:09 cent.name flexget[460456]: Traceback (most recent call last):
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
May 21 20:42:09 cent.name flexget[460456]:     self._bootstrap_inner()
May 21 20:42:09 cent.name flexget[460456]:     |    -> <function Thread._bootstrap_inner at 0x7f6be0ef3e18>
May 21 20:42:09 cent.name flexget[460456]:     -> <Thread(task_queue, started daemon 140100449052416)>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
May 21 20:42:09 cent.name flexget[460456]:     self.run()
May 21 20:42:09 cent.name flexget[460456]:     |    -> <function Thread.run at 0x7f6be0ef3bf8>
May 21 20:42:09 cent.name flexget[460456]:     -> <Thread(task_queue, started daemon 140100449052416)>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/lib64/python3.6/threading.py", line 864, in run
May 21 20:42:09 cent.name flexget[460456]:     self._target(*self._args, **self._kwargs)
May 21 20:42:09 cent.name flexget[460456]:     |    |        |    |        |    -> {}
May 21 20:42:09 cent.name flexget[460456]:     |    |        |    |        -> <Thread(task_queue, started daemon 140100449052416)>
May 21 20:42:09 cent.name flexget[460456]:     |    |        |    -> ()
May 21 20:42:09 cent.name flexget[460456]:     |    |        -> <Thread(task_queue, started daemon 140100449052416)>
May 21 20:42:09 cent.name flexget[460456]:     |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f6bd53fcf28>>
May 21 20:42:09 cent.name flexget[460456]:     -> <Thread(task_queue, started daemon 140100449052416)>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/task_queue.py", line 46, in run
May 21 20:42:09 cent.name flexget[460456]:     self.current_task.execute()
May 21 20:42:09 cent.name flexget[460456]:     |    |            -> <function Task.execute at 0x7f6bd94ae378>
May 21 20:42:09 cent.name flexget[460456]:     |    -> <flexget.task.Task object at 0x7f6bd4d549e8>
May 21 20:42:09 cent.name flexget[460456]:     -> <flexget.task_queue.TaskQueue object at 0x7f6bd53fcf28>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 87, in wrapper
May 21 20:42:09 cent.name flexget[460456]:     return func(self, *args, **kw)
May 21 20:42:09 cent.name flexget[460456]:            |    |      |       -> {}
May 21 20:42:09 cent.name flexget[460456]:            |    |      -> ()
May 21 20:42:09 cent.name flexget[460456]:            |    -> <flexget.task.Task object at 0x7f6bd4d549e8>
May 21 20:42:09 cent.name flexget[460456]:            -> <function Task.execute at 0x7f6bd94ae2f0>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 722, in execute
May 21 20:42:09 cent.name flexget[460456]:     self._execute()
May 21 20:42:09 cent.name flexget[460456]:     |    -> <function Task._execute at 0x7f6bd94ae268>
May 21 20:42:09 cent.name flexget[460456]:     -> <flexget.task.Task object at 0x7f6bd4d549e8>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 688, in _execute
May 21 20:42:09 cent.name flexget[460456]:     self.__run_task_phase(phase)
May 21 20:42:09 cent.name flexget[460456]:     |                     -> 'input'
May 21 20:42:09 cent.name flexget[460456]:     -> <flexget.task.Task object at 0x7f6bd4d549e8>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 514, in __run_task_phase
May 21 20:42:09 cent.name flexget[460456]:     response = self.__run_plugin(plugin, phase, args)
May 21 20:42:09 cent.name flexget[460456]:                |                 |       |      -> (<flexget.task.Task object at 0x7f6bd4d549e8>, True)
May 21 20:42:09 cent.name flexget[460456]:                |                 |       -> 'input'
May 21 20:42:09 cent.name flexget[460456]:                |                 -> <PluginInfo(name=lostfilm)>
May 21 20:42:09 cent.name flexget[460456]:                -> <flexget.task.Task object at 0x7f6bd4d549e8>
May 21 20:42:09 cent.name flexget[460456]: > File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 547, in __run_plugin
May 21 20:42:09 cent.name flexget[460456]:     result = method(*args, **kwargs)
May 21 20:42:09 cent.name flexget[460456]:              |       |       -> {}
May 21 20:42:09 cent.name flexget[460456]:              |       -> (<flexget.task.Task object at 0x7f6bd4d549e8>, True)
May 21 20:42:09 cent.name flexget[460456]:              -> <Event(name=plugin.lostfilm.input,func=on_task_input,priority=128)>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/event.py", line 20, in __call__
May 21 20:42:09 cent.name flexget[460456]:     return self.func(*args, **kwargs)
May 21 20:42:09 cent.name flexget[460456]:            |    |     |       -> {}
May 21 20:42:09 cent.name flexget[460456]:            |    |     -> (<flexget.task.Task object at 0x7f6bd4d549e8>, True)
May 21 20:42:09 cent.name flexget[460456]:            |    -> <bound method LostFilm.on_task_input of <flexget.components.sites.sites.lostfilm.LostFilm object at 0x7f6bd5480128>>
May 21 20:42:09 cent.name flexget[460456]:            -> <Event(name=plugin.lostfilm.input,func=on_task_input,priority=128)>
May 21 20:42:09 cent.name flexget[460456]:   File "/usr/local/lib/python3.6/site-packages/flexget/components/sites/sites/lostfilm.py", line 209, in on_task_input
May 21 20:42:09 cent.name flexget[460456]:     logger.error('Failed to get lostfilm download page: {:s}'.format(e))
May 21 20:42:09 cent.name flexget[460456]:     |      -> <function Logger.error at 0x7f6be0ed6620>
May 21 20:42:09 cent.name flexget[460456]:     -> <loguru.logger handlers=[(id=2, level=10, sink=<lambda>), (id=3, level=20, sink='/var/lib/transmission/.config/flexget/flexge...
May 21 20:42:09 cent.name flexget[460456]: TypeError: unsupported format string passed to HTTPError.__format__
May 21 20:42:09 cent.name flexget[460456]: 2021-05-21 20:42:09 CRITICAL manager       lostfilm        An unexpected crash has occurred. Writing crash report to /var/lib/transmission/.config/flexget/crash_report.2021.05.21.204209291032.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.127
May 21 20:42:09 cent.name flexget[460456]: 2021-05-21 20:42:09 WARNING  task          lostfilm        Aborting task (plugin: lostfilm)

**Comment by Balzhur** [comment]
It seems the only way to 'fix' Lostfilm plugin at the moment is use the site that does not utilize Cloudflare protection, i.e. https://www.lostfilm.run/

**Flexget config:**
```
[...]
  lostfilm_test:
    lostfilm: yes
    lostfilm:
      url: https://www.lostfilm.run/rss.xml
    headers:
      cookie: "lf_session=<new cookie from losfilm.run>;"
    verify_ssl_certificates: no
    #cfscraper: yes
[...]
```

**lostfilm.py plugin:**
```
[...]
redirect_url = 'https://www.lostfilm.run/v_search.php'
[...]
```

**Comment by johnmate** [comment]
I only changed `redirect_url` in **lostfilm.py**, now works, thanks for the fix

**Comment by Karlson2k** [comment]
Thanks for the hints, I'll try them all and update lostfilm plugins.
