### ISSUE TITLE
IMDB BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by 00lex** [Flexget/Flexget#3017]
Hi! i have this issue since a few days. I tried older versions of flex get but nothing. imdb seems changed something

Here my output: 
https://pastebin.com/EL5HJBEg

**Comment by BrutuZ** [comment]
Duplicate of #3014 and fixed with #3016
Should be up in about 9h from now.

**Comment by soloam** [comment]
Like stated, it was solved in #3016 

Issue can be closed

**Comment by 00lex** [comment]
whoops sry. I searched yesterday and post today without checking again
