### ISSUE TITLE
Error occurred while evaluating statement `imdb_year < 2000`. ('<' not supported between instances of 'NoneType' and 'int')

### ISSUE THREAD

**Issue by terrellgf** [Flexget/Flexget#3039]
Flexget: 3.1.130
API: 1.8.0

Error occurred while evaluating statement `imdb_year < 2000`. ('<' not supported between instances of 'NoneType' and 'int')

**Comment by soloam** [comment]
Probably imdb_year is None/Null... You should check if imdb_year is present and different from null

Try

```yaml
( imdb_year is number ) and ( imdb_year < 2000):
```
