### ISSUE TITLE
Error: check_hostname requires server_hostname when using FlexGet with Proxy Enabled on Python 3.9

### ISSUE THREAD

**Issue by jack2game** [Flexget/Flexget#3069]
I'm currently constantly using proxy on my PC and recently upgraded to python 3.9, with FlexGet re-installed using pip.

Previously FlexGet works just fine but since I moved to Py3.9, whenever I enabled my socks5 proxy, FlexGet would return this error: check_hostname requires server_hostname

Based on some quick Googling it may be caused by urllib3 version being too high, which came with Python 3.9.

After I downgraded urllib3 to 1.25.x, FlexGet works properly even when I enable my proxy.

It would be great if this can be fixed, i.e. make FlexGet working with most recent urllib3

**Comment by jack2game** [comment]
Just to add, pip actually gave me this when I change urllib3 version:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flexget 3.1.131 requires urllib3==1.26.4, but you have urllib3 1.26.6 which is incompatible.

**Comment by gazpachoking** [comment]
You are using the proxy plugin in flexget? If so what does your config look like? I'm thinking you probably have the configuration problem seen here #2744
