### ISSUE TITLE
[feature request] user-agent randomizer

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#3350]
i am trying to use one rss to one server that looks to give 403 if to much petitions are made on a row from same client, maybe making a  randomizer this limit can be avoided.

ie:
random_user_agent:
  agent_1: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
  agent_2: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0"
  agent_3: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"

**Comment by soloam** [comment]
We talked back on discord. 

```yaml
headers:
   "User-Agent": {{["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0","Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"][range(0,2)|random]}}
```

Should work

**Comment by Aokromes** [comment]
no luck :(

2022-02-06 21:03:10 CRITICAL manager                       while scanning for the next token found character '|' that cannot start any token in "<unicode string>", line 4, column 268: ... 0) Gecko/20100101 Firefox/98.0"]|random }} ^

-------------------------------------------------------------------------------
 Malformed configuration file (check messages above). Common reasons:
-------------------------------------------------------------------------------

 o Indentation error
 o Missing : from end of the line
 o Non ASCII characters (use UTF8)
 o If text contains any of :[]{}% characters it must be single-quoted (eg. value{1} should be 'value{1}')

 Reason: found character '|' that cannot start any token

 Check configuration near line 3, column 267

 Fault is almost always in this or previous line

**Comment by soloam** [comment]
Did you quoted the template? It should be quoted

**Comment by Aokromes** [comment]
that looks to work.
