### ISSUE TITLE
api_bluray Not finding movie details

### ISSUE THREAD

**Issue by eSoares** [Flexget/Flexget#3354]
This is a revisit of issue #1832

Currently api_bluray searchs for movies using as search parameter [section: 'bluraymovies'](https://github.com/Flexget/Flexget/blob/4a8fdc97ab2b2cf34556b40c5462d21cd14dac84/flexget/plugins/internal/api_bluray.py#L84), this causes movies to be missing.

A quick example is searching for movies with releases on digital only (Coda from 2021 for example).
This behaviour is testable at a terminal with curl:
```
curl https://m.blu-ray.com/quicksearch/search.php\?userid\=0\&section\=blueraymovies\&country\=ALL\&keyword\=coda+2021\&_\=1644421145191
``` 

A possible solution is after searching at the section `blueraymovies`, IF no results are found (or matched the year), fallback in searching in section `theatrical`. 
In the example above, would provide results:
```
curl https://m.blu-ray.com/quicksearch/search.php\?userid\=0\&section\=theatrical\&country\=ALL\&keyword\=coda+2021\&_\=1644421145191
{"items":[{"title":"CODA (2021)","flag":"","reldate":"Aug 13, 2021","year":"2021","rating":"7.49439","url":"https://m.blu-ray.com/CODA/1405732/","cover":"https://images.static-bluray.com/products/20/111189_2_small.jpg"},{"title":"Coda 77 (2021)","flag":"","reldate":"No theatrical date","year":"2021","rating":"0","url":"https://m.blu-ray.com/Coda-77/1509025/","cover":""}],"time":"0.00080"}
```

**Comment by soloam** [comment]
I noticed now that I didn't updated the wiki with a recent change! Please set the release_estimations to smart

```yaml
release_estimations: smart
```

That should solve that problem

Please confirm and I'll update the wiki 🤦

**Comment by eSoares** [comment]
Thanks for the quick update!

While for the test case in question, indeed solved the problem, still the issue happens sometimes!
Just notice recently with "Turning Red" where the release was estimated to hasn't been released yet, but was released.

In the endpoints tested in my previous comment the "blueraymovies" endpoint is returning "No release date" but in "theatrical" endpoint gives "March 11, 2022" as reldate!

**Comment by eSoares** [comment]
The issue still happens.

**Comment by eSoares** [comment]
I would still like to solve this.
