### ISSUE TITLE
webui becomes blank

### ISSUE THREAD

**Issue by RikkaBlue** [Flexget/Flexget#3394]
### Expected behaviour:
I fresh  install the flexget in docker-compose, I use the webui to manage the service.

### Steps to reproduce:
- Step 1: 
   I install it by docker-compose 
   ```flexget:
    image: wiserain/flexget:3
    container_name: flexget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - FLEXGET_LOG_LEVEL=info
      - HTTPS_PROXY=http://192.168.1.185:7890
      - HTTP_PROXY=http://192.168.1.185:7890
      - FLEXGET_LOG_MAXCOUNT=3
    volumes:
      - ./flexget:/config
      - /mnt/data/download:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    restart: unless-stopped
    ```
- step2
When I open the webui http://192.168.1.185:5050 and check the http://192.168.1.185:5050/log ，the web turns blank, the console throw some errors as below
![image](https://user-images.githubusercontent.com/46104879/160324418-61eb5596-a899-4ab0-9b74-6b65e7d91163.png)
```
TypeError: Invalid Version: null
Invalid Version: null
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'as')
```
![image](https://user-images.githubusercontent.com/46104879/160325155-16ff29ea-e283-4698-bb5e-f25d34ce527e.png)

#### Config:
```yaml
➜  flexgetQpt cat ./flexget/config.yml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  example-task:
    rss: http://example.com/feed.xml
    download: /data
    series:
      - some series 1
      - some series 2

schedules: no
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
flexget        | *** New config.yml from template
flexget        | *** Flexget v3.3.4 ready!
flexget        | [cont-init.d] 20-config: exited 0.
flexget        | [cont-init.d] 90-custom-folders: executing...
flexget        | [cont-init.d] 90-custom-folders: exited 0.
flexget        | [cont-init.d] 99-custom-files: executing...
flexget        | [custom-init] no custom files found exiting...
flexget        | [cont-init.d] 99-custom-files: exited 0.
flexget        | [cont-init.d] done.
flexget        | [services.d] starting services
flexget        | [services.d] executing => flexget -c /config/config.yml --loglevel info --logfile flexget.log daemon start --autoreload-config
flexget        | [services.d] done.
flexget        | 2022-03-28 11:54:26 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
flexget        | 2022-03-28 11:54:26 INFO     web_server_daemon                 Initiating API
flexget        | 2022-03-28 11:54:26 INFO     web_server_daemon                 Registering WebUI v2
flexget        | 2022-03-28 11:54:26 INFO     web_server                    Web server started at http://172.19.0.2:5050
flexget        | 2022-03-28 11:54:26 INFO     web_server                    API available at http://172.19.0.2:5050/api
flexget        | 2022-03-28 11:54:26 INFO     web_server                    WebUI (v2) available at http://172.19.0.2:5050/
```
</details>

### Additional information:

- FlexGet version: 3.3.4
- Python version: Python 3.9.5
- Installation method:  pip
- Using daemon (yes/no): yes
- OS and version: Linux version 5.10.0-12-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.103-1 (2022-03-07)
- Link to crash log:

**Comment by evoblicec** [comment]
Hi @RikkaBlue did you check if your host/container could resolve public internet? 
Had the same issue and was related to faulty DNS configuration

**Comment by RikkaBlue** [comment]
> Hi @RikkaBlue did you check if your host/container could resolve public internet? Had the same issue and was related to faulty DNS configuration
Thanks for you reply.
I can login, I guess there is no problem with DNS configuration. In addition, the problem also occurs when  using ip access.

**Comment by Lihewin** [comment]
Met the same problem as well in the area where flexget updating servers are blocked by firewall. I solved the problem by adding an all_proxy env when creating the container.
