### ISSUE TITLE
https://feathub.com/Flexget/Flexget does not exits.

### ISSUE THREAD

**Issue by Techwolf** [Flexget/Flexget#3422]
Before opening an issue, verify:

- Is this a feature request? Post it on https://feathub.com/Flexget/Flexget

This site does not exits. Is there a place to make a feature request for series->timeframe->target of none?

As of Sep, still does not exits.

**Comment by Techwolf** [comment]
When opening a new issue, this site is recomemnded and it does not exits there.

**Comment by gazpachoking** [comment]
Thanks for the report. Didn't realize we had that link still sticking around.

> Is there a place to make a feature request for series->timeframe->target of none?

Not sure what you mean by making the target none?

**Comment by Techwolf** [comment]
Right now, I use a target of 2160p on an RSS feed that does not have those. This is so after waiting a few hours from the first post/match, pick the best one, usally 1080p, but sometime best aviable is 720p. Soon the feed will have 2160p and that trick will no longer work.

**Comment by gazpachoking** [comment]
Is there no quality that you find to be most desirable, such that waiting isn't needed anymore? If there won't be better than 2160p released in the feed, why wait any longer? You can be very specific with your quality, and define resolution, codec, audio.
