### ISSUE TITLE
aria2.py  is not compatible to new version of aira2

### ISSUE THREAD

**Issue by wx69wx** [Flexget/Flexget#3460]
### Steps to reproduce:
- Step 1: ...

#### Config:
```yaml
Paste FULL config and remove any personal info if config is too long, attach the file to the ticket.
If issue is with a single task, you can get get resulting configuration by running:
  flexget execute --task <NAME> --dump-config
Make sure to redact any personal information (passwords, api keys, etc) !
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version:
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

hi, good gays, thanks for your good tools.
now i have a problem, the new  aria2  RPC  could not support http,  only support https/wss,  i connect  https://xxx:jsonrpc well in aria2ng.  but it give the error message below in flexget.  thanks a lot!
INFO     aria2         soft            Connecting to daemon at **### http://xxxx:2083/rpc**
CRITICAL task          soft            BUG: Unhandled error in plugin aria2: <ProtocolError for **### xxx:2083/rpc: 400 Bad Request**>

**Comment by aidan-** [comment]
It's hard to know exactly what you're facing without seeing your configuration and some log output, but I think the issue is that you are trying to connect Flexget with [`AiraNg`](https://github.com/mayswind/AriaNg) which isn't supported.  The Flexget aria2 plugin connects *directly* to the aria2 process' XML-RPC running in daemon mode.

**Comment by wx69wx** [comment]
thanks for your reply.   i make a mistake,  it is that AiraNg do not support  http  but https/wss  ,  and   aira rpc support  http,https,ws,wss, all. 
so i have to enable  tls in aria2.conf.  
because  flexget connect aria2-rpc by ' http://ip:port/rpc'  default  ,so  it get error.
then i modify the aria2.py  (/root/env/lib/python3.9/site-packages/flexget/plugins/clients/aria2.py) , it works well now.
"url = 'http://%s%s:%s/rpc' % (userpass, server, port)"----->"url = 'https://%s%s:%s/rpc' % (userpass, server, port)"

**Comment by aidan-** [comment]
@wx69wx You might be interested in following #3473 as it looks like it will address your issue.

**Comment by wx69wx** [comment]
yes，you are right.  my problem is same to #3473 ，thanks for your advice. let me try use_ssl. haha
