### ISSUE TITLE
FlexGet log reporting in GMT even though system is set to EST

### ISSUE THREAD

**Issue by crkinard** [Flexget/Flexget#3486]
Not sure why but the logs in the web interface are in GMT instead of EDT that the system is.

Version Info
Flexget: 3.3.17
API: 1.8.0

Linux flexget 5.15.0-1011-raspi #13-Ubuntu SMP PREEMPT Thu Jun 2 11:44:34 UTC 2022 aarch64 GNU/Linux

**Comment by aidan-** [comment]
I just did a quick test locally and the logs in the web UI are showing the same time zone as the CLI logs, which matches my system timezone.  Can you provide some more information on how you are running Flexget?  Are you perhaps running it in a docker container and don't have the correct timezone set in the container?
