### ISSUE TITLE
rss_pubdate does not consider local timezone

### ISSUE THREAD

**Issue by Jorman** [Flexget/Flexget#3489]
Hi,

I don't understand if I am doing something wrong or there is a problem with `rss_pubdate`.

I currently acquire data from multiple feeds and each feed has its own timezone, some different from mine.
I live in a CEST zone which is equivalent to UTC+2, so if it is 18:00:00 here in UTC it is el 16:00:00

In a `if` filter where I use `now` (which returns my CEST timezone) I expect all comparisons to be made with my local time, while I seem to see that the date in `rss_pubdate` is not being "converted" to my timezone

I created a simple condition:
```
    if:
      - rss_pubdate >= now - timedelta(minutes=15): accept
```
and I pass this rss_file:
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link rel="self" type="application/rss+xml" />
    <title>Prowlarr</title>
    <item>
      <title>Title1</title>
      <description />
      <guid>https://tracker1/torrents.php?id=2343876&amp;torrentid=2343845</guid>
      <prowlarrindexer id="4">Tracker1</prowlarrindexer>
      <comments>https://tracker1/torrents.php?id=2343876&amp;torrentid=2343845</comments>
      <pubDate>Sun, 26 Jun 2022 16:38:01 +0000</pubDate>
      <size>1073751824</size>
      <link>http://10.0.0.100:9696/4/download?apikey=000000000000000000&amp;link=link&amp;file=Title1</link>
      <category>3050</category>
      <category>100029</category>
      <enclosure url="http://10.0.0.100:9696/4/download?apikey=000000000000000000&amp;link=link&amp;file=Title1" length="1073751824" type="application/x-bittorrent" />
      <category>3050</category>
      <category>100029</category>
      <rageid>0</rageid>
      <tvdbid>0</tvdbid>
      <imdb>0000000</imdb>
      <tmdbid>0</tmdbid>
      <traktid>0</traktid>
      <seeders>0</seeders>
      <files>8</files>
      <grabs>0</grabs>
      <peers>0</peers>
      <downloadvolumefactor>0</downloadvolumefactor>
      <uploadvolumefactor>1</uploadvolumefactor>
    </item>
    <item>
      <title>Title2</title>
      <description />
      <guid>https://tracker2/download.php?id=4587&amp;torrentid=4587</guid>
      <prowlarrindexer id="28">Tracker2</prowlarrindexer>
      <comments>https://tracker2/details.php?id=4587</comments>
      <pubDate>Sun, 26 Jun 2022 17:38:01 +0100</pubDate>
      <size>1073751824</size>
      <link>http://10.0.0.100:9696/28/download?apikey=000000000000000000&amp;link=link&amp;file=Title2</link>
      <category>2040</category>
      <enclosure url="http://10.0.0.100:9696/4/download?apikey=000000000000000000&amp;link=link&amp;file=Title2" length="1073751824" type="application/x-bittorrent" />
      <category>2040</category>
      <tag>freeleech</tag>
      <rageid>0</rageid>
      <tvdbid>0</tvdbid>
      <imdb>0000000</imdb>
      <tmdbid>0</tmdbid>
      <traktid>0</traktid>
      <seeders>1</seeders>
      <peers>2</peers>
      <downloadvolumefactor>0</downloadvolumefactor>
      <uploadvolumefactor>1</uploadvolumefactor>
    </item>
    <item>
      <title>Title3</title>
      <description />
      <guid>https://tracker3/torrents.php?id=39385&amp;torrentid=39385</guid>
      <prowlarrindexer id="42">Tracker3</prowlarrindexer>
      <comments>https://tracker3/details.php?id=39385</comments>
      <pubDate>Sun, 26 Jun 2022 18:38:01 +0200</pubDate>
      <size>1073751824</size>
      <link>http://10.0.0.100:9696/28/download?apikey=000000000000000000&amp;link=link&amp;file=Title3</link>
      <category>2000</category>
      <category>100001</category>
      <enclosure url="http://10.0.0.100:9696/4/download?apikey=000000000000000000&amp;link=link&amp;file=Title3" length="1073751824" type="application/x-bittorrent" />
      <category>2000</category>
      <category>100001</category>
      <tag>freeleech</tag>
      <rageid>0</rageid>
      <tvdbid>0</tvdbid>
      <imdb>14549466</imdb>
      <tmdbid>819876</tmdbid>
      <traktid>0</traktid>
      <seeders>1</seeders>
      <files>2</files>
      <grabs>0</grabs>
      <peers>3</peers>
      <minimumseedtime>604800</minimumseedtime>
      <downloadvolumefactor>0</downloadvolumefactor>
      <uploadvolumefactor>2</uploadvolumefactor>
    </item>
  </channel>
</rss>
```
It would be 3 separate files but for "ease" I put everything in one file so I can do the tests easier.
As you can see I set up 3 different timezones, but they are all are the same when converted to my timezone which is UTC+2
```
<pubDate>Sun, 26 Jun 2022 16:38:01 +0000</pubDate>
<pubDate>Sun, 26 Jun 2022 17:38:01 +0100</pubDate>
<pubDate>Sun, 26 Jun 2022 18:38:01 +0200</pubDate>
```
However, when I run Flexget only the last torrent (the CEST one) is added to the downloads.
Looking at the trace log it seems that `rss_pubdate` does not take into account the timezone and therefore the other 2 files are not added.
Here is the trace log:
https://pastebin.com/ythBsydf

I would expect all `rss_pubdate` to be converted to my timezone to be processed properly

Am I doing it wrong or is there a problem with `rss_pubdate`.

J

**Comment by gazpachoking** [comment]
I think probably all of the datetime handling is using naive times, which makes this pretty awkward. Perhaps it's time we start trying to parse more datetimes to be timezone aware. We could perhaps do something fancy to ease compatibility with existing configs, as if we convert rss_pubdate to be timezone aware it will break any comparisons to naive datetimes. I've started using [pendulum](https://pendulum.eustace.io/) in another project, which seems to be a pretty nice library. The hard bit will just be breaking the minimum amount of configs with any new changes.

**Comment by aidan-** [comment]
> We could perhaps do something fancy to ease compatibility

What are you thoughts on how this could be done?  Just add a user controlled config to revert back to timezone naive parsing for a few releases and then deprecate it?  Or something more fancy?

**Comment by Jorman** [comment]
Hi @gazpachoking,

thank you for your reply.
Yes I didn't think about possible broken configurations, although I think they will be really minimal, they will affect everyone like me who needs to deal with timezones other than local, at least I think so.
I didn't know that library, it might be handy, so much as I understand that exactly like `now`, if the date is not aware, it remains naive, so if in the `rss_pubdate` string there is no timezone, it will still be treated as naive, so I don't see any discriminants in doing that, do you?

It is possible to convert all dates to aware considering the local timezone right? Exactly as the `now` function does in its current state, am I wrong?

Ps I think if the dates in `rss_pubdate` are going to be treated as aware, then we will also need to create a function similar to `utcnow`, to also have `rss_pubdate.now`, so that we always treat the dates the same way, am I wrong?

Currently I already edit the xml file to fix some of the fields I need, at this point I can insert one more edit and convert all the dates in `rss_pubdate` in such a way that they take my timezone into consideration, I think it is quite easy, waiting for Flexget to update and treat all the dates the same way.

Do you think this alignment with dates will ever be implemented?

J

**Comment by gazpachoking** [comment]
> Yes I didn't think about possible broken configurations, although I think they will be really minimal, they will affect everyone like me who needs to deal with timezones other than local, at least I think so.

There are a few situations we have to be careful of:
- The timezone isn't included in the field (not sure if the spec guarantees this or not.) This one shouldn't be too bad, I think we just assume user's local timezone in this case, which means it would work pretty much the same as now.
- The user set up their comparison to take in to account the offset already. Not sure there is anything we can do about this other than to document the change and bump our version number if/when it goes through.
- Comparing a timezone aware time to a naive time results in a crash. If we change `now` in jinja filters and the `if` plugin to be timezone aware, it will now crash when compared with any naive times. If we change both `now` and the `rss_pubdate` field to be timezone aware, that will prevent the crash, but people may be using `now` against many more fields than just `rss_pudbdate`

> > We could perhaps do something fancy to ease compatibility
> 
> What are you thoughts on how this could be done? Just add a user controlled config to revert back to timezone naive parsing for a few releases and then deprecate it? Or something more fancy?

My initial thought was related to point 3 above, but I haven't fully thought through whether it's possible or advisable. If we could provide `now` as a timezone aware datetime, that was still able to compare against naive datetimes, by just assuming they were in the same timezone.

A bit separate than fixing timezone issues, pendulum has some other nice things that would be great in our jinja filters:
- [Addition/subtraction](https://pendulum.eustace.io/docs/#addition-and-subtraction):
  old:
  ```yaml
  if:
    - tvdb_ep_air_date < now - timedelta(days=10): reject
  ```
  possible new:
  ```yaml
  if:
    - tvdb_ep_air_date < now.subtract(days=10): reject
  ```
- Human formatted timedeltas, or comparison to now e.g. [diff_for_humans](https://pendulum.eustace.io/docs/#difference-for-humans): ```{{rss_pubdate.diff_for_humans()}}``` could be something like `1 hour ago` which could be useful in notifications

**Comment by Jorman** [comment]
For what I know and I saw, `now` already consider timezone, both because only the +0200 are considered (in my case) and because of this https://github.com/Flexget/Flexget/commit/56aca05e874857c7c1805ab9217c9d10a0de6dfa

Have I interpreted correctly?

I like the new possibility about the timedelta, is more readable

**Comment by gazpachoking** [comment]
> For what I know and I saw, `now` already consider timezone, both because only the +0200 are considered (in my case) and because of this [56aca05](https://github.com/Flexget/Flexget/commit/56aca05e874857c7c1805ab9217c9d10a0de6dfa)
> 
> Have I interpreted correctly?

That commit is only setting the timezone for the scheduler, has nothing to do with time in jinja filters, rss plugin, or if plugin.

**Comment by Jorman** [comment]
Okay, thanks for the information, I didn't notice that it was only for scheduling

**Comment by antivirtel** [comment]
Hi,

I still see this issue today, Flexget version 3.9.4, the `rss_pubdate` still has the source RSS's timezone (and it isn't converted to my local). Eg. I'm in BST timezone currently (UTC+1), some of my RSS sources are in CEST (UTC+2), they all display the wrong their time when I send the notification about the availability of an upload. Can we please reopen the issue?

Thanks

**Comment by gazpachoking** [comment]
I'm not sure there is much to do without properly supporting timezones in dates. It should be addressed when #3758 goes in, but we are waiting for a new release of pendulum, which I think should happen soon. Once that is in, it won't automatically convert everything to local time, but you will have the option of doing that yourself in templates, and comparisons to local time will work properly.

**Comment by antivirtel** [comment]
Hi @gazpachoking, now having pendulum used by Flexget, what Jinja filter would convert the UTC+2 RSS time to my local timezone when trying to send a notify message (email & pushbullet)? (I'm in UTC+1 in the summer).

With Flexget version 3.15.39, I still have this showing time in UTC+2 instead of my local timezone set on the server is UTC+1.

```yaml
message: "⬇{{ rss_pubdate | d(now) | formatdate(\"%H:%M:%S, %a, %d.\") }} {{ task }}\n{{ url }}"
```

Thank you

**Comment by gazpachoking** [comment]
rss_pubdate.in_tz('local')
