### ISSUE TITLE
Unable to install flexget (tried three different methods and server)

### ISSUE THREAD

**Issue by Leonyan938** [Flexget/Flexget#3501]
Below is the error message. I have tried three different way of installing Flexget but all failed. Please see below error message. 

Building wheels for collected packages: zxcvbn-python, psutil
  Running setup.py bdist_wheel for zxcvbn-python ... error
  Complete output from command /root/flexget/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xjaa8_ah/zxcvbn-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-fnmt_jne --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for zxcvbn-python
  Running setup.py clean for zxcvbn-python
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command /root/flexget/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xjaa8_ah/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-6iosseia --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build zxcvbn-python psutil
Installing collected packages: zxcvbn-python, psutil, flexget
  Running setup.py install for zxcvbn-python ... done
  Running setup.py install for psutil ... error
    Complete output from command /root/flexget/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xjaa8_ah/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-i4bbuy22/install-record.txt --single-version-externally-managed --compile --install-headers /root/flexget/include/site/python3.7/psutil:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.7/psutil
    creating build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=590 -DPSUTIL_LINUX=1 -I/root/flexget/include -I/usr/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/flexget/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xjaa8_ah/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-i4bbuy22/install-record.txt --single-version-externally-managed --compile --install-headers /root/flexget/include/site/python3.7/psutil" failed with error code 1 in /tmp/pip-install-xjaa8_ah/psutil/

**Comment by aidan-** [comment]
Can you please share the three different ways you have tried and not just their output?  What version of python are you running? What system is this on? os, version, architecture etc

**Comment by Leonyan938** [comment]
I'm running Debian 10. I normally use two seedbox install scripts to install Flexget, and this is the first time I failed to install Flexget, even though I tried many times and on different servers (GCP, HZ server, OVH server). The python version is 3.7.3.
Below are methods I used to install flexget: First two are open-source seedbox install scripts: https://github.com/Aniverse/inexistence and https://github.com/amefs/quickbox-lite.

1. bash <(wget --no-check-certificate -qO- https://github.com/Aniverse/inexistence/raw/master/inexistence.sh)
2. bash <(wget -qO- https://git.io/qbox-lite -o /dev/null) COMMAND
3. Flexget Official website install instruction.

**Comment by Leonyan938** [comment]
> Can you please share the three different ways you have tried and not just their output? What version of python are you running? What system is this on? os, version, architecture etc

I can see it is fixed now. Thank you for your help!
