### ISSUE TITLE
ImportError: cannot import name 'main'

### ISSUE THREAD

**Issue by specie77** [Flexget/Flexget#3512]
### Expected behaviour:
Utilizing a normal user account - Launch Flexget - even Flexget check

### Actual behaviour:
Sometime in the last month, I think I may have upgraded to Synology DSM 7.1 Update 2, Flexget stopped launching from Task Manager.  Below is the error from the task manager and I was able to replicate in CLI:

<img width="523" alt="Screen Shot 2022-07-30 at 10 24 32 AM" src="https://user-images.githubusercontent.com/29892340/181918753-ea100de0-f2cf-47fa-8ac3-da534f45e2c2.png">

The error is resolved if I execute in CLI as root.  The error is also resolved if I run from Task Manager as root.  However, I have always run this using user "Flexget" without issue, until now.  Running as root full time doesn't seem like a smart idea.

### Steps to reproduce:
#!/bin/sh
cd /volume1/homes/Flexget/.flexget
exec /opt/bin/flexget check

#### Config:

[config.yml.txt](https://github.com/Flexget/Flexget/files/9226620/config.yml.txt)

  
#### Log:
<details>
 <summary>Synology Task Manager and Terminal CLI</summary>

```
Traceback (most recent call last):
  File "/opt/bin/flexget", line 5, in <module>
    from flexget import main
ImportError: cannot import name 'main'
```
</details>

No Flexget log is written

### Additional information:

- FlexGet version: 3.3.22
- Python version: 3.8.12
- Installation method: Local Python Package
- Using daemon (yes/no): Problem occurs with or without daemon
- OS and version: Synology DSM 7.1-42661 Update 2
- Link to crash log: No crash log generated.

**Comment by paranoidi** [comment]
I don't think any of our devs run synology systems and all the guides for it are provided by the community. This is unlikely to be resolved by core team.

Personally, I'd always recommend installing running flexget as user via virtualenv. Tool called pipx does this wonderfully.

**Comment by specie77** [comment]
@paranoidi Thanks for the update! Do you happen to have a guide I can reference? I’d like to try to reconfigure with your suggestion.
