### ISSUE TITLE
self-signed certificates for notifications

### ISSUE THREAD

**Issue by Loader23** [Flexget/Flexget#3522]
Hi,

with verify_ssl_certificates: no its possible to turn off SSL certificate verification on a task. But that does not work for the notifications.
A self hosted ntfy with self-signed certs is not working:
```
Error while sending notification to `ntfysh`: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /test?title=test (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
```
An option to also disable the verification for notifications would be nice :-)

**Comment by ksurl** [comment]
I think this is a ntfy issue, not flexget.

**Comment by Loader23** [comment]
How is this a ntfy issue when flexget says "certificate verify failed: self signed certificate" ?

**Comment by ksurl** [comment]
is that possibly the output from ntfy plugin though?  I saw someone ask on the ntfy discord and they said ntfy doesn't support https for self signed certs

**Comment by Loader23** [comment]
Its the output from the flexget log. So I thought, it must have something to do with flexget.^^
ntfy also does work fine with self signed certs :-)

**Comment by ksurl** [comment]
It's possible then the ntfy plugin is too simple and not supporting self signed certs properly from the global setting.

**Comment by Loader23** [comment]
I still think that should be fixed 😊
