### ISSUE TITLE
Use the torrent name instead of torrent filename

### ISSUE THREAD

**Issue by javikobcn** [Flexget/Flexget#3535]
Hi, is possible to use the torrent name (directory name in the picture) instead of the torrent file (.mkv) to search and rename/move the file?
It's more easy to find the name on tvdb or tmdb with this without errors.  For example, as you can see, the normal method is to use the file with .mkv extension to search, rename, move, etc. But if I can put the name of the dir it's easiest for flexget to do it.

![top gun](https://user-images.githubusercontent.com/20561692/188305911-15874217-db45-401e-9a65-ca9e7b966bc7.png)

**Comment by paranoidi** [comment]
Please open issues only for bugs and feature requests, everything else should be in discussion.
