### ISSUE TITLE
Feature Request: add "watch/providers" to TMDB lookup fields

### ISSUE THREAD

**Issue by neothematrix** [Flexget/Flexget#3545]
hello,
a few years ago themoviedb added a new method allowing to retrieve, together with movies info, also the list of all the streaming providers where the movie is available: https://developers.themoviedb.org/3/movies/get-movie-watch-providers
Could this be added to the fields made available by "tmdb_lookup" so that accept/reject filters could be based on that? i.e. if a movie is present on Netflix/Amazon Prime, reject it, remove it from trakt watchlist or similar scenarios?

thanks!

**Comment by BrutuZ** [comment]
That's a rather long response being split by country and then payment type 👀 

Then there's that footnote:
> **Please note:** In order to use this data **you must** attribute the source of the data as JustWatch. If we find any usage not complying with these terms we will revoke access to the API.

How to attribute it in a CLI interface with little to no output?

**Comment by neothematrix** [comment]
Maybe the long response could be filtered with the country code/payment type via a parameter, similar to the "language" parameter that is possible to pass to tmdb_lookup and can help in filtering and have a flat list with just the list of providers offering the movie?

Regarding the attribution, I'm no expert, but if your flexget configuration reports something like "justwatch_country: uk" and/or "justwatch_subscriptiontype: flatrate" it's probably enough?
