### ISSUE TITLE
Node 12 deprecation on github actions

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#3575]
see info [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

The deliverybot deployment status action has not been updated since 2019 and is still using node12. Looks like the dev has not been updating it. Maybe time to look for an alternative before it breaks next summer.

**Comment by gazpachoking** [comment]
This one looks a little more active, but also hasn't been updated. Maybe we wait till a little closer to the end date to decide. https://github.com/marketplace/actions/deployment-status

I have to admit, I'm not 100% clear what a 'deployment' is in our case, or what the actions are doing. I think we are just using at as an intermediary to somehow verify the status of all checks have passed before triggering a release.

**Comment by gazpachoking** [comment]
I think we still need to take care of this. Looks like that alternative I linked has been updated to new node. Haven't researched if there is a better one.

**Comment by ksurl** [comment]
It looks like it's the best option. It does have an extra field required to run, the deployment id. since this job is called from another workflow, is there any way to pass that value to the child workflow? This action assumes it runs in the same job that creates the deployment since it has an action available to create deployments also (maybe the nightly workflow can also switch to that rather than the github script?)

**Comment by ksurl** [comment]
Do you think it's worth forking and just updating the action to run on node16? The code in index.js looks pretty straightforward though I don't know if there's any breaking changes in node 12->16. 

also it seems to still be running fine in the latest actions. so maybe leave it alone even though it is supposed to be removed by now (github cut over last month to node16 by default)

**Comment by gazpachoking** [comment]
I don't think we should need to make our own action, there should be some fairly straightforward way to use existing ones. I'll have to take a peek, because I forget what it's even doing.

**Comment by ksurl** [comment]
it sets a deployment status but I don't even see any workflows creating a deployment. unless that means the pypi package publishing which is in the release workflow and uses a twine script. I was going to say it's vestigial but I don't know what I don't know.

**Comment by ksurl** [comment]
Github must have upgraded the runners by now? Is this still an open issue or can be closed until it breaks some time later?

**Comment by gazpachoking** [comment]
It looks like we are still getting that deprecation warning. Seems like someone forked the action we are using, switching to this is probably the path of least resistance. https://github.com/justacodename/deployment-status

**Comment by ksurl** [comment]
PR https://github.com/Flexget/Flexget/pull/3892
