### ISSUE TITLE
changelog is still broken

### ISSUE THREAD

**Issue by trim21** [Flexget/Flexget#3579]
https://github.com/Flexget/Flexget/releases/tag/v3.3.39

**Comment by gazpachoking** [comment]
I think this one might actually be expected. There was no commits that had the proper changelog tags, so the changelog was empty at the time of release.

**Comment by gazpachoking** [comment]
Perhaps the bit to update the release body shouldn't be in the actual release workflow.. maybe it's done on another workflow that triggers on a new release. That way it could be after the changelog is updated, and will include the link to all the commits within that version.

**Comment by gazpachoking** [comment]
> Could not find version 3.3.39 in changelog

Yeah, because it wasn't in there at the time of release. That line only got generated when the changelog workflow ran _after_ the release. That's why I'm reconsidering where to run that particular bit from.

**Comment by trim21** [comment]
maybe just create a dummy git tag for `env.release_tag` and generate changelog

**Comment by ksurl** [comment]
this was what I was afraid of with the timing of the workflows. it should probably run in the wiki changelog workflow

**Comment by gazpachoking** [comment]
> this was what I was afraid of with the timing of the workflows. it should probably run in the wiki changelog workflow and update both simultaneously

That's probably most ideal, but I didn't see a super easy way to update the existing release. Let's see what happens with the current method next time we actually have changelog entries for a release.

**Comment by gazpachoking** [comment]
I think it's good enough for now. Moving it over to the changelog workflow might improve it slightly, but I don't think it makes much difference.
