### ISSUE TITLE
Error using docker image : exec /config/entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by Zw012d** [Flexget/Flexget#3608]
I am using docker compose for flexget but keep getting this error.

`exec /config/entrypoint.sh: no such file or directory`

 My compose file is below

      flexget:
        image: ghcr.io/flexget/flexget
        container_name: flexget
        environment:
          - TZ=UTC
        entrypoint: /config/entrypoint.sh
        volumes:
          - /mnt/d/docker/flexget:/config
        ports:
          - 5050:5050

entrypoint.sh

    #!/bin/sh
    apk add --no-cache curl;
    pip install pysocks;
    flexget daemon start --autoreload-config;

i have already done chmod+x to make it executable ( ls -la in /mnt/d/docker/flexget)

![Untitled](https://user-images.githubusercontent.com/76645315/201509901-60a54509-a045-46cf-9f6b-e5fa25e97a9a.png)

**Comment by ksurl** [comment]
It looks correct to me. Does it exit or stays running? If it runs, try docker exec -it flexget bash and then ls /config. It might be a  permission issue with the owner

**Comment by Zw012d** [comment]
Contianer extis . but if i remove `entrypoint` like below and use `command` it runs without issues and i go to /config folder in container it shows user has permissions. 

    services:
      flexget:
        image: ghcr.io/flexget/flexget
        container_name: flexget
        command:
          - daemon
          - start
          - --autoreload-config         # optional
        ports:
          - 5050:5050                   # optional: for webui
        environment:
          - TZ=$TIMEZONE                # optional: defaults to UTC
        volumes:
          - /host/config:/config        # required
 
Is there another way i can install packages without using entrypoint ?

**Comment by ksurl** [comment]
the image entrypoint is `flexget` so you need to override it if you want to run anything before running flexget. the other option is to build your own using it as a base image.

```
FROM ghcr.io/flexget/flexget

RUN apk add --no-cache curl && pip install pysocks
```

**Comment by Zw012d** [comment]
> assuming you're using the latest image?

yes i am pulling the latest images


> you don't need `;` in your lines. also not sure if it matters but add a new line between the `#!/bin/sh` and 1st line.

same issue

>other option is to build your own using it as a base image.

Thanks i will try that . Also for the time being i will keep this issue open untill we know more why it is occuring

**Comment by ksurl** [comment]
Can you try a simpler test script? Something that just echo hello and exit

Then try adding flexget at the end.

I'm using a custom entrypoint script as well but it finds it and runs fine.

**Comment by Zw012d** [comment]
@ksurl  Thanks , i have found the issue. It is caused by saving the executable in windows. If someone have this isssue it can be fixed by using the below command.

`sed -i -e 's/\r$//' entrypoint.sh`

Link  - https://stackoverflow.com/questions/38905135/why-wont-my-docker-entrypoint-sh-execute

**Comment by gazpachoking** [comment]
> @ksurl Thanks , i have found the issue. It is caused by saving the executable in windows. If someone have this isssue it can be fixed by using the below command.
> 
> `sed -i -e 's/\r$//' entrypoint.sh`
> 
> Link - https://stackoverflow.com/questions/38905135/why-wont-my-docker-entrypoint-sh-execute

Oh wow, that's really subtle. Good investigation work. That error is confusing, really seemed like `/config/entrypoint.sh` was the thing that didn't exist, rather than `/bin/sh\r` being the culprit.

**Comment by ksurl** [comment]
Ah yes, the new line windows crlf vs unix lf. Good to hear it's fixed. Notepad++ can also change it easily
