### ISSUE TITLE
depending on backports-zoneinfo backports.zoneinfo

### ISSUE THREAD

**Issue by abugher** [Flexget/Flexget#3610]
### Expected behaviour:

`pip3 install flexget` or equivalent should install flexget.

### Actual behaviour:

```
Collecting backports-zoneinfo==0.2.1; python_version >= "3.7" and python_version < "3.9" (from flexget)
  Could not find a version that satisfies the requirement backports-zoneinfo==0.2.1; python_version >= "3.7" and python_version < "3.9" (from flexget) (from versions: )
No matching distribution found for backports-zoneinfo==0.2.1; python_version >= "3.7" and python_version < "3.9" (from flexget)
```

### Additional information:

A dependency error is reported because no suitable version of `backports-zoneinfo` can be found.  PyPI seems to have no such package, but there is `backports.zoneinfo` with the expected version number.  Manually adjusting the requirement allows flexget to be installed and to run.

I am assuming that the `METADATA` file in the package, where I made my edit, corresponds to `requirements.txt`.  I see that the relevant line in `requirements.txt` was added just over a month ago with commit 4358202cab5223da65ad90b20679f03cfdd7a8eb .  The commit message is "Try out poetry for dependency management", so I wonder if poetry made the mistake.

### Recommendation:

```
s/backports-zoneinfo/backports.zoneinfo/
```

**Comment by gazpachoking** [comment]
This is an issue with old versions of pip. The new packaging standard
normalizes to dashes, but old pip versions don't understand. Should work
fine if you upgrade pip

**Comment by abugher** [comment]
Thank you for the quick answer.  I'm taking that to mean WNF since the code is correct, and the real problem is that my environment was too old.

Be advised that the pip shipped with Debian 10 Buster doesn't seem new enough to handle it.  Debian 11 Bullseye is currently marked "stable", but 10 is "oldstable", and it looks like 9 is "LTS".  So this will affect any of those users, but only if they try to install or update flexget using the pip supplied by the OS.  I don't know how common that is, and I'll just let you figure out whether that's something to worry about.

I'm up and running, though.  I appreciate you keeping up the project.  I've gotten years of use out of flexget, with no end in sight.

Closing.

**Comment by gazpachoking** [comment]
I've been thinking for a while about changing our docs to have pipx as the
primary install method. I believe that would automatically use a new
version of pip, as well as take care of isolating the install in a virtual
environment and adding flexget to the PATH. Maybe it's time to pull the
trigger on that
