### ISSUE TITLE
Feature request: a combination of loose and optimistic for release estimations

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#3614]
https://flexget.com/Plugins/discover

> loose will check for release dates, if release date can not be determined perform search anyway.
> optimistic sets the estimation mode to strict but starts searching interval units (eg. 7 days) before release date.

The recommended option is `optimistic` but this will prevent flexget from searching for movies that don't have a release date on blu-ray.com. This should be covered by `loose` - it will perform the search anyway but apparently honors the release date reported by blu-ray.com - and I've observed that sometimes releases are available much sooner than that.
Since neither of these options suit me I'm forced to use `ignore` which will make flexget search for movies which have obviously not yet released - making dozens of unnecessary requests.

Ideally I would like to have a combination of loose and optimistic - i.e. have `loose` accept interval units just like `optimistic` does.

**Comment by aidan-** [comment]
@girtsl I've had a crack at implementing this in #3650 - it'd be great if you could give it a test and make sure it fits your requirements.

**Comment by girtsl** [comment]
@aidan-, thanks for taking a stab at this. Unfortunately I don't have an environment where I could test this and verify that it covers the cases I put forth but I have a few comments.

I had 2 cases to cover:
- when the release date cannot be determined, the search would be performed anyway;
- if the release date can be determined, perform the search `{interval}` before it.

I was not able to test this and by reading the PR's source code I was not able to determine if the first case would be covered (I'm a Python noob, though), perhaps the behavior is implicit.
However, not only are the changes in #3650 breaking, IMO they are also not very intuitive - where there was just one configuration option (`release_estimations`), now there are two. The interval is also not relevant to all modes (it seems most of them would ignore it). This is for the maintainers to decide though.
