### ISSUE TITLE
Feature request: make delay conditional based on the entry's fields

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#3621]
This is the same idea I've posted in discussions - https://github.com/Flexget/Flexget/discussions/2883. It hasn't gained any attention there but I'm reposting with the hope it might get some here.

Today I have two tasks that both filter entries on quality: first one only accepts 2160p, the second one - 1080p. The second task also delays all matches by 7 days with the expectation that a 2160p entry might soon appear. 
This works reasonably well but I'd like more control over by how much entries are delayed, based on certain metadata fields. E.g. if the release year is 198x there is little chance that a 2160p entry will appear within my specified delay. Or more generally [in an abstract syntax] - `entry.release_year <= now.year - 2 ? 0 : 7d` - this would immediately accept all entries whose release date is 2019 or earlier and delay the rest for 7 days.
Is something like that possible today? If not - would it be hard to implement?

**Comment by gazpachoking** [comment]
I think this should be possible using the `delay` plugin inside the `if` plugin?

**Comment by girtsl** [comment]
Well, now I feel silly because an `if` is essentially what I was describing but somehow it didn't occur to me that there would be such plugin. Thanks! The docs on `if` even have an example based on the entry's year.
For anyone else wondering, the answer to my question is:
```yaml
trakt_lookup: yes
if:
  - movie_year > now.year - 2:
      delay: 7 days
```
