### ISSUE TITLE
Not Bug: CRITICAL manager Failed to find configuration file config.yml

### ISSUE THREAD

**Issue by levenwindy** [Flexget/Flexget#3654]
### Additional information:
- FlexGet version: 3.5.17

For convenience after migration, I put config.yml in other location /volume1/config.yml, only run
```
flexget -c /volume1/config.yml status
# or
cd /volume1
root@:/volume1# flexget status
```
Otherwise it will report an error

#### Log:
```
CRITICAL manager Failed to find configuration file config.yml
manager Tried to read from: /root, /root/.flexget, /root/.config/flexget
```

Eventually, I found manager.py, and modified it to work properly.

*/site-packages/flexget/manager.py
```
     def _init_config(*):
        possible = []
# added this
        possible.append('/volume1/')
```

Is there any simpler or general way to deal with this problem?

**Comment by gazpachoking** [comment]
You could make an alias that includes your config flag

**Comment by BrutuZ** [comment]
Creating a symlink on one of the valid paths pointing to the new location is another option

**Comment by levenwindy** [comment]
> You could make an alias that includes your config flag

```
alias flexget='flexget -c /volume1/ $1'
```
is it like this?

**Comment by ksurl** [comment]
`alias flexget=flexget -c /volume1/config.yml`

alias is just a placeholder so anything you type after will be appended. so if you run `flexget status` it is the same as `flexget -c /volume1/config.yml status` after you set the alias
