### ISSUE TITLE
urlrewriter doesn't work

### ISSUE THREAD

**Issue by v-milenin** [Flexget/Flexget#3661]
Hi!
I have such issue and i don't know, why it doesn't work.

Urlrewriter yml settings:

    `urlrewrite:
      kinozal:
        regexp: 'https://kinozal.tv/details.php\?id=(?P<id>\d+)'
        format: 'https://dl.kinozal.tv/download.php?id=\g<id>'`

the piece of rss feed:

              `
              <item>
                  <title>Blue Bloods </title>
                  <link>https://kinozal.tv/details.php?id=1936533</link>
                  <category>46</category>
                  <guid>https://kinozal.tv/details.php?id=1936533</guid>
                  <pubDate>Wed, 18 Jan 2023 19:11:42 +0300</pubDate>
              </item>
              `

So when the flexget executes, the debug shows only replacing of guid field and title (because i use the field "guid" as the title) field. No one record with urlrewrite plugin:

```
DEBUG    manipulate    kinozal         field: `title` from_field: `title` field_value: `1936533`
DEBUG    manipulate    kinozal         field `title` after replace: `1936533`
DEBUG    manipulate    kinozal         field: `guid` from_field: `guid` field_value: `https://dl.kinozal.tv/download.php?id=1936533`
DEBUG    manipulate    kinozal         field `guid` after replace: `https://dl.kinozal.tv/download.php?id=1936533`
<...>
VERBOSE  task          kinozal         REJECTED: `1936533` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Unexpected html content received from `https://kinozal.tv/details.php?id=1936533` - maybe a login page?)

```

I've tried to force the field "guid" as the "link", but with no result.

**Comment by BrutuZ** [comment]
```
    format: 'https://dl.kinozal.tv/download.php?id=\g<id>'`

DEBUG    manipulate    kinozal         field `guid` after replace: `https://dl.kinozal.tv/download.php?id=1936533`
```
Looks like it's working. Maybe `urlrewrite` is just lacking some log output?

**Comment by v-milenin** [comment]
> ```
>     format: 'https://dl.kinozal.tv/download.php?id=\g<id>'`
> 
> DEBUG    manipulate    kinozal         field `guid` after replace: `https://dl.kinozal.tv/download.php?id=1936533`
> ```
> 
> Looks like it's working. Maybe `urlrewrite` is just lacking some log output?

Unfortunally, no. This is a result of "manipulate" function, which works with "guid" field. I've made the same transform for this to check my regexp rule for "urlrewrite". So the rule makes the proper transform, but urlrewriter doesn't want to work.

In case of "urlrewriter" there should be "urlrewrite" instead of "manipulate" in the log, but there is no such word in my log.

**Comment by BrutuZ** [comment]
Maybe the link tag isn't being mapped properly to the url field?
```yaml
tasks:
  test:
    mock:
      - { title: 'Blue Bloods', url: 'https://kinozal.tv/details.php?id=1936533'}
    accept_all: yes
    urlrewrite:
      kinozal:
        regexp: 'https://kinozal.tv/details.php\?id=(?P<id>\d+)'
        format: 'https://dl.kinozal.tv/download.php?id=\g<id>'
```
```
--test execute --dump accepted eval
2023-01-19 00:45:11 INFO     manager                       Test mode, creating a copy from database ...
2023-01-19 00:45:13 VERBOSE  manager                       Creating new database C:\Users\BrutuZ\flexget\test-test.sqlite - DO NOT INTERRUPT ...
2023-01-19 00:45:15 VERBOSE  task_queue                    There are 3 tasks to execute. Shutdown will commence when they have completed.
2023-01-19 00:45:15 VERBOSE  details       test            Produced 1 entries.
2023-01-19 00:45:15 VERBOSE  task          test            ACCEPTED: `Blue Bloods` by accept_all plugin
2023-01-19 00:45:15 INFO     urlrewriter   test            Entry 'Blue Bloods' URL rewritten to https://dl.kinozal.tv/download.php?id=1936533 (with urlrewrite)
2023-01-19 00:45:15 VERBOSE  details       test            Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2023-01-19 00:45:15 WARNING  task          test            Task doesn't have any output plugins, you should add (at least) one!
─── Accepted ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
title         : Blue Bloods
url           : https://dl.kinozal.tv/download.php?id=1936533
original_url  : https://kinozal.tv/details.php?id=1936533
accepted_by   : accept_all
media_id      : None
original_title: Blue Bloods
quality       : unknown
task          : test

2023-01-19 00:45:16 INFO     manager                       Removed test database
```

**Comment by v-milenin** [comment]
Thanks for help and reply!
i've tried your test config and my config with the option "accept_all", and urlrewriter changed all urs using my format. So i think, that the problem is in my series list, because as i have understood, urlrewrite works only for accepted series, so i'll try to dig into this way.

**Comment by v-milenin** [comment]
I don't know why, but now it's working. Maybe it was a mistake in rss file.
