### ISSUE TITLE
Improve series processing

### ISSUE THREAD

**Issue by paranoidi** [Flexget/Flexget#3691]
The series plugin should be able to process entries by learning them into series db. As discussed on chat.

Solution:

- Deprecate parse_only option
- Introduce new `do` option which takes list of operations done

Example:

```
do: [parse]
do: [parse, learn]
do: [parse, learn, accept, reject]  # default value
```

Values accept, reject might be combined into single option "actions" ?

In future, this can be expanded into verifying successful download in local filesystem when doing sorting task.

- Add new verified column (datetime)
- Add new `do` option `verify` that marks current datetime there
- Add new series option `verify: 10 hours` after which new download is allowed.

**Comment by paranoidi** [comment]
@Ram-Z ping

**Comment by gazpachoking** [comment]
```
do: [parse]
do: [parse, learn]
do: [parse, learn, accept, reject]  # default value
```
Are there instances where we wouldn't want the previous modes? i.e. would we ever want 'learn' without 'parse'? Or the filtering without learn? Maybe it could just be `mode: parse|learn|filter`

**Comment by paranoidi** [comment]
@gazpachoking  yes, spesifically the future plan mentioned `do: [parse, verify]` in the sorting task

**Comment by gazpachoking** [comment]
Oh, I missed the whole verify idea, that's interesting. I assume the use of that would be to somehow make a task that forgets episodes that haven't been verified after some time?

**Comment by paranoidi** [comment]
Something like that or make series plugin option that ignores unverified downloads after some period of time. Also CLI could show verified status, not just download status.
