### ISSUE TITLE
KeyError: 'infohash_v1' when using From_qbittorrent plugin

### ISSUE THREAD

**Issue by qqzzxx** [Flexget/Flexget#3735]
config:

```
tasks:
 sometask:
  from_qbittorrent:
   host: localhost
   port: 8080
   username:
   password:
   completed: yes
   category: free
  accept_all: yes
    
  transmission:
   host: localhost
   port: 9092
   username:
   password:  
```
Crash Log:
<details><summary>Details</summary>
<p>
2023-04-08 04:44:57 CRITICAL task          mt free qbt to tr BUG: Unhandled error in plugin from_qbittorrent: 'infohash_v1'
Traceback (most recent call last):

  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f40b77bd900>
    └ <Thread(task_queue, started daemon 139915809753912)>
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f40b77bd630>
    └ <Thread(task_queue, started daemon 139915809753912)>
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 139915809753912)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 139915809753912)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f40b0887190>>
    └ <Thread(task_queue, started daemon 139915809753912)>
  File "/usr/lib/python3.10/site-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f40b47141f0>
    │    └ <flexget.task.Task object at 0x7f40b46efd30>
    └ <flexget.task_queue.TaskQueue object at 0x7f40b0887190>
  File "/usr/lib/python3.10/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f40b46efd30>
           └ <function Task.execute at 0x7f40b4714160>
  File "/usr/lib/python3.10/site-packages/flexget/task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f40b47140d0>
    └ <flexget.task.Task object at 0x7f40b46efd30>
  File "/usr/lib/python3.10/site-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x7f40b46efd30>
  File "/usr/lib/python3.10/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f40b46efd30>, {'host': '192.168.1.66', 'port': 8080, 'username': 'admin', 'password': 'admin...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=from_qbittorrent)>
               └ <flexget.task.Task object at 0x7f40b46efd30>
> File "/usr/lib/python3.10/site-packages/flexget/task.py", line 550, in __run_plugin
    result = list(result)
                  └ <generator object FromQBitTorrent.on_task_input at 0x7f40b46b6180>
  File "/usr/lib/python3.10/site-packages/flexget/plugins/clients/qbittorrent.py", line 375, in on_task_input
    torrent_info_hash=torrent['infohash_v1'],
                      └ AttrDict({'added_on': 1680926977, 'amount_left': 0, 'auto_tmm': True, 'availability': 1, 'category': 'free', 'completed': 331...

KeyError: 'infohash_v1'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flexget/task.py", line 550, in __run_plugin
    result = list(result)
  File "/usr/lib/python3.10/site-packages/flexget/plugins/clients/qbittorrent.py", line 375, in on_task_input
    torrent_info_hash=torrent['infohash_v1'],
KeyError: 'infohash_v1'

</p>
</details> 
### Additional information:

- FlexGet version: 3.5.36
- Python version: 3.10
- Transmission version: 3.00
- Qbittorren version: 4.3.9
- Installation method: pip
- OS and version: Synologh, Docker

**Comment by Insulinocytus** [comment]
@qqzzxx 
Same problem here. How you fix this?

**Comment by Insulinocytus** [comment]
I've figured out the cause of the issue. Only qBittorrent versions after 4.5.1 return the infohash_v1 attribute, so version 4.3.9 will throw an error.

https://www.qbittorrent.org/news#sunday-feb-12th-2023---qbittorrent-v4.5.1-release
