### ISSUE TITLE
Plugin proposol: add download name `dn` to magnet link

### ISSUE THREAD

**Issue by trim21** [Flexget/Flexget#3747]
suggest a plugin to add download name to magnet link

it process link with `magnet:?xt=urn:sha1:...` to `magnet:?xt=urn:sha1:...?dn=...` with `entry["title"]`

And I have a woking plugin to do this, I'd like to send a PR if you are open to this

**Comment by BrutuZ** [comment]
Can't achieve that with `set`?
```yaml
set:
  url: '{{url}}&dn={{title}}'
```

**Comment by trim21** [comment]
> Can't achieve that with `set`?
> 
> ```yaml
> set:
>   url: '{{url}}&dn={{title}}'
> ```

need escaping

**Comment by BrutuZ** [comment]
`{{title|urlencode}}`

**Comment by gazpachoking** [comment]
I'm not against it, but I also don't really see it being super useful. I'm a +0

**Comment by trim21** [comment]
ack

**Comment by trim21** [comment]
ack
