### ISSUE TITLE
docker: reuse base docker image

### ISSUE THREAD

**Issue by trim21** [Flexget/Flexget#3748]
we have locked all requirements, so it's possible to reuse base docker image between versions.

we can build a base docker image based on `${{ hashFiles('requirements-docker.txt') }}` and re-used it, just build flexget wheel if previous base docker image exists. generate base docker image tag hash, try pull, and build new one if not exist, then push it.

# Pro

So if we we only change one source file and push a new version, users only need to pull very small layers with only source code change, most size of docker image will be reused from previous pulled docker image.

```text
base --- requiremenets --- src # version 0.0.1
                |-----  new src # version 0.0.2
```

# Con

developers can't build docker image from repo directly, them need to build base docker image like ci workflow.

**Comment by gazpachoking** [comment]
Is this just to speed up build times? Is it possible we could keep the dockerfiles simpler but use something like this in github actions to achieve something similar?
https://docs.docker.com/build/cache/backends/gha/

**Comment by trim21** [comment]
> Is this just to speed up build times?

To make users pull smaller size of docker image.

**Comment by gazpachoking** [comment]
> To make users pull smaller size of docker image.

Oh right, you said that.

Doesn't docker already divide any image up in to layers created on each line of the Dockerfile? An user should only need to download layers after a changed step, so it seems like we could achieve something similar by just optimizing the order of the lines in the Dockerfile.

**Comment by trim21** [comment]
> Is it possible we could keep the dockerfiles simpler but use something like this in github actions to achieve something similar?

Yes, but this is **one layer**

https://github.com/Flexget/Flexget/blob/bf0fd6d311f66fd89f7490a3682f1ce8de43a48f/Dockerfile#L35-L41

**Comment by trim21** [comment]
> Why not just split it up then to make multiple layers? Seems simpler than making totally separate docker files and images.

after second thoughts, docker image will storage file metadata like create time and mod time, so it would be very hard to generate generate same layer hash in different build, reuse docker image would be easier

**Comment by gazpachoking** [comment]
Ahh, maybe I see. Having the separate builder image makes it a bit complicated to optimize the layers.
I'm not sure I'm totally sold on this though, my preference is to keep things simple, and I'm not sure saving a bit of bandwidth on upgrade seems worth it to me.

**Comment by gazpachoking** [comment]
I meant optimizing the layers in our current single dockerfile vs splitting out into multiple dockerfiles.

How much of a problem is having a bigger pull on upgrade? How much space does this save per version (where the deps didn't change)?

**Comment by trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/235270643-8c7ba324-d9eb-45bd-91ba-e495967e0699.png)

```text
ubuntu@localhost ~ $ docker history ghcr.io/trim21/flexget2:develop
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
c3ea423113d3   5 minutes ago   RUN /bin/sh -c ls -ahl /wheels &&     pip in…   38.7MB    buildkit.dockerfile.v0
<missing>      5 minutes ago   COPY /wheels /wheels # buildkit                 9.14MB    buildkit.dockerfile.v0
<missing>      7 minutes ago   ENTRYPOINT ["flexget"]                          0B        buildkit.dockerfile.v0
```

uncompressed 37mb

**Comment by gazpachoking** [comment]
Looking closer at your PR... is there a reason we can't just join your two files back into the same dockerfile? I think that should accomplish both of our goals?

**Comment by trim21** [comment]
> Looking closer at your PR... is there a reason we can't just join your two files back into the same dockerfile? I think that should accomplish both of our goals?

because different build from same requirement may not have same layer hash...

**Comment by gazpachoking** [comment]
Maybe building the wheels for deps to a different folder and copying them separately (and first) to final image will do the trick?

**Comment by gazpachoking** [comment]
@trim21 Still waiting to see if everything passes and builds properly. But #3760 is what I was thinking of to get some of the layer caching we want without separating to separate built images. What do you think?

**Comment by trim21** [comment]
@gazpachoking can you manually trigger that job again

**Comment by gazpachoking** [comment]
> can you manually trigger that job again

The tests on your PR? Sure, just reran it.

**Comment by trim21** [comment]
> > can you manually trigger that job again
> 
> The tests on your PR? Sure, just reran it.

3760

**Comment by trim21** [comment]
> > 3760
> 
> reran that one too

I see, you are right, steps are cached. I think it works fine.
