### ISSUE TITLE
Document pipx install method

### ISSUE THREAD

**Issue by furoTmark** [Flexget/Flexget#3770]
### Expected behaviour:

Plugins would get noticed when installing via pipx. 
Documentation should reflect how to install a plugin with pipx.

### Actual behaviour:

Plugins do not get notices

Fix: pipx inject flexget <<plugin name>>

### Steps to reproduce:
- Step 1: Follow the guide from https://flexget.com/InstallWizard/RPi4Lite
- Step 2: Pick a plugin and install it with pip

#### Config:
```yaml
Paste FULL config and remove any personal info if config is too long, attach the file to the ticket.
If issue is with a single task, you can get get resulting configuration by running:
  flexget execute --task <NAME> --dump-config
Make sure to redact any personal information (passwords, api keys, etc) !
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: latest
- Python version: 3.9
- Installation method: https://flexget.com/InstallWizard/RPi4Lite
- Using daemon (yes/no): yes
- OS and version: RPi
- Link to crash log:

**Comment by gazpachoking** [comment]
We have been meaning to write up some more explicit instructions to use pipx as a recommended install method. Is this ticket for just that, or are you having an issue getting it to work? I think you already figured it out, for plugins that have an optional extra dependency they can indeed be added with pipx inject, for example transmission-rpc:
```sh
pipx install flexget
pipx inject flexget transmission-rpc
```

**Comment by furoTmark** [comment]
Yes, it is mainly for updating the documentation.

Thanks!

**Comment by paranoidi** [comment]
Added note to [RPi4Lite](https://flexget.com/InstallWizard/RPi4Lite)
