### ISSUE TITLE
transmission-rpc versions mismatch

### ISSUE THREAD

**Issue by idogrf** [Flexget/Flexget#3833]
### Expected behaviour:
Installed transmission-rpc version in the docker image should be >=4.1.4 and < 5.0.0

### Actual behaviour:
Installed version is 6.0.0 (release on september 1st)
This results in an error when trying to run flexget and transmission - `transmission-rpc module version mismatch, requiring transmission-rpc>=4.1.4,<5.0.0`

### Steps to reproduce:
- Step 1: docker pull wiserain/flexget:3.9
- Step 2: docker run wiserain/flexget:3.9 pip show transmission-rpc
- Step 3: See the version printed out (currently 6.0.0)

**Comment by gazpachoking** [comment]
We don't maintain the wiserain image. You could open up a ticket [over there.](https://github.com/wiserain/docker-flexget/issues)
We do supply our own docker image which could be used as well.  https://flexget.com/en/InstallWizard/Docker#official-image

**Comment by idogrf** [comment]
oh, sorry for the confusion 😞
thanks for the great product 🙏
