### ISSUE TITLE
Feature Request: Develop a plugin for Download Station (Synology)

### ISSUE THREAD

**Issue by once375ml** [Flexget/Flexget#3865]
Hi, All.

Yesterday, I installed Radarr for test purpose. I found it integrates Download Station (Synology) as a downloader, which you can pass on torrents, specify download path and categorize torrents.

Since Radarr has realized these functions and it is opensource in GitHub, would you please adopt some code(s) from it and develop the same functions for Flexget? This will greatly help Download Station users, as Deluge, Transmission, rTorrent, qBittorrent have had their own plugins.

Thanks in advance!

**Comment by gazpachoking** [comment]
This would have to be something that someone with a Download Station creates and contributes. Happy for someone to take up the task.
