### ISSUE TITLE
Support newer setuptools

### ISSUE THREAD

**Issue by TnTBass** [Flexget/Flexget#3873]
I have been using flexget using pip installs for a while.

I upgraded my setuptools and I get this warning:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flexget 3.8.0 requires setuptools==65.6.3; python_version >= "3.7" and python_version < "4.0", but you have setuptools 68.2.2 which is incompatible.

```

Everything still seems to work fine, but the dependencies expect a certain version of setup tools. Any chance this can be updated?

**Comment by gazpachoking** [comment]
We pin all of our deps to make sure installs and issues are reproducible across the most systems possible. (For this reason, it's important to install Flexget in its own virtualenv.) Latest release has setuptools pinned to 68.0.0, which is the last release that supports python 3.7. Once we drop support for python 3.7 the pinned setuptools version will also update.
