### ISSUE TITLE
all rss feed items are downloaded every times rss feed is fetched

### ISSUE THREAD

**Issue by trim21** [Flexget/Flexget#3971]
### Expected behaviour:

I have a rss feed with all generated dynamically. Which mean it can't be cached by url.

In this case, rss plugin will re-download all torrents every times it fetch this rss feed.

### Actual behaviour:

Hope rss plugin could cache torrent file by rss feed url and it's guid. 

### Steps to reproduce:

make a rss feed with guid fiexed, and enclosure url changed.

flexget run task with rss plugin

you will find all torrents downloaded, every times.

### Additional information:

- FlexGet version: 3.11.27

**Comment by BrutuZ** [comment]
Add the unique field to the seen plugin?

**Comment by trim21** [comment]
> Add the unique field to the seen plugin?

torrent is downloaded by rss plugin I think

https://github.com/Flexget/Flexget/blob/07b56d611531f53adec9020a05985759e9304a58/flexget/plugins/input/rss.py#L270-L273

**Comment by trim21** [comment]
looks like I'm wrong about this, closing it.
