### ISSUE TITLE
How To Make Flexget Check ifA Local paht

### ISSUE THREAD

**Issue by once375ml** [Flexget/Flexget#3991]
if:
      - "'BMDru' in title and transmission_secondsSeeding > 86400": accept
      - "'BMDru' in title and os.path.exists(transmission_downloadDir)": accept

I have confirmed the first line works. 

But sometimes, files are removed remotely by Syncthing. In this case, I would like to check if the directories exists for the torrents. If not, ask Transmission to purge the related torrents.

How does Fleget check if a directory exists?

Or another solution: What the parameter for torrent create time? "transmission_date_done: is the done time. "transmission_date_created"??

**Comment by gazpachoking** [comment]
> Or another solution: What the parameter for torrent create time? "transmission_date_done: is the done time. "transmission_date_created"??

Running with --dump is the best way to discover entry fields you can use. e.g. `flexget --test exec --task mytask --dump`

You might be able to use [exists](https://flexget.com/en/Plugins/exists) plugin to detect if something exists.
