### ISSUE TITLE
update quality match

### ISSUE THREAD

**Issue by andrei376** [Flexget/Flexget#4043]
example:
1.    Test.S02E04.2160p.WEB-DL.DDP5.1.DoVi.H.265-xyz
2.    Test.S02E04.2160p.WEB-DL.DDP5.1.HDR.H.265-xyz
3.    Test.S02E04.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-xyz

Please update quality match for:
"2160p webrip|webdl hdr|hdrplus"

to match number 2 and 3

currently this quality matches only number 2

"HDR" text is present in 3 so it should match that "hdr|hdrplus"

**Comment by gazpachoking** [comment]
The issue is that 3 is getting detected as dolbyvision, which is considered a separate higher quality than plain hdr. You could change `hdr|hdrplus` to `hdr|hdrplus|dolbyvision` or `hdr+` or `>=hdr` to allow matching it.

**Comment by andrei376** [comment]
"hdr|hdrplus|hdr+"  will match only 1

(my TV does not support dovi in mkv, so that's why i need  2 or 3 and to avoid 1)

**Comment by gazpachoking** [comment]
Hmm. I guess I don't know what the tags mean. When it has 'dovi' and 'hdr' in the title, does that mean it has 2 separate audio streams? The issue is that our parser only picks the highest matching quality, it isn't built to support files that have multiple streams contained.

**Comment by BrutuZ** [comment]
For reference, we already had this discussion on #4042 but they failed to mention it on the OP

**Comment by gazpachoking** [comment]
Ahh. Yeah, our parser is not compatible with multiple streams is the answer. And it isn't an easy thing to change. (It also isn't an easy thing to know based on the title. Some files might have 'dovi.hdr' and just be dovi, since dovi is a type of hdr.)

**Comment by gazpachoking** [comment]
You could use the regex plugin instead to do a more naive match. Just reject everything that doesn't have "hdr" in the title, and use quality plugin to do the other bits.
