### ISSUE TITLE
Error: --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#61]
Hi!

I've been tried to upgrade to the latest version(1.1.66) today, but after running this command: sudo pip install --upgrade flexget - the pip reported error. I've uploaded the full output, and the last pip log from root dir: http://paste2.org/GD5Z5JEk (my username has been replaced with "$MY_NAME$").

Please, help me to make this version work! Thanks!

**Comment by crawln45** [comment]
Intresting to see if flexget still works in py2.6 @antivirtel since we are moving to a 2.7+ platform.
