### ISSUE TITLE
Flexget Rtorrent plugin does not support local socket file

### ISSUE THREAD

**Issue by kouze** [Flexget/Flexget#661]
Hi,

according to the documention, the rtorrent plugin should support a local socket file:

Name	Info	Description
uri	Text	rTorrent URI. IE: scgi://localhost:5000, ​http://localhost:80/RPC2, **/home/rtorrent/rtorrent.sock**

Unfortunately this is not working, mainly because of:
```
        # Determine the proxy server
        if parsed_uri.scheme in ['http', 'https']:
            sp = HTTPServerProxy
        elif parsed_uri.scheme == 'scgi':
            sp = SCGIServerProxy
        else:
            raise IOError('Unsupported scheme %s for uri %s' % (parsed_uri.scheme, self.uri))
```

Here there is no support of a local socket as the parsed_uri.scheme will be empty in case of using local file and then the plugin will raise the Unsupported scheme error message

Thanks,
kouze

**Comment by stevezau** [comment]
Ah yes.. you are right.. i must of missed that.. ill fix it when i have a moment

**Comment by kouze** [comment]
Thanks stevezau :)

**Comment by stevezau** [comment]
@kouze appears I was going to support local socket but never got around to it.. 

This might take a little longer to fix as i've gota implement how to connect to local sockets.

**Comment by stevezau** [comment]
Fixed in https://github.com/Flexget/Flexget/compare/2bc431653111...1f4ef0e1db19
