### ISSUE TITLE
Error trying to authorize trakt account

### ISSUE THREAD

**Issue by Oletros** [Flexget/Flexget#668]
When I use the command flexget trakt auth <Username> PIN I receive this error:

Authorization failed: Token exchange with trakt failed: 401 Client Error: Unauthorized for url: https://api-v2launch.trakt.tv/oauth/token

I'm using version 1.2.397 inside a docker container

**Comment by gazpachoking** [comment]
You specified the correct pin you received from trakt site in the command?

**Comment by Oletros** [comment]
Those are the screenshots of the process I run

![pin01](https://cloud.githubusercontent.com/assets/590911/11524823/95091878-98ce-11e5-9b01-04851d63c110.jpg)
![pin02](https://cloud.githubusercontent.com/assets/590911/11524824/950b717c-98ce-11e5-97ec-10df8665c5e0.jpg)

**Comment by gazpachoking** [comment]
Have you tried getting a new pin? That's the error I'm getting when the pin is wrong.

**Comment by Oletros** [comment]
I have deleted the old app in Trakt and created a new one and the error persists.

**Comment by gazpachoking** [comment]
You shouldn't have to create an app or anything, you just go to http://trakt.tv/pin/346

**Comment by gazpachoking** [comment]
@Oletros I'm hoping this resolved your issue. Please reopen if not.

**Comment by Oletros** [comment]
Thanks, solved
