### ISSUE TITLE
Crash with discover and TVMaze

### ISSUE THREAD

**Issue by niawag** [Flexget/Flexget#677]
Hi, there is an issue in latest version (1.2.400) with the discover plugin and TVMaze, here is the error: http://pastie.org/10606946
There is a workaround, you need to add `ignore_estimations: yes` to your discover plugin configuration.

If you need anything to help solving this I'm willing to help!

**Comment by liiight** [comment]
This should have been auto closed. Weird. Should be fixed now.

**Comment by gazpachoking** [comment]
My commit was a temporary fix, we should still fix the lookup functions to raise a LookupError any time they don't return a result.
