### ISSUE TITLE
Flexget - backwards compatible with rtorrent 0.9.2

### ISSUE THREAD

**Issue by HA4g3n** [Flexget/Flexget#687]
The only stabile version of rtorrent on Qnap NAS is 0.9.2 wich flexget is not compatible with according to the debuged log:
**TaskAbort(reason=rtorrent version >=0.9.4 required, found 0.9.2, silent=False)**

Would be good if flexget was backwards compatible : )

Have tried installed older version but no success with even get the flexget to work there.
(pip install -Iv flexget==1.2.341)
If there is a version you know that is compatible with rtorrent 0.9.2 please post the version since i have tried about 20 versions now.

Thanks in advance 
HA4g3n

Created by requested [feature](http://discuss.flexget.com/t/make-flexget-backwards-compatible-with-rtorrent-0-9-2/1801)

**Comment by stevezau** [comment]
fixed in commit ba777bf

**Comment by stevezau** [comment]
I quickly tested 0.9.2.. It seems to work but it need more intensive testing.
