### ISSUE TITLE
IMDB plugin unable to get genre

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#695]
When running the tasks which require imdb_lookup, the task fails with the following:

>2015-12-10 18:24 WARNING  imdb_lookup   My-Movies-1080p IMDB lookup failed for Sinatra-All or Nothing at All 2015 Bluray 1080p DTS-HD x264-Grym
>2015-12-10 18:24 INFO     log_once      My-Movies-1080p Title `Sinatra-All or Nothing at All 2015 Bluray 1080p DTS-HD x264-Grym` lookup failed
>2015-12-10 18:24 INFO     imdb_lookup   My-Movies-1080p Imdb lookup failed for sinatra-all or nothing at all 2015 bluray 1080p dts-hd x264-grym
>2015-12-10 18:24 WARNING  utils.imdb    My-Movies-1080p Unable to find genres section for http://www.imdb.com/title/tt3838978/ - plugin needs update?

**Comment by tarzasai** [comment]
that is tagged as "tv mini-series", imdb_lookup does not works with tv stuff.

**Comment by xathin** [comment]
Why do I have so many of them showing up then? That was just one instance, but there are many more that have shown up in the last day. Did something change on IMDB?

[imdb_update.txt](https://github.com/Flexget/Flexget/files/60009/imdb_update.txt)

**Comment by DigitalConceptions** [comment]
I am pretty sure that it is because imdb is changing their layout. I also think this is the same issue as what is happening in #697

**Comment by tarzasai** [comment]
> Did something change on IMDB?

maybe, but it's a separate issue, the plugin has never worked with tv series & miniseries as far as I know.

**Comment by msj33** [comment]
Should we create a new bug record, hence this is also happening to movies? Or should were-open this or continue on reporting on #697 ?

**Comment by tarzasai** [comment]
#697 looks like a real issue to me, so please report there for movies. I've closed this one because AFAIK the plugin is not intended to work with tv stuff, so this is not an issue.
