### ISSUE TITLE
After timeframe expires, best quality found is downloaded even if a better match to target is available

### ISSUE THREAD

**Issue by tremby** [Flexget/Flexget#699]
From http://flexget.com/ticket/3105

Consider a configuration such as

```
timeframe: 2 hours
target: 720p webdl
quality: 720p-1080p hdtv+
```

and the following scenario:

Flexget finds a suitable episode in two formats: 720p hdtv and 1080p hdtv, whether at the same time or within two hours of each other. Due to them not fulfilling the webdl requirement of the target quality it correctly doesn't download anything yet.

The timeframe then expires and there is still no 720p webrip available.

At this point, Flexget's current behaviour is to download the best quality it has seen, which in this case is the 1080p hdtv.

This may be what is wanted, but it also may not be. It's not what I want, and I would imagine that most users would agree that in this scenario the 720p hdtv would be more appropriate, since the resolution matches the target and the source, though not matching the target, is in the valid quality range. On the other hand the 1080p hdtv, which was downloaded, does not match the target resolution (though it is in the valid range) and the source also does not match the target (though again it is in the valid range).

I think the default behaviour should be to match as many of the target requirements as possible, while of course staying within the quality requirements.

If it seems not all users would want this new default behaviour, it could be configurable. It could either be a "choose closest match: yes or no" option, or it could be more sophisticated with the "target" option expanded. A user who wants "720p webrip" could somehow specify that the 720p part is important, and the webrip part not so important, or some other such combination.

liiight asked in a comment on the old ticket:

> if you don't want 1080p to begin with? why even include it in the original requirement? if that is not a valid option on your part, do not include it.
> 
> i'm not saying i'm against adding a 'closest match' feature, that does sound interesting and doable, i'm just wondering.

The answer is that I do want 1080p if no 720p is available, but I prefer 720p. At present I have no way to tell Flexget that I _prefer_ a "worse" quality, or rather I do since that's what I'm saying in the "target", but it isn't taken into account when timeframe expires.

**Comment by crawln45** [comment]
Let's see.  

1. You specified the target as the 'Preferred' so of course it's going to match exactly. 
2. You specified a rant of 720p-1080p at hdtv or above. 1st it's going to pick the 'best' qualities available. If you wish that it doesn't. Then that is up to you to specify. If you specify a range well then it's going to give you the best of that range since there's not a single option.  
3. All assigned values for qualities are given a numeric value. Those values are then totaled giving you a numeric weight to each episode, as long as the values are within the range assigned. That is then calculated on what episode is the 'best'. So there's no way currently to assign 720p as important over 1080p since their values are treated equally when added to the other values present.

**Comment by tremby** [comment]
> You specified the target as the 'Preferred' so of course it's going to match exactly.

I don't understand what you mean by this.

> You specified a rant of 720p-1080p at hdtv or above. 1st it's going to pick the 'best' qualities available. If you wish that it doesn't. Then that is up to you to specify. If you specify a range well then it's going to give you the best of that range since there's not a single option.

Well yes, that's the problem, that's why I opened this ticket. I specify as "target" 720p webdl, so it ought to be obvious that I prefer 720p webdl. But whether that means I prefer 720p hdtv over 1080p hdtv, if these end up being the only available options, is admittedly unclear. I want an option which allows me to make this clear no flexget.

> All assigned values for qualities are given a numeric value. Those values are then totaled giving you a numeric weight to each episode, as long as the values are within the range assigned. That is then calculated on what episode is the 'best'. So there's no way currently to assign 720p as important over 1080p since their values are treated equally when added to the other values present.

So I want a way to configure these weights.

**Comment by crawln45** [comment]
@liiight thoughts making a new option per quality list:  
```  
target:
  - 720p hdtv:
      priority: 2
  - 1080p hdtv:
      priority: 3
  - 1080p webdl:
       priority: 1
```

**Comment by tremby** [comment]
That sounds like a decent solution to me.

**Comment by pesho-shaibata** [comment]
@crawln45 this is probably the best solution. Is it going to be added?

**Comment by paranoidi** [comment]
That suggestion makes even more complicated. It's already too confusing ... besides priority could be determined by order.

**Comment by paranoidi** [comment]
Quality option could be improved to take list of requirements in the order of preferece.

**Comment by vincentbernat** [comment]
I would also be interested to be able to specify an ordered list of preferences (or even an unordered list). For example, I want to be able to express that I accept "720p h264" and "720p|1080p h265". I don't want to accept "1080p h264". I think, this is currently not possible.

**Comment by vincentbernat** [comment]
Another option for me would be to be able to have something like that:

```yaml
           normal:
             timeframe: 12 hours
            target: 1080p dd5.1|ac3|dts|dtshd
            quality:
              - "720p|1080p webrip|hdtv|webdl|bluray h265 !aac"
              - "720p webrip|hdtv|webdl|bluray h264 !aac"
```

Unfortunately, the quality setting of the serie plugin doesn't support a list (while the quality plugin does, this is a bit confusing).

**Comment by mabo1** [comment]
Would the reorder_quality plugin solve this problem?

reorder_quality:
  720p:
    above: 1080p

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
