### ISSUE TITLE
Use task priority to pick between similar files' sources at timeframe end

### ISSUE THREAD

**Issue by tremby** [Flexget/Flexget#701]
From http://flexget.com/ticket/3106

After a timeframe expires, if the target quality has not been met but suitable files were found matching the valid quality range, currently the "best quality found so far" is chosen.

In some cases this same "best quality" is available from multiple sources, such as multiple RSS feeds.

Where the tasks supplying those RSS feeds were in an order of priority, I'd expect Flexget to choose the file from the feed which was downloaded first. But from observation this is not always what happens: I often get a file downloaded from a lesser-preferred source instead, even though a suitable match was available from a preferred source.

**Comment by crawln45** [comment]
As far as this goes. I think this is done by what time the 'matching' best quality is seen. from what I can see regardless of what priority the rss feeds are. Since I don't believe it stores what feed or source each file is from just that the file has been found.

**Comment by crawln45** [comment]
@gazpachoking If multiple 'best quality' available is matched. Isn't the 1st one seen downloaded. I think that's what I read when going through the series code, but it seems so jumbled I'm not 100% sure on that.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
