### ISSUE TITLE
Transmission plugin ignores addpaused for magnet links

### ISSUE THREAD

**Issue by timdp** [Flexget/Flexget#705]
I'm trying to figure out why [this code](https://github.com/Flexget/Flexget/blob/3025c51455a6bbebb00e86c320613c652fb7b816/flexget/plugins/plugin_transmission.py#L417-L420) is necessary. The comment doesn't make sense to me. Before I started using Flexget, I used to add magnet links in the paused state all the time. I don't see why magnet links would need an override of the addpaused option. Can anyone clarify?

**Comment by cvium** [comment]
It is unpaused to ensure the meta data is downloaded, which is required for stuff like `main_file_only`.

**Comment by timdp** [comment]
It'd make more sense to show me a warning if I have conflicting options enabled than to silently override my choice whether or not that's the case.

**Comment by cvium** [comment]
Ideally, it should pause it once it has been magnetized, but I haven't gotten around to it. Feel free to create a PR.

**Comment by timdp** [comment]
I don't need those additional options, so I just commented out the override. It's working as expected. Thanks for the background info though.

**Comment by cvium** [comment]
Sure, no problem. It's still something I'd like to add eventually though.

**Comment by timdp** [comment]
Would it make sense to add a separate option that forces a pause in all cases? Or, as I already suggested, show a warning for the combination of `addpaused` and `main_file_only` and others. I'm not a huge fan of commenting out production code. :wink:

**Comment by gazpachoking** [comment]
I think we just need something here that calls pause `if options['post']['paused'] and not downloaded` or something on those lines.
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/plugin_transmission.py#L587-L591

**Comment by gazpachoking** [comment]
Wait, is this the exact opposite #672? Do we just have some logic inverted somewhere?

**Comment by timdp** [comment]
I came across that issue before filing this one and yes, it had me confused. I just assumed it was outdated.

**Comment by gazpachoking** [comment]
@Flexget/transmission anyone want to look into this and #672?

**Comment by tarzasai** [comment]
I will have some time in the holidays.

**Comment by timdp** [comment]
:+1:

**Comment by tarzasai** [comment]
Well, I cannot verify #672 because in my test case (there) addpaused is correctly ignored, the magnet-torrent downloaded immediately and never paused by flexget or transmission or whatever.
But now I'm a bit lost: do we want to change it? How it should work?

**Comment by cvium** [comment]
@tarzasai I am thinking that if `addpaused: yes`, then the magnets should be paused as soon as they are magnetized. Just my opinion though.

**Comment by X-dark** [comment]
@cvium this makes sense. But it is the more complex to do.

**Comment by tarzasai** [comment]
perhaps right after [this line](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/plugin_transmission.py#L475) we can just call `cli.stop_torrent` (is it the right method?).

**Comment by X-dark** [comment]
Seems the right place to do it and I don't see any other method for doing it. Worth a try.

**Comment by tarzasai** [comment]
guess we forgot to close this one...
