### ISSUE TITLE
Discover / Series Emit improvments

### ISSUE THREAD

**Issue by bagobones** [Flexget/Flexget#708]
1. Allow the number of additional Discovery runs to be set, instead of the apparent fixed 5
2. Optionally disable searching for the first episode of the next season as it can generate a lot of unnecessary search requests to APIs that have low limits.

Alternatively have a discover mode that searches for all episodes of a series and then has the series plugin run repeatedly against the cached results thus minimizing web search requests.

**Comment by cvium** [comment]
The first one is already possible using `rerun`.

**Comment by liiight** [comment]
With regards to 2, that is problematic since discover plugin need that air-date to return a proper response. Don't forget that searching for next season doesn't necessarily means searching for unaired episodes since there is no way for flexget to know which episodes aired and when. A show can have 5 season aired already and discover plugin will search for the 1st episode of the 3rd season for example. It all depends on the user data.

**Comment by bagobones** [comment]
However Discover ALWAYS searches ahead and this is burning up API calls per hour allowed with some sites. In my use case I mostly use discover to back fill or catch up a series that I have been late to adding to tracking and are few episodes into the first season. 

Another option might  be to have a tbdb strict mode where discover doesn't try and find unknown episodes. 

I am currently tracking a lot of series for multiple people in the house hold... for each series I am tracking I am burning up useless search requests.

**Comment by liiight** [comment]
what would you qualify as an 'unknown' episode?

**Comment by bagobones** [comment]
An episode not yet in tvdb. Discover kind of blindly increments and
searches. I am suggesting a strict mode would check the highest known
episode for a series and not search past it.

On Tuesday, 15 December 2015, Or Carmi <notifications@github.com> wrote:

> what would you qualify as an 'unknown' episode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/708#issuecomment-164751733>.
>


-- 
David Greekas

**Comment by gazpachoking** [comment]
> The first one is already possible using rerun.

I think you mean `max_reruns`. We should add that plugin to the wiki.

As for why it's always searching the next season, it's because we built the system to work properly even in the absence of any metadata.

> However Discover ALWAYS searches ahead and this is burning up API calls per hour allowed with some sites. In my use case I mostly use discover to back fill or catch up a series that I have been late to adding to tracking and are few episodes into the first season.

It should only search for the next season if it looked for the next expected ep of current season and didn't find it.

Have you already adjusted your interval to something good for the discover plugin? That's the easiest way to lower the amount of searches being done. Also, make sure you are on the latest version, for a while every episode was being searched automatically because all of our metainfo providers were down. When metainfo is available, it should prevent any episode from being searched that has a release date in the future.

**Comment by bagobones** [comment]
>>It should only search for the next season if it looked for the next
expected ep of current season and didn't find it.

So essentially every execution accept the one time it finds something.

If I am using emit series there are always going to be a lot of searches
every time the interval is up even if it is weekly since they will all
attempt to run on that one day anyway, in my case 72 distinct series 2X 2.

Why 72? because a lot of British shows have tiny seasons that are on and
off frequently. Also a number of US cable shows now run split seasons so
some shows are only on for half the year.

I realize it is designed to work without metadata, as it should, however I
am basically asking for the option that does depend on metadata and maybe
doesn't even search if the meta-data provider is down.


I am using Discover as costly fall back in this case, it should be filling
series if for some reason the main RSS failed and when new series are added
it should be catching up to the point that RSS will function.


On Tue, Dec 15, 2015 at 12:51 PM, Chase Sterling <notifications@github.com>
wrote:

> The first one is already possible using rerun.
>
> I think you mean max_reruns. We should add that plugin to the wiki.
>
> As for why it's always searching the next season, it's because we built
> the system to work properly even in the absence of any metadata.
>
> However Discover ALWAYS searches ahead and this is burning up API calls
> per hour allowed with some sites. In my use case I mostly use discover to
> back fill or catch up a series that I have been late to adding to tracking
> and are few episodes into the first season.
>
>
> Have you already adjusted your interval to something good for the discover
> plugin? That's the easiest way to lower the amount of searches being done.
> Also, make sure you are on the latest version, for a while every episode
> was being searched automatically because all of our metainfo providers were
> down. When metainfo is available, it should prevent any episode from being
> searched that has a release date in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/708#issuecomment-164893143>.
>



-- 
David Greekas

**Comment by liiight** [comment]
@gazpachoking Maybe we could map a new series and episodes in db so that discover plugin won't be so blind

**Comment by paranoidi** [comment]
Please see my commit 2bfe5b252c873ec6ce70eebbde5f71ecaed34d3d which was reverted as it broke tests. However the functionality was working fine! I used it for several months.

**Comment by gazpachoking** [comment]
> If I am using emit series there are always going to be a lot of searches
> every time the interval is up even if it is weekly since they will all
> attempt to run on that one day anyway, in my case 72 distinct series 2X 2.

I think it's much better to put your discover interval high, and run the task very often. This helps load balance so that not that many episodes are searched per run. Like put the interval at 1 day, but run the task every hour.

**Comment by bagobones** [comment]
I gave weekly as an example. As you noted it only runs so many before
stopping everything else overflows to the next run.

Come to think of it that should probably be a setting as well, max queries
per execution.  Especially when using series emit.

I currently run discovery every 1.5hrs with an interval of 1day. This still
seems to result in excessive requests once a day.

The results still tend to be a little odd, which might be because the
search plugin I am using has an API limit of 100-150 requests an hour and I
think it is tripping and returning nothing which causes the interval to
kick in again.

On Wednesday, 16 December 2015, Chase Sterling <notifications@github.com>
wrote:

> If I am using emit series there are always going to be a lot of searches
> every time the interval is up even if it is weekly since they will all
> attempt to run on that one day anyway, in my case 72 distinct series 2X 2.
>
> I think it's much better to put your discover interval high, and run the
> task very often. This helps load balance so that not that many episodes are
> searched per run. Like put the interval at 1 day, but run the task every
> hour. If you have 24 shows, you should get an average of one show (probably
> 2 eps) per run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/708#issuecomment-165158939>.
>


-- 
David Greekas

**Comment by gazpachoking** [comment]
> Come to think of it that should probably be a setting as well, max queries
> per execution.  Especially when using series emit.

> I currently run discovery every 1.5hrs with an interval of 1day. This still
> seems to result in excessive requests once a day.

Yeah, there isn't anything enforcing the load balancing, so if they don't start on a balanced schedule they'll often stay that way. (if you run once with --discover-now it will automatically spread them out for next runs though) I would certainly like something to cause this to happen automatically, a max_queries might be good, but what happens if you set it lower than your total search quantity? i.e. you run your task every hour, have interval set up for an hour, have 2 shows, but you set max queries per run to 1? This will allow 1 search per hour, but you've told it to search for 2 shows per hour...

**Comment by bagobones** [comment]
Yes, it would be a problem if interval was less or equal to the scheduled
run.

However given my example of let's say 70 series, scheduled run of 1.5hrs
and interval of 1 day it would work nicely.

Set max queries per execution to 20. It would take 5.25 hours to search
them all without exceeding API limits even if it searched for the next
episode in season and the first episode of the next season for each.

Another option would be a max queries per hour/min setting then the user
might be less likely to make a dumb combination.

Anything would be better than smashing the search function of some sites
once a day.


On Wednesday, 16 December 2015, Chase Sterling <notifications@github.com>
wrote:

> Come to think of it that should probably be a setting as well, max queries
> per execution. Especially when using series emit.
>
> I currently run discovery every 1.5hrs with an interval of 1day. This still
> seems to result in excessive requests once a day.
>
> Yeah, there isn't anything enforcing the load balancing, so if they don't
> start on a balanced schedule they'll often stay that way. (if you run once
> with --discover-now it will automatically spread them out for next runs
> though) I would certainly like something to cause this to happen
> automatically, a max_queries might be good, but what happens if you set it
> lower than your total search quantity? i.e. you run your task every hour,
> have interval set up for an hour, have 2 shows, but you set max queries per
> run to 1? This will allow 1 search per hour, but you've told it to search
> for 2 shows per hour...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/708#issuecomment-165165955>.
>


-- 
David Greekas

**Comment by gazpachoking** [comment]
Is there some smart way we can make the leveling happen automatically? The problem is that we know the interval, but we don't necessarily know how often they have the task scheduled to run.

**Comment by bagobones** [comment]
Well lets look at what we have:

1. we have a variable number of discover query requests per execution
2. we have a variable number of results per query (we have a limit option
for this)
3. we have a variable number of times the discovery plugin may be run (we
have a limit on the SAME query being run "duration")
4. successful results may also result in up to 5 additional executions to
increment series queries.


I am starting to think that maybe what we need is a series_discover plugin
that works differently than the current discover plugin.






On Wed, Dec 16, 2015 at 9:24 AM, Chase Sterling <notifications@github.com>
wrote:

> Is there some smart way we can make the leveling happen automatically? The
> problem is that we know the interval, but we don't necessarily know how
> often they have the task scheduled to run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/708#issuecomment-165182903>.
>



-- 
David Greekas

**Comment by gazpachoking** [comment]
> I am starting to think that maybe what we need is a series_discover plugin
> that works differently than the current discover plugin.

What might it do differently?

**Comment by gazpachoking** [comment]
I also like @paranoidi's 2bfe5b2 commit, would allow discover to catch up on tv shows in many fewer runs. We could possibly lower the default max_retries to 3 or so if we implement this sort of thing too.

**Comment by gazpachoking** [comment]
> I currently run discovery every 1.5hrs with an interval of 1day. This still
> seems to result in excessive requests once a day.

If your site's api limits are per hour, probably scheduling more often would be beneficial. With 1.5 hours, you'll be wasting some of your requests. Scheduling more often should not increase the number of searches per time period, only discover interval will. I've also added a new domain limiting feature to the requests util, which may be of interest. It supports token bucket limiters, so it can slow down (or abort over limit) requests before you actually hit api limits if set properly for sites. I think the aborting feature _may_ have some load leveling effect, as it would allow some entries to complete, and some to fail after api limit was reached, which would fall back to next run.

**Comment by paranoidi** [comment]
Reruns now scale automatically, if there's still something specific to be done open new ticket.
