### ISSUE TITLE
bad imdb data after 1.2.408

### ISSUE THREAD

**Issue by m-hume** [Flexget/Flexget#714]
with the update to 1.2.408 some imdb tables were truncated
the link table between movies and genres (imdb_movie_genres) wasnt
I'm now getting movies rejected by reject_genres because the movie id's are being reused
ie.
The movie with id 40 was a musical (and rejected by my config) 
update to 1.2.408, movies table is truncated
A new movie (not a musical) gets inserted with id 40 and its genres are added to imdb_movie_genres
movie 40 is filtered by by the config due to movie 40 appearing to be a musical

looks like imdb_movie_actors, imdb_movie_directors, imdb_movie_genres and imdb_movie_languages should have all been truncated also
mh

**Comment by gazpachoking** [comment]
Ooh. It looks like the secondary tables didn't get cleared like they should as they aren't marked as belonging to imdb_lookup plugin.

**Comment by m-hume** [comment]
Maybe plugins/filter/imdb.py should have a few mods to report what 'thing' value got rejected?
i.e. line 146 `reasons.append('reject_genres (%s)' % (genre))`
That was how i determined what was picking up the wrong genre
