### ISSUE TITLE
SSL Issue on server only allowing ECDH

### ISSUE THREAD

**Issue by kecksk0enig** [Flexget/Flexget#715]
Hi!
I am getting an Error
> : [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

when trying to fetch rss feed from TLS enabled server.

It looks like the server only allows ECDHE ciphers.
![ciphers](https://cloud.githubusercontent.com/assets/4678750/11827874/cda133fc-a38f-11e5-9918-6abf2a6addd7.png)

Is this a python ssl error? 
Is there anything I can do instead of pinging the server administrator to allow  other ciphers?
Thanks in advance

**Comment by crawln45** [comment]
TLS and urllib don't see eye to eye much. You can ignore ssl certs if you wish with  
http://flexget.com/wiki/Plugins/verify_ssl_certificates

**Comment by kecksk0enig** [comment]
I do not think this has anything to do with certificate verification but an error on the handshake itself, since I already have verify_ssl disabled.
The error it self states the error in server hello.
I looked a litle bit and found this: 
https://askubuntu.com/questions/649000/openssl-curl-error-ssl23-get-server-hellotlsv1-alert-internal-error

also found this:
http://flexget.com/ticket/2992

**Comment by gazpachoking** [comment]
First thing to try with any ssl issues is to upgrade python to >= 2.7.9, or if it isn't available on your platform, `pip install requests[security]` (in your flexget virtualenv, if you are using a virtualenv.)

**Comment by kecksk0enig** [comment]
Thanks :+1:  running  
> pip install requests[security] --upgrade
did the trick.
