### ISSUE TITLE
Fresh install on Ubuntu 14.04LTS doesnt work out of the box

### ISSUE THREAD

**Issue by thepace** [Flexget/Flexget#727]
Steps to reproduce:
install Ubuntu 14.04
do apt-get update/upgrade
follow guide on http://flexget.com/wiki/InstallWizard/Linux/Environment
flexget wont work untill "pip install flexget --upgrade" is triggered
tested on vm install and later on on real system

**Comment by paranoidi** [comment]
> flexget wont work untill "pip install flexget --upgrade" is triggered

That is what installs it .. what did you expect? How does it fail?

**Comment by thepace** [comment]
--upgrade options does not install flexget it upgrades packages. when u install something first time its expected that it will work and there is nothing to upgrade witch is not the case on mentioned ubuntu version and possibly other versions.

anyway this is just reminder for gazpachoking. im adding pic with info what happens without upgrade command http://www.imagebam.com/image/dac3c5453078355

**Comment by cvium** [comment]
This may have been due to dependency clashing. I am unable to reproduce the error. You can re-open if the problem resurfaces.
