### ISSUE TITLE
header + form does not seem to be changing user-agent

### ISSUE THREAD

**Issue by bagobones** [Flexget/Flexget#728]
I am using headers, form to try and log into a web form. However the sites bot protection is showing the user agent as python and rejecting it..

headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"

Agent detected by the site (I am admin and can see the logs):

AGENT:  Python-urllib%2F2.7

It appears that the form plugin is the one that is not sending the new user agent.

I saw an old ticket indicating that using the default Python agent was a bad idea, and I agree. The program should probably ID as flexget + build number.

**Comment by bagobones** [comment]
Did some more testing, it appears to be the form plugin that is sending the generic Python-urllib user agent regardless of what the headers plugin has set. Edited the original ticket text since I also though the html plugin was at fault but it appears to be purely the forms plugin

This is fairly important functionality for the forms plugin to work at all on many sites.. I saw an old trak ticket from 9mo ago with the answer "use the headers plugin", well it doesn't seem to work.

**Comment by bagobones** [comment]
Did more digging.

forms uses mechanize which uses its own browser object.

I hacked in the following line after the browser was initialized and it worked

br.addheaders = [('User-agent', 'Flexget Forms')]

I would suggest that forms needs two changes:

1. A new Flexget default user agent
2. a new parameter for user agent as part of the plugin, unless a way to make it inherit from headers can be found, however I suspect the way mechanize works that might not be possible.

**Comment by gazpachoking** [comment]
Here's where we are setting the default user agent now https://github.com/Flexget/Flexget/blob/develop/flexget/utils/requests.py#L107 the problem is that we switched to requests, and this plugin is still on urllib. I think the headers plugin still has some legacy code to change the default urllib2 opener, maybe if we build the mechanize opener based on that? For a headers hack it could just grab them from `task.requests`, which is the requests session that is meant to be used. Is there a requests based alternative to mechanize? That would be nicest solution.

**Comment by bagobones** [comment]
Past what I have posted I don't know. Just got as far as hacking in a
forced user agent change and that worked.

My forums anti abuse tools blacklist the python default user agents so
almost almost any fix would do that changes the user agent used by forms.

On Monday, 21 December 2015, Chase Sterling <notifications@github.com>
wrote:

> Here's where we are setting the default user agent now
> https://github.com/Flexget/Flexget/blob/develop/flexget/utils/requests.py#L107
> the problem is that we switched to requests, and this plugin is still on
> urllib. I think the headers plugin still has some legacy code to change the
> default urllib2 opener, maybe if we build the mechanize opener based on
> that? For a headers hack it could just grab them from task.requests,
> which is the requests session that is meant to be used. Is there a requests
> based alternative to mechanize? That would be nicest solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/728#issuecomment-166468978>.
>


-- 
David Greekas

**Comment by bagobones** [comment]
I am assuming a workaround or fix is not in the current main code...

Any chance the workaround could be hacked in for now until a more wide spread change is made?

**Comment by bagobones** [comment]
Just updated my old install and found this still exists.

I am fairly sure this issue is relevant to anyone that wants to scrape a site with logins that might have script protection of any kind.. Outputting the python user agent will likely be blocked in a number of more tightly controlled sites.
