### ISSUE TITLE
{{imdb_name}} // {{movie_name}} has white spaces and returns a lot of whitespaces

### ISSUE THREAD

**Issue by blastcodem** [Flexget/Flexget#731]
{{imdb_name}} // {{movie_name}} was returning None after an imdb layout changes I guess.

I update to latest flexget today.

Now the movie name returns a lot of white spaces and returns:

ex copy / paste of {{imdb_name}} // {{movie_name}} : 
```
Moviename
                   (2015)
                   
            .2015
```

LOG output:
```
imdb_lookup   movie_search    movie `MOVIENAME\n                   (2015)\n                   \n            ` age 0 expires in 2 days
```

**Comment by blastcodem** [comment]
I just find where the error is:
imdb.com looks like this
```
<h1 itemprop="name" class="">Sicario
                   <span id="titleYear">(<a href="/year/2015/?ref_=tt_ov_inf"
>2015</a>)
                   </span>
            </h1>
```

Flexget/flexget/utils/imdb.py
::
line 242:
        name_elem = title_overview.find('h1', itemprop='name')
        self.name = name_elem.find(text=True, recursive=False).strip()

**Comment by gazpachoking** [comment]
This is the source of issue #729, and should be fixed in next release by commit:
ef99ebb37dbd863197d5ab21735e538c2fba64c6

**Comment by blastcodem** [comment]
Excellent! Thanks

Here is the source HTML of the new IMDB layout if anyone interested.
http://pastebin.com/s40SA5rp

There is no </span> anymore
