### ISSUE TITLE
Imdb_list rejects 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#734]
I'm not sure if this issue is related to this report https://github.com/Flexget/Flexget/issues/729 .. But all new movies in watch list from the imdb_list is being rejected because of possible login page.  Nothing from the watch list is getting through to be added to the movie-queue.  Thanks 

Attached is a debug log

[imdb_list_debug.txt](https://github.com/Flexget/Flexget/files/67999/imdb_list_debug.txt)

**Comment by gazpachoking** [comment]
If this is meant to be a task that adds to your movie queue, you shouldn't have the download plugin in there.

**Comment by chewy74** [comment]
That's the weird thing... I don't have a download plugin with my imdb task. It's only to fill the movie queue and I use discover with the movie queue to download.. 

Here's my complete config
[config.txt](https://github.com/Flexget/Flexget/files/68021/config.txt)

**Comment by chewy74** [comment]
@gazpachoking, I am such a idiot. The reason why it's rejecting and trying to download is because of the transmission plugin under global template. It's trying to pass the accepted imdb entry through transmission, then rejecting. The retry_failed keeps trying in a endless loop and nothing gets added to the movie queue. 

:facepunch: for myself. Sorry
