### ISSUE TITLE
Unable to download the RSS due to sslv3 alert handshake failure

### ISSUE THREAD

**Issue by tommyjiang** [Flexget/Flexget#741]
I use Flexget and Transmission on Mac. 

Yesterday everything was OK. But today I get the following error after running Flexget:

    2015-12-23 23:35 CRITICAL plugin        Tommy           
    Unable to download the RSS for task Tommy     
    (https://hdchina.club/torrentrss.php?...): [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] 
    sslv3 alert handshake failure (_ssl.c:590)

So maybe it is caused by SSL3 but I can not solve this.

**Comment by gazpachoking** [comment]
First thing to try with any ssl issues is to upgrade python to >= 2.7.9, and/or `pip install requests[security]` (in your flexget virtualenv, if you are using a virtualenv.)

**Comment by tommyjiang** [comment]
Thanks @gazpachoking for providing the solution.

I get no error after running `pip install requests --upgrade` with `requests` upgraded to 2.9.1 from 2.9.0.
