### ISSUE TITLE
Header-based filter plugin

### ISSUE THREAD

**Issue by devster31** [Flexget/Flexget#750]
Some rss feeds don't have a plain link in the `<url>` field but instead use php to trigger the download, a sample link would be:

```
https://domain/download.php?action=download&authkey=<similar to api key>&pass=<similar to api secret>&id=<torrent_id>
```

Without knowing anything reliable about the `<title>` or `<description>` fields flexget could try and filter them with a regex on the downloaded filename, instead of using url or title that could return a lot of false positives, however that requires a temporary directory and deleting rejected files after filtering them.
To make it easier the filter could act on the headers of the above link, that contain the file name as well as some extra information that could be useful, this is an example curl -X HEAD -I <url> response:

```
HTTP/1.1 200 OK
Date: Thu, 24 Dec 2015 17:38:32 GMT
Server: Apache
Content-disposition: attachment; filename="Softwarename (SemVer [PlatformInfo]).torrent"
Vary: Accept-Encoding
Cache-Control: private, no-cache, no-store, must-revalidate, proxy-revalidate
Pragma: no-cache
Content-Type: application/x-bittorrent; charset=utf-8
```

In this case adding a `<filename>` field to the Entry would be optimal to make a regex filter work, and analyzing headers could catch redirects, 404 and proxies before even attempting the download, thus giving the possibility of rejecting/failing the Entry early or avoid specific proxies.

**Comment by liiight** [comment]
This seems interesting, started working on it.
As opposed to entry, each headers are stored per task, and not per entry (unless a specific input plugin will store them as part of the entry itself). I'm not sure what the correlation between `task.requests.headers` and `task.entries` should be

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
