### ISSUE TITLE
2 crashes last run 

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#751]
[crash_report.2015.12.28.005046249000.txt](https://github.com/Flexget/Flexget/files/72960/crash_report.2015.12.28.005046249000.txt)
[crash_report.2015.12.28.020628547000.txt](https://github.com/Flexget/Flexget/files/72961/crash_report.2015.12.28.020628547000.txt)
[crash_report.2015.12.28.042806699000.txt](https://github.com/Flexget/Flexget/files/72959/crash_report.2015.12.28.042806699000.txt)
[crash_report.2015.12.28.052110526000.txt](https://github.com/Flexget/Flexget/files/72962/crash_report.2015.12.28.052110526000.txt)

**Comment by liiight** [comment]
Please go over [this](https://github.com/Flexget/Flexget/blob/develop/CONTRIBUTING.md) and update your issue accordingly

**Comment by crack00r** [comment]
[crash_report.2015.12.29.071639081000.txt](https://github.com/Flexget/Flexget/files/73751/crash_report.2015.12.29.071639081000.txt)
[flexget.txt](https://github.com/Flexget/Flexget/files/73752/flexget.txt)

**Comment by crack00r** [comment]
latest flexget

**Comment by crack00r** [comment]
[config.txt](https://github.com/Flexget/Flexget/files/73753/config.txt)

**Comment by crack00r** [comment]
update to 1.2.417 - same crash

**Comment by crack00r** [comment]
Nobody?

**Comment by liiight** [comment]
Your db looks locked. Did you try to reboot?

**Comment by crack00r** [comment]
Yes

**Comment by crack00r** [comment]
I already delete full Python etc just to Check... No help

**Comment by liiight** [comment]
Is this still relevant?
