### ISSUE TITLE
TVDB Crash - latest update

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#754]
since latest update, flexget crash with sql fail and tvdb

[crash_report.2015.12.30.024842960000.txt](https://github.com/Flexget/Flexget/files/74528/crash_report.2015.12.30.024842960000.txt)
[crash_report.2015.12.30.024853220000.txt](https://github.com/Flexget/Flexget/files/74527/crash_report.2015.12.30.024853220000.txt)
[crash_report.2015.12.30.024903696000.txt](https://github.com/Flexget/Flexget/files/74530/crash_report.2015.12.30.024903696000.txt)
[crash_report.2015.12.30.024913937000.txt](https://github.com/Flexget/Flexget/files/74531/crash_report.2015.12.30.024913937000.txt)
[flexget.txt](https://github.com/Flexget/Flexget/files/74529/flexget.txt)

**Comment by crack00r** [comment]
Nobody?

**Comment by liiight** [comment]
Looks like your db is locked. Did you try rebooting?

**Comment by crack00r** [comment]
Yes

**Comment by liiight** [comment]
This is more of an issue for the forums
