### ISSUE TITLE
IMDB don't use movie_name to make the lookup

### ISSUE THREAD

**Issue by PhoneixS** [Flexget/Flexget#761]
I have an input of movies that has titles like:

    2010 Odisea 2 [MicroHD 1080p][AC3 5.1-Castellano-AC3 5.1 Ingles+Subs][ES-EN]

Imdb lookup for this title fails (and if you search in imdb with it, it also fails). So what I have done is to use `manipulate` plugin to populate the `movie_name` field so imdb can use it to make the search.

```
    manipulate:
      - movie_name:
          from: title
          extract: ([^\[]+)
```

But imdb don't use it when the title search failed. I thought it use movie_name if it is populated.

I think it must do it as title contains a lot of information that interfere with the search. Also you can't modify the title removing this extra information because then the quality, language, etc. will be lost (although imdb lookup will run ok).

The alternative for me is to parse all fields by myself but it's a extra work knowing that flexget do it correctly.

Edit: fixed the yml configuration that was not copied correctly.

**Comment by crawln45** [comment]
Try using guessit parser. That might parse that better than the internal.

**Comment by PhoneixS** [comment]
It also guess the movie name correctly but still imdb lookup don't use it so this don't fix the problem (and guessit run after imdb so is normal that imdb can't use it).

**Comment by crawln45** [comment]
@PhoneixS after actually working on the IMDb code. movie_name is a set field from the imdb return. So of course it's not going to search using movie_name it's going to search by entry['title'].
So the solution to this is not to manipulate the movie_name, instead manipulate the title. On that note. From my quick search on IMDB. You won't find that movie even if you do use '2010 Odisea 2 ' as the search paramater. least not in from the US site.

**Comment by liiight** [comment]
So, not a bug.

**Comment by PhoneixS** [comment]
@crawln45 but if I remove the extra information in the title, I lose quality and audio.

**Comment by liiight** [comment]
don't remove the extra information, just manipulate the `title` fields instead

**Comment by PhoneixS** [comment]
Sorry if I didn't explain well or I don't understand it. I'll try with the example title in the top, if I use some configuration like:

```
manipulate:
      - title:
          from: title
          extract: ([^\[]+)
```

This will make the title to appear as `2010 Odisea 2 `. Which is ok for imdb but bad because then quality fields aren't filled.

If didn't change the tile, then quality fields are filled but imdb don't find it because all the extra stuff in the title.

Maybe is better to put all this in a forum instead of here.

**Comment by crawln45** [comment]
Forum would be much better for this discussion. This is used for actual bugs and traceback.
