### ISSUE TITLE
Can tvdb_ep_id be made to handle double-episodes?

### ISSUE THREAD

**Issue by leetwanker** [Flexget/Flexget#767]
I'm using tvdb_ep_id to set the episode numbers and I had a double episode "S01E01-E02" renamed to "S01E01".

Is there a way to fix this problem with tvdb_ep_id? Even if it fell back to series_id when handling double episodes, that would at least solve some issues.

**Comment by liiight** [comment]
@gazpachoking not sure if this is an enhancement or a bug. How do we address double episodes?

**Comment by crawln45** [comment]
First never set it to use tvdb_ep_id mainly for these reasons. It's not coded into and I'm not sure any of us find it a priority since we all just user {{series_id}}

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
