### ISSUE TITLE
Undefined variable in plex plugin

### ISSUE THREAD

**Issue by gazpachoking** [Flexget/Flexget#769]
Landscape seems to have found an use of an undefined variable in the plex input.

https://landscape.io/github/Flexget/Flexget/36/modules/flexget/plugins/input/plex.py#L285

@Flexget/plex Want to take a look?

**Comment by crawln45** [comment]
Didnt we find this out in the beginning when we first ran landscape

**Comment by gazpachoking** [comment]
> Didnt we find this out in the beginning when we first ran landscape

Yeah, but we didn't open a ticket it seems.

**Comment by crawln45** [comment]
Ah oops :-)

**Comment by crawln45** [comment]
@gazpachoking after running the config multiple ways for plex I'm still not exactly sure what those lines of code are for.

**Comment by crawln45** [comment]
@gazpachoking after removing that section of code. I don't see any difference in anything.

**Comment by gazpachoking** [comment]
@planeturban Care to dig deeper? Is this just leftover to be removed?

**Comment by planeturban** [comment]
Oh, one can get notifications here as well. Haven't seen this until now..

I'll have a look.
