### ISSUE TITLE
Add option to restart daemon

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#783]

**Comment by lepinkainen** [comment]
The workaround here is to use a shellscript:

```
#!/bin/sh
flexget daemon stop --wait
flexget daemon start --daemonize
```

This issue is about allowing just a simple ```flexget daemon restart``` which would do the equivalent action to the above script, FULLY restarting the daemon so that no part remains running.

**Comment by crawln45** [comment]
Or do what I did and make it a service on the linux box

**Comment by lepinkainen** [comment]
Did that too :)

Services are rather ungracefully shot down when restarting, with SIGTERM.
