### ISSUE TITLE
Reject years. 

### ISSUE THREAD

**Issue by fhede** [Flexget/Flexget#791]
Hello.
I not find anything about reject years more than this example.
imdb:
      min_year: 2014

What about to have like this to.
reject:
        - 60ths
        - 70ths

thanks

**Comment by liiight** [comment]
so why not set `min_year: 1980`?
Also this isn't an issue, it should be in the [forums](http://discuss.flexget.com/)

**Comment by alneven** [comment]
I would use regex, mostly the year is in the entry.title (release name)

For example you can skip
193|194|195|196|197|198|199|200|2010|2011 ... etc
