### ISSUE TITLE
Add option for different languages

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#795]
Can you please add a option to seek in different languages?

Right now, i export my movies and series vom plex to trakt, to get a list what i have and whats missing
and i import my watchlist from imdb to trakt to get what i want
then i import everything from trakt

But right now it allways looks for the english title, becourse trakt only understand english...

Is it may possible to add something that it import
Import missed movies/seriene from trakt and ask after this the optional title from imdb
imdb send the name of everything in the language you want...

The Problem is right now, flexget seeks in my feeds for the english title and cant find what i want becourse i tell flexget i want audiolanguage german and reject everyting else
at this point, flexget dont find anything....
I have something like
http://www.imdb.com/title/tt0111161/?ref_=wl_li_tt
english is: The Shawshank Redemption
german is: Die Verurteilten
france is:  Les évadés
finland is:  Rita Hayworth - avain pakoon
etc... 
and in the feeds its allways in original language
Like here:
german: http://www.hd-area.org/?s=search&q=die+verurteilten
english: http://www.hd-area.org/?s=search&q=The+Shawshank+Redemption

and flexget just get me
2016-01-15 08:43 VERBOSE  est_movies    Movies_Watchlist_Search Querying release estimation for The Graduate 1967
2016-01-15 08:43 VERBOSE  discover      Movies_Watchlist_Search Searching for `The Shawshank Redemption 1994` with plugin `search_rss` (1 of 37)
2016-01-15 08:43 WARNING  rss           Movies_Watchlist_Search Skipped 1 RSS-entries without required information (title, link or enclosures)
2016-01-15 08:43 VERBOSE  discover      Movies_Watchlist_Search No search results for `The Shawshank Redemption 1994`
2016-01-15 08:43 VERBOSE  discover      Movies_Watchlist_Search Searching for `One Flew Over the Cuckoo's Nest 1975` with plugin `search_rss` (2 of 37)
2016-01-15 08:44 WARNING  rss           Movies_Watchlist_Search Skipped 1 RSS-entries without required information (title, link or enclosures)
2016-01-15 08:44 VERBOSE  discover      Movies_Watchlist_Search No search results for `One Flew Over the Cuckoo's Nest 1975`
2016-01-15 08:44 VERBOSE  discover      Movies_Watchlist_Search Searching for `The Matrix 1999` with plugin `search_rss` (3 of 37)
2016-01-15 08:44 WARNING  rss           Movies_Watchlist_Search Skipped 1 RSS-entries without required information (title, link or enclosures)
2016-01-15 08:44 VERBOSE  discover      Movies_Watchlist_Search No search results for `The Matrix 1999`
2016-01-15 08:44 VERBOSE  discover      Movies_Watchlist_Search Searching for `Star Wars: The Force Awakens 2015` with plugin `search_rss` (4 of 37)
2016-01-15 08:44 WARNING  rss           Movies_Watchlist_Search Skipped 1 RSS-entries without required information (title, link or enclosures)
2016-01-15 08:44 VERBOSE  discover      Movies_Watchlist_Search No search results for `Star Wars: The Force Awakens 2015`
2016-01-15 08:44 VERBOSE  discover      Movies_Watchlist_Search Searching for `Once Upon a Time in the West 1968` with plugin `search_rss` (5 of 37)

**Comment by snickers2k** [comment]
+1

**Comment by crawln45** [comment]
It can be done if I thought hard enough about it.
http://docs.trakt.apiary.io/#reference/movies/aliases/get-all-movie-translations

**Comment by snickers2k** [comment]
would be really awesome. i'm dreaming of this feature for years^^

**Comment by crack00r** [comment]
API works perfect, pls include it!!!

https://trakt.tv/movies/the-intern-2015
gets me on
http://docs.trakt.apiary.io/#reference/movies/translations/get-all-movie-translations?console=1

[
  {
    "title": "Man lernt nie aus",
    "overview": "",
    "tagline": "",
    "language": "de"
  },

 "title": "Le nouveau stagiaire",
    "overview": "Ben Whittaker, un veuf de 70 ans s'aperçoit que la retraite ne correspond pas vraiment à l'idée qu'il s'en faisait. Dès que l'occasion se présente de reprendre du service, il accepte un poste de stagiaire sur un site Internet de mode, créé et dirigé par Jules Ostin.",
    "tagline": "Il n'y a pas d'âge pour refaire un stage.",
    "language": "fr"

{
    "title": "El becario",
    "overview": "La joven dueña de un exitoso negocio online dedicado a la moda no se toma demasiado bien el hecho de que la compañía contrate como becario a un hombre de 70 años, pero eso irá cambiando progresivamente, ya que poco a poco el hombre comienza a convertirse en alguien indispensable.",
    "tagline": "La experiencia nunca pasa de moda.",
    "language": "es"
  }

**Comment by crack00r** [comment]
@liiight any chance to get this in the near future?
It will help extreme for nonenglish users

**Comment by liiight** [comment]
i'm not entirely sure what you wanna lookup in a different language. IMDB, trakt or everything?

**Comment by crack00r** [comment]
Right now:
Import German Movies and Series in german... becource Flexget right now import titles in english and seek in rss feeds for english titles...
But in all my RSS Feeds the titles are in german... 

2016-01-15 08:43 VERBOSE discover Movies_Watchlist_Search Searching for One Flew Over the Cuckoo's Nest 1975 with plugin search_rss (2 of 37)
2016-01-15 08:44 WARNING rss Movies_Watchlist_Search Skipped 1 RSS-entries without required information (title, link or enclosures)
2016-01-15 08:44 VERBOSE discover Movies_Watchlist_Search No search results for One Flew Over the Cuckoo's Nest 1975

the German titles is "Einer Flog über´s Kukuksnest" ... so with a german import  of titles it would find it in my feeds...
The same for ALL Series...
Flexget import and seek for "mickey mouse clubhouse"
http://trakt.tv/shows/mickey-mouse-clubhouse
My Feeds just have "Micky Maus Wunderhaus"
But when flexget import german titles, it should work... so we need a option for import title language

**Comment by crack00r** [comment]
@liiight 
we need this api
http://docs.trakt.apiary.io/#reference/movies/translations/get-all-movie-translations?console=1

you are allready import the title with flexgte, but allways in english, with this api you could add a option for language... ore just
Language = DE then import title prefered german/DE language, else Trakt-Original-title

**Comment by snickers2k** [comment]
@liiight, we mean the discover-function with localized titles. Right now, flexget is kinda "losing" the localized titles and is searching with discover for original titles instead of localized titles

**Comment by crack00r** [comment]
Any news on this?

**Comment by liiight** [comment]
Sit tight, it's not going to happen soon

**Comment by crack00r** [comment]
Dont you think its a good thing?

There are a lot of people who dont have english as native language, and want movies and series in their language... and it cant be much hard to add this option, i think :D 
If i could code i would do it, but i cant :/

Is there a way to donate just for this option? :)

**Comment by crack00r** [comment]
@liiight maybe? :)

**Comment by antivirtel** [comment]
Isn't this is what you want: https://github.com/Flexget/Flexget/pull/444 ?

**Comment by segelkma** [comment]
I hope this message gets recognized.

@antivirtel It is not the same. It will filter the language but it's not worth a penny when the title does not match, just because it is in english instead of german.

I also was searching for a good way to automize my movie downloads using flexget but this looks nearly impossible in foreign languages. While tv shows have identical names in english and german, movies do not. So it is quite easy to automize tv shows in german, while it is not for movies, because most movie names are different.
Example: I use trakt.tv (very good UI) to manage my lists of what to watch. But the trakt_list plugin only returns the english movie title, even though, as shown in this topic, it is possible to return it in other languages using another API method.

So in my opinion there are two ways to easily fix this:
1. Add a parameter for trakt_list to select a language (neat but does not include other sources for watchlists)
2. Add another plugin that can handle this by using any service

I think the first one is easier to integrate, but the second would be the best solution, since it is not only for trakt.tv...

I think this is still a big thing for flexget to have, because right now, automization for movies in foreign languages is a dealbreaker.

**Comment by crack00r** [comment]
@liiight maybe now, since imdb is dead?

**Comment by liiight** [comment]
I'll look into trakt languages. I added it to thetvdb_lookup and it was very easy, if it's similar it shouldn't be an issue

**Comment by segelkma** [comment]
I dig my head into this couple of days ago. But I'm still very new to python and my skills are very limited so I implemented my first idea of my last post. But I think it is not the solution you are looking for right?

However, it's working so I want to share it. So I added a language parameter to trakt_list and whenever getting a list from trakt with movies in it the movie names will be translated into the selected language if it was successful.

Changes can be seen here.
https://github.com/Flexget/Flexget/compare/develop...segelkma:develop

Possible task to store into movie list:
```
update_movie_list:
  trakt_list:
    account: accountname
    list: Movielist
    type: movies
    language: de
  accept_all: yes
  list_add:
    - movie_list: trakt_movies
```

**Comment by cvium** [comment]
Looks pretty good. Only thing missing is some db caching

**Comment by segelkma** [comment]
Indeed. I noticed that calling the API for translations takes very long. Getting translations for 50 Movies took around 80 seconds.
But the caching can't be done by me, I would need many hours just to understand how it's done and I can't spend the time right now...

**Comment by snickers2k** [comment]
something new here?

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)

**Comment by snickers2k** [comment]
feature request done. but  still, @cvium can  you maybe take another look at @segelkma's pull-request?  seems it was already kind a done, right?  would be a really great feature. thx

**Comment by snickers2k** [comment]
i dont know if you guys even know this.. but without localized titles, search makes almost no sense for any language other than english. at least 40 percent is just not working. would be damn happy if you could add this

**Comment by snickers2k** [comment]
@liiight , @sixteeN11 successfully tested this pull-request from @segelkma for days now. What is the problem exactly ? thanks

**Comment by cvium** [comment]
^

**Comment by snickers2k** [comment]
thank you so much cvium. Works like a charm now. I'm getting like 300% more results with discover now. thank you!
