### ISSUE TITLE
Windows 10: cli operations & daemon don't get along :P

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#799]
I have flexget running in daemon mode (run by a logon task in windows) Its been running for the last year without issue... recently, if I do a query or interact with flexget by cli, the lock file gets deleted and it doesn't seem like the cli is communicating with the daemon. (even "flexget daemon status" -- which says there doesn't appear to be a daemon running)

**Comment by crawln45** [comment]
That's easy. Don't use windows 10. :P

**Comment by gazpachoking** [comment]
Is your daemon service running as the same user as you log in from? It could be the daemon is running for a different config file than picked by default when you log in.

**Comment by lostsubstance** [comment]
@crawln45 ha :} I know, but it ***was*** a windows 7 media center pc ... only updated to 10 because it was easy... I'm stuck on windows for this box for now.

@gazpachoking I created the task to run the daemon as my user. The correct lock file is created when it starts. the cli/daemon interaction has been solid for most of the last 12mo. :/ I recently started using PowerShell instead of the normal shell... (since it has bash like commands.) I wonder if its just that?

**Comment by lostsubstance** [comment]
nope... just tried the normal command shell. still failed to communicate to the daemon, then when the `flexget daemon status` finished, the lock file was deleted. (daemon still running... but no way to cleanly stop it)

**Comment by liiight** [comment]
Weir. I use win10 and daemon without any issues so I'm not sure that's related

**Comment by lostsubstance** [comment]
figured it out. User Account Control ... the command prompt needed to be run as admin.

i used to have command prompts always run as admin but turned that off.  now i know flexget cli needs elevated privileges to communicate to the daemon... it would be nice to detect that some how and warn instead of clean up the lock file.
