### ISSUE TITLE
Subliminal plugin (v1.0.1) is not working 

### ISSUE THREAD

**Issue by germanschnyder** [Flexget/Flexget#803]
Latest version of flexget, and subliminal 1.0.1 (in a python env) is not working, i get this:

```bash
2016-01-20 05:19 CRITICAL task          SubtitlesSearch Plugin `subliminal` cannot be used because dependency `subliminal` is missing.
2016-01-20 05:19 WARNING  task          SubtitlesSearch Aborting task (plugin: subliminal)
```

Basically flexget is not recognizing subliminal executable for some reason, despite i can successfully query both versions:
```bash
root@cubox-i:~# subliminal --version
subliminal, version 1.0.1
root@cubox-i:~# flexget --version
1.2.431
You are on the latest release.

**Comment by cvium** [comment]
It is because Flexget uses Guessit2, but Subliminal is still using Guessit1. If you don't use the guessit parser, you can reinstall Subliminal. This will result in the guessit parser failing to load, but it's not a problem if you don't use it.

**Comment by germanschnyder** [comment]
I´m not sure i get your solution. I also tried with latest subliminal (1.1.1) and i get the exact same error.

**Comment by cvium** [comment]
Rollback to guessit 1.0.2

**Comment by germanschnyder** [comment]
Successfully installed guessit-1.0.2
root@cubox-i:~# flexget --version
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3130, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3116, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3143, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 644, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'guessit>=2.0rc5' distribution was not found and is required by FlexGet

**Comment by cvium** [comment]
Strange. Worked for me.

**Comment by germanschnyder** [comment]
Can you provide your current setup regarding this ? Flexget, Subliminal and Guessit versions... plus if you are using virtualenvs or not ?

**Comment by cvium** [comment]
```
osmc@osmc:~$ flexget -V
Latest release: 1.2.433
osmc@osmc:~$ flexget -V
1.2.431
Latest release: 1.2.433
osmc@osmc:~$ guessit --version
+-------------------------------------------------------+
+                   GuessIt 1.0.2                       +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/wackou/guessit/issues.       |
+-------------------------------------------------------+
osmc@osmc:~$ subliminal --version
subliminal, version 1.1.1
osmc@osmc:~$ uname -a
Linux osmc 4.3.3-3-osmc #1 SMP PREEMPT Sat Jan 2 04:01:24 UTC 2016 armv7l GNU/Linux
```

**Comment by AezDropZz** [comment]
I am having the same problem, although for me it's even worse as I can't even get ``` subliminal --version``` to work and get the following error:
```Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 14, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
ImportError: No module named matchtree ```

I have tried reinstalling subliminal without any succes.

**Comment by cvium** [comment]
> EDIT: in some weird way, rolling back to flexget 1.2.429 solved it for me. Subliminal now works again and gives me version 1.0.1.

That's not weird at all. We moved to guessit 2.0 in version 1.2.431 and subliminal requires guessit 1.0.2.

**Comment by liiight** [comment]
This works now, right? That all guessit stuff is over?

**Comment by cvium** [comment]
No. New Subliminal version has not yet been released.

**Comment by liiight** [comment]
No shit. I guess we'll keep this open then.

**Comment by gkocjan** [comment]
Try to update sublime to new RC version. Worked for me
`pip install subliminal==2.0-rc1`

**Comment by cvium** [comment]
I have updated the subliminal plugins to require >=2.0-rc1. Update and all problems should go away.

**Comment by germanschnyder** [comment]
Working like charm, thanks !
