### ISSUE TITLE
Deluge plugin, regression with main_file_only

### ISSUE THREAD

**Issue by colonelpanic-42** [Flexget/Flexget#804]
Recently I updated my older FlexGet install to try and solve an unrelated issue (which didn't work anyway). Over the last few weeks I started noticing my previously working setup suddenly not working (files being kept inside their folders instead of being moved to the parent, with another plugin in Deluge to remove the remains on torrent removal). After much searching I came across #489, I have to admit I was pretty shocked to find this was actually a "fix" to something that wasn't broken as far as I was aware and has now removed functionality that was crucial in my setup.

Currently I have no way of working around this "fix". I tried to remove and roll back to 1.2.303 (presumably the last version of FlexGet before this was locked in) but apparently that breaks unknown dependency chains throughout its plugins and I have no way of working out which pip packages to remove to fix it (I don't want to hose my database in the process, but don't have much choice and to be honest would prefer to have a blank slate than to have what is effectively a crippled plugin in my case). There appears to be no plugin in Deluge to handle this use case. In an attempt to roll my own solution, I can't seem to get the Deluge Web JSON API plugin to work (500 errors when accessing the /json address), and I can't find any decent documentation on actually HOW to aces the Deluge RPC API in any other way. I thought I could write a bash script to work around the problem but using Deluge's console UI doesn't provide enough information to differentiate between different torrents (even labels would be nice, but a feature request from 5 years ago suggests this isn't going to happen anytime soon). I'm not even going to attempt to make a Deluge plugin because their documentation is a total mess and I have no idea where to start.

Assuming this "fix" is the desired behaviour, there needs to be a configuration option to go back to the old behaviour, i.e. get the main file and move it to the root alongside its parent folder, and rename the parent folder so it's hidden.

**Comment by lepinkainen** [comment]
+1 on the impossibility of doing any deluge plugins, this is my attempt at an external deluge controller: https://github.com/lepinkainen/delugemanager

I just started using the main_file_only -option and it has never worked for me, so I just kind of gave up. I did hear rumors about it working at one point though.

Has the feature ever worked or even been tested properly?

What I've been doing is setting the path in the movedone with a leading slash like this:

/{{ tvdb_series_name|d(series_name) }}/{{ tvdb_series_name|d(series_name) }} ... etc

This way SOME shows are downloaded into separate per-show directories, some aren't.

**Comment by colonelpanic-42** [comment]
After finally giving up on a workaround, I tried once again to roll back. I think I managed to get it rolling back to 1.2.303, by removing the guessit plugin through pip. Forcing the install with pip install flexget==1.2.303, it seems to be working OK without errors so far (even the DB seems to be compatible which I'm impressed by, although I have no idea what DB changes have been made since this version).

I can confirm behaviour works as expected in this version (1.2.303). By using main_file_only as well as hide_sparse_files, and using the Delete Partials plugin for Deluge, each episode will download in the correct season folder and hidden noise files and folders are removed on torrent removal automatically. I'm sure there are other issues that have been fixed since this version, but unless an option to keep this functionality is implemented I will have to stay on 1.2.303, and encourage anyone else wanting this same functionality to stick with this version too.

**Comment by liiight** [comment]
@flexget/deluge

**Comment by gazpachoking** [comment]
This is the normal behavior as of merging #489. Not sure if there is a better way to fix

**Comment by gazpachoking** [comment]
> Assuming this "fix" is the desired behaviour, there needs to be a configuration option to go back to the old behaviour, i.e. get the main file and move it to the root alongside its parent folder, and rename the parent folder so it's hidden.

The problem was that deluge doesn't like it when the files are not all in one directory. The move on completion was only working for the files inside the hidden directory, not the ones moved out of the torrent folder.

**Comment by colonelpanic-42** [comment]
Strange, in my setup this has never been a problem. Running Deluge 1.3.6, torrents download to an .incomplete folder then the main file is moved leaving the sparse files behind (which then get deleted anyway with the Deluge plugin to remove Do Not Download files on torrent removal). Of course there's also the matter of not every setup HAS a move on complete, so an option to override the default behaviour with a possible caveat in the docs would still be preferable.

**Comment by gazpachoking** [comment]
> Running Deluge 1.3.6, torrents download to an .incomplete folder then the main file is moved leaving the sparse files behind

Yeah, that doesn't sound right (even if it is what you desire.) I think if we want to re-implement this flexget side, we have to make sure things still work properly deluge side. Maybe we can raise a ticket there to discuss more, seems we lost the history that used to be on the deluge forum.

**Comment by cvium** [comment]
If someone wants to do this, reopen. Closing this for now as interest seems lacking.
