### ISSUE TITLE
send_telegram Plugin error.

### ISSUE THREAD

**Issue by iruyanka** [Flexget/Flexget#805]
http://flexget.com/wiki/Plugins/send_telegram
Install 'python-telegram-bot' python pkg (i.e. pip install python-telegram-bot)

I installed python-telegram-bot. but logs error.
The key `send_telegram` is not valid here. Only known plugin names are valid keys.

python2.7/site-packages/flexget/plugins/output

Do not have send_telegram.py

**Comment by lepinkainen** [comment]
What does ```flexget -V``` say to you?

**Comment by iruyanka** [comment]
1.2.432

**Comment by lepinkainen** [comment]
Did you install via pip or something else?

I've got a pip install of that version and I can find send_telegram.py in /usr/local/lib/python2.7/dist-packages/flexget/plugins/output/

There's no sane reason why the file would be missing from a recent version.

**Comment by iruyanka** [comment]
Umm... Ok. Thanks.

**Comment by lepinkainen** [comment]
You could try ```pip install flexget --upgrade --force-reinstall``` and see if that fixes it.

Other than that I'm at a loss figuring out why the plugin isn't where it's supposed to be.
