### ISSUE TITLE
Support both markdown and html in send_telegram

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#806]
Telegram supports both: https://core.telegram.org/bots/api#formatting-options

the ```markdown: yes``` configuration option isn't sufficient and should be renamed, maybe to ```parse_mode``` as in the API?

**Comment by liiight** [comment]
Ideally i'd change the parameter name in the config from `use_markdown` to `parse_mode` and let it accept ENUM, but that will trigger an upgrade action.
What do you think @lepinkainen?

**Comment by lepinkainen** [comment]
That's acceptable, the send_telegram plugin is still under construction anyway, we just changed from use-markdown to use_markdown, so this is just another in the same vein.

**Comment by liiight** [comment]
OK, cool, i'll change it
