### ISSUE TITLE
Make log files per-run instead of continuously

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#812]
- Increase logger maxBytes to a number large enough to contain DEBUG-level log files (with guessit enabled...)
- Call [RotatingFileHandler.doRollover](https://docs.python.org/2/library/logging.handlers.html#logging.handlers.RotatingFileHandler.doRollover) after every run or every scheduler event, this will rotate the logs
- Add option to compress logs (encoding='bz2' works on python2 at least)
- Optionally, make it configurable

**Comment by stevezau** [comment]
@lepinkainen what are you trying to solve with this enhancement request?

**Comment by liiight** [comment]
His logs are too damn big!

**Comment by lepinkainen** [comment]
Trying to get relevant logs from Flexget runs, mostly for my own purposes (grepping and analyzing) and for debugging.

I've got a few specific problems here:
1) Running Flexget with debug on (without guessit, which is loud af) generates more log files than fit in the full rotation.
2) Trying to find out the reason for that one weird behavior 7 runs ago to report a bug is next to impossible from the continuous log stream, with a per-session rotate I could just find the timestamp and less through that.

**Comment by tarzasai** [comment]
with my [log_filter](https://github.com/tarzasai/.flexget/blob/master/plugins/log_filter.py) you can prevent the messages you don't need to be written... perhaps it's not the best solution for developers but it helps a bit.

**Comment by liiight** [comment]
why is that a 3rd party @tarzasai ?

**Comment by tarzasai** [comment]
I sent a PR a couple of years ago but in the end we believed it to be pretty useless... I think this is just the second request on log management we've ever seen. I can send it again of course.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
