### ISSUE TITLE
Series begin crashes when any punctuation is present in the show title

### ISSUE THREAD

**Issue by jaimbo** [Flexget/Flexget#814]
This is the error message.

C:\Users\Administrator\Desktop>flexget series begin "DC's Legends of Tomorrow" S
01E01
Traceback (most recent call last):
  File "C:\Python27\Scripts\flexget-script.py", line 9, in <module>
    load_entry_point('FlexGet==1.2.433', 'console_scripts', 'flexget')()
  File "c:\python27\lib\site-packages\flexget\__init__.py", line 37, in main
    manager.start()
  File "c:\python27\lib\site-packages\flexget\manager.py", line 300, in start
    self.handle_cli()
  File "c:\python27\lib\site-packages\flexget\manager.py", line 327, in handle_c
li
    options.cli_command_callback(self, command_options)
  File "c:\python27\lib\site-packages\flexget\plugins\cli\series.py", line 28, i
n do_cli
    begin(manager, options)
  File "c:\python27\lib\site-packages\flexget\plugins\cli\series.py", line 103,
in begin
    series = shows_by_name(series_name, session)[0]
IndexError: list index out of range

C:\Users\Administrator\Desktop>

**Comment by Bouke** [comment]
Still running into this issue; shouldn't the code also include `name = normalize_series_name(name)` like the command `show` does?

**Comment by liiight** [comment]
Are you sure that you're on latest version? Works for me

**Comment by Bouke** [comment]
FlexGet==1.2.441

On that version it throws;

    sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: series.name_lower [SQL: u'INSERT INTO series (name, name_lower, identified_by, begin_episode_id) VALUES (?, ?, ?, ?)'] [parameters: (u"Grey's Anatomy", u'greys anatomy', u'ep', None)]

Note that `greys anatomy` is an `alternate_name` I've configured.

After adding `series_name = normalize_series_name(series_name)` in that method, it works.

**Comment by liiight** [comment]
That's a completely different error. Please open a new issue
