### ISSUE TITLE
gcc error when trying to upgrade to 1.2.431

### ISSUE THREAD

**Issue by nuwonda** [Flexget/Flexget#815]
When upgrading on NAS (possibly slim python installs in general) to 1.2.431 flexget encounters an error on regex aborting install with error code 1

Building wheels for collected packages: flexget, regex
  Running setup.py bdist_wheel for flexget
  Stored in directory: /root/.cache/pip/wheels/13/54/23/c41beb8191327ca213a2b960e9b02009c8d16db94b6c0123a5
  Running setup.py bdist_wheel for regex
  Complete output from command /usr/local/flexget/bin/python -c "import setuptools;__file__='/mnt/ram/pip-build-mQaxvZ/regex/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpzRFIsmpip-wheel-:
  /usr/local/flexget/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '2016.01.10' to '2016.1.10'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv5tel-2.7
  copying Python2/regex.py -> build/lib.linux-armv5tel-2.7
  copying Python2/_regex_core.py -> build/lib.linux-armv5tel-2.7
  copying Python2/test_regex.py -> build/lib.linux-armv5tel-2.7
  running build_ext
  building '_regex' extension
  creating build/temp.linux-armv5tel-2.7
  creating build/temp.linux-armv5tel-2.7/Python2
  gcc -fno-strict-aliasing -L/opt/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/flexget/include/python2.7 -c Python2/_regex.c -o build/temp.linux-armv5tel-2.7/Python2/_regex.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for regex
Successfully built flexget
Failed to build regex
Installing collected packages: regex, rebulk, guessit, flask-restplus, flexget, futures
  Running setup.py install for regex
    Complete output from command /usr/local/flexget/bin/python -c "import setuptools, tokenize;__file__='/mnt/ram/pip-build-mQaxvZ/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ynFo3D-record/install-record.txt --single-version-externally-managed --compile:
    /usr/local/flexget/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '2016.01.10' to '2016.1.10'
      normalized_version,
    running install
    running build
    running build_py
    running build_ext
    building '_regex' extension
    gcc -fno-strict-aliasing -L/opt/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/flexget/include/python2.7 -c Python2/_regex.c -o build/temp.linux-armv5tel-2.7/Python2/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/flexget/bin/python -c "import setuptools, tokenize;__file__='/mnt/ram/pip-build-mQaxvZ/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ynFo3D-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /mnt/ram/pip-build-mQaxvZ/regex

**Comment by AezDropZz** [comment]
I had the same error,

``` sudo apt-get install python-dev ```

helped me out.

**Comment by nuwonda** [comment]
seems installing python-dev not always works, see here: [http://discuss.flexget.com/t/upgrading-to-1-2-431/1949/5]

**Comment by liiight** [comment]
This seems to be connected with a recent upgrade to guessit... Check out #646. No solution yet though.

**Comment by stevezau** [comment]
@nuwonda please try again, guessit removed the dep's that required CC compiler.

**Comment by nuwonda** [comment]
Yep, fixed! Thanks!
