### ISSUE TITLE
Offline-TVDB-proof rename for anime

### ISSUE THREAD

**Issue by Merwenus** [Flexget/Flexget#816]
In the last few weeks TVDB went offline quit often. I asked here how could I manage to rename files even when the TVDB is down.

You guys helped me to create this rename tool:
```
    set:
      content_filename: "{{ tvdb_series_name|default(series_name)|replace('/','-')|replace('~','-')|replace(':',' -')|replace('?','_') }} - {{series_id|lower}}{% if tvdb_ep_name %} - {{ tvdb_ep_name|default('')|replace('/','-')|replace('~','-')|replace(':',' -')|replace('?','_') }} {% endif %}"
```

It is working like a charm, perfect for everything, but not for Animes, because I get this renamed files:
Dragon Ball Super - 26 - A Chance of Victory in a Pinch! It is Time for a Counterattack Son Goku!.mkv
#Instead of this:
Dragon Ball Super - s02e09 - A Chance of Victory in a Pinch! It is Time for a Counterattack Son Goku!.mkv 

#So how can I manage to do this:

**IF** tvdb_season **AND** tvdb_episode exists (tvdb online), then rename like this
s{{ tvdb_season|pad(2) }}e{{ tvdb_episode|pad(2) }}

Else use this:
{{series_id|lower}}

**Comment by liiight** [comment]
of the top of my head you can try to use [`number`](http://jinja.pocoo.org/docs/dev/templates/#number).
Also, the forums are ideally the place for these types of question next time.
