### ISSUE TITLE
ignore subfolder using regexp with filesystem plugin

### ISSUE THREAD

**Issue by plittlefield** [Flexget/Flexget#821]
I would like the filesystem plugin to ignore the subfolder 'extrafanart' when building the list for input.

My folder tree looks like this:-

   /home/paully/Videos/TV/
   ├── 2 Broke Girls
   │   └── extrafanart
   ├── Adventure Time
   │   └── extrafanart

I have tried this:-

      from:
        filesystem:
          path: /home/paully/Videos/TV/
          recursive: 2
          retrieve: dirs
          regexp: '(?!extrafanart)'

However, it still scans those subfolders.

Can anyone help?

**Comment by liiight** [comment]
I'm not exactly sure what data you're trying to retrieve. Using `retrieve: dirs` will just return dir names as entry.
If you want to scan just the parent dir, use `recursive: 1`. But think of the output you're trying to generate, and whether it's file names or dir names.
`

**Comment by plittlefield** [comment]
My apologies if the original question was unclear. I thought I had explained it well.

I am using the filesystem plugin to retrieve just the names of my TV shows, hence my use of `retrieve: dirs` code shown in my config.

I would like to only go 1 level deep, in order to IGNORE the sub-folders 'extrafanart' but I cannot use `recursive: 1` because of the error...

`[/templates/tv/configure_series/from/filesystem/recursive] 1 is less than the minimum of 2`

...so I am trying to find another way.

Questions:-

1. Why doesn't that plugin allow recursive of just 1 level?
2. How can I make it mask or ignore certain words?

I know it can search for words to find (shown in the flexget page for the plugin).

I need it to SKIP certain words... in my case, the folder name 'extrafanart'.

Now do you see?

**Comment by plittlefield** [comment]
I have just solved my own problem.

Remove the recursive, so it now becomes `recursive: no`

My apologies for wasting time.

**Comment by liiight** [comment]
Not wasteful at all, thanks for sharing solution.

**Comment by alneven** [comment]
@plittlefield: Maybe you can update the wiki for filesystem with this example and the solution.

**Comment by liiight** [comment]
BTW, my bad with suggesting using 1 level of recursion, of course it doesn't make sense if it's similar to no recursion at all. Didn't remember implementing it that way :smile:

**Comment by plittlefield** [comment]
@liiight no worries :-)

**Comment by plittlefield** [comment]
@alneven No need to update the Wiki. It's my bad actually, plus not realising that `recursive: no` was (by peeking in the code) actually `recursive: 0+1`. I was having a senior moment and just didn't put 2 + 2 together. If I am asking the plugin to look in this folder for the list of folders that are IN this folder then it doesn't need to recurse. I think :-)

**Comment by liiight** [comment]
yeah, recursion is more than 1 level deep
