### ISSUE TITLE
imdb parse error in 1.2.439

### ISSUE THREAD

**Issue by wtluke** [Flexget/Flexget#826]
I know this won't be music to your ears, but it's broken again :(

`2016-01-27 21:59 ERROR    utils.imdb    extratorrent    Possible IMDB parser needs updating, Please report on Github.`

**Comment by crawln45** [comment]
Do not make duplicate posts. Please read open issues before posting an issue.

**Comment by wtluke** [comment]
I did look and couldn't see any mention. Sorry
