### ISSUE TITLE
TypeError: %d format: a number is required, not unicode

### ISSUE THREAD

**Issue by dotixx** [Flexget/Flexget#833]
Hello :)

I have an issue using your plugin: it's stuck in an infinite loop when running it without --debug.

When I used --debug to see what happened, this error showed up continuously : http://fr.tinypic.com/r/357kidu/9

dotixx

**Comment by liiight** [comment]
That was fast...  @lildadou check this out

**Comment by dotixx** [comment]
Here's the flexget task:

> tv:
>     #cfscraper: yes
>     thetvdb_lookup: yes
>     t411_lookup: fill
>     discover:
>       what:
>         # - trakt_list:
>             # username: '{{ secrets.trakt.username }}'
>             # account: '{{ secrets.trakt.username }}'
>             # list: collection
>             # type: shows
>             # strip_dates: yes
>         - emit_series: yes
>       from:
>         - t411:
>             category: série tv
>             terms:
>               - vostfr
>               - hdrip 1080
>               - web-dl 1080
>               - tvriphd 1080
>               - hdrip 720
>               - web-dl 720
>               - tvriphd 720
>         #- piratebay: yes
>         #- torrentz: verified
>         #- cpasbien:
>         #    category: series-vostfr
>     torrent_alive:
>       min_seeds: 10
>     set:
>       path: '/home/osmc/dl/'

**Comment by liiight** [comment]
T411 was just updated in last release with a major overhaul. Please try again and report. 
Note that there may be changes required to config, wiki should be updated though.

**Comment by lildadou** [comment]
@liiight : I can reproduce. Integer passing into entry metadata was convert into string. I add a int cast to resolve the problem (that was not blocking)

**Comment by liiight** [comment]
Cool. Are you submitting PR?

**Comment by liiight** [comment]
Closed with #841
