### ISSUE TITLE
webui History tab - no list

### ISSUE THREAD

**Issue by Tskmst** [Flexget/Flexget#836]
Hello,

Few days back, i had to modify my imdb.py script to fix the "parser" errors fixed in #825

I have also just updated flexget to 1.2.442 and for some reason my webui history tab still does not show any lists of History for accepted/downloaded entries.

Anyone else having the same problem?

**Comment by stevezau** [comment]
Hey,

The WebUI is under development at the moment. It's slow going as i'm the only one writing it.

I'm re-writing the execute part of the ui at the moment. I'll fix up history once ive finished.

I didn't realise anyone was actually using it..

**Comment by Tskmst** [comment]
You are the man. Thank you.

**Comment by stevezau** [comment]
it's showing again.. still needs some work tho
