### ISSUE TITLE
Could not start manager: 'ascii' codec can't decode byte 0xfd in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by jUsjDnr9vNok4kelSGyl** [Flexget/Flexget#837]
Suddenly my flexget instance would stop working and just produce this output:

Could not start manager: 'ascii' codec can't decode byte 0xfd in position 0: ordinal not in range(128)

The trace output before this is:
2016-01-30 14:05 DEBUG    manager                       Figuring out config load paths
2016-01-30 14:05 DEBUG    manager                       Found config: /home/lazy/.flexget/config.yml
2016-01-30 14:05 DEBUG    manager                       Config file /home/lazy/.flexget/config.yml selected
2016-01-30 14:05 DEBUG    manager                       sys.defaultencoding: ascii
2016-01-30 14:05 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-01-30 14:05 DEBUG    manager                       os.path.supports_unicode_filenames: False
Could not start manager: 'ascii' codec can't decode byte 0xfd in position 0: ordinal not in range(128)

I tried modifying the config.yml and noticed that it produces the same error even if the config.yml is completely empty.

Does anyone have an idea on how to approach this?

I'm running latest flexget as of now (1.2.442).

**Comment by liiight** [comment]
Are you sure you're on latest? Is it possible that you have unupgraded daemons running?

**Comment by jUsjDnr9vNok4kelSGyl** [comment]
I did a double check and there is no older daemon running. I've updated the application with "pip install --upgrade flexget "

This one seems to be really difficult to track down because it fails so early. There is no indication that the problem might be cause by a plugin.

**Comment by liiight** [comment]
@gazpachoking what do you make of this?

**Comment by jUsjDnr9vNok4kelSGyl** [comment]
I noticed that when I run "flexget --test execute" it executes correctly. Could this be related to a database corruption? Or how does the test execution differ from the normal?

**Comment by jUsjDnr9vNok4kelSGyl** [comment]
I got it working by renaming the config.yml to config_basic.yml and did the same to the sqlite db. Now it executes correctly. I don't know why it does not work when the config is named as the default. I could not find any extra config.yml files from the default search paths. This problem might be cause by something in my setup. I'm closing this bug.

**Comment by liiight** [comment]
Renaming the config creates a new db. Looks like something was corrupt in yours
