### ISSUE TITLE
With debug None API Token

### ISSUE THREAD

**Issue by alpha13fr** [Flexget/Flexget#849]
I add my self with auth-add
but everytime i got with debug
None API token. Authenticating with "myaccount" account ...
I open database in credential table
my username is ok
my password is ok
api-token  NULL

Thx

**Comment by liiight** [comment]
I **assume** you're talking about trakt CLI? What command are you inputting?

**Comment by alpha13fr** [comment]
Sorry, mistake from me. ( t411 don't send token)
You can delete

Thx a lots
