### ISSUE TITLE
Add support for multiple movie_queue

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#851]
- Each movie queue should be completely independent
- Should be 100% compatible with current config
- Should apply to relevant movie_queue plugins (movie_queue and emit_movie_queue)

**Comment by alneven** [comment]
@liiight : do you plan to update the wiki with examples as well?

http://flexget.com/wiki/Plugins/movie_queue
http://flexget.com/wiki/Plugins/emit_movie_queue

**Comment by liiight** [comment]
Ofcourse. This isn't merged yet, should be early next week
