### ISSUE TITLE
Feature suggestion: Set start year in series_premieres

### ISSUE THREAD

**Issue by Davst** [Flexget/Flexget#860]
Series premieres leaves you open to reposts of old series that you do not want to follow. This plugin should be able to filter premieres by the year the series started similar to what the imdb plugin provides. for matching movies based on imdb info.

Suggestion would be for year to support current or a set year value.

**Comment by Davst** [comment]
Spoke too soon, noticed that using if and the handy 
tvdb_ep_air_date < now - timedelta(days=10): reject did what i needed.

**Comment by Davst** [comment]
reopened upon popular request in #flexget

**Comment by lepinkainen** [comment]
This should be an option in the premiere plugin itself.

Something like ```premieres: all``` to keep the current feature ```premieres: new``` to get shows that are under a year old or something.

**Comment by Davst** [comment]
The default state should be to not accept ancient premieres as well

**Comment by liiight** [comment]
i don't think this can be acheived by the premiere plugin or any other series plugin wrapper for that matter. unless show has a year in the title, we can't know its year without a metainfo lookup.
this would have to be a plugin like `imdb`. maybe `tvmaze_filter` or something

**Comment by gazpachoking** [comment]
> i don't think this can be acheived by the premiere plugin or any other series plugin wrapper for that matter. unless show has a year in the title, we can't know its year without a metainfo lookup.
> this would have to be a plugin like imdb. maybe tvmaze_filter or something

Yeah, agreed. I think it could basically work like the `if` statement above, but perhaps a nicer filter plugin could be made than `if`, specific to tvdb or something.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
