### ISSUE TITLE
Feature suggestion: Output/Move

### ISSUE THREAD

**Issue by mebu83** [Flexget/Flexget#864]
I think it would be cool if you could, optionally of course, specify if the the move option should try to copy the metadata or not.

[Shutil Documentation](https://docs.python.org/3/library/shutil.html)
The default copy_function is copy2(). Using copy() as the copy_function allows the move to succeed when it is not possible to also copy the metadata, at the expense of not copying any of the metadata.

That's all :)

**Comment by crawln45** [comment]
Well if you look at the code you'll notice we try [shutil.move](https://docs.python.org/2/library/shutil.html#shutil.move ) first. Then we try [shutil.copytree](https://docs.python.org/2/library/shutil.html#shutil.copytree) and if all else fails we try copy. So yes first we use functions that actually use copy2 before resorting to copy() function only.

**Comment by mebu83** [comment]
Aye! But before you resort to just copy what about trying to use 

`shutil.move(s, d, copy_function=copy)`

I might be barking up the wrong tree, but would still move it, just without the metadata, right?

**Comment by crawln45** [comment]
shutil.move takes 2 params (src, dst), it first tries to do os.rename() unless it's a directory then copy2 is used. which is why it's used first if move is selected, other wise it defaults to copy().

**Comment by mebu83** [comment]
Just saw that the [third param was added in vers 3.5](https://docs.python.org/3/library/shutil.html#shutil.move), I am completely out of my depth regarding which version of Python Flexget recommends to run.

**Comment by crawln45** [comment]
We run on python 2.7.

**Comment by mebu83** [comment]
Well there we go, so it is a no go until then, thanks for your help.
