### ISSUE TITLE
Webui and API security issues

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#866]
1. Webui always automatically generates the default flexget/flexget user, even when explicitly removed, this is just plain idiotic. Especially since all the examples open the webui to the public internet (listen port defined as 0.0.0.0)
2. It's impossible to see said user being added as there is no ```flexget users list``` anymore

Fix proposal:
1. DON'T AUTOGENERATE THE DEFAULT USER. Thank you. Typing ```flexget users add <username> <password>``` isn't that much of a hassle for the extra security.
2. (re-)add the list -command, or make it clear that there is only one user account for webui.

**Comment by stevezau** [comment]
It's on my todo list, slowing move up the list to number 1

**Comment by stevezau** [comment]
Since we are single user the default username is now flexget with no password.. User must set a password via flexget web password <some pwd>

they can also generate a token via flexget web gentoken 
view token via flexget web showtoken
