### ISSUE TITLE
error when using both secrets and exec plugins

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#878]
I was trying to use `{{now|formatdate("%Y%m%d")}}` inside a call to exec, but was getting failures indicating the entry did not have the required fields for string replacement. I narrowed it down to the use a the secrets plugin, even if the secrets file is empty. The following task demonstrates that 
with secrets the output is `Stdout: <function now at 0x10f9a5320>` but without it you get the expected answer: `Stdout: 20160224`

    secrets: secrets.yml
    tasks:
      test2:
        manual: yes
        disable:
          - seen
          - download
          - backlog
        html:
          url: http://flexget.com/wiki/Plugins
        limit_new: 1
        accept_all: yes
        exec:
          on_output:
            for_accepted:
              - echo "{{now|formatdate("%Y%m%d")}}"
          fail_entries: true

**Comment by tarzasai** [comment]
I tried to figure this out but I don't know, perhaps the wrong object is built/retrieved in https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/modify/config_secrets.py#L50 (below what I've found in memory, maybe someone can help) and I can only suggest to modify the if on line 46 as `if val and not '<function' in val:`
If someone else has a better idea...

```
Globals	Global variables	
element	unicode: echo "{{now|formatdate("%Y%m%d")}}"	
environment	Environment: <jinja2.environment.Environment object at 0x067DEA50>	
template	FlexGetTemplate: <FlexGetTemplate memory:67de410>	
	_debug_info	str: 1=10	
	_module	NoneType: None	
	_uptodate	NoneType: None	
	blocks	dict: {}	
	debug_info	<type 'list'>: [(1, 10)]	
	environment	Environment: <jinja2.environment.Environment object at 0x067DEA50>	
	filename	str: <template>	
	globals	dict: {'joiner': <class 'jinja2.utils.Joiner'>, u'secrets': {}, 'lipsum': <function generate_lorem_ipsum at 0x03910BF0>, 'range': <type 'xrange'>, 'dict': <type 'dict'>, 'cycler': <class 'jinja2.utils.Cycler'>, u'now': <function now at 0x0399F170>}	
		__len__	int: 7	
		'cycler' (59797824)	type: <class 'jinja2.utils.Cycler'>	
		'dict' (3747296)	type: <type 'dict'>	
		'joiner' (59797920)	type: <class 'jinja2.utils.Joiner'>	
		'lipsum' (59764128)	function: <function generate_lorem_ipsum at 0x03910BF0>	
		'range' (3746592)	type: <type 'xrange'>	
		u'now' (59699688)	function: <function now at 0x0399F170>	
		u'secrets' (101098392)	dict: {}	
	is_up_to_date	bool: True	
	module	TemplateModule: echo "<function now at 0x0399F170>"	
		_body_stream	<type 'list'>: [u'echo "<function now at 0x0399F170>"']	
			__len__	int: 1	
			0	unicode: echo "<function now at 0x0399F170>"	
	name	NoneType: None	

```

**Comment by y** [comment]
i'm also running into this problem but it only happens when run from cron. it works as expected when i run it manually from the commandline.
