### ISSUE TITLE
seen_movies not rejecting imdb_ids marked as seen using cli

### ISSUE THREAD

**Issue by y** [Flexget/Flexget#879]
when i manually download a movie i mark it seen with the cli using `flexget seen add tt2910904` so flexget will not download it later. i also use `seen_movies: strict` in the task. but the marked movie still gets downloaded:

    $ flexget seen search tt2910904
    ID: 45123 Name: tt2910904 Task: cli_add Added: Sun Feb 21 02:41:09 2016
     cli_add: tt2910904

    ID: 45201 Name: The Dressmaker 2015 LIMITED BDRip x264-GECKOS Task: my_movies Added: Wed Feb 24 01:13:28 2016
     imdb_id: tt2910904

the first record is the one i manually added after i manually download the movie, the second one is from flexget downloading it a few days later.

**Comment by liiight** [comment]
Apparently this is not how the plugin works. It validates the non standard `seen` IDS (`imdb_id`, `tmdb_id`, `trakt_movie_id`) against the local task entries only and not against the seen DB. @gazpachoking, @paranoidi am I right with this statement? And if so, should this be considered a bug?

**Comment by y** [comment]
if there is no way to tell flexget to not download a movie then it would be a bug or a missing critical feature. with series, we can do `flexget series begin SeriesName S02E04`  to tell it to skip episodes up until a certain episode, but there's no control for movies.

**Comment by liiight** [comment]
Seen plugin still works using title and url

**Comment by y** [comment]
But the same movie will appear in different feeds and from different release groups, so each title will be different for the same movie and the download url will always be different. Can you give an effective method, from the commandline, to prevent flexget from downloading a specific movie?

**Comment by gazpachoking** [comment]
Hmm, this is supposed to work.

**Comment by liiight** [comment]
@gazpachoking as far as I can see, ids are not saved to db unless they're the usual title and url

**Comment by y** [comment]
I just tested the fix but it doesn't appear to work. I removed the 2nd seen entry above by running `flexget seen forget 'The Dressmaker 2015 LIMITED BDRip x264-GECKOS'`. So that left:

    $ flexget seen search tt2910904
    ID: 45123 Name: tt2910904 Task: cli_add Added: Sun Feb 21 02:41:09 2016
     cli_add: tt2910904

Then I used inject like so, but it still accepted the entry:

    flexget --test --debug execute --verbose --tasks my_movies --now --inject "The Dressmaker 2015 LIMITED BDRip x264-GECKOS" "http://localhost/random" imdb_id=tt2910904

These are some relevant log lines:

    2016-02-28 14:20 DEBUG    seen          my_movies Learned 'tt2910904' (field: imdb_id)
    2016-02-28 14:20 DEBUG    seen          my_movies Learned 'The Dressmaker 2015 LIMITED BDRip x264-GECKOS' (field: title)
    2016-02-28 14:20 DEBUG    seen          my_movies Learned 'http://localhost/random' (field: url)

**Comment by gazpachoking** [comment]
@y You running from github source? A release didn't come out on pypi yet with the fix.

**Comment by y** [comment]
Oh, sorry. I'm using source from git branch master, but didn't realize the commit was on the develop branch.
