### ISSUE TITLE
Changing flexget python from 2.6 to 2.7

### ISSUE THREAD

**Issue by nishster7** [Flexget/Flexget#880]
My /opt/local/bin/flexget on Synology reads:

#!/opt/bin/python2.6
# EASY-INSTALL-ENTRY-SCRIPT: 'FlexGet==1.2.458','console_scripts','flexget'
__requires__ = 'FlexGet==1.2.458'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('FlexGet==1.2.458', 'console_scripts', 'flexget')()
    )

How do I change the python2.6 to python2.7. Simply changing the #! to /usr/local/bin/python2.7 does not work. 
Sorry if this is a noob question.

**Comment by stevezau** [comment]
first uninstall the 2.6 version using pip2.6 uninstall flexget

then you need to install it using pip2.7.. IE:

pip2.7 install flexget
