### ISSUE TITLE
Release input built-in plugin

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#882]
I'd this idea, and created a ticket nearly 2 years ago on  [Trac](http://flexget.com/ticket/2723). Meanwhile, I've discovered, that a version_checker plugin has been implemented.

My idea is, that instead of just writing the new version number out to the log, it should write the full changelog of the newest version, if there is just 1 version difference between the actuality installed and the latest version.

If the difference is more than one version, the lines should be limited to a #, you decide, then the full changelog link to the site should be displayed.
Except, if meanwhile a new version arrives, then the limited # of lines changelog should be displayed again, then just the reminder...
Maybe you could think of some extra config options, to fine tune the plugin...

The full changelog of the newest version should be just written out only once, then just a one line reminder, like what the version_checker can do now.

This plugin should be a built in one, with a one-day run interval. This interval could be overwritten (in hourly bases) in the config file. Of course, this built-in plugin  could be disabled in config.

I hope this helps, thank you...

[Trac](http://flexget.com/ticket/2723) ticket:

> I had an idea today, what if we could check the changelog with something like this:
> 
> `flexget --changelog 1.2.3` OR `flexget -C 1.2.3` OR `flexget changelog 1.2.3`
> 
> where the '''optional''' argument is the version, I want to see the changelog from?
> 
> I was thinking, that the output will be something like this: http://flexget.com/ChangeLog (using this source: http://download.flexget.com/ChangeLog) - but I'd add the links to the commits and tags using this: https://github.com/blog/985-git-io-github-url-shortener!
> 
> Example:
> {{{
> # Assuming we have 1.2.199 installed.
> 
> $ flexget -C
> Consider checking the http://flexget.com/wiki/UpgradeActions page before upgrading!
> === 1.2.200 (2014.10.07) === http://git.io/GENERATE_A_HASH-tags
> - (572ebcb) Add --debug-db-sessions | http://git.io/GENERATE_A_HASH-commits
> 
> $ flexget -C 1.2.198
> Consider checking the http://flexget.com/wiki/UpgradeActions page before upgrading!
> === 1.2.200 (2014.10.07) === http://git.io/GENERATE_A_HASH-tags
> - (572ebcb) Add --debug-db-sessions | http://git.io/GENERATE_A_HASH-commits
>   === 1.2.199 (2014.10.05) === http://git.io/GENERATE_A_HASH-tags
> - (dac3c76) Don't let urlrewrite_redirect rewrite urls it can't handle | http://git.io/GENERATE_A_HASH-commits
> - (6dffda8) Don't log url rewritten message if url hasn't changed. Fix urlrewriting passing task to urlrewriters | http://git.io/GENERATE_A_HASH-commits
>   }}}
> 
> Also, for the PR, I'd like to add this line to the version checker:
> {{{
> $ flexget -V
> 1.2.199
> Latest release: 1.2.200
> Hint! Use `flexget -C` to show the changelog from the current version!
> }}}
> 
> '''Return value (important, if we want to use it in a script!):'''
> - 0 if it was successfully checked, downloaded, wrote to output, or you are on the latest version
> - >0 (eg. 1) if it was not successful to download or anything else happened

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
