### ISSUE TITLE
Unable to download RSS: SSLv3 alert handshake failure

### ISSUE THREAD

**Issue by mseymour** [Flexget/Flexget#891]
I would think that this issue has been around for quite some time for me now, although I never encountered it until recently when an RSS feed that I use started redirecting to HTTPS.

When it tries to download the feed, it fails with the error `Unable to download the RSS for task <task> (<url>): [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)`

**Comment by stevezau** [comment]
What's the feed url and openssl version you are using.

**Comment by gazpachoking** [comment]
SSL issue are often solved by either or both:
- upgrading to python 2.7.9+
- `pip install --upgrade requests[security]`

**Comment by mseymour** [comment]
https://www.nyaa.eu/?page=rss&cats=1_37, OpenSSL 0.9.8zg 14 July 2015

Upgrading requests[security] using `sudo -H pip install --ignore-install six --upgrade requests[security]` on OS X 10.11 El Capitan works. Thanks!
