### ISSUE TITLE
Secrets not accepting integers

### ISSUE THREAD

**Issue by Jonybat** [Flexget/Flexget#892]
Continuing the discussion from: http://flexget.com/ticket/2745

Does it look like something that could be fixed or it would require too much work?

Like i mentioned before, a workaround would be to remove the int validation from the plugins that have it, but that does not seem like a good idea at all (from someone who has a very limited understanding of programming).

Just looking for a clear answer on this, is all.

Thanks

**Comment by gazpachoking** [comment]
Yeah, I'm not sure what can be done. We are using jinja, which is a string formatting language, thus we can't really make it output anything but a string.

**Comment by liiight** [comment]
There is no elegant way to do this
