### ISSUE TITLE
webui password - can't contain $

### ISSUE THREAD

**Issue by behemoth1979** [Flexget/Flexget#908]
Just noticed that when trying to set a webui password was getting the error 'too few arguments'

Eventually realised it was because the password I was trying to use contained a '$'

not sure if i can be modified to allow for these characters or maybe update the wiki/help to specify the requirements.

Cheers

**Comment by stevezau** [comment]
Are you on linux or windows??

On linux you might need to escape the $ char from the command line.. I tested and it works

flexget web passwd "Some\$assword"

**Comment by liiight** [comment]
@stevezau I consider this a bug...

**Comment by stevezau** [comment]
@liiight as far as i can tell it's a linux command line parsing thing.. not much we can do?

**Comment by stevezau** [comment]
to clarify, it's bash treats $ as a variable.
