### ISSUE TITLE
Warning message regarding Users commandline interface not loaded

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#914]
With the recent updates, I have noticed the following warning show in my log whenever I start flexget. I'm not sure if this is something that should be addressed, or if it is a setting that has been changed?

```
2016-03-02 23:51 WARNING  plugin                        Users commandline interface not loaded
```

Is this something that just would require an uninstall/reinstall of flexget? I have not made any significant changes to my config file that I am aware of. Currently running 1.2.469, but have noticed it from at least 1.2.466.

**Comment by liiight** [comment]
That's weird, that was removed. Maybe leftover pyw files?

**Comment by xathin** [comment]
It appears to be extra plugin files that were left over and not removed after an upgrade. I performed ```pip uninstall flexget``` then removed the folder that was remaining, which had several files left in it, then reinstalled and all appears OK. No more warning messages.

**Comment by liiight** [comment]
Cool
