### ISSUE TITLE
T411 new URL

### ISSUE THREAD

**Issue by gjdass** [Flexget/Flexget#918]
Hi;

T411 moved to .ch. So flexget can't connect to it anymore :(

Could not find a self-fix. If there is, im sorry for this message.

**Comment by stevezau** [comment]
update to the latest, it's been fixed already

**Comment by metasystem** [comment]
updated not working for me...
Updated, re-generate cookie from t411.ch but already "login page" on execute.
Tried to use github repo with pull today.
url_rewriter use correctly t411.ch, so, I don't understand why...
pastebin debug mode : http://pastebin.com/GwMBqeGT

**Comment by Ekhozie** [comment]
@metasystem got the same problem, fixed by https://github.com/Flexget/Flexget/pull/944

**Comment by Gsivade** [comment]
Same problem here.. Someone found a solution?

**Comment by metasystem** [comment]
@Gsivade pull + recreate cookie ident and it works for me...
