### ISSUE TITLE
seen forget is not working

### ISSUE THREAD

**Issue by alirz1** [Flexget/Flexget#920]
Im running the latest flexget on my synology NAS.

I tried to remove the series and also did a seen forget, yet flexget keeps rejecting episodes saying that they are marked as seen

newnaspc> /usr/local/flexget/env/bin/flexget series forget Arrow      
Removed series `Arrow` from database.

newnaspc> /usr/local/flexget/env/bin/flexget seen forget Arrow  
Removed 0 titles (0 fields)

but i still get:

2016-03-04 10:48 VERBOSE  task          showsrss1       REJECTED: `Arrow S04E15 720p HDTV X264 DIMENSION` by seen plugin because entry with title `Arrow S04E15 720p HDTV X264 DIMENSION` is already marked seen in the task showsrss1 at 2016-02-24 22:01

**Comment by tarzasai** [comment]
Have you tried to clear the lists rejected and failed too?

**Comment by alirz1** [comment]
well from what i can see, its being rejected because its been determined to be SEEN. So if im clearing out the SEEN shows, i see no reason for the rejection?

**Comment by tarzasai** [comment]
Try `flexget rejected clear` and `flexget failed clear`, I think those are different lists.

**Comment by liiight** [comment]
Doesn't seem like seen forget is working at all, investigating

**Comment by liiight** [comment]
oh, I misspoke, it just looking for **EXACT** match. Do a `seen search <term>` and run `seen forget <term>` on each on of those.
This type of functionality should be available soon using the web client so i dunno if i wanna add it to CLI just yet, or at all.

**Comment by alirz1** [comment]
Well there is some problem with  "seen forget"


newnaspc> flexget seen forget "MythBusters S16E09 The MythBusters Grand Finale HDTV x264 W4F"
Removed 2 titles (3 fields)

newnaspc> flexget execute
2016-03-06 15:10 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.

2016-03-06 15:10 VERBOSE  task          showsrss1       REJECTED: `MythBusters S16E09 The MythBusters Grand Finale HDTV x264 W4F` by series plugin because quality already downloaded

**Comment by alirz1** [comment]
newnaspc> flexget seen search MythBusters
ID: 20 Name: MythBusters S16E08 The Reddit Special HDTV x264 W4F Task: showsrss1 Added: Fri Mar  4 15:53:18 2016
 title: MythBusters S16E08 The Reddit Special HDTV x264 W4F
 url: http://reflektor.karmorra.info/torrent/A6D9AB33FF35F3FDF9CEA710028770667BFF0D4C.torrent

ID: 30 Name: MythBusters S16E07 Rocketmen HDTV x264 W4F Task: showsrss1 Added: Fri Mar  4 15:53:18 2016
 title: MythBusters S16E07 Rocketmen HDTV x264 W4F
 url: http://reflektor.karmorra.info/torrent/64AB3228169428D1393DDA8D7FE5CE277F864A63.torrent

**Comment by liiight** [comment]
You need to differentiate between seen entry and downloaded quality. Two different Plugins, two different things

**Comment by gazpachoking** [comment]
> REJECTED: MythBusters S16E09 The MythBusters Grand Finale HDTV x264 W4F by series plugin because quality already downloaded

This is the series plugin rejecting, not seen plugin. See `flexget series forget --help`

**Comment by alirz1** [comment]
ok. The issue can be closed then. thanks

**Comment by liiight** [comment]
It's already closed :smile:
