### ISSUE TITLE
seen search <search term> is not working

### ISSUE THREAD

**Issue by alneven** [Flexget/Flexget#922]
hi there,
somehow seen search is not working for me atm:

`root@palinka:~/flexget-dev# ~/flexget-dev/bin/flexget -V
1.2.472.dev`

> root@palinka:~/flexget-dev# ~/flexget-dev/bin/flexget seen search Restless
> There is a FlexGet process already running for this config, sending execution there.
> Traceback (most recent call last):
>   File "/root/flexget-dev/bin/flexget", line 9, in <module>
>     load_entry_point('FlexGet', 'console_scripts', 'flexget')()
>   File "/root/flexget-dev/flexget/__init__.py", line 37, in main
>     manager.start()
>   File "/root/flexget-dev/flexget/manager.py", line 286, in start
>     client.handle_cli(self.args)
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
>     return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
>     return conn.sync_request(handler, oid, *args)
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
>     raise obj
> TypeError: getattr(): attribute name must be string
> 
> ========= Remote Traceback (1) =========
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
>     res = self._HANDLERS[handler](self, *args)
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
>     return self._local_objects[oid](*args, **dict(kwargs))
>   File "/root/flexget-dev/flexget/ipc.py", line 75, in exposed_handle_cli
>     self.manager.handle_cli(options)
>   File "/root/flexget-dev/flexget/manager.py", line 330, in handle_cli
>     options.cli_command_callback(self, command_options)
>   File "/root/flexget-dev/flexget/plugins/cli/seen.py", line 17, in do_cli
>     seen_search(options)
>   File "/root/flexget-dev/flexget/utils/database.py", line 30, in wrapper
>     return func(*args, **kwargs)
>   File "/root/flexget-dev/flexget/plugins/cli/seen.py", line 45, in seen_search
>     seen_entries = seen.search(value=search_term, status=None, session=session)
>   File "/root/flexget-dev/flexget/utils/database.py", line 27, in wrapper
>     return func(*args, **kwargs)
>   File "/root/flexget-dev/flexget/plugins/filter/seen.py", line 348, in search
>     query = query.order_by(getattr(SeenEntry, order_by))
> TypeError: getattr(): attribute name must be string
> 
> root@palinka:~/flexget-dev# ~/flexget-dev/bin/flexget seen search -h
> There is a FlexGet process already running for this config, sending execution there.
> usage: flexget seen search [-h] <search term>
> 
> positional arguments:
>   <search term>
> 
> optional arguments:
>   -h, --help     show this help message and exit

Do I missed something? Like a package what I would need?

**Comment by alneven** [comment]
I have these packages:

```
root@palinka:~/flexget-dev# bin/pip install --upgrade -e .
Obtaining file:///root/flexget-dev
Requirement already up-to-date: FeedParser>=5.2.1 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: SQLAlchemy!=0.9.0,<1.999,>=0.7.5 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: beautifulsoup4!=4.2.0,<4.5,>=4.1 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: html5lib>=0.11 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: PyRSS2Gen in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: pynzb in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: progressbar in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: rpyc in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: requests!=2.4.0,<2.99,>=1.0 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: python-dateutil!=2.0,!=2.2 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: jsonschema>=2.0 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: tmdb3 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: path.py in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: guessit>=2.0.3 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: apscheduler in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: pytvmaze>=1.4.5 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: ordereddict>=1.1 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: cherrypy>=3.7.0 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: flask>=0.7 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: flask-restful>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: flask-restplus==0.8.6 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: flask-compress>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: flask-login>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: flask-cors>=2.1.2 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: pyparsing>=2.0.3 in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: Safe in ./lib/python2.7/site-packages (from FlexGet==1.2.472.dev0)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from html5lib>=0.11->FlexGet==1.2.472.dev0)
Requirement already up-to-date: setuptools in ./lib/python2.7/site-packages (from pynzb->FlexGet==1.2.472.dev0)
Requirement already up-to-date: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->FlexGet==1.2.472.dev0)
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->FlexGet==1.2.472.dev0)
Requirement already up-to-date: functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema>=2.0->FlexGet==1.2.472.dev0)
Requirement already up-to-date: babelfish>=0.5.5 in /usr/local/lib/python2.7/dist-packages (from guessit>=2.0.3->FlexGet==1.2.472.dev0)
Requirement already up-to-date: rebulk>=0.7.0 in ./lib/python2.7/site-packages (from guessit>=2.0.3->FlexGet==1.2.472.dev0)
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from apscheduler->FlexGet==1.2.472.dev0)
Requirement already up-to-date: tzlocal in ./lib/python2.7/site-packages (from apscheduler->FlexGet==1.2.472.dev0)
Requirement already up-to-date: futures in ./lib/python2.7/site-packages (from apscheduler->FlexGet==1.2.472.dev0)
Requirement already up-to-date: Werkzeug>=0.7 in ./lib/python2.7/site-packages (from flask>=0.7->FlexGet==1.2.472.dev0)
Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask>=0.7->FlexGet==1.2.472.dev0)
Requirement already up-to-date: aniso8601>=0.82 in /usr/local/lib/python2.7/dist-packages (from flask-restful>=0.3.3->FlexGet==1.2.472.dev0)
Installing collected packages: FlexGet
  Running setup.py develop for FlexGet
Successfully installed FlexGet-1.2.472.dev0
```

**Comment by liiight** [comment]
Crap, that's my fault. Will fix at the start of next week

**Comment by alneven** [comment]
Thanks ;-)
