### ISSUE TITLE
Add inject API endpoint

### ISSUE THREAD

**Issue by subzero79** [Flexget/Flexget#929]
IRC announces are instant, so for some people is really important to gain ratio using autodl-irssi.

At the moment there is no way of processing them through flexget. There is an ongoing plugin project here

http://discuss.flexget.com/t/plugin-wip-irc-input/1497/77

This could be easily solved on the autdl-irssi side by using a custom script that can push the release through the new flexget API using curl, then let flexget process, see if is eligible and pass it to download client.

**Comment by liiight** [comment]
@stevezau this probably goes without saying but i think this should be added as an option to the task endpoint, rather than a new one.

**Comment by gazpachoking** [comment]
I think we need to add support to the execute api endpoint to specify options. Whether we should also have another plugin to make injecting easier (like we also have inject cli command) can also be considered.

**Comment by stevezau** [comment]
@liiight started the work

https://github.com/Flexget/Flexget/pull/977

**Comment by liiight** [comment]
done with #977
