### ISSUE TITLE
TypeError: makeRecord() takes exactly 8 arguments (10 given)

### ISSUE THREAD

**Issue by AshIndigo** [Flexget/Flexget#931]
After restarting my NAS I am unable to run Flexget.

[http://pastebin.com/tsWjsyGj](http://pastebin.com/tsWjsyGj)

**Comment by stevezau** [comment]
your pastebin is invalid

**Comment by AshIndigo** [comment]
Sorry never used Github linking before. Should work now.

**Comment by AshIndigo** [comment]
Managed to fix it by editing the logging.py file and removing the extra arguments.
