### ISSUE TITLE
[WebUI] Forget series

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#935]
The button to forget a TV Show is broken, no error messages. 

Probably got broken during refactoring to components. Will look at it as soon as possible.

**Comment by kristenmills** [comment]
Yeah probably. I knew I was bound to break something...most likely the function didn't get bound to one of the smaller components or I mispelled the function name during the binding.

**Comment by Tommatheussen** [comment]
Yea, no worries though. It gave me a chance to play around with the component stuff, now I know how it works together :)
