### ISSUE TITLE
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE with RSS Feeds

### ISSUE THREAD

**Issue by freddles** [Flexget/Flexget#937]
I am having similar issues with Flexget as some of the other members , however i cant seem to resolve. 

When downloading from RSS feeds using HTTPS i get the following:

(failure reason: Network error during request: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590))

This is flexget running within a jail on a FreeNAS environment.

Various Package Version Numbers:
Python 2.7.11 (default, Feb 20 2016, 07:48:16)
[GCC 4.2.1 20070831 patched [FreeBSD]] on freebsd9
Type "help", "copyright", "credits" or "license" for more information.

OpenSSL 1.0.2g  1 Mar 2016

requests (2.9.1)
FlexGet (1.2.476)
six (1.6.1)

The RSS Feed I am using is a cloudflare HTTPS Feed. I have also tried incorporating verify_ssl_certificates: no under both the task and global var, however did not resolve the issue.

Any help is greatly appreciated.

**Comment by gazpachoking** [comment]
SSL support is totally changed on python 2.7.9+ I'd upgrade to that. You can also try `pip install --upgrade requests[security]`

**Comment by freddles** [comment]
Thanks for your response, i have managed to sort it out. Looks like even through OpenSSL was ugraded, python was still linked to the old version.
