### ISSUE TITLE
WebUI - Corrupted views using IE11

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#938]
Series:
![image](https://cloud.githubusercontent.com/assets/4374581/13637259/16f4e5aa-e60f-11e5-9016-363614003983.png)

Login:
![image](https://cloud.githubusercontent.com/assets/4374581/13637263/1b26a9ce-e60f-11e5-8c4b-58078c308613.png)

**Comment by Tommatheussen** [comment]
Fixed in latest release, reopen if this is not the case.
