### ISSUE TITLE
Upgrade to version 1.2.484 bug - Could not start manager: Extra data: line 1 column 5 - line 1 column 21 (char 4 - 20)

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#954]
I just did the update and configuration change as described in the upgrade action page to version 1.2.484.
I use thetvdb plugin so I had to switch to username and password, but now it crashes: http://pastebin.com/xRtPPM32

**Comment by stevezau** [comment]
Thanks, this is a bug due to the latest version where we are attempting to remove picklefield to prepare for PY3 support. Im looking into it.

**Comment by stevezau** [comment]
Found the issue, i'm pushing out a new release, should be done in about 5-10mins

**Comment by effemmeffe** [comment]
Good job.
Thanks.
