### ISSUE TITLE
Series/template caching?

### ISSUE THREAD

**Issue by Jonybat** [Flexget/Flexget#957]
Hi

As a result of my investigation:
http://discuss.flexget.com/t/does-flexget-cache-the-templates-in-the-config-file/1607/2

In short:
Adding a new tvshow to series in config file and using emit_series with from_start does not emit the new tvshow. A combination of both begin setting and from_start also does not work.

Setting the begin episode in the config and removing the option from_start works. Using the cli to set the begin episode also works (while still using both the begin setting in the config and from_start option).

**Comment by liiight** [comment]
can you provide an example config of this please?

**Comment by Jonybat** [comment]
Ok, while trying to build the smallest reproducible config, I've discovered something else that should make it pretty easy for you to find the issue. It goes back to my original idea that flexget somehow caches the templates/config file.

It seems that this problem only applies if the series plugin is in a template, because if it is inside a task it works as it should. This also matches with something that my friend told me the other day, that commenting and uncommenting the from_begin line forces the expected behavior, until the next time you change the series list. In fact, it doesn't seem to have anything to do with emit_series or from_start, as changing anything in the task also forces the expected behavior.

Steps to reproduce:
- https://gist.github.com/Jonybat/406e82458417b556930999fd164c895b
- `flexget -c test.yml execute --discover-now`

> You should see discovering 1 title (Arrow)

- Uncomment the Daredevil lines and run the task again

> You should still only see discovery 1 title (Arrow)

- Now change torrentz: good to any, or anything at all in the task

> You should now see discovering 2 titles
