### ISSUE TITLE
series API

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#960]
In the series API, when you do a delete request to `/series/{show_id}/episodes/{ep_id}/releases` no releases are being reset, probably caused by 3629650c0d0e704d144adda33700813a0f7ca107

I think I fixed it in 68b08911460d644917a609d5bc566734d5b190b5, @liiight can you check if this is correct?

**Comment by liiight** [comment]
Yeah, it's the same stiff I did in the get endpoint right? Forgot to add it to delete.

**Comment by Tommatheussen** [comment]
Yes indeed, it seem to fully work for me now, I don't think it's used elsewhere? If not I'll merge webui in dev and close this

**Comment by liiight** [comment]
Sounds good to me
