### ISSUE TITLE
ERROR filesystem File not decodable with filesystem encoding: ANSI_X3.4-1968

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#970]
In my log I have some lines like this:

`ERROR filesystem populate-series-db File /media/Tera/Library/TV/Boris/S01/Boris - S01E04 - Qualit�� o morte.avi not decodable with filesystem encoding: ANSI_X3.4-1968`

The file is referring to is this:
```
fmf@kodi:~$ ls /media/Tera/Library/TV/Boris/S01/Boris\ -\ S01E04*
/media/Tera/Library/TV/Boris/S01/Boris - S01E04 - Qualità o morte.avi
fmf@kodi:~$
```
And the trakt episode is this: [https://trakt.tv/shows/boris/seasons/1/episodes/4](https://trakt.tv/shows/boris/seasons/1/episodes/4)

My locale is this:

```
fmf@kodi:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
fmf@kodi:~$
```

[Full debug log](http://pastebin.com/3DVg491S)

**Comment by crawln45** [comment]
@effemmeffe is this still an issue. If not I'll close the ticket.

**Comment by effemmeffe** [comment]
I removed the archive plugin from my config, so now it doesn't scan anymore my hard disk for existing series, so I have no idea if the problem is still there.
Should I still close the bug?

**Comment by liiight** [comment]
it's the `filesystem` plugin that caused the error, not `archive`.

**Comment by effemmeffe** [comment]
Sorry.
I just checked and the problem is solved, I'll close.
