### ISSUE TITLE
Enhancement: Enable end-to-end encryption for Pushbullet

### ISSUE THREAD

**Issue by numericOverflow** [Flexget/Flexget#971]
Pushbullet has supported end-to-end encryption since Aug 2015.  Would be a great feature for privacy conscious flexget users for sending alerts. 

https://docs.pushbullet.com/#end-to-end-encryption2

**Comment by liiight** [comment]
It look like this is irrelevant for flexget's purposes:

> We support end-to-end encryption for Notification Mirroring, Universal Copy & Paste, and SMS

**Comment by liiight** [comment]
Not relevant, closing.
