### ISSUE TITLE
tmdbsimple issue

### ISSUE THREAD

**Issue by FeromonDE** [Flexget/Flexget#972]
After migrating from tmdb3 to tmdbsimple, not possible to get search results in other languages than English.
Before migrating I just edited the api_tmdb.py, and edited locale to my language, but with tmdbsimple I have not found this possibility, now i installed the latest version with tmdb3 support.

**Comment by pemargo** [comment]
¿Any change about that? is not posible to get the content_filename in others languages-
Thank you

**Comment by liiight** [comment]
This is treated as a feature request.

**Comment by crawln45** [comment]
hmm seeing as we now parse tmdb ourselves instead of relying on external software. this should be a mute point.

**Comment by liiight** [comment]
Please reopen in [feathub](http://feathub.com/Flexget/Flexget)
