### ISSUE TITLE
problem with TV shows config 

### ISSUE THREAD

**Issue by Saman24** [Flexget/Flexget#985]
hi
i have problem with downloading TV shows through rss
this is my config
`tasks:
  test task:
    rss: http://mysite.com/rss.php
    series:
      - 'Arrow':
          qualities:
          - 720p WEBDL
          - 1080p WEBDL
          - 720p HDTV
          - 1080p HDTV
          - 1080i WEBDL
          - 1080i HDTV
      - 'The.Walking.Dead':
          qualities:
          - 720p WEBDL
          - 1080p WEBDL
          - 720p HDTV
          - 1080p HDTV
          - 1080i WEBDL
          - 1080i HDTV
    download: /mytvfolder`

this config work great for first release of TV show but it wont download the second release with the some quality

for example it will download first available torrent:

The.Walking.Dead.S06E15.1080p.HDTV.x264-**groupX**

but it wont download the second torrent with some quality but different release groups:

The.Walking.Dead.S06E15.1080p.HDTV.x264-**groupY**

can anyone help me what code i should use for Flexget config to download all release groups with some quality

**Comment by Saman24** [comment]
tasks:
  test task:
    rss: http://mysite.com/rss.php
    series:
      - 'Arrow':
          qualities:
          - 720p WEBDL
          - 1080p WEBDL
          - 720p HDTV
          - 1080p HDTV
          - 1080i WEBDL
          - 1080i HDTV
      - 'The.Walking.Dead':
          qualities:
          - 720p WEBDL
          - 1080p WEBDL
          - 720p HDTV
          - 1080p HDTV
          - 1080i WEBDL
          - 1080i HDTV
    download: /mytvfolder

**Comment by cvium** [comment]
> The.Walking.Dead.S06E15.1080p.HDTV.x264-groupX
> The.Walking.Dead.S06E15.1080p.HDTV.x264-groupY

You can't really make it download the same quality twice even if the groups are different.

**Comment by alneven** [comment]
Maybe you could just use regexp
Not the series or movies plugins, nor quality, etc
Just regexp to allow what you like (whatever group or quality from the
listed one, also dupes)
What you need to check also the seen part of flexget
How to disable that!?


On Mon, Mar 28, 2016 at 6:28 PM, Claus Vium <notifications@github.com>
wrote:

> The.Walking.Dead.S06E15.1080p.HDTV.x264-groupX
> The.Walking.Dead.S06E15.1080p.HDTV.x264-groupY
>
> You can't really make it download the same quality twice even if the
> groups are different.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/issues/985#issuecomment-202472810>
>



-- 
http://www.keksz.net
news & photoportal

**Comment by Saman24** [comment]
i just tested my config with regexp and its working perfectly.
problem solved 
thank you!
