### ISSUE TITLE
imdb_list new list interface plugin

### ISSUE THREAD

**Issue by Clem-** [Flexget/Flexget#991]
It seems that the documentation for imdb_list plugin updated for the introduction of list interface plugins does not reflect the actual state of the plugin in 1.2.497.
"login" and "password" keys are indeed not valid during schema interpretation.

**Comment by liiight** [comment]
Yeah, I may have jumped the gun with the wiki update, I was pretty confident that the new feature will be ready by now. 
I'll see how soon the feature can be added and revert the wiki if it takes too long

**Comment by cvium** [comment]
wiki has been updated and new imdb_list is out. There is a bug though, #1020. Closing this one.

**Comment by Clem-** [comment]
I still get the same error : 
`[/tasks/checkIMDBlist/imdb_list] The keys 'login', 'password' are not valid here.`
