### ISSUE TITLE
SOCKS support in Proxy plugin

### ISSUE THREAD

**Issue by averissimo** [Flexget/Flexget#992]
This is a Feature request to add socks support in proxy plugin, currently only http(s) and ftp protocols are supported (https://github.com/Flexget/Flexget/blob/master/flexget/plugins/operate/proxy.py)

There was an old ticket with this request at: http://flexget.com/ticket/2671

I've tried adding the socks proxy in configuration as below, but did not work.

```
proxy: socks5://127.0.0.1:<port>
```

Thanks for considering!

**Comment by averissimo** [comment]
Can use as workarounds:
- tsocks
- http://github.com/dgoulet/torsocks

**Comment by averissimo** [comment]
Another workaround is setting up an HTTP(S) proxy that forwards request to socks proxy

such as: privoxy

**Comment by gazpachoking** [comment]
Looks like this might be supported now. http://docs.python-requests.org/en/master/user/advanced/#socks

Try running `pip install --upgrade requests[socks]`, then using the proxy address like you did.

**Comment by averissimo** [comment]
Thakns for the tip!

Just tried it, but seems like the url with socks5 protocol is not recognized as a valid url

    u'socks5://127.0.0.1:3213' is not a u'url'

I'll try to debug it later on :)

**Comment by paranoidi** [comment]
This may be coming from our configuration validation. Maybe it just needs support for socks5?

You could try modifying proxy plugin to allow text instead of url

**Comment by liiight** [comment]
I added socks5 to allowed protocols, try again
